#!/bin/bash

source $NS_WDIR/lib/automation_util
Input_File="/home/automation/workbench/automation/nscore/regression/testcases/Regression011/ParamList"
TESTRUN_ID=$(get_testidx)
Tname=$(get_tname)
reg_status=1

function calculate_metric_deviation(){
    baseline_test_run=$1
    current_test_run=$2
    param_string=$3
    param_name=$4  
    test_case_name=$5
    ParamListFile=$6
    #parameter values for baseline and current test run when all parameters are to be matched(param_string =ALL)
    if [ "XX$3" == "XXALL" ]; then
        IFS=$'\n'
        for line in $(cat $ParamListFile); do
            baseline_param=$(testStats $baseline_test_run 0 "${line}" "$param_name")
            debug_log "baseline value for ${line}:${baseline_param}"
            current_param=$(testStats $current_test_run 1 "${line}" "$param_name")
            debug_log "current value for ${line}:${current_param}"
            param_change="${line}_change"
            if [ "${line}" == "Average Response Time (Secs)(NA)" ]; then
                debug_log "calculating difference but not percentage difference"
                param_change=$(bc -l <<<"$baseline_param - $current_param")
            else
                param_change=$(echo "$baseline_param" "$current_param" | awk '{print ($1-$2)/$1*100}')
                param_change=$(echo $param_change | awk '{printf "%.0f\n", $1}')
            fi
            debug_log "Change in value of ${line}: ${param_change}"
            get_test_status $param_change "$line" "$test_case_name"
        done
        if [ $reg_status -eq 1 ]; then
            log_status_and_exit_ex "PASS" "Regression test for ${test_case} passed"
        fi

    #parameter values for baseline and current test run when a given parameter is under evaluation(single param_string)
    else
        baseline_param=$(testStats $baseline_test_run 0 "${param_string}" "$param_name")
        current_param=$(testStats $current_test_run 1 "${param_string}" "$param_name")
        param_change="${param_name}_change"
        param_change=`echo ${baseline_param} ${current_param}|awk '{print ($1-$2)/$1*100}'`
        param_change=$(echo $param_change | awk '{printf "%.0f\n", $1}')
        debug_log "Change in value of ${param_string}:${param_change}"
        get_test_status $param_change $param_string "$test_case_name"
    fi
}

function get_metric_deviation_multiple_filter(){
    test_run=$1
    filter_strings=$2
    test_case_name=$3
    param_list=$4
    if [ "XX$2" == "XXALL" ]; then
        i=1
        cat $param_list| while read line
        do
            param_list[$i]=$(echo ${line} | awk -F ',' '{print $i}')
            i=`expr $i + 1`
        done
        param1=$(grep -w "$param_list[1]" $NS_WDIR/logs/TR$test_run/summary_gdf.data | grep -w "$param_list[2]" | cut -d '|' -f6)
        param2=$(grep -w "$param_list[3]" $NS_WDIR/logs/TR$test_run/summary_gdf.data | cut -d '|' -f6)
        param_change=`echo ${param1} ${param2}|awk '{print ($1-$2)/$1*100}'`
        param_change=$(echo $param_change | awk '{printf "%.0f\n", $1}')
        debug_log "Change in value of ${param_list[1]}:${param_change}"
        get_test_status $param_change $param_list[1] "$test_case_name"
    fi 
}

function get_test_status() {
    diff=$1
    param_name=$2
    test_case=$3
    debug_log "get_test_status()| Diff = $diff"
    if [ $diff -gt 5 ]; then
        debug_log "Value inside failure loop is=$param_name"
        if [ "${param_name}" == "Active Vusers(NA)" ]; then
            continue
        else
            reg_status=0
            log_status_and_exit_ex "FAIL" "Regression test for ${test_case} failed;because difference of  baseline and current test metric ${param_name} = ${diff} is more than expected difference 5%"
        fi
    fi
}


function get_results(){
    BaseLine_Tsr_Directory_Regression1="$NS_WDIR/logs/tsr/072815_181628/2335/Regression001_results.csv"
    Test_Run=`grep -w $Tname $BaseLine_Tsr_Directory_Regression1 |cut -d ',' -f2`
    echo "$Test_Run"
    calculate_metric_deviation $Test_Run $TESTRUN_ID "ALL" "metric_value" "FCU with RampUp in Step mode" $Input_File
}


function main(){
get_results
}
main
exit 0
