$K_TNAME|$K_SCRIPT1|$K_SCRIPT2|$K_INLINE_DELAY|$K_GET_NO_INLINE|$K_AUTOFETCH

# NS TIMER API
FUNC-001-001|hpd_tours_timer_api|hpd_tours_timer_api|G_INLINE_DELAY G1 ALL 2 2000|G_GET_NO_INLINED_OBJ ALL 0|G_AUTO_FETCH_EMBEDDED ALL ALL 0
