#!/usr/bin/env bash
# Check status written by: Asheesh Kumar Tivaree
#Check status description: It is covered AutoFetch cases for HTTP/2.0 protocol.
#    Date Time: 09/09/16 10:54:38 AM
#  Description: Check status to validate cases for smoke
# 
# Conventions
#   1. Two(2) space indentation. No tabs
#   2. Variables and function starts with snake_case
#		3. Constants are declared with ALL_CAPS

# Source out required files
source $NS_WDIR/lib/automation_util

# Default Constants
PATH_TO_TEST_RUN="$NS_WDIR/logs/TR${T_RUN_ID}"
PARTITION_PATH="${PATH_TO_TEST_RUN}/$(get_test_partition)"
PROGRESS_REPORT_FILE="${PATH_TO_TEST_RUN}/progress.report"
DEBUG_LOG_FILE="${PATH_TO_TEST_RUN}/debug.log"
URL_REQ_FILE="${PATH_TO_TEST_RUN}/2*/ns_logs/req_rep/url_req*"
URL_REP_FILE="${PATH_TO_TEST_RUN}/2*/ns_logs/req_rep/url_rep*"
T_NAME="$(get_tname)"

# Entry point to check status
# Add cases to handle your validation
function main() {
	case $(get_tname) in
    "SMOKE-061-001") handle_Auto_Fetch_http2-001 ;;
    "SMOKE-061-002") handle_Auto_Fetch_http2-002 ;;
    "SMOKE-061-003") handle_Auto_Fetch_http2-003 ;;
    "SMOKE-061-004") handle_Auto_Fetch_http2-004 ;;
    "SMOKE-061-005") handle_Auto_Fetch_http2-005 ;;
    "SMOKE-061-006") handle_Auto_Fetch_http2-006 ;;
    "SMOKE-061-007") handle_Auto_Fetch_http2-007 ;;
    "SMOKE-061-008") handle_Auto_Fetch_http2-008 ;;
    "SMOKE-061-009") handle_Auto_Fetch_http2-009 ;;
    "SMOKE-061-010") handle_Auto_Fetch_http2-010 ;;
    "SMOKE-061-011") handle_Auto_Fetch_http2-011 ;;
    "SMOKE-061-012") handle_Auto_Fetch_http2-012 ;;
    "SMOKE-061-013") handle_Auto_Fetch_http2-013 ;;
    "SMOKE-061-014") handle_Auto_Fetch_http2-014 ;;
# End case def
		*) handle_unknown_case ;;
		?) handle_unknown_case ;;
  esac
}

# Helper function to log status
# Sets additional product id and
# category id
function handle_unknown_case() {
	error "Testcase name not found"
	log_status_and_exit_ex "FAIL" "Testcase name not found"
}

# TODO: 
# 1. Add logic to validate case smoke-001
# 2. Depending upon evaluation update the status with your own description

function get_expected_result()
{
echo "Future purpose"
}

function get_actual_result()
{ 
  connection_count=$(grep "HTTP TCP Conns" $PROGRESS_REPORT_FILE | cut -d '(' -f3 | awk '{print $1}' | awk -F '=' '{print $2}'|tail -1)
  get_total_stream_ids=$(grep -c "free->max_stream_id" $DEBUG_LOG_FILE)
  switching_protocol_count=$(grep -a "HTTP/1.1 101 Switching Protocols" $URL_REP_FILE | wc -l)
  Upgrade_header_count=$(grep -a "Upgrade: h2c" $URL_REQ_FILE | wc -l)
  Url_success=$(grep "Url  Report" $PROGRESS_REPORT_FILE | cut -d '/' -f2| awk '{print $2}')
  Url_completed=$(grep "Url  Report" $PROGRESS_REPORT_FILE | cut -d ':' -f3 | cut -d '/' -f1 | awk '{print $2}')
  if [ $Url_completed -eq $Url_success ];then
   Failure_reason=0
  else
   Failure_reason=$(grep "Url  Report" $PROGRESS_REPORT_FILE | cut -d '/' -f3 | cut -d ':' -f1)
  fi
}


function handle_Auto_Fetch_http2-001() {
get_expected_result
get_actual_result
debug_log "case1"
debug_log "failure reason is : $Failure_reason"
debug_log "completed url : $Url_completed"
debug_log "connection count : $connection_count"
debug_log "stream count : $get_total_stream_ids"
if [ $Failure_reason -eq 0 ];then
    if [ $Url_completed -eq 30 ];then
        if [ $connection_count -eq 2 ];then
            if [ $get_total_stream_ids -eq 28 ];then
                log_status_and_exit_ex "PASS" "HTTP2 Upgrade Mode- Enable AutoFetch without applying any pattern based filter on embedded URLs"
        else
            log_status_and_exit_ex "FAIL" "HTTP2 Upgrade Mode- Enable AutoFetch without applying any pattern based filter on embedded URLs: failed because expected stream count was 28 and actual is $get_total_stream_ids"
        fi
    else
        log_status_and_exit_ex "FAIL" "HTTP2 Upgrade Mode- Enable AutoFetch without applying any pattern based filter on embedded URLs: failed because expected connection count was 2 and actual is $connection_count"
    fi
else
    log_status_and_exit_ex "FAIL" "HTTP2 Upgrade Mode- Enable AutoFetch without applying any pattern based filter on embedded URLs: failed because completed URLs is not as per expectation"
fi
else
    log_status_and_exit_ex "FAIL" "HTTP2 Upgrade Mode- Enable AutoFetch without applying any pattern based filter on embedded URLs failed due to $Failure_reason error"
fi
}

function handle_Auto_Fetch_http2-002() {
get_expected_result
get_actual_result
debug_log "case2"
debug_log "failure reason is : $Failure_reason"
debug_log "completed url : $Url_completed"
debug_log "connection count : $connection_count"
debug_log "stream count : $get_total_stream_ids"
if [ $Failure_reason -eq 0 ];then
    if [ $Url_completed -eq 28 ];then
        if [ $connection_count -eq 1 ];then
            if [ $get_total_stream_ids -eq 27 ];then
            log_status_and_exit_ex "PASS" "HTTP2 Upgrade Mode- Enable AutoFetch by applying filter on domain pattern i.e include only same domain of embedded URLs as main URL"
            else
            log_status_and_exit_ex "FAIL" "HTTP2 Upgrade Mode- Enable AutoFetch by applying filter on domain pattern i.e include only same domain of embedded URLs as main URL: failed because expected stream count was 27 and actual is $get_total_stream_ids"
            fi
        else
        log_status_and_exit_ex "FAIL" "HTTP2 Upgrade Mode- Enable AutoFetch by applying filter on domain pattern i.e include only same domain of embedded URLs as main URL: failed because expected connection count was 1 and actual is $connection_count"
        fi
    else
    log_status_and_exit_ex "FAIL" "HTTP2 Upgrade Mode- Enable AutoFetch by applying filter on domain pattern i.e include only same domain of embedded URLs as main URL: failed because completed URLs is not as per expectation"
    fi
else
log_status_and_exit_ex "FAIL" "HTTP2 Upgrade Mode- Enable AutoFetch by applying filter on domain pattern i.e include only same domain of embedded URLs as main URL failed due to $Failure_reason error"
fi
}

function handle_Auto_Fetch_http2-003() {
get_expected_result
get_actual_result
debug_log "case3"
debug_log "failure reason is : $Failure_reason"
debug_log "completed url : $Url_completed"
debug_log "connection count : $connection_count"
debug_log "stream count : $get_total_stream_ids"
if [ $Failure_reason -eq 0 ];then
    if [ $Url_completed -eq 28 ];then
        if [ $connection_count -eq 1 ];then
            if [ $get_total_stream_ids -eq 27 ];then
                log_status_and_exit_ex "PASS" "HTTP2 Upgrade Mode- Enable AutoFetch by applying filter on domain pattern i.e exclude specified domain of embedded URLs"
            else
            log_status_and_exit_ex "FAIL" "HTTP2 Upgrade Mode- Enable AutoFetch by applying filter on domain pattern i.e exclude specified domain of embedded URLs: failed because expected stream count was 27 and actual is $get_total_stream_ids"
            fi
        else
        log_status_and_exit_ex "FAIL" "HTTP2 Upgrade Mode- Enable AutoFetch by applying filter on domain pattern i.e exclude specified domain of embedded URLs: failed because expected connection count was 1 and actual is $connection_count"
        fi
    else
    log_status_and_exit_ex "FAIL" "HTTP2 Upgrade Mode- Enable AutoFetch by applying filter on domain pattern i.e exclude specified domain of embedded URLs: failed because completed URLs is not as per expectation"
    fi
else
log_status_and_exit_ex "FAIL" "HTTP2 Upgrade Mode- Enable AutoFetch by applying filter on domain pattern i.e exclude specified domain of embedded URLs failed due to $Failure_reason error"
fi
}

function handle_Auto_Fetch_http2-004() {
debug_log "case4"
get_expected_result
get_actual_result
debug_log "failure reason is : $Failure_reason"
debug_log "completed url : $Url_completed"
debug_log "connection count : $connection_count"
debug_log "stream count : $get_total_stream_ids"
if [ $Failure_reason -eq 0 ];then
    if [ $Url_completed -eq 12 ];then
        if [ $connection_count -eq 1 ];then
            if [ $get_total_stream_ids -eq 11 ];then
                log_status_and_exit_ex "PASS" "HTTP2 Upgrade Mode- Enable AutoFetch by applying filter on URL pattern i.e include only *.gif type embedded URLs"
            else
            log_status_and_exit_ex "FAIL" "HTTP2 Upgrade Mode- Enable AutoFetch by applying filter on URL pattern i.e include only *.gif type embedded URLs: failed because expected stream count was 11 and actual is $get_total_stream_ids"
            fi
        else
        log_status_and_exit_ex "FAIL" "HTTP2 Upgrade Mode- Enable AutoFetch by applying filter on URL pattern i.e include only *.gif type embedded URLs: failed because expected connection count was 1 and actual is $connection_count"
        fi
    else
    log_status_and_exit_ex "FAIL" "HTTP2 Upgrade Mode- Enable AutoFetch by applying filter on URL pattern i.e include only *.gif type embedded URLs: failed because completed URLs is not as per expectation"
    fi
else
log_status_and_exit_ex "FAIL" "HTTP2 Upgrade Mode- Enable AutoFetch by applying filter on URL pattern i.e include only *.gif type embedded URLs failed due to $Failure_reason error"
fi
}

function handle_Auto_Fetch_http2-005() {
debug_log "case5"
get_expected_result
get_actual_result
debug_log "failure reason is : $Failure_reason"
debug_log "completed url : $Url_completed"
debug_log "connection count : $connection_count"
debug_log "stream count : $get_total_stream_ids"
if [ $Failure_reason -eq 0 ];then
    if [ $Url_completed -eq 14 ];then
        if [ $connection_count -eq 1 ];then
            if [ $get_total_stream_ids -eq 13 ];then
                log_status_and_exit_ex "PASS" "HTTP2 Upgrade Mode- Enable AutoFetch by applying filter on URL pattern i.e include only *.js *.jsp and *.css type embedded URLs"
            else
            log_status_and_exit_ex "FAIL" "HTTP2 Upgrade Mode- Enable AutoFetch by applying filter on URL pattern i.e include only *.js *.jsp and *.css type embedded URLs: failed because expected stream count was 13 and actual is $get_total_stream_ids"
            fi
        else
        log_status_and_exit_ex "FAIL" "HTTP2 Upgrade Mode- Enable AutoFetch by applying filter on URL pattern i.e include only *.js *.jsp and *.css type embedded URLs: failed because expected connection count was 1 and actual is $connection_count"
        fi
    else
    log_status_and_exit_ex "FAIL" "HTTP2 Upgrade Mode- Enable AutoFetch by applying filter on URL pattern i.e include only *.js *.jsp and *.css type embedded URLs: failed because completed URLs is not as per expectation"
    fi
else
log_status_and_exit_ex "FAIL" "HTTP2 Upgrade Mode- Enable AutoFetch by applying filter on URL pattern i.e include only *.js *.jsp and *.css type embedded URLs failed due to $Failure_reason error"
fi
}

function handle_Auto_Fetch_http2-006() {
get_expected_result
get_actual_result
debug_log "case6"
debug_log "failure reason is : $Failure_reason"
debug_log "completed url : $Url_completed"
debug_log "connection count : $connection_count"
debug_log "stream count : $get_total_stream_ids"
if [ $Failure_reason -eq 0 ];then
    if [ $Url_completed -eq 20 ];then
        if [ $connection_count -eq 2 ];then
            if [ $get_total_stream_ids -eq 18 ];then
                log_status_and_exit_ex "PASS" "HTTP2 Upgrade Mode- Enable AutoFetch by applying filter on URL pattern i.e exclude *.gif type embedded URLs"
            else
            log_status_and_exit_ex "FAIL" "HTTP2 Upgrade Mode- Enable AutoFetch by applying filter on URL pattern i.e exclude *.gif type embedded URLs: failed because expected stream count was 18 and actual is $get_total_stream_ids"
            fi
        else
        log_status_and_exit_ex "FAIL" "HTTP2 Upgrade Mode- Enable AutoFetch by applying filter on URL pattern i.e exclude *.gif type embedded URLs: failed because expected connection count was 2 and actual is $connection_count"
        fi
    else
    log_status_and_exit_ex "FAIL" "HTTP2 Upgrade Mode- Enable AutoFetch by applying filter on URL pattern i.e exclude *.gif type embedded URLs: failed because completed URLs is not as per expectation"
    fi
else
log_status_and_exit_ex "FAIL" "HTTP2 Upgrade Mode- Enable AutoFetch by applying filter on URL pattern i.e exclude *.gif type embedded URLs failed due to $Failure_reason error"
fi
}

function handle_Auto_Fetch_http2-007() {
debug_log "case7"
get_expected_result
get_actual_result
debug_log "failure reason is : $Failure_reason"
debug_log "completed url : $Url_completed"
debug_log "connection count : $connection_count"
debug_log "stream count : $get_total_stream_ids"
if [ $Failure_reason -eq 0 ];then
    if [ $Url_completed -eq 10 ];then
        if [ $connection_count -eq 2 ];then
            if [ $get_total_stream_ids -eq 8 ];then
                log_status_and_exit_ex "PASS" "HTTP2 Upgrade Mode- Enable AutoFetch by applying filter on URL pattern i.e exclude *.gif *.js and *.css type embedded URLs"
            else
            log_status_and_exit_ex "FAIL" "HTTP2 Upgrade Mode- Enable AutoFetch by applying filter on URL pattern i.e exclude *.gif *.js and *.css type embedded URLs: failed because expected stream count was 8 and actual is $get_total_stream_ids"
            fi
        else
        log_status_and_exit_ex "FAIL" "HTTP2 Upgrade Mode- Enable AutoFetch by applying filter on URL pattern i.e exclude *.gif *.js and *.css type embedded URLs: failed because expected connection count was 2 and actual is $connection_count"
        fi
    else
    log_status_and_exit_ex "FAIL" "HTTP2 Upgrade Mode- Enable AutoFetch by applying filter on URL pattern i.e exclude *.gif *.js and *.css type embedded URLs: failed because completed URLs is not as per expectation"
    fi
else
log_status_and_exit_ex "FAIL" "HTTP2 Upgrade Mode- Enable AutoFetch by applying filter on URL pattern i.e exclude *.gif *.js and *.css type embedded URLs failed due to $Failure_reason error"
fi
}


function handle_Auto_Fetch_http2-008() {
get_expected_result
get_actual_result
debug_log "case8"
debug_log "failure reason is : $Failure_reason"
debug_log "completed url : $Url_completed"
debug_log "connection count : $connection_count"
debug_log "stream count : $get_total_stream_ids"
if [ $Failure_reason -eq 0 ];then
    if [ $Url_completed -eq 30 ];then
        if [ $connection_count -eq 2 ];then
            if [ $get_total_stream_ids -eq 30 ];then
                log_status_and_exit_ex "PASS" "HTTP2 Prior Knowledge Mode- Enable AutoFetch without applying any pattern based filter on embedded URLs"
        else
            log_status_and_exit_ex "FAIL" "HTTP2 Prior Knowledge Mode- Enable AutoFetch without applying any pattern based filter on embedded URLs: failed because expected stream count was 30 and actual is $get_total_stream_ids"
        fi
    else
        log_status_and_exit_ex "FAIL" "HTTP2 Prior Knowledge Mode- Enable AutoFetch without applying any pattern based filter on embedded URLs: failed because expected connection count was 2 and actual is $connection_count"
    fi
else
    log_status_and_exit_ex "FAIL" "HTTP2 Prior Knowledge Mode- Enable AutoFetch without applying any pattern based filter on embedded URLs: failed because completed URLs is not as per expectation"
fi
else
    log_status_and_exit_ex "FAIL" "HTTP2 Prior Knowledge Mode- Enable AutoFetch without applying any pattern based filter on embedded URLs failed due to $Failure_reason error"
fi
}

function handle_Auto_Fetch_http2-009() {
get_expected_result
get_actual_result
debug_log "case9"
debug_log "failure reason is : $Failure_reason"
debug_log "completed url : $Url_completed"
debug_log "connection count : $connection_count"
debug_log "stream count : $get_total_stream_ids"
if [ $Failure_reason -eq 0 ];then
    if [ $Url_completed -eq 28 ];then
        if [ $connection_count -eq 1 ];then
            if [ $get_total_stream_ids -eq 28 ];then
            log_status_and_exit_ex "PASS" "HTTP2 Prior Knowledge Mode- Enable AutoFetch by applying filter on domain pattern i.e include only same domain of embedded URLs as main URL"
            else
            log_status_and_exit_ex "FAIL" "HTTP2 Prior Knowledge Mode- Enable AutoFetch by applying filter on domain pattern i.e include only same domain of embedded URLs as main URL: failed because expected stream count was 28 and actual is $get_total_stream_ids"
            fi
        else
        log_status_and_exit_ex "FAIL" "HTTP2 Prior Knowledge Mode- Enable AutoFetch by applying filter on domain pattern i.e include only same domain of embedded URLs as main URL: failed because expected connection count was 1 and actual is $connection_count"
        fi
    else
    log_status_and_exit_ex "FAIL" "HTTP2 Prior Knowledge Mode- Enable AutoFetch by applying filter on domain pattern i.e include only same domain of embedded URLs as main URL: failed because completed URLs is not as per expectation"
    fi
else
log_status_and_exit_ex "FAIL" "HTTP2 Prior Knowledge Mode- Enable AutoFetch by applying filter on domain pattern i.e include only same domain of embedded URLs as main URL failed due to $Failure_reason error"
fi
}

function handle_Auto_Fetch_http2-010() {
get_expected_result
get_actual_result
debug_log "case10"
debug_log "failure reason is : $Failure_reason"
debug_log "completed url : $Url_completed"
debug_log "connection count : $connection_count"
debug_log "stream count : $get_total_stream_ids"
if [ $Failure_reason -eq 0 ];then
    if [ $Url_completed -eq 28 ];then
        if [ $connection_count -eq 1 ];then
            if [ $get_total_stream_ids -eq 28 ];then
                log_status_and_exit_ex "PASS" "HTTP2 Prior Knowledge Mode- Enable AutoFetch by applying filter on domain pattern i.e exclude specified domain of embedded URLs"
            else
            log_status_and_exit_ex "FAIL" "HTTP2 Prior Knowledge Mode- Enable AutoFetch by applying filter on domain pattern i.e exclude specified domain of embedded URLs: failed because expected stream count was 28 and actual is $get_total_stream_ids"
            fi
        else
        log_status_and_exit_ex "FAIL" "HTTP2 Prior Knowledge Mode- Enable AutoFetch by applying filter on domain pattern i.e exclude specified domain of embedded URLs: failed because expected connection count was 1 and actual is $connection_count"
        fi
    else
    log_status_and_exit_ex "FAIL" "HTTP2 Prior Knowledge Mode- Enable AutoFetch by applying filter on domain pattern i.e exclude specified domain of embedded URLs: failed because completed URLs is not as per expectation"
    fi
else
log_status_and_exit_ex "FAIL" "HTTP2 Prior Knowledge Mode- Enable AutoFetch by applying filter on domain pattern i.e exclude specified domain of embedded URLs failed due to $Failure_reason error"
fi
}

function handle_Auto_Fetch_http2-011() {
debug_log "case11"
get_expected_result
get_actual_result
debug_log "failure reason is : $Failure_reason"
debug_log "completed url : $Url_completed"
debug_log "connection count : $connection_count"
debug_log "stream count : $get_total_stream_ids"
if [ $Failure_reason -eq 0 ];then
    if [ $Url_completed -eq 12 ];then
        if [ $connection_count -eq 1 ];then
            if [ $get_total_stream_ids -eq 12 ];then
                log_status_and_exit_ex "PASS" "HTTP2 Prior Knowledge Mode- Enable AutoFetch by applying filter on URL pattern i.e include only *.gif type embedded URLs"
            else
            log_status_and_exit_ex "FAIL" "HTTP2 Prior Knowledge Mode- Enable AutoFetch by applying filter on URL pattern i.e include only *.gif type embedded URLs: failed because expected stream count was 12 and actual is $get_total_stream_ids"
            fi
        else
        log_status_and_exit_ex "FAIL" "HTTP2 Prior Knowledge Mode- Enable AutoFetch by applying filter on URL pattern i.e include only *.gif type embedded URLs: failed because expected connection count was 1 and actual is $connection_count"
        fi
    else
    log_status_and_exit_ex "FAIL" "HTTP2 Prior Knowledge Mode- Enable AutoFetch by applying filter on URL pattern i.e include only *.gif type embedded URLs: failed because completed URLs is not as per expectation"
    fi
else
log_status_and_exit_ex "FAIL" "HTTP2 Prior Knowledge Mode- Enable AutoFetch by applying filter on URL pattern i.e include only *.gif type embedded URLs failed due to $Failure_reason error"
fi
}

function handle_Auto_Fetch_http2-012() {
debug_log "case12"
get_expected_result
get_actual_result
debug_log "failure reason is : $Failure_reason"
debug_log "completed url : $Url_completed"
debug_log "connection count : $connection_count"
debug_log "stream count : $get_total_stream_ids"
if [ $Failure_reason -eq 0 ];then
    if [ $Url_completed -eq 14 ];then
        if [ $connection_count -eq 1 ];then
            if [ $get_total_stream_ids -eq 14 ];then
                log_status_and_exit_ex "PASS" "HTTP2 Prior Knowledge Mode- Enable AutoFetch by applying filter on URL pattern i.e include only *.js *.jsp and *.css type embedded URLs"
            else
            log_status_and_exit_ex "FAIL" "HTTP2 Prior Knowledge Mode- Enable AutoFetch by applying filter on URL pattern i.e include only *.js *.jsp and *.css type embedded URLs: failed because expected stream count was 14 and actual is $get_total_stream_ids"
            fi
        else
        log_status_and_exit_ex "FAIL" "HTTP2 Prior Knowledge Mode- Enable AutoFetch by applying filter on URL pattern i.e include only *.js *.jsp and *.css type embedded URLs: failed because expected connection count was 1 and actual is $connection_count"
        fi
    else
    log_status_and_exit_ex "FAIL" "HTTP2 Prior Knowledge Mode- Enable AutoFetch by applying filter on URL pattern i.e include only *.js *.jsp and *.css type embedded URLs: failed because completed URLs is not as per expectation"
    fi
else
log_status_and_exit_ex "FAIL" "HTTP2 Prior Knowledge Mode- Enable AutoFetch by applying filter on URL pattern i.e include only *.js *.jsp and *.css type embedded URLs failed due to $Failure_reason error"
fi
}

function handle_Auto_Fetch_http2-013() {
get_expected_result
get_actual_result
debug_log "case13"
debug_log "failure reason is : $Failure_reason"
debug_log "completed url : $Url_completed"
debug_log "connection count : $connection_count"
debug_log "stream count : $get_total_stream_ids"
if [ $Failure_reason -eq 0 ];then
    if [ $Url_completed -eq 20 ];then
        if [ $connection_count -eq 2 ];then
            if [ $get_total_stream_ids -eq 20 ];then
                log_status_and_exit_ex "PASS" "HTTP2 Prior Knowledge Mode- Enable AutoFetch by applying filter on URL pattern i.e exclude *.gif type embedded URLs"
            else
            log_status_and_exit_ex "FAIL" "HTTP2 Prior Knowledge Mode- Enable AutoFetch by applying filter on URL pattern i.e exclude *.gif type embedded URLs: failed because expected stream count was 20 and actual is $get_total_stream_ids"
            fi
        else
        log_status_and_exit_ex "FAIL" "HTTP2 Prior Knowledge Mode- Enable AutoFetch by applying filter on URL pattern i.e exclude *.gif type embedded URLs: failed because expected connection count was 2 and actual is $connection_count"
        fi
    else
    log_status_and_exit_ex "FAIL" "HTTP2 Prior Knowledge Mode- Enable AutoFetch by applying filter on URL pattern i.e exclude *.gif type embedded URLs: failed because completed URLs is not as per expectation"
    fi
else
log_status_and_exit_ex "FAIL" "HTTP2 Prior Knowledge Mode- Enable AutoFetch by applying filter on URL pattern i.e exclude *.gif type embedded URLs failed due to $Failure_reason error"
fi
}

function handle_Auto_Fetch_http2-014() {
debug_log "case14"
get_expected_result
get_actual_result
debug_log "failure reason is : $Failure_reason"
debug_log "completed url : $Url_completed"
debug_log "connection count : $connection_count"
debug_log "stream count : $get_total_stream_ids"
if [ $Failure_reason -eq 0 ];then
    if [ $Url_completed -eq 10 ];then
        if [ $connection_count -eq 2 ];then
            if [ $get_total_stream_ids -eq 10 ];then
                log_status_and_exit_ex "PASS" "HTTP2 Prior Knowledge Mode- Enable AutoFetch by applying filter on URL pattern i.e exclude *.gif *.js and *.css type embedded URLs"
            else
            log_status_and_exit_ex "FAIL" "HTTP2 Prior Knowledge Mode- Enable AutoFetch by applying filter on URL pattern i.e exclude *.gif *.js and *.css type embedded URLs: failed because expected stream count was 10 and actual is $get_total_stream_ids"
            fi
        else
        log_status_and_exit_ex "FAIL" "HTTP2 Prior Knowledge Mode- Enable AutoFetch by applying filter on URL pattern i.e exclude *.gif *.js and *.css type embedded URLs: failed because expected connection count was 2 and actual is $connection_count"
        fi
    else
    log_status_and_exit_ex "FAIL" "HTTP2 Prior Knowledge Mode- Enable AutoFetch by applying filter on URL pattern i.e exclude *.gif *.js and *.css type embedded URLs: failed because completed URLs is not as per expectation"
    fi
else
log_status_and_exit_ex "FAIL" "HTTP2 Prior Knowledge Mode- Enable AutoFetch by applying filter on URL pattern i.e exclude *.gif *.js and *.css type embedded URLs failed due to $Failure_reason error"
fi
}

# Do not override it
main
exit 0
