/*-----------------------------------------------------------------------------
    Name: flow
    Generated By: netstorm
    Date of generation: 08/24/2013 10:17:38
    Flow details:
    Modification History:
-----------------------------------------------------------------------------*/
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "ns_string.h"


#define NS_DECODE_TRIPLETS 1 
#define SECRET_KEY "it is Vijay's secret key" 
#define DECODED_FILE "DecodedCaptchaList.dat" 
#define SAVE_CAPTCHAS_TO_FILE 


void get_decoded_captcha() { 
    char output[32] = "0";
    char *encrypted_captcha ; 

    ns_advance_param("CaptchaFP"); 
    encrypted_captcha = ns_eval_string("{CaptchaFP}");
    
	/*
    #ifdef NS_DEBUG_ON
    printf("[INFO] Encrypted Captcha = [%s]\n", encrypted_captcha);
    printf("[INFO] NS_DECODE_TRIPLETS = %d\n",NS_DECODE_TRIPLETS);
    #endif 
    */    
    
	int status = ns_decode_3des(SECRET_KEY, encrypted_captcha, output, 32, NS_DECODE_TRIPLETS); 

    //printf("[INFO] status = %d\n", status) ; 

    if (status == -1) 
        return ;

    ns_save_string(output,"DecryptedCaptchaDP"); 

    /*#ifdef SAVE_CAPTCHAS_TO_FILE 
    ns_save_data_ex("/tmp/DecodedCaptchaList.dat", NS_TRUNC_FILE, "%s,%s", output,encrypted_captcha);
    #endif 

    #ifdef NS_DEBUG_ON
    printf("[INFO] Encrypted Captcha = [%s]\n", encrypted_captcha);
    printf("[INFO] Decrypted Captcha = [%s]\n", ns_eval_string("{DecryptedCaptchaDP}")); 
    #endif*/  
} 


void flow(){
    get_decoded_captcha();

    ns_web_url ("tiny",
        "URL=http://127.0.0.1/tiny",
        "HEADER=Captcha: {DecryptedCaptchaDP}", 
        "HEADER=CaptchaFP: {CaptchaFP}", 
    );

    ns_page_think_time(0);
}
