/*-----------------------------------------------------------------------------
    Name: exit_script
    Generated By: root
    Date of generation: 04/18/2015 11:46:10
    Flow details:
    Build details: 4.1.2 (build# 1)
    Modification History:
-----------------------------------------------------------------------------*/

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "ns_string.h"

int exit_script()
{
    return 0;
}
