/*-----------------------------------------------------------------------------
    Name: flow
    Generated By: root
    Date of generation: 04/18/2015 11:46:10
    Flow details:
    Build details: 4.1.2 (build# 1)
    Modification History:
-----------------------------------------------------------------------------*/

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "ns_string.h"

void flow()
{
    ns_web_url ("First_Page",
        "URL=http://127.0.0.1/ManRedirect/manual_page1.html",
        "REDIRECT=NO",
        "LOCATION=http://127.0.0.1/tours/index.html",
        INLINE_URLS,
            "URL=http://127.0.0.1/tours/index.html", END_INLINE,
    );


    ns_web_url ("Second_Page",
        "URL=http://127.0.0.1/ManRedirect/manual_page2.html",
        "REDIRECT=YES",
        "LOCATION=http://127.0.0.1/ManRedirect/manual_page6.html",
         INLINE_URLS,
             "URL=http://127.0.0.1/ManRedirect/manual_page6.html", END_INLINE,
    );
}
