#!/usr/bin/env bash

. $NS_WDIR/lib/automation_util

T_NAME=$(get_tname)
PAGE_FAIL=$(grep --binary-files=text -r "Page Failures" $NS_WDIR/logs/TR$T_RUN_ID/summary.data |awk '{print $2}' | cut -d '|' -f2)
AUTH_HEADER=$(grep --binary-files=text -w "WWW-Authenticate:" $T_ID_REQ_PATH/url_rep_0_0_0_0_0_0_0_0_0.dat |cut -d ':' -f2)
SEARCH_VAR=$(grep --binary-files=text -o "?response from 38 serevr for" $T_ID_REQ_PATH/url_req_0_0_0_1_0_0_0_1_0.dat |wc -l)
PAGE_DUMP=$(grep --binary-files=text -o "Flowers are modified leaves possessed only by the group known" $T_ID_REQ_PATH/../../page_dump/docs/0\:0\:Main_apache_PageDump\:flower_html\:0.orig)



if [ "XX$T_NAME" == "XXSMOKE-002-001" ];then 
    debug_log "fail url count=${SD_URLFailures};success url count=${SD_TotalSuccURL};header value=$AUTH_HEADER"
    
    if [ "XX$SD_URLFailures" == "XX0" ] && \
       [ "XX$SD_TotalSuccURL" == "XX6" ] && \
       [ "$AUTH_HEADER" == " Basic realm=\"Basic Authentication\"" ];then
        log_status_and_exit_ex "PASS" "Http authentication basic for apache main param session Passed"
    else
	log_status_and_exit_ex "FAIL" "Http authentication basic for apache main param session Failed" 
    fi
fi

if [ "XX$T_NAME" == "XXSMOKE-002-002" ];then
    debug_log "fail url count=${SD_URLFailures};success url count=${SD_TotalSuccURL};header value=${AUTH_HEADER}"
    
    if [ "XX$SD_URLFailures" == "XX0" ] && \
       [ "XX$SD_TotalSuccURL" == "XX4" ] && \
       [ "$AUTH_HEADER" == " Basic realm=\"Basic Authentication\"" ];then
        log_status_and_exit_ex "PASS" "Http authentication basic for apache main param use Passed"
    else
        log_status_and_exit_ex "FAIL" "Http authentication basic for apache main param use Failed"
    fi
fi


if [ "XX$T_NAME" == "XXSMOKE-002-003" ];then
    debug_log "fail url count=${SD_URLFailures};success url count=${SD_TotalSuccURL};header value=${AUTH_HEADER} ; PAGE_DUMP=${PAGE_DUMP}"

    if [ "XX$SD_URLFailures" == "XX0" ] && \
       [ "XX$SD_TotalSuccURL" == "XX2" ] && \
       [ "$AUTH_HEADER" == " Basic realm=\"Basic Authentication\"" ] && \
       [ "XX$PAGE_DUMP" == "XXFlowers are modified leaves possessed only by the group known" ]; then
        log_status_and_exit_ex "PASS" "Http authentication basic for apache for Page Dump Passed"
    else
        log_status_and_exit_ex "FAIL" "Http authentication basic for apache for PageDump Failed"
    fi
fi


if [ "XX$T_NAME" == "XXSMOKE-002-004" ];then
    debug_log "fail url count=${SD_URLFailures};success url count=${SD_TotalSuccURL};header value=${AUTH_HEADER} ; SEARCH_VAR=${SEARCH_VAR}"
    
    if [ "XX$SD_URLFailures" == "XX1" ] && \
       [ "XX$SD_TotalSuccURL" == "XX4" ] && \
       [ "$AUTH_HEADER" == " Basic realm=\"Basic Authentication\"" ]; then
       #[ "XX$SEARCH_VAR" == "XX2" ]; then
        log_status_and_exit_ex "PASS" "Http authentication basic main with keep alive Passed"
    else
        log_status_and_exit_ex "FAIL" "Http authentication basic main with keep alive Failed"
    fi
fi


if [ "XX$T_NAME" == "XXSMOKE-002-005" ];then
    debug_log "PAGE_FAIL=${PAGE_FAIL};success url count=${SD_TotalSuccURL};header value=${AUTH_HEADER}; SEARCH_VAR=${SEARCH_VAR}"

    if [ "XX$PAGE_FAIL" == "XX2" ] && \
       [ "XX$SD_TotalSuccURL" == "XX4" ] && \
       [ "$AUTH_HEADER" == " Basic realm=\"Basic Authentication\"" ]; then
       #[ "XX$SEARCH_VAR" == "XX2" ]; then
        log_status_and_exit_ex "PASS" "Http authentication basic main cvfail without keepalive Passed"
    else
        log_status_and_exit_ex "FAIL" "Http authentication basic main cvfail without keepalive Failed"
    fi
fi


exit 0
