/*-----------------------------------------------------------------------------
    Name: flow1
    Generated By: netstorm
    Date of generation: 06/20/2012 04:39:39
    Flow details:
    Modification History:
-----------------------------------------------------------------------------*/

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "ns_string.h"

void flow1()
{
    ns_web_url ("index",
        "URL=http://127.0.0.1/Redirection/%Page",
        "METHOD=%Method",
    );

    ns_page_think_time(0);

}
