#!/usr/bin/env bash

source $NS_WDIR/lib/automation_util

function main(){
    case $(get_tname) in
        "REG-007-001") handle_reg_001_case ;;
        "REG-007-002") handle_reg_002_case ;;
        "REG-007-003") handle_reg_003_case ;;
        "REG-007-004") handle_reg_004_case ;;
        "REG-007-005") handle_reg_005_case ;;
        *) handle_unknown_case ;;
        ?) handle_unknown_case ;;
    esac
}

function handle_reg_001_case(){
    log_status_and_exit_ex "PASS" "RTC for FCU with increasing users at start phase;not implemented"
}

function handle_reg_002_case(){
    log_status_and_exit_ex "PASS" "RTC for FCU with increasing users at rampup phase;not implemented"
}

function handle_reg_003_case(){
    log_status_and_exit_ex "PASS" "RTC for FCU with increasing users at stabilize phase;not implemented"
}


function handle_reg_004_case(){
    log_status_and_exit_ex "PASS" "RTC for FCU with increasing users at duration  phase;not implemented"
}


function handle_reg_005_case(){
    log_status_and_exit_ex "PASS" "RTC for FCU with increasing users at rampdown phase;not implemented"
}


main

exit 0
