#!/bin/bash

. $NS_WDIR/lib/automation_util
#fill_report_summary
T_NAME=$(get_tname)
PAGE_FAIL=`grep -r "Page Failures" $NS_WDIR/logs/TR$T_RUN_ID/summary.data |awk '{print $2}' | cut -d '|' -f2`
echo "Page fail check="$PAGE_FAIL


#Cases for Basic Authentication

if [ "XX$T_NAME" == "XXHttp_auth_Basic_apache_main_param_session" ];then 
		 AUTH_HEADER=`grep -w "WWW-Authenticate:" $T_ID_REQ_PATH/url_rep_0_0_0_0_0_0_0_0_0.dat |cut -d ':' -f2`
		 echo "Auth header is="$AUTH_HEADER
		 if [ "XX$SD_URLFailures" == "XX0" ] && [ "XX$SD_TotalSuccURL" == "XX6" ] && [ "$AUTH_HEADER" == " Basic realm=\"Basic Authentication\"" ];then
			    log_status_and_exit_ex "PASS" "$T_NAME passed"
			    else
			    log_status_and_exit_ex "FAIL" "$T_NAME failed"
	         fi 
fi

if [ "XX$T_NAME" == "XXHttp_auth_Basic_apache_main_param_use" ];then
                 AUTH_HEADER=`grep -w "WWW-Authenticate:" $T_ID_REQ_PATH/url_rep_0_0_0_0_0_0_0_0_0.dat |cut -d ':' -f2`
                 echo "Auth header is="$AUTH_HEADER
                 if [ "XX$SD_URLFailures" == "XX0" ] && [ "XX$SD_TotalSuccURL" == "XX4" ] && [ "$AUTH_HEADER" == " Basic realm=\"Basic Authentication\"" ];then
                 #if [ "XX$SD_URLFailures" == "XX0" ] && [ "XX$SD_TotalSuccURL" == "XX4" ];then
                            log_status_and_exit_ex "PASS" "$T_NAME passed"
                            else
                            log_status_and_exit_ex "FAIL" "$T_NAME failed"
                 fi
fi

if [ "XX$T_NAME" == "XXHttp_auth_Basic_apache_PageDump" ];then
                 AUTH_HEADER=`grep -w "WWW-Authenticate:" $T_ID_REQ_PATH/url_rep_0_0_0_0_0_0_0_0_0.dat |cut -d ':' -f2`
                 echo "Auth header is="$AUTH_HEADER
                PAGE_DUMP=`grep -o "docs/127.0.0.1/BasicDigest/0:0:Main_apache_PageDump:flower_html:0" $T_ID_REQ_PATH/page_dump.txt`	 
		if [ "XX$SD_URLFailures" == "XX0" ] && [ "XX$SD_TotalSuccURL" == "XX2" ] && [ "$AUTH_HEADER" == " Basic realm=\"Basic Authentication\"" ] && [ "XX$PAGE_DUMP" == "XXdocs/127.0.0.1/BasicDigest/0:0:Main_apache_PageDump:flower_html:0" ]; then
                            log_status_and_exit_ex "PASS" "$T_NAME passed"
                            else
                            log_status_and_exit_ex "FAIL" "$T_NAME failed"
                 fi
fi

if [ "XX$T_NAME" == "XXHttp_auth_Basic_main_CheckWithKA" ];then
                 AUTH_HEADER=`grep -w "WWW-Authenticate:" $T_ID_REQ_PATH/url_rep_0_0_0_0_0_0_0_0_0.dat |cut -d ':' -f2`
                 SEARCH_VAR=`grep -o "?response from 82 serevr for" $T_ID_REQ_PATH/url_req_0_0_0_1_0_0_0_1_0.dat |wc -l`
                if [ "XX$SD_URLFailures" == "XX0" ] && [ "XX$SD_TotalSuccURL" == "XX5" ] && [ "$AUTH_HEADER" == " Basic realm=\"Basic Authentication\"" ] && [ "XX$SEARCH_VAR" == "XX2" ]; then
                            log_status_and_exit_ex "PASS" "$T_NAME passed"
                            else
                            log_status_and_exit_ex "FAIL" "$T_NAME failed"
                 fi
fi



if [ "XX$T_NAME" == "XXHttp_auth_Basic_main_CVfailWithOutKA" ];then
                 AUTH_HEADER=`grep -w "WWW-Authenticate:" $T_ID_REQ_PATH/url_rep_0_0_0_0_0_0_0_0_0.dat |cut -d ':' -f2`
                 SEARCH_VAR=`grep -o "?response from 82 serevr for" $T_ID_REQ_PATH/url_req_0_0_0_1_0_0_0_1_0.dat |wc -l`
                if [ "XX$PAGE_FAIL" == "XX1" ] && [ "XX$SD_TotalSuccURL" == "XX5" ] && [ "$AUTH_HEADER" == " Basic realm=\"Basic Authentication\"" ] && [ "XX$SEARCH_VAR" == "XX2" ]; then
                            log_status_and_exit_ex "PASS" "$T_NAME passed"
                            else
                            log_status_and_exit_ex "FAIL" "$T_NAME failed"
                 fi
fi

exit 0
