#!/usr/bin/env bash

#python /home/netstorm/test/SmokeTest_NS/testcases/SmokeTest_Auth_Basic/Change_Httpd.py 192.168.1.82 Ntlm_Smoke

# Add rmon command to copy httpd file of ntlm case


sleep 10

# Add rmon command to resart httpd server for ntlm case

exit 0
