$K_TNAME|$K_NUM_USERS|$K_RAMP_UP_TIME|$K_DURATION|$K_RAMP_DOWN_TIME|$K_SCRIPT|$K_SVR_HOST|$K_NEW_USER|$K_HIERARICHAL_VIEW|$K_User_CleanUp

#G_USER_CLEANUP_MSECS ALL 0 . then user_cleanup display in debug log and NUM_NVM 1 Machine then for 1 user 2 user_cleanup
SMOKE-043-001|1|ALL RATE 120 M LINEARLY|SESSIONS 10|ALL TIME 00:00:30 LINEARLY|hpd_tours|127.0.0.1 10.10.30.96 -|ALL 1|default|G_USER_CLEANUP_MSECS ALL 0

#END_ITERATION


