/*-----------------------------------------------------------------------------
    Name: flow
    Generated By: netstorm
    Date of generation: 06/19/2012 01:35:43
    Flow details:
    Modification History:
-----------------------------------------------------------------------------*/

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "ns_string.h"
#define %API_TYPE
#define TEST_TYPE %TEST_CASE_TYPE_NUM

char *name=%FILE_NAME ; //File name with or without path.
int mode=%FILE_MODE ; //NS_APPEND_FILE && NS_TRUNC_FILE



void call_to_ns_url_get_resp_msg_api()
{
    int size;
    char *resp = ns_url_get_resp_msg(&size);
    int return_val = ns_save_data_ex(name, mode,"%s", resp);
    fprintf(stderr, "Resp = %s\n", resp);
}

void flow() {
    ns_start_transaction("URLRespMsgAPI");
    ns_web_url ("index",
        "URL=http://10.10.30.96/hpd_url.html",
        "HEADER=Accept-Language:en-us,en;q=0.5",
        "PreSnapshot=webpage_13946124026631.png",
        "Snapshot=webpage_13946124027021.png",
        "POSTURLCALLBACK=call_to_ns_url_get_resp_msg_api"
        ) 
    ns_page_think_time(0.2);
    ns_end_transaction("URLRespMsgAPI", NS_AUTO_STATUS);
}

