#----------------------------------------------------------------------------------------------------#  
#  Generated by needle                                                                            #
#  Convention: ALL variables starts with K followed by underscore and appropriate name               #
#  Note: Do not use blank line and spaces. Comments are allowed                                      #
#----------------------------------------------------------------------------------------------------#
$K_TNAME|$K_NUM_USERS|$K_RAMP_UP_TIME|$K_DURATION|$K_RAMP_DOWN_TIME|$K_SCRIPT|$K_SVR_HOST|$K_RR_MODE|$K_REPORTING|$K_SESSION_PACING|$K_O_THINK_TIME|$K_THINK_TIME|$K_NEW_USER|$K_TRACING|$K_HIERARICHAL_VIEW|$K_MAX_CON_PER_VUSER|$K_KA_PCT

#Enable DEBUG_TRACE and making opening and closing conection 
SMOKE-050-001|1|ALL IMMEDIATELY|SESSIONS 1|ALL IMMEDIATELY|hpd_tours|127.0.0.1 10.10.30.96 -|1|ALL 1|ALL 1 0 2000|ALL ALL 1|ALL ALL 3 10 50|#|ALL 0 0 0 0|default|#|#

#Enable DEBUG_TRACE and G_MAX_CON_PER_VUSER and making opening and closing conection
SMOKE-050-002|1|ALL IMMEDIATELY|SESSIONS 1|ALL IMMEDIATELY|hpd_tours|127.0.0.1 10.10.30.96 -|1|ALL 1|ALL 1 0 2000|ALL ALL 1|ALL ALL 3 10 50|#|ALL 0 0 0 0|default|G_MAX_CON_PER_VUSER ALL 0 1 1 1 1 1|#

#Enable DEBUG_TRACE and making opening and closing conection
SMOKE-050-003|1|ALL IMMEDIATELY|SESSIONS 5|ALL IMMEDIATELY|hpd_tours|127.0.0.1 10.10.30.96 -|1|ALL 1|ALL 1 0 2000|ALL ALL 1|ALL ALL 3 10 50|#|ALL 0 0 0 0|default|#|#

#Enable DEBUG_TRACE and G_NEW_USER_ON_SESSION and making opening and closing conection
SMOKE-050-004|1|ALL IMMEDIATELY|SESSIONS 5|ALL IMMEDIATELY|hpd_tours|127.0.0.1 10.10.30.96 -|1|ALL 1|ALL 1 0 2000|ALL ALL 1|ALL ALL 3 10 50|G_NEW_USER_ON_SESSION ALL 1|ALL 0 0 0 0|default|#|#

#Enable DEBUG_TRACE and G_KA_PCT and making opening and closing conection
SMOKE-050-005|1|ALL IMMEDIATELY|SESSIONS 1|ALL IMMEDIATELY|hpd_tours|127.0.0.1 10.10.30.96 -|1|ALL 1|ALL 1 0 2000|ALL ALL 1|ALL ALL 3 10 50|#|ALL 0 0 0 0|default|#|G_KA_PCT ALL 0
#END_ITERATION
