#!/usr/bin/env bash

source $NS_WDIR/lib/automation_util
CYCLE_SUM_REPORT="/home/netstorm/work/logs/tsr/${TEST_CYCLE_NUM}/cycle_summary.report"
USER_TEST_TIME_FILE="/home/netstorm/work/users/user_test_times.dat"
PRE_TEST_SETUP_REPORT="$TS_LOG_DIR/SmokeTest_API_1_1/pre_test_setup.report"
T_NAME=$(get_tname)
LOG_FILE="/home/netstorm/work/logs"

if [ "$T_NAME" == "SMOKE-031-001" ];then
	before_test_execution_time_sec=$(grep "BEFORE_TEST_EXECUTION_TIME" "$PRE_TEST_SETUP_REPORT" | cut -d'=' -f2 |  awk -F: '{ print ($1 * 3600) + ($2 * 60) + $3 }')
	after_test_execution_time_sec=$(sed -n 3p $USER_TEST_TIME_FILE | awk -F'|' {'print $2'} | awk -F: '{ print ($1 * 3600) + ($2 * 60) + $3 }')
	actual_time_diff=$((after_test_execution_time_sec - before_test_execution_time_sec))
	debug_log "actual_time_diff = $actual_time_diff"
	
	#declaring array of all the TRs that run	
	tr_array=($(grep "SmokeTest_" $CYCLE_SUM_REPORT| awk '{print $3}'))

	##current TR is not present in tr_array so adding current TR to array by increament 1 to the last element of array
	tr_array=("${tr_array[@]}" "$((`echo ${tr_array[-1]}`+1))")
	
	no_of_testrun=${#tr_array[@]}
	time_sec=0
	for ((i=0;i<$no_of_testrun;i++));do
		tr_time=$(awk -F"|" '{print $(NF-1)}' "${LOG_FILE}/TR${tr_array[$i]}/summary.top" | awk -F: '{print $1*3600 + $2*60 +$3}')
		time_sec=$((time_sec+tr_time))
	done

	debug_log "No. of testrun =$no_of_testrun ; total time execution =$time_sec"

	no_test_after_execution=$(sed -n 3p $USER_TEST_TIME_FILE | awk -F'|' {'print $3'})
	no_of_test_run_before_execution=$(grep "NO_OF_TEST_RUN_BEFORE_EXECUTION" "$PRE_TEST_SETUP_REPORT" | cut -d'=' -f2)
	test_run_diff=$((no_test_after_execution - no_of_test_run_before_execution))
	
	if [ "$no_of_testrun" -eq "$test_run_diff" ] && [ "$time_sec" -eq "$actual_time_diff" ];then
		debug_log "time taken by all the testcase is equal to the expected time "
	    log_status_and_exit_ex "PASS" "testcase passed for no. of test run and time"
	else
		log_status_and_exit_ex "FAIL" "testcase failed for no. of test run and time"
	fi

else

log_status_and_exit_ex "FAIL" "testcase not found"

fi

exit 0
