/*-----------------------------------------------------------------------------
    Name: flow
    Recorded By: netstorm
    Date of recording: 04/01/2015 07:20:59
    Flow details:
    Build details: 4.1.1 (build# 11)
    Modification History:
-----------------------------------------------------------------------------*/

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "ns_string.h"

void flow()
{
    ns_web_url ("login_jsp",
        "URL=http://10.10.30.13:8004/netstorm",
        "HEADER=Accept-Language:en-us,en;q=0.5",
        "REDIRECT=YES",
        "LOCATION=http://10.10.30.13:8004/netstorm/",
        "PreSnapshot=webpage_1427896199915.png",
        "Snapshot=webpage_1427896201686.png",
        INLINE_URLS,
            "URL=http://10.10.30.13:8004/netstorm/", "HEADER=Accept-Language:en-us,en;q=0.5", "REDIRECT=YES", "LOCATION=http://10.10.30.13:8004/netstorm/admin/login.jsp", END_INLINE,
            "URL=http://10.10.30.13:8004/netstorm/admin/login.jsp", "HEADER=Accept-Language:en-us,en;q=0.5", "COOKIE=JSESSIONID", "REDIRECT=YES", "LOCATION=http://10.10.30.13:8004/netfunction", END_INLINE,
            "URL=http://10.10.30.13:8004/netfunction", "HEADER=Accept-Language:en-us,en;q=0.5", "REDIRECT=YES", "LOCATION=http://10.10.30.13:8004/netfunction/", END_INLINE,
            "URL=http://10.10.30.13:8004/netfunction/", "HEADER=Accept-Language:en-us,en;q=0.5", "REDIRECT=YES", "LOCATION=http://10.10.30.13:8004/netfunction/admin/login.jsp", END_INLINE,
            "URL=http://10.10.30.13:8004/netfunction/admin/login.jsp", "HEADER=Accept-Language:en-us,en;q=0.5", "COOKIE=JSESSIONID", END_INLINE,
            "URL=http://10.10.30.13:8004/netfunction/js/sortableTable.js", "HEADER=Accept-Language:en-us,en;q=0.5", "COOKIE=JSESSIONID", END_INLINE,
            "URL=http://10.10.30.13:8004/netfunction/js/validation.js", "HEADER=Accept-Language:en-us,en;q=0.5", "COOKIE=JSESSIONID", END_INLINE,
            "URL=http://10.10.30.13:8004/netfunction/js/nsStringUtils.js", "HEADER=Accept-Language:en-us,en;q=0.5", "COOKIE=JSESSIONID", END_INLINE,
            "URL=http://10.10.30.13:8004/netfunction/js/nsDateUtils.js", "HEADER=Accept-Language:en-us,en;q=0.5", "COOKIE=JSESSIONID", END_INLINE,
            "URL=http://10.10.30.13:8004/netfunction/js/nsUtils.js", "HEADER=Accept-Language:en-us,en;q=0.5", "COOKIE=JSESSIONID", END_INLINE,
            "URL=http://10.10.30.13:8004/netfunction/js/help.js", "HEADER=Accept-Language:en-us,en;q=0.5", "COOKIE=JSESSIONID", END_INLINE,
            "URL=http://10.10.30.13:8004/netfunction/admin/adminUtils.js", "HEADER=Accept-Language:en-us,en;q=0.5", "COOKIE=JSESSIONID", END_INLINE,
            "URL=http://10.10.30.13:8004/netfunction/yui/js/yahoo-dom-event.js", "HEADER=Accept-Language:en-us,en;q=0.5", "COOKIE=JSESSIONID", END_INLINE,
            "URL=http://10.10.30.13:8004/netfunction/yui/js/container_core-min.js", "HEADER=Accept-Language:en-us,en;q=0.5", "COOKIE=JSESSIONID", END_INLINE,
            "URL=http://10.10.30.13:8004/netfunction/yui/js/menu-min.js", "HEADER=Accept-Language:en-us,en;q=0.5", "COOKIE=JSESSIONID", END_INLINE,
            "URL=http://10.10.30.13:8004/netfunction/yui/js/connection-min.js", "HEADER=Accept-Language:en-us,en;q=0.5", "COOKIE=JSESSIONID", END_INLINE,
            "URL=http://10.10.30.13:8004/netfunction/yui/js/animation-min.js", "HEADER=Accept-Language:en-us,en;q=0.5", "COOKIE=JSESSIONID", END_INLINE,
            "URL=http://10.10.30.13:8004/netfunction/yui/js/dragdrop-min.js", "HEADER=Accept-Language:en-us,en;q=0.5", "COOKIE=JSESSIONID", END_INLINE,
            "URL=http://10.10.30.13:8004/netfunction/yui/js/container-min.js", "HEADER=Accept-Language:en-us,en;q=0.5", "COOKIE=JSESSIONID", END_INLINE,
            "URL=http://10.10.30.13:8004/netfunction/images/netFunctionLogo.png", "HEADER=Accept-Language:en-us,en;q=0.5", "COOKIE=JSESSIONID", END_INLINE,
            "URL=http://10.10.30.13:8004/netfunction/images/user.jpg", "HEADER=Accept-Language:en-us,en;q=0.5", "COOKIE=JSESSIONID", END_INLINE,
            "URL=http://10.10.30.13:8004/netfunction/images/pwd.jpg", "HEADER=Accept-Language:en-us,en;q=0.5", "COOKIE=JSESSIONID", END_INLINE,
            "URL=http://10.10.30.13:8004/netfunction/yui/css/fonts-min.css", END_INLINE,
            "URL=http://10.10.30.13:8004/netfunction/yui/css/container.css", END_INLINE,
            "URL=http://10.10.30.13:8004/netfunction/yui/js/yahoo-dom-event.js", END_INLINE,
            "URL=http://10.10.30.13:8004/netfunction/images/sprite.png", "HEADER=Accept-Language:en-us,en;q=0.5", "COOKIE=JSESSIONID", END_INLINE
    );

    ns_page_think_time(0.282);

    ns_web_url ("login_jsp_2",
        "URL=http://10.10.30.13:8004/netfunction/admin/login.jsp",
        "HEADER=Accept-Language:en-us,en;q=0.5",
        "COOKIE=JSESSIONID",
        "PreSnapshot=webpage_1427896201890.png",
        "Snapshot=webpage_1427896202312.png",
        INLINE_URLS,
            "URL=http://10.10.30.13:8004/netfunction/js/sortableTable.js", "HEADER=Accept-Language:en-us,en;q=0.5", "COOKIE=JSESSIONID", END_INLINE,
            "URL=http://10.10.30.13:8004/netfunction/js/validation.js", "HEADER=Accept-Language:en-us,en;q=0.5", "COOKIE=JSESSIONID", END_INLINE,
            "URL=http://10.10.30.13:8004/netfunction/js/nsStringUtils.js", "HEADER=Accept-Language:en-us,en;q=0.5", "COOKIE=JSESSIONID", END_INLINE,
            "URL=http://10.10.30.13:8004/netfunction/js/nsDateUtils.js", "HEADER=Accept-Language:en-us,en;q=0.5", "COOKIE=JSESSIONID", END_INLINE,
            "URL=http://10.10.30.13:8004/netfunction/js/nsUtils.js", "HEADER=Accept-Language:en-us,en;q=0.5", "COOKIE=JSESSIONID", END_INLINE,
            "URL=http://10.10.30.13:8004/netfunction/js/help.js", "HEADER=Accept-Language:en-us,en;q=0.5", "COOKIE=JSESSIONID", END_INLINE,
            "URL=http://10.10.30.13:8004/netfunction/admin/adminUtils.js", "HEADER=Accept-Language:en-us,en;q=0.5", "COOKIE=JSESSIONID", END_INLINE,
            "URL=http://10.10.30.13:8004/netfunction/yui/js/yahoo-dom-event.js", "HEADER=Accept-Language:en-us,en;q=0.5", "COOKIE=JSESSIONID", END_INLINE,
            "URL=http://10.10.30.13:8004/netfunction/yui/js/container_core-min.js", "HEADER=Accept-Language:en-us,en;q=0.5", "COOKIE=JSESSIONID", END_INLINE,
            "URL=http://10.10.30.13:8004/netfunction/yui/js/menu-min.js", "HEADER=Accept-Language:en-us,en;q=0.5", "COOKIE=JSESSIONID", END_INLINE,
            "URL=http://10.10.30.13:8004/netfunction/yui/js/connection-min.js", "HEADER=Accept-Language:en-us,en;q=0.5", "COOKIE=JSESSIONID", END_INLINE,
            "URL=http://10.10.30.13:8004/netfunction/yui/js/animation-min.js", "HEADER=Accept-Language:en-us,en;q=0.5", "COOKIE=JSESSIONID", END_INLINE,
            "URL=http://10.10.30.13:8004/netfunction/yui/js/dragdrop-min.js", "HEADER=Accept-Language:en-us,en;q=0.5", "COOKIE=JSESSIONID", END_INLINE,
            "URL=http://10.10.30.13:8004/netfunction/yui/js/container-min.js", "HEADER=Accept-Language:en-us,en;q=0.5", "COOKIE=JSESSIONID", END_INLINE
    );

    ns_page_think_time(9.22);

    ns_web_url ("NOToolbar_jsp",
        "URL=http://10.10.30.13:8004/netfunction/admin/login.jsp",
        "METHOD=POST",
        "HEADER=Accept-Language:en-us,en;q=0.5",
        "HEADER=Content-Length:52",
        "HEADER=Content-Type:application/x-www-form-urlencoded",
        "COOKIE=JSESSIONID",
        "REDIRECT=YES",
        "LOCATION=http://10.10.30.13:8004/netfunction/admin/NOToolbar.jsp?strLoginName=netstorm&strGroupName=netstorm&strUserType=Engineers&sesRole=Standard",
        "PreSnapshot=webpage_1427896211204.png",
        "Snapshot=webpage_1427896211846.png",
        BODY_BEGIN,
            "strOperName=loginUser&strOperValue=netstorm+netstorm",
        BODY_END,
        INLINE_URLS,
            "URL=http://10.10.30.13:8004/netfunction/admin/NOToolbar.jsp?strLoginName=netstorm&strGroupName=netstorm&strUserType=Engineers&sesRole=Standard", "HEADER=Accept-Language:en-us,en;q=0.5", "COOKIE=JSESSIONID", END_INLINE,
            "URL=http://10.10.30.13:8004/netfunction/js/sortableTable.js", "HEADER=Accept-Language:en-us,en;q=0.5", "COOKIE=JSESSIONID", END_INLINE,
            "URL=http://10.10.30.13:8004/netfunction/js/validation.js", "HEADER=Accept-Language:en-us,en;q=0.5", "COOKIE=JSESSIONID", END_INLINE,
            "URL=http://10.10.30.13:8004/netfunction/js/nsStringUtils.js", "HEADER=Accept-Language:en-us,en;q=0.5", "COOKIE=JSESSIONID", END_INLINE,
            "URL=http://10.10.30.13:8004/netfunction/js/nsDateUtils.js", "HEADER=Accept-Language:en-us,en;q=0.5", "COOKIE=JSESSIONID", END_INLINE,
            "URL=http://10.10.30.13:8004/netfunction/js/nsUtils.js", "HEADER=Accept-Language:en-us,en;q=0.5", "COOKIE=JSESSIONID", END_INLINE,
            "URL=http://10.10.30.13:8004/netfunction/js/help.js", "HEADER=Accept-Language:en-us,en;q=0.5", "COOKIE=JSESSIONID", END_INLINE,
            "URL=http://10.10.30.13:8004/netfunction/admin/adminUtils.js", "HEADER=Accept-Language:en-us,en;q=0.5", "COOKIE=JSESSIONID", END_INLINE,
            "URL=http://10.10.30.13:8004/netfunction/yui/js/yahoo-dom-event.js", "HEADER=Accept-Language:en-us,en;q=0.5", "COOKIE=JSESSIONID", END_INLINE,
            "URL=http://10.10.30.13:8004/netfunction/yui/js/container_core-min.js", "HEADER=Accept-Language:en-us,en;q=0.5", "COOKIE=JSESSIONID", END_INLINE,
            "URL=http://10.10.30.13:8004/netfunction/yui/js/menu-min.js", "HEADER=Accept-Language:en-us,en;q=0.5", "COOKIE=JSESSIONID", END_INLINE,
            "URL=http://10.10.30.13:8004/netfunction/css/Netstorm.css", END_INLINE,
            "URL=http://10.10.30.13:8004/netfunction/correlation/corrServices.jsp", "HEADER=Accept-Language:en-us,en;q=0.5", "COOKIE=JSESSIONID", END_INLINE,
            "URL=http://10.10.30.13:8004/netfunction/correlation/corrServices.jsp", END_INLINE,
            "URL=http://10.10.30.13:8004/netfunction/js/jquery-latest.js", "HEADER=Accept-Language:en-us,en;q=0.5", "COOKIE=JSESSIONID", END_INLINE,
            "URL=http://10.10.30.13:8004/netfunction/correlation/corrSettingHints.js", "HEADER=Accept-Language:en-us,en;q=0.5", "COOKIE=JSESSIONID", END_INLINE,
            "URL=http://10.10.30.13:8004/netfunction/js/sortableTable.js", "HEADER=Accept-Language:en-us,en;q=0.5", "COOKIE=JSESSIONID", END_INLINE,
            "URL=http://10.10.30.13:8004/netfunction/js/jquery-impromptu.js", "HEADER=Accept-Language:en-us,en;q=0.5", "COOKIE=JSESSIONID", END_INLINE,
            "URL=http://10.10.30.13:8004/netfunction/correlation/corrUtils.js", "HEADER=Accept-Language:en-us,en;q=0.5", "COOKIE=JSESSIONID", END_INLINE,
            "URL=http://10.10.30.13:8004/netfunction/js/nsUtils.js", "HEADER=Accept-Language:en-us,en;q=0.5", "COOKIE=JSESSIONID", END_INLINE,
            "URL=http://10.10.30.13:8004/netfunction/js/prototype.js", "HEADER=Accept-Language:en-us,en;q=0.5", "COOKIE=JSESSIONID", END_INLINE,
            "URL=http://10.10.30.13:8004/netfunction/js/fastinit.js", "HEADER=Accept-Language:en-us,en;q=0.5", "COOKIE=JSESSIONID", END_INLINE,
            "URL=http://10.10.30.13:8004/netfunction/js/tablekit.js", "HEADER=Accept-Language:en-us,en;q=0.5", "COOKIE=JSESSIONID", END_INLINE,
            "URL=http://10.10.30.13:8004/netfunction/js/tableEnhancement.js", "HEADER=Accept-Language:en-us,en;q=0.5", "COOKIE=JSESSIONID", END_INLINE,
            "URL=http://10.10.30.13:8004/netfunction/js/tablePagination.js", "HEADER=Accept-Language:en-us,en;q=0.5", "COOKIE=JSESSIONID", END_INLINE,
            "URL=http://10.10.30.13:8004/netfunction/js/validation.js", "HEADER=Accept-Language:en-us,en;q=0.5", "COOKIE=JSESSIONID", END_INLINE,
            "URL=http://10.10.30.13:8004/netfunction/correlation/corrValidateCondition.js", "HEADER=Accept-Language:en-us,en;q=0.5", "COOKIE=JSESSIONID", END_INLINE,
            "URL=http://10.10.30.13:8004/netfunction/js/nsStringUtils.js", "HEADER=Accept-Language:en-us,en;q=0.5", "COOKIE=JSESSIONID", END_INLINE,
            "URL=http://10.10.30.13:8004/netfunction/js/help.js", "HEADER=Accept-Language:en-us,en;q=0.5", "COOKIE=JSESSIONID", END_INLINE,
            "URL=http://10.10.30.13:8004/netfunction/yui/js/yahoo-dom-event.js", "HEADER=Accept-Language:en-us,en;q=0.5", "COOKIE=JSESSIONID", END_INLINE,
            "URL=http://10.10.30.13:8004/netfunction/yui/js/container_core-min.js", "HEADER=Accept-Language:en-us,en;q=0.5", "COOKIE=JSESSIONID", END_INLINE,
            "URL=http://10.10.30.13:8004/netfunction/yui/js/menu-min.js", "HEADER=Accept-Language:en-us,en;q=0.5", "COOKIE=JSESSIONID", END_INLINE,
            "URL=http://10.10.30.13:8004/netfunction/yui/js/connection-min.js", "HEADER=Accept-Language:en-us,en;q=0.5", "COOKIE=JSESSIONID", END_INLINE,
            "URL=http://10.10.30.13:8004/netfunction/yui/js/animation-min.js", "HEADER=Accept-Language:en-us,en;q=0.5", "COOKIE=JSESSIONID", END_INLINE,
            "URL=http://10.10.30.13:8004/netfunction/yui/js/dragdrop-min.js", "HEADER=Accept-Language:en-us,en;q=0.5", "COOKIE=JSESSIONID", END_INLINE,
            "URL=http://10.10.30.13:8004/netfunction/yui/js/container-min.js", "HEADER=Accept-Language:en-us,en;q=0.5", "COOKIE=JSESSIONID", END_INLINE,
            "URL=http://10.10.30.13:8004/netfunction/css/AdvancedNetstorm.css", END_INLINE,
            "URL=http://10.10.30.13:8004/netfunction/yui/css/menu.css", END_INLINE,
            "URL=http://10.10.30.13:8004/netfunction/css/jquery-impromptu.css", END_INLINE,
            "URL=http://10.10.30.13:8004/netfunction/images/recordingAnimation.gif", "HEADER=Accept-Language:en-us,en;q=0.5", "COOKIE=JSESSIONID", END_INLINE,
            "URL=http://10.10.30.13:8004/netfunction/images/Recycle-Bin_e.png", "HEADER=Accept-Language:en-us,en;q=0.5", "COOKIE=JSESSIONID", END_INLINE,
            "URL=http://10.10.30.13:8004/netfunction/images/logo.png", "HEADER=Accept-Language:en-us,en;q=0.5", "COOKIE=JSESSIONID", END_INLINE,
            "URL=http://10.10.30.13:8004/netfunction/images/question.png", "HEADER=Accept-Language:en-us,en;q=0.5", "COOKIE=JSESSIONID", END_INLINE,
            "URL=http://10.10.30.13:8004/netfunction/images/tableHeader.png", "HEADER=Accept-Language:en-us,en;q=0.5", "COOKIE=JSESSIONID", END_INLINE,
            "URL=http://10.10.30.13:8004/netfunction/images/menubaritem_submenuindicator.png", "HEADER=Accept-Language:en-us,en;q=0.5", "COOKIE=JSESSIONID", END_INLINE,
            "URL=http://10.10.30.13:8004/netfunction/images/downArrow.gif", "HEADER=Accept-Language:en-us,en;q=0.5", "COOKIE=JSESSIONID", END_INLINE
    );

    ns_page_think_time(2.295);

    //Page Auto splitted for Link 'test' Clicked by User
    ns_web_url ("cavisson_com_strFld2_default",
        "URL=http://10.10.30.13:8004/netfunction/correlation/corrServiceEdit.jsp?strTemplateUrl=/cavisson.com&strFld1=/cavisson.com&strFld2=default&strFld3=test&currentVersion=NA",
        "HEADER=Accept-Language:en-us,en;q=0.5",
        "COOKIE=JSESSIONID",
        "PreSnapshot=webpage_1427896215963.png",
        "Snapshot=webpage_1427896217089.png",
        INLINE_URLS,
            "URL=http://10.10.30.13:8004/netfunction/css/jquery-ui-1.8.13.custom.css", END_INLINE,
            "URL=http://10.10.30.13:8004/netfunction/css/style.css", END_INLINE,
            "URL=http://10.10.30.13:8004/netfunction/css/grid.css", END_INLINE,
            "URL=http://10.10.30.13:8004/netfunction/css/jquery-ui.css", END_INLINE,
            "URL=http://10.10.30.13:8004/netfunction/css/jquery.treeview.css", END_INLINE,
            "URL=http://10.10.30.13:8004/netfunction/correlation/corrAllTemplates.jsp", "HEADER=Accept-Language:en-us,en;q=0.5", "COOKIE=JSESSIONID", END_INLINE,
            "URL=http://10.10.30.13:8004/netfunction/images/tabright.gif", "HEADER=Accept-Language:en-us,en;q=0.5", "COOKIE=JSESSIONID", END_INLINE,
            "URL=http://10.10.30.13:8004/netstorm/images/blank.gif", "HEADER=Accept-Language:en-us,en;q=0.5", "COOKIE=JSESSIONID", END_INLINE
    );

    ns_page_think_time(1.698);

    //Page Auto splitted for Link 'Parameters' Clicked by User
    ns_web_url ("corrMain_jsp",
        "URL=http://10.10.30.13:8004/netfunction/correlation/corrMain.jsp",
        "HEADER=Accept-Language:en-us,en;q=0.5",
        "COOKIE=showSelectedTemplateId;JSESSIONID",
        "PreSnapshot=webpage_1427896218740.png",
        "Snapshot=webpage_1427896219854.png",
        INLINE_URLS,
            "URL=http://10.10.30.13:8004/netfunction/js/jquery-latest.js", "HEADER=Accept-Language:en-us,en;q=0.5", "COOKIE=JSESSIONID", END_INLINE,
            "URL=http://10.10.30.13:8004/netfunction/correlation/corrSettingHints.js", "HEADER=Accept-Language:en-us,en;q=0.5", "COOKIE=showSelectedTemplateId;JSESSIONID", END_INLINE,
            "URL=http://10.10.30.13:8004/netfunction/js/sortableTable.js", "HEADER=Accept-Language:en-us,en;q=0.5", "COOKIE=JSESSIONID", END_INLINE,
            "URL=http://10.10.30.13:8004/netfunction/js/jquery-impromptu.js", "HEADER=Accept-Language:en-us,en;q=0.5", "COOKIE=JSESSIONID", END_INLINE,
            "URL=http://10.10.30.13:8004/netfunction/correlation/corrUtils.js", "HEADER=Accept-Language:en-us,en;q=0.5", "COOKIE=showSelectedTemplateId;JSESSIONID", END_INLINE,
            "URL=http://10.10.30.13:8004/netfunction/js/nsUtils.js", "HEADER=Accept-Language:en-us,en;q=0.5", "COOKIE=JSESSIONID", END_INLINE,
            "URL=http://10.10.30.13:8004/netfunction/js/prototype.js", "HEADER=Accept-Language:en-us,en;q=0.5", "COOKIE=JSESSIONID", END_INLINE,
            "URL=http://10.10.30.13:8004/netfunction/js/fastinit.js", "HEADER=Accept-Language:en-us,en;q=0.5", "COOKIE=JSESSIONID", END_INLINE,
            "URL=http://10.10.30.13:8004/netfunction/js/tablekit.js", "HEADER=Accept-Language:en-us,en;q=0.5", "COOKIE=JSESSIONID", END_INLINE,
            "URL=http://10.10.30.13:8004/netfunction/js/tableEnhancement.js", "HEADER=Accept-Language:en-us,en;q=0.5", "COOKIE=JSESSIONID", END_INLINE,
            "URL=http://10.10.30.13:8004/netfunction/js/tablePagination.js", "HEADER=Accept-Language:en-us,en;q=0.5", "COOKIE=JSESSIONID", END_INLINE,
            "URL=http://10.10.30.13:8004/netfunction/js/validation.js", "HEADER=Accept-Language:en-us,en;q=0.5", "COOKIE=JSESSIONID", END_INLINE,
            "URL=http://10.10.30.13:8004/netfunction/correlation/corrValidateCondition.js", "HEADER=Accept-Language:en-us,en;q=0.5", "COOKIE=showSelectedTemplateId;JSESSIONID", END_INLINE,
            "URL=http://10.10.30.13:8004/netfunction/js/nsStringUtils.js", "HEADER=Accept-Language:en-us,en;q=0.5", "COOKIE=JSESSIONID", END_INLINE,
            "URL=http://10.10.30.13:8004/netfunction/js/help.js", "HEADER=Accept-Language:en-us,en;q=0.5", "COOKIE=JSESSIONID", END_INLINE,
            "URL=http://10.10.30.13:8004/netfunction/yui/js/yahoo-dom-event.js", "HEADER=Accept-Language:en-us,en;q=0.5", "COOKIE=JSESSIONID", END_INLINE,
            "URL=http://10.10.30.13:8004/netfunction/yui/js/container_core-min.js", "HEADER=Accept-Language:en-us,en;q=0.5", "COOKIE=JSESSIONID", END_INLINE,
            "URL=http://10.10.30.13:8004/netfunction/yui/js/menu-min.js", "HEADER=Accept-Language:en-us,en;q=0.5", "COOKIE=JSESSIONID", END_INLINE,
            "URL=http://10.10.30.13:8004/netfunction/yui/js/connection-min.js", "HEADER=Accept-Language:en-us,en;q=0.5", "COOKIE=JSESSIONID", END_INLINE,
            "URL=http://10.10.30.13:8004/netfunction/yui/js/animation-min.js", "HEADER=Accept-Language:en-us,en;q=0.5", "COOKIE=JSESSIONID", END_INLINE,
            "URL=http://10.10.30.13:8004/netfunction/yui/js/dragdrop-min.js", "HEADER=Accept-Language:en-us,en;q=0.5", "COOKIE=JSESSIONID", END_INLINE,
            "URL=http://10.10.30.13:8004/netfunction/yui/js/container-min.js", "HEADER=Accept-Language:en-us,en;q=0.5", "COOKIE=JSESSIONID", END_INLINE,
            "URL=http://10.10.30.13:8004/netfunction/correlation/corrLeftPane.jsp", "HEADER=Accept-Language:en-us,en;q=0.5", "COOKIE=showSelectedTemplateId;JSESSIONID", END_INLINE,
            "URL=http://10.10.30.13:8004/netfunction/correlation/corrServiceNames.jsp", "HEADER=Accept-Language:en-us,en;q=0.5", "COOKIE=showSelectedTemplateId;JSESSIONID", END_INLINE,
            "URL=http://10.10.30.13:8004/netfunction/images/down.jpg", "HEADER=Accept-Language:en-us,en;q=0.5", "COOKIE=JSESSIONID", END_INLINE
    );

    ns_page_think_time(2.405);

    ns_web_url ("corrLeftPane_jsp",
        "URL=http://10.10.30.13:8004/netfunction/correlation/corrEditFileParam.jsp?strUrl=/cavisson.com",
        "HEADER=Accept-Language:en-us,en;q=0.5",
        "COOKIE=showSelectedTemplateId;JSESSIONID",
        "PreSnapshot=webpage_1427896222005.png",
        "Snapshot=webpage_1427896237741.png",
        INLINE_URLS,
            "URL=http://10.10.30.13:8004/netfunction/correlation/corrLeftPane.jsp", "HEADER=Accept-Language:en-us,en;q=0.5", "COOKIE=showSelectedTemplateId;JSESSIONID", END_INLINE,
            "URL=http://10.10.30.13:8004/netfunction/js/jquery-latest.js", "HEADER=Accept-Language:en-us,en;q=0.5", "COOKIE=JSESSIONID", END_INLINE,
            "URL=http://10.10.30.13:8004/netfunction/correlation/corrSettingHints.js", "HEADER=Accept-Language:en-us,en;q=0.5", "COOKIE=showSelectedTemplateId;JSESSIONID", END_INLINE,
            "URL=http://10.10.30.13:8004/netfunction/js/sortableTable.js", "HEADER=Accept-Language:en-us,en;q=0.5", "COOKIE=JSESSIONID", END_INLINE,
            "URL=http://10.10.30.13:8004/netfunction/js/jquery-impromptu.js", "HEADER=Accept-Language:en-us,en;q=0.5", "COOKIE=JSESSIONID", END_INLINE,
            "URL=http://10.10.30.13:8004/netfunction/correlation/corrUtils.js", "HEADER=Accept-Language:en-us,en;q=0.5", "COOKIE=showSelectedTemplateId;JSESSIONID", END_INLINE,
            "URL=http://10.10.30.13:8004/netfunction/js/nsUtils.js", "HEADER=Accept-Language:en-us,en;q=0.5", "COOKIE=JSESSIONID", END_INLINE,
            "URL=http://10.10.30.13:8004/netfunction/js/prototype.js", "HEADER=Accept-Language:en-us,en;q=0.5", "COOKIE=JSESSIONID", END_INLINE,
            "URL=http://10.10.30.13:8004/netfunction/js/fastinit.js", "HEADER=Accept-Language:en-us,en;q=0.5", "COOKIE=JSESSIONID", END_INLINE,
            "URL=http://10.10.30.13:8004/netfunction/js/tablekit.js", "HEADER=Accept-Language:en-us,en;q=0.5", "COOKIE=JSESSIONID", END_INLINE,
            "URL=http://10.10.30.13:8004/netfunction/js/tableEnhancement.js", "HEADER=Accept-Language:en-us,en;q=0.5", "COOKIE=JSESSIONID", END_INLINE,
            "URL=http://10.10.30.13:8004/netfunction/js/tablePagination.js", "HEADER=Accept-Language:en-us,en;q=0.5", "COOKIE=JSESSIONID", END_INLINE,
            "URL=http://10.10.30.13:8004/netfunction/js/validation.js", "HEADER=Accept-Language:en-us,en;q=0.5", "COOKIE=JSESSIONID", END_INLINE,
            "URL=http://10.10.30.13:8004/netfunction/correlation/corrValidateCondition.js", "HEADER=Accept-Language:en-us,en;q=0.5", "COOKIE=showSelectedTemplateId;JSESSIONID", END_INLINE,
            "URL=http://10.10.30.13:8004/netfunction/js/nsStringUtils.js", "HEADER=Accept-Language:en-us,en;q=0.5", "COOKIE=JSESSIONID", END_INLINE,
            "URL=http://10.10.30.13:8004/netfunction/js/help.js", "HEADER=Accept-Language:en-us,en;q=0.5", "COOKIE=JSESSIONID", END_INLINE,
            "URL=http://10.10.30.13:8004/netfunction/yui/js/yahoo-dom-event.js", "HEADER=Accept-Language:en-us,en;q=0.5", "COOKIE=JSESSIONID", END_INLINE,
            "URL=http://10.10.30.13:8004/netfunction/yui/js/container_core-min.js", "HEADER=Accept-Language:en-us,en;q=0.5", "COOKIE=JSESSIONID", END_INLINE,
            "URL=http://10.10.30.13:8004/netfunction/yui/js/menu-min.js", "HEADER=Accept-Language:en-us,en;q=0.5", "COOKIE=JSESSIONID", END_INLINE,
            "URL=http://10.10.30.13:8004/netfunction/yui/js/connection-min.js", "HEADER=Accept-Language:en-us,en;q=0.5", "COOKIE=JSESSIONID", END_INLINE,
            "URL=http://10.10.30.13:8004/netfunction/yui/js/animation-min.js", "HEADER=Accept-Language:en-us,en;q=0.5", "COOKIE=JSESSIONID", END_INLINE,
            "URL=http://10.10.30.13:8004/netfunction/yui/js/dragdrop-min.js", "HEADER=Accept-Language:en-us,en;q=0.5", "COOKIE=JSESSIONID", END_INLINE,
            "URL=http://10.10.30.13:8004/netfunction/yui/js/container-min.js", "HEADER=Accept-Language:en-us,en;q=0.5", "COOKIE=JSESSIONID", END_INLINE,
            "URL=http://10.10.30.13:8004/netfunction/correlation/corrEditFileParam.jsp?strUrl=/cavisson.com", END_INLINE,
            "URL=http://10.10.30.13:8004/netfunction/correlation/corrUploadDataFile.jsp?destFile=&rowId=-1&mode=addFileParam&redirectFile=corrEditFileParam.jsp&deli=,&checkFlag=undefined", "HEADER=Accept-Language:en-us,en;q=0.5", "COOKIE=showSelectedTemplateId;JSESSIONID", END_INLINE,
            "URL=http://10.10.30.13:8004/netfunction/js/jquery-latest.js", "HEADER=Accept-Language:en-us,en;q=0.5", "COOKIE=JSESSIONID", END_INLINE,
            "URL=http://10.10.30.13:8004/netfunction/correlation/corrSettingHints.js", "HEADER=Accept-Language:en-us,en;q=0.5", "COOKIE=showSelectedTemplateId;JSESSIONID", END_INLINE,
            "URL=http://10.10.30.13:8004/netfunction/js/sortableTable.js", "HEADER=Accept-Language:en-us,en;q=0.5", "COOKIE=JSESSIONID", END_INLINE,
            "URL=http://10.10.30.13:8004/netfunction/js/jquery-impromptu.js", "HEADER=Accept-Language:en-us,en;q=0.5", "COOKIE=JSESSIONID", END_INLINE,
            "URL=http://10.10.30.13:8004/netfunction/correlation/corrUtils.js", "HEADER=Accept-Language:en-us,en;q=0.5", "COOKIE=showSelectedTemplateId;JSESSIONID", END_INLINE,
            "URL=http://10.10.30.13:8004/netfunction/js/nsUtils.js", "HEADER=Accept-Language:en-us,en;q=0.5", "COOKIE=JSESSIONID", END_INLINE,
            "URL=http://10.10.30.13:8004/netfunction/js/prototype.js", "HEADER=Accept-Language:en-us,en;q=0.5", "COOKIE=JSESSIONID", END_INLINE,
            "URL=http://10.10.30.13:8004/netfunction/js/fastinit.js", "HEADER=Accept-Language:en-us,en;q=0.5", "COOKIE=JSESSIONID", END_INLINE,
            "URL=http://10.10.30.13:8004/netfunction/js/tablekit.js", "HEADER=Accept-Language:en-us,en;q=0.5", "COOKIE=JSESSIONID", END_INLINE,
            "URL=http://10.10.30.13:8004/netfunction/js/tableEnhancement.js", "HEADER=Accept-Language:en-us,en;q=0.5", "COOKIE=JSESSIONID", END_INLINE,
            "URL=http://10.10.30.13:8004/netfunction/js/tablePagination.js", "HEADER=Accept-Language:en-us,en;q=0.5", "COOKIE=JSESSIONID", END_INLINE,
            "URL=http://10.10.30.13:8004/netfunction/js/validation.js", "HEADER=Accept-Language:en-us,en;q=0.5", "COOKIE=JSESSIONID", END_INLINE,
            "URL=http://10.10.30.13:8004/netfunction/correlation/corrValidateCondition.js", "HEADER=Accept-Language:en-us,en;q=0.5", "COOKIE=showSelectedTemplateId;JSESSIONID", END_INLINE,
            "URL=http://10.10.30.13:8004/netfunction/js/nsStringUtils.js", "HEADER=Accept-Language:en-us,en;q=0.5", "COOKIE=JSESSIONID", END_INLINE,
            "URL=http://10.10.30.13:8004/netfunction/js/help.js", "HEADER=Accept-Language:en-us,en;q=0.5", "COOKIE=JSESSIONID", END_INLINE,
            "URL=http://10.10.30.13:8004/netfunction/yui/js/yahoo-dom-event.js", "HEADER=Accept-Language:en-us,en;q=0.5", "COOKIE=JSESSIONID", END_INLINE,
            "URL=http://10.10.30.13:8004/netfunction/yui/js/container_core-min.js", "HEADER=Accept-Language:en-us,en;q=0.5", "COOKIE=JSESSIONID", END_INLINE,
            "URL=http://10.10.30.13:8004/netfunction/yui/js/menu-min.js", "HEADER=Accept-Language:en-us,en;q=0.5", "COOKIE=JSESSIONID", END_INLINE,
            "URL=http://10.10.30.13:8004/netfunction/yui/js/connection-min.js", "HEADER=Accept-Language:en-us,en;q=0.5", "COOKIE=JSESSIONID", END_INLINE,
            "URL=http://10.10.30.13:8004/netfunction/yui/js/animation-min.js", "HEADER=Accept-Language:en-us,en;q=0.5", "COOKIE=JSESSIONID", END_INLINE,
            "URL=http://10.10.30.13:8004/netfunction/yui/js/dragdrop-min.js", "HEADER=Accept-Language:en-us,en;q=0.5", "COOKIE=JSESSIONID", END_INLINE,
            "URL=http://10.10.30.13:8004/netfunction/yui/js/container-min.js", "HEADER=Accept-Language:en-us,en;q=0.5", "COOKIE=JSESSIONID", END_INLINE
    );

    //Page Auto splitted for Method = POST
    ns_web_url ("corrUploadDataFile_jsp",
        "URL=http://10.10.30.13:8004/netfunction/correlation/corrUploadDataFile.jsp?strOperName=Upload&sourceFile=",
        "METHOD=POST",
        "HEADER=Accept-Language:en-us,en;q=0.5",
        "HEADER=Content-Length:904717",
        "HEADER=Content-Type:multipart/form-data; boundary=---------------------------41184676334",
        "COOKIE=showSelectedTemplateId;JSESSIONID",
        "PreSnapshot=webpage_1427896237741.png",
        "Snapshot=webpage_1427896237897.png",
        MULTIPART_BODY_BEGIN,
            MULTIPART_BOUNDARY,
            //-----------------------------41184676334
                "HEADER=Content-Disposition: form-data; name=\"strOperName\"",
                BODY_BEGIN,
                    "",
                BODY_END,
            MULTIPART_BOUNDARY,
            //-----------------------------41184676334
                "HEADER=Content-Disposition: form-data; name=\"strOperValue\"",
                BODY_BEGIN,
                    "",
                BODY_END,
            MULTIPART_BOUNDARY,
            //-----------------------------41184676334
                "HEADER=Content-Disposition: form-data; name=\"FileUpload\"; filename=\"{ExcelFilename}\"",
                "HEADER=Content-Type: application/kset",
                //"HEADER=Range(@\"U2\", ). B(xlDow n)).Name i\"dpsid\" ",
                BODY_BEGIN,
                    "{ExcelFilePath}",
                BODY_END,
            MULTIPART_BOUNDARY,
            //-----------------------------41184676334
                "HEADER=Content-Disposition: form-data; name=\"submitbutton\"",
                BODY_BEGIN,
                    "Upload File",
                BODY_END,
        MULTIPART_BODY_END,
        INLINE_URLS,
            "URL=http://10.10.30.13:8004/netfunction/correlation/corrEditFileParam.jsp?destFile=LSImport1Prd10ColorwayEach_1.xls&strAction=finish&uploadCheck=true&strMode=addFileParam&rowId=-1&deli=,", "HEADER=Accept-Language:en-us,en;q=0.5", "COOKIE=showSelectedTemplateId;JSESSIONID", END_INLINE
    );

    ns_page_think_time(0.015);

}
