#!/bin/bash

. $NS_WDIR/lib/automation_util
T_NAME=$(get_tname)
SUMMARY_FILE="$NS_WDIR/logs/TR$T_RUN_ID/summary_gdf.data"
TRANS_DETAIL_FILE="$NS_WDIR/logs/TR$T_RUN_ID/trans_detail.dat"


function set_think_time_params(){
    MaxSesRepTime_Float=$(grep  "Average Session Response Time (Secs)" ${SUMMARY_FILE} |cut -d '|' -f8)
    MaxSesRepTime=$(printf '%.0f\n' $MaxSesRepTime_Float)
    
    ThinkingVusers_Float=$(grep  "Thinking Vusers" ${SUMMARY_FILE} |cut  -d '|' -f8)
    ThinkingVusers=$(printf '%.0f\n' $ThinkingVusers_Float)
    
    FirstPageMaxTransTime_Float=$(grep  "hpd_page1_trans1" ${TRANS_DETAIL_FILE}  |cut -d '|' -f4)
    FirstPageMaxTransTime=$(printf '%.0f\n' $FirstPageMaxTransTime_Float)
    
    SecondPageMaxTransTime_Float=$(grep  "hpd_page2_trans2" ${TRANS_DETAIL_FILE}  |cut -d '|' -f4)
    SecondPageMaxTransTime=$(printf '%.0f\n' $SecondPageMaxTransTime_Float)
    
    SpecificPageMaxTransTime_Float=$(grep  "hpd_page3_trans3" ${TRANS_DETAIL_FILE} |cut -d '|' -f4)
    SpecificPageMaxTransTime=$(printf '%.0f\n' $SpecificPageMaxTransTime_Float)
    
    OverrideWithMultiplyValue_Float=$(grep  "hpd_page7_trans7" ${TRANS_DETAIL_FILE} |cut -d '|' -f4)
    OverrideWithMultiplyValue=$(printf '%.0f\n' $OverrideWithMultiplyValue_Float)
    
    OverideRandomPctValue_Float=$(grep  "hpd_page6_trans6" ${TRANS_DETAIL_FILE} |cut -d '|' -f4)
    OverideRandomPctValue=$(printf '%.0f\n' $OverideRandomPctValue_Float)
    
    debug_log "MaxSesRepTime=$MaxSesRepTime;ThinkingVusers=$ThinkingVusers;"
    debug_log "FirstPageMaxTransTime=$FirstPageMaxTransTime;SecondPageMaxTransTime=$SecondPageMaxTransTime;"
    debug_log "SpecificPageMaxTransTime=$SpecificPageMaxTransTime;OverrideWithMultiplyValue=$OverrideWithMultiplyValue;"
    debug_log "OverideRandomPctValue=$OverideRandomPctValue;"
}


set_think_time_params

if [ "$T_NAME" == "SMOKE-008-001" ];then 
    if [ $SD_TotalSuccURL -eq 46 ] && \
       [ $MaxSesRepTime -ge 35 -a $MaxSesRepTime -le 36 ] && \
       [ $ThinkingVusers -eq 1 ] && \
       [ $FirstPageMaxTransTime -ge 5 -a $FirstPageMaxTransTime -le 6 ] && \
       [ $SecondPageMaxTransTime -ge 5 -a $SecondPageMaxTransTime -le 6 ];then
        log_status_and_exit_ex "PASS" "Page think time with constant mode Passed"
    else
        log_status_and_exit_ex "FAIL" "Page think time with constant mode Failed"
    fi
fi

if [ "$T_NAME" == "SMOKE-008-002" ];then
    if [ $SD_TotalSuccURL -eq 23 ] && \
       [ $MaxSesRepTime -ge 40 -a $MaxSesRepTime -le 70 ] && \
       [ $ThinkingVusers -eq 1 ] && \
       [ $FirstPageMaxTransTime -ge 5 -a $FirstPageMaxTransTime -le 10 ] && \
       [ $SecondPageMaxTransTime -ge 5 -a $SecondPageMaxTransTime -le 10 ];then
        log_status_and_exit_ex "PASS" "Page think time with uniform distribution mode Passed"
    else
        log_status_and_exit_ex "FAIL" "Page think time with uniform distribution mode Failed"
    fi
fi

if [ "$T_NAME" == "SMOKE-008-003" ];then
    if [ $SD_TotalSuccURL -eq 23 ] && \
       [ $MaxSesRepTime -ge 0 -a $MaxSesRepTime -le 2 ] && \
       [ $ThinkingVusers -ge 0 -a $ThinkingVusers -le 1 ] && \
       [ $FirstPageMaxTransTime -ge 0 -a $FirstPageMaxTransTime -le 2 ] && \
       [ $SecondPageMaxTransTime -ge 0 -a $SecondPageMaxTransTime -le 2 ];then
        log_status_and_exit_ex "PASS" "Page think time with internet type distribution mode Passed"
    else
        log_status_and_exit_ex "FAIL" "Page think time with internet type distribution mode Failed"
    fi
fi

if [ "$T_NAME" == "SMOKE-008-004" ];then
    if [ $SD_TotalSuccURL -eq 23 ] && \
       [ $MaxSesRepTime -ge 5 -a $MaxSesRepTime -le 6 ] && \
       [ $SpecificPageMaxTransTime -ge 5 -a $SpecificPageMaxTransTime -le 6 ] && \
       [ $ThinkingVusers -eq 1 ];then
        log_status_and_exit_ex "PASS" "Page think time keyword for specific page Passed"
    else
        log_status_and_exit_ex "FAIL" "Page think time keyword for specific page Failed"
    fi
fi

if [ "$T_NAME" == "SMOKE-008-005" ];then
    if [ $SD_TotalSuccURL -eq 23 ] && \
       [ $MaxSesRepTime -ge 26 -a $MaxSesRepTime -le 27 ] && \
       [ $OverrideWithMultiplyValue -ge 1 -a $OverrideWithMultiplyValue -le 2 ] && \
       [ $ThinkingVusers -eq 1 ];then
        log_status_and_exit_ex "PASS" "Page think time keyword with overide and multiply values Passed"
    else
        log_status_and_exit_ex "FAIL" "Page think time keyword with overide and multiply values Failed"
    fi
fi

if [ "$T_NAME" == "SMOKE-008-006" ];then
    if [ $SD_TotalSuccURL -eq 23 ] && \
       [ $MaxSesRepTime -ge 1 -a $MaxSesRepTime -le 3 ] && \
       [ $ThinkingVusers -eq 1 ];then
        log_status_and_exit_ex "PASS" "Page think time keyword with overide random percentage values Passed"
    else
        log_status_and_exit_ex "FAIL" "Page think time keyword with overide random percentage values Failed"
    fi
fi

exit 0
