/*-----------------------------------------------------------------------------
    Name: flow
    Generated By: netstorm
    Date of generation: 08/13/2014 06:16:13
    Flow details:
    Build details: 4.0.0 (build# 10)
    Modification History:
-----------------------------------------------------------------------------*/

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "ns_string.h"

void flow()
{
    ns_web_url ("FirstView",
         "URL=http://10.10.30.96/tours/index.html",
         "METHOD=%method",
         "HEADER=%header",
         "BrowserUserProfile={BrowserUserProfile}",
         "PageLoadWaitTime=%PageLoadWaitTime",
         "HarLogDir={HarLogDir}",
         "VncDisplayId={VncDisplayId}",
         "HarRenameFlag=1",
    );
    ns_page_think_time(1.0);
       
    ns_web_url ("RepeatView",
         "URL=http://10.10.30.96/tours/index.html",
         "METHOD=%method",
         "HEADER=%header",
         "BrowserUserProfile={BrowserUserProfile}",
         "PageLoadWaitTime=%PageLoadWaitTime",
         "HarLogDir={HarLogDir}",
         "VncDisplayId={VncDisplayId}",
         "HarRenameFlag=1",
    );
    ns_page_think_time(1.0);
}
