/*-----------------------------------------------------------------------------
    Name: MainUrlAuth
    Generated By: netstorm
    Date of generation: 02/26/2012 11:12:39
    Flow details:
    Modification History:
-----------------------------------------------------------------------------*/

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "ns_string.h"

void MainUrlAuth()
{
    ns_web_url ("ntlm_html",
        "URL=http://127.0.0.1/BasicDigest/Basic.html",
        "HTTPAuthUserName=%Username",
        "HTTPAuthPassword=%Password",
        "BODY={Pagename}"
);
 
   ns_web_url ("index_html",
        "URL=http://127.0.0.1/BasicDigest/flower.html?{Pagename}",
        "HTTPAuthUserName=netstorm",
       "HTTPAuthPassword=netstorm",
        "BODY={Pagename}"
);



   ns_page_think_time(0);
ns_web_url ("ntlm_html1",
        "URL=http://127.0.0.1/NoAuth/NoAuth.html?{Pagename}",
);
}
