/*-----------------------------------------------------------------------------
    Name: Trans_login
    Generated By: netstorm
    Date of generation: 09/29/2016 10:14:17
    Flow details:
    Build details: 4.1.6 (build# 18)
    Modification History:
-----------------------------------------------------------------------------*/

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "ns_string.h"

void Trans_login()
{
    ns_web_url ("Trans_login",
        "URL=http://10.10.30.96:80/cgi-bin/login*"
    );

    ns_page_think_time(((double )ns_get_pg_think_time())/1000.0);

}
