#!/bin/bash

source $NS_WDIR/lib/automation_util

NStmpdir=/home/netstorm/work/.tmp/

if [ -d "${NStmpdir}" ]; then
    rm -rf "${NStmpdir}"
else
    debug_log "does not exist .tmp directry"
fi

if [ -f "/tmp/rtc.log" ]; then 
    sudo rm -rf /tmp/rtc.log
else
    debug_log "rtc log file does not exist"
fi

exit 0
