#!/bin/bash
TEST_NAME=`grep -e "TNAME" scenario |awk '{print $2}'`
TESTRUN_ID=$2
echo "Test Run Number is "=$TESTRUN_ID
TESTRUN_WITH_PATH=$NS_WDIR/logs/TR$TESTRUN_ID
echo "test run with path"=$TESTRUN_WITH_PATH
RESPONSE=`cat $TESTRUN_WITH_PATH/url_req_0_0_* | grep -o class2K.html?9`

function check_status() 
{
  if [ "$RESPONSE" == "class2K.html?9" ];then
    STATUS="PASS"
    else
    STATUS="FAIL"
  fi 
}

function log_msg() 
{
  echo $* 
  echo $* >> $TEST_RESULT_FILE
}
check_status
if [ "XX$STATUS" == "XXFAIL" ]; then
  log_msg "TESTRESULT           :$STATUS"
  exit -1 
  else
  log_msg "TESTRESULT		:$STATUS" 
fi 
exit 0

