/*-----------------------------------------------------------------------------
    Name: flow
    Generated By: netstorm
    Date of generation: 06/19/2012 01:35:43
    Flow details:
    Modification History:
-----------------------------------------------------------------------------*/

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "ns_string.h"

void flow()
{
    ns_start_transaction("ipv6Redirect");
    ns_web_url ("index",
        "URL=http://127.0.0.1/Smoke_Redirect/urlIPV6redirection.html"
    );
    ns_end_transaction("ipv6Redirect",NS_AUTO_STATUS);
  
    ns_page_think_time(0);

}
