/*-----------------------------------------------------------------------------
    Name: flow
    Generated By: netstorm
    Date of generation: 12/24/2012 04:45:23
    Flow details:
    Modification History:
-----------------------------------------------------------------------------*/

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "ns_string.h"

void flow()
{
    ns_web_url ("Page_html",
        "URL=http://127.0.0.1/url_service/url_test.xml?Status=200&SvcTime=150&Hdr1={xcheck}&Hdr2={xcache}&Hdr3={xcacheremote}RespSize=10&RespFile=test"
    );
    
}
