/*-----------------------------------------------------------------------------
    Name: MainUrlAuth
    Generated By: netstorm
    Date of generation: 02/26/2012 11:12:39
    Flow details:
    Modification History:
-----------------------------------------------------------------------------*/

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "ns_string.h"

void MainUrlAuth()
{
    ns_web_url ("ntlm_html",
        "URL=http://10.10.30.69:8011/BasicDigest/Basic.html",
        "HTTPAuthUserName=%Username",
        "HTTPAuthPassword=%Password",
);
ns_page_think_time(0); 
   ns_web_url ("index_html",
        "URL=http://10.10.30.69:8011/BasicDigest/flower.html",
        "HTTPAuthUserName={Username}",
        "HTTPAuthPassword={Password}",
);
   ns_page_think_time(0);
}
