$TestDescription

#Testcases for Firefox/Chromium browser
#Firefox 24 is used as NS Firefox(default case)
#Chromium 34 is used as NS Chrome
SMOKE-037-001

# TODO

#Testcases for clip capture feature to get page render time value
#Testcases for browser cache mechanism for chrome implementation of RBU

#SMOKE-011-001|Smoke_RBU|1|1|60|G_RBU ALL ALL 1 1 0 1 0|G_RBU_CAPTURE_CLIPS ALL 0 100 100|G_RBU_CACHE_SETTING G1 0 0|RBU_USER_AGENT 2 RBU_FIREFOX_USER_AGENT|ENABLE_NS_FIREFOX 1|G_RBU_ADD_HEADER G1 0 GET automation:header

#$TESTNAME|$SCRIPT|$VUSER|$SESSIONS|%PAGELOADWAITTIME|$RBU_KEYWORD|$RBU_CAPTURE_CLIP|$RBU_CACHE_SETTING|$RBU_USER_AGENT|$ENABLE_RBU_TYPE|$RBU_ADD_HEADER

# CLICK AND SCRIPT RBU TESTCASE

# TIME TO INTERACT RBU TESTCASE

# RBU TEST WITH MULTIPLE SCRIPTS; ISSUE WAS IN MACY'S CORE WAS GENERATED IN SUCH SCENARIO
