/*-----------------------------------------------------------------------------
    Name: init_script
    Generated By: netstorm
    Date of generation: 11/26/2010 3:15:34
    Flow details:
    Modification History:
-----------------------------------------------------------------------------*/

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "ns_string.h"

extern int selectStartService();

int init_script()
{
    return(selectStartService());
    //return 0;
}
