/*-----------------------------------------------------------------------------
    Name: Load_KS_NEW
    Generated By: netstorm
    Date of generation: 11/26/2010 3:15:34
    Flow details:
    Modification History:
-----------------------------------------------------------------------------*/

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "ns_string.h"

#define GetCustCredit 0
#define DiscountValidationService 1
#define RentService 2
#define KioskOptInService 3
#define ReconcileService 4
#define ReturnService 5
#define KioskPing 6
#define AuthorizeFailure 7
#define ReconcileFailure 8
#define UnplayableReturnService 9
#define ReturnService2 10
#define KioskAnalytics 11
#define DiscActionService 12
#define EmailConfirmation 13
#define PickUpValidation 14
#define PickUp 15

#include "RedBoxSettings.c"
#include "RedBoxRentPurchase.c"
#include "RedBoxPing.c"

static void CCNumVal(int per)
{
  int percent = per * 100;
  int random = ns_get_random_number_int(1,10000);
  if(percent < random)
  {
    ns_advance_param("CCNumVar1");
    ns_save_string(ns_eval_string("{CCNumVar1}"),"CCNumVar");
    ns_save_string(ns_eval_string("{CCLastNameVar1}"),"CCLastNameVar");
    ns_save_string(ns_eval_string("{CCFirstNameVar1}"),"CCFirstNameVar");
    ns_save_string(ns_eval_string("{CCPostalCodeVar1}"),"CCPostalCodeVar");
    ns_save_string(ns_eval_string("{CCExpirationMonthVar1}"),"CCExpirationMonthVar");
    ns_save_string(ns_eval_string("{CCExpirationYearVar1}"),"CCExpirationYearVar");
    ns_save_string(ns_eval_string("{CCIdVar1}"),"CCIdVar");
    ns_save_string(ns_eval_string("{CCLastFourVar1}"),"CCLastFourVar");
    ns_save_string(ns_eval_string("{CCTypeVar1}"),"CCTypeVar");
    ns_save_string(ns_eval_string("{CCKeyIdVar1}"),"CCKeyIdVar");
    ns_save_string(ns_eval_string("{CCTrack2Var1}"),"CCTrack2Var");
  }
  else
  {
    ns_advance_param("CCNumVar2");
    ns_save_string(ns_eval_string("{CCNumVar2}"),"CCNumVar");
    ns_save_string(ns_eval_string("{CCLastNameVar2}"),"CCLastNameVar");
    ns_save_string(ns_eval_string("{CCFirstNameVar2}"),"CCFirstNameVar");
    ns_save_string(ns_eval_string("{CCPostalCodeVar2}"),"CCPostalCodeVar");
    ns_save_string(ns_eval_string("{CCExpirationMonthVar2}"),"CCExpirationMonthVar");
    ns_save_string(ns_eval_string("{CCExpirationYearVar2}"),"CCExpirationYearVar");
    ns_save_string(ns_eval_string("{CCIdVar2}"),"CCIdVar");
    ns_save_string(ns_eval_string("{CCLastFourVar2}"),"CCLastFourVar");
    ns_save_string(ns_eval_string("{CCTypeVar2}"),"CCTypeVar");
    ns_save_string(ns_eval_string("{CCKeyIdVar2}"),"CCKeyIdVar");
    ns_save_string(ns_eval_string("{CCTrack2Var2}"),"CCTrack2Var");
  }
}

static void GCNumVal()
{
    ns_advance_param("GCNumVar");
    ns_save_string(ns_eval_string("{GCNumVar}"),"CCNumVar");
    ns_save_string(ns_eval_string("{GCExpirationMonthVar}"),"CCExpirationMonthVar");
    ns_save_string(ns_eval_string("{GCExpirationYearVar}"),"CCExpirationYearVar");
    ns_save_string(ns_eval_string("{GCIdVar}"),"CCIdVar");
    ns_save_string(ns_eval_string("{GCLastFourVar}"),"CCLastFourVar");
    ns_save_string(ns_eval_string("{GCKeyIdVar}"),"CCKeyIdVar");
    ns_save_string(ns_eval_string("{GCTrack2Var}"),"CCTrack2Var");
}
	
static void GCPickUp(int per)
{
  int percent = per * 100;
  int random = ns_get_random_number_int(1,10000);
  if(percent < random)
  {
   ns_advance_param("CCCardNumber");
   ns_advance_param("CCKioskId");
   ns_save_string(ns_eval_string("{CCFirstName}"),"FirstName");
   ns_save_string(ns_eval_string("{CCLastName}"),"LastName");
   ns_save_string(ns_eval_string("{CCCardNumber}"),"CardNumber");
   ns_save_string(ns_eval_string("{CCPostalCode}"),"PostalCode");
   ns_save_string(ns_eval_string("{CCExpMonth}"),"ExpMonth");
   ns_save_string(ns_eval_string("{CCExpYear}"),"ExpYear");
   ns_save_string(ns_eval_string("{CCKeyId}"),"KeyId");
   ns_save_string(ns_eval_string("{CCCardID}"),"CardID");
   ns_save_string(ns_eval_string("{CCLastFour}"),"LastFour");
   ns_save_string(ns_eval_string("{CCCardType}"),"CardType");
   ns_save_string(ns_eval_string("{CCTrack2}"),"Track2");
   ns_save_string(ns_eval_string("{CCPickUpEmail}"),"PickUpEmail");
   ns_save_string(ns_eval_string("{CCBarcodeVal}"),"BarcodeVal");
   ns_save_string(ns_eval_string("{CCRefNumber}"),"RefNumber");
   ns_save_string(ns_eval_string("{CCKioskId}"),"KioskId");
  }
  else
  {
   ns_advance_param("GCCardNumber");
   ns_advance_param("GCKioskId");
   ns_save_string(ns_eval_string("{GCFirstName}"),"FirstName");
   ns_save_string(ns_eval_string("{GCLastName}"),"LastName");
   ns_save_string(ns_eval_string("{GCCardNumber}"),"CardNumber");
   ns_save_string(ns_eval_string("{GCExpMonth}"),"ExpMonth");
   ns_save_string(ns_eval_string("{GCExpYear}"),"ExpYear");
   ns_save_string(ns_eval_string("{GCKeyId}"),"KeyId");
   ns_save_string(ns_eval_string("{GCCardID}"),"CardID");
   ns_save_string(ns_eval_string("{GCLastFour}"),"LastFour");
   ns_save_string(ns_eval_string("{GCTrack2}"),"Track2");
   ns_save_string(ns_eval_string("{GCPickUpEmail}"),"PickUpEmail");
   ns_save_string(ns_eval_string("{GCBarcodeVal}"),"BarcodeVal");
   ns_save_string(ns_eval_string("{GCRefNumber}"),"RefNumber");
   ns_save_string(ns_eval_string("{GCKioskId}"),"KioskId");
  }
}

static void preGetCredit()
{
 #ifdef NS_DEBUG_ON 
  fprintf(stderr, "Info: %s method called.\n", __FUNCTION__);
 #endif

  ns_start_transaction("GetCreditMessage");
  CCNumVal(100);
  //ns_advance_param("CCNumVar"); 
  set_data_rent_service();
  set_msg_id();
  setLastGetCustCreditTS();
}

static int postGetCredit()
{
 #ifdef NS_DEBUG_ON 
  fprintf(stderr, "Info: %s method called.\n", __FUNCTION__);
 #endif

  int next_page;
  double pg_think_time;
  ns_end_transaction("GetCreditMessage", NS_AUTO_STATUS);
  next_page = getNextPageAndThinkTime("GetCustCredit", GetCustCredit, &pg_think_time);
  ns_page_think_time(pg_think_time); // This is to start think timer. Think time value will be set by above function call
  return(next_page);
}

static void preDiscount()
{
 #ifdef NS_DEBUG_ON 
  fprintf(stderr, "Info: %s method called.\n", __FUNCTION__);
 #endif

  ns_start_transaction("DiscountMessage");
  set_msg_id();
  setLastDiscountValidationTS();
}

static int postDiscount()
{
 #ifdef NS_DEBUG_ON 
  fprintf(stderr, "Info: %s method called.\n", __FUNCTION__);
 #endif
 
  int next_page;
  double pg_think_time;
  ns_end_transaction("DiscountMessage", NS_AUTO_STATUS);
  next_page = getNextPageAndThinkTime("DiscountValidationService", DiscountValidationService, &pg_think_time);
  ns_page_think_time(pg_think_time);
  return(next_page); 
}

static void preRent()
{
 #ifdef NS_DEBUG_ON 
  fprintf(stderr, "Info: %s method called.\n", __FUNCTION__);
 #endif
   int id = ns_get_int_val("ServiceIdVar");
 
  if(id == RB_GETCUST_CREDIT_ID){
    ns_start_transaction("GetCredit_AuthMessage");
    ns_save_string( "Authorize", "AuthMsgType");
   }
   else if(id == RB_DISCOUNT_VALIDATION_ID) {
    ns_start_transaction("Discount_AuthMessage");
    ns_save_string( "Authorize", "AuthMsgType");
    CCNumVal(0);
    set_data_rent_service();
   }
   else if(id == RB_GIFTCARD_ID) {
    ns_start_transaction("GC_AuthorizeMessage");
    ns_save_string( "GCAuthorize", "AuthMsgType");
    ns_save_string( "Redbox", "CCFirstNameVar");
    ns_save_string( "Server", "CCLastNameVar");
    ns_save_string( "null", "CCPostalCodeVar");
    ns_save_string( "6", "CCTypeVar");
    GCNumVal();
    set_data_rent_service();
    setLastGCRentalTS();
   }
   else{
    ns_start_transaction("AuthorizeMessage");
    ns_save_string( "Authorize", "AuthMsgType");
    CCNumVal(0);
    set_data_rent_service();
    if(id == RB_RENT_OPTIN_ID)
     setLastOptInRentalTS();
    else
     setLastRentalTS();
   }
  set_msg_id();
}

static int postRent()
{
#ifdef NS_DEBUG_ON 
  fprintf(stderr, "Info: %s method called.\n", __FUNCTION__);
#endif

  int next_page;
  double pg_think_time;
  ErrorCheck("RentService");
  int id = ns_get_int_val("ServiceIdVar");

  if(id == RB_GETCUST_CREDIT_ID) 
     ns_end_transaction("GetCredit_AuthMessage", NS_AUTO_STATUS);
  else if(id == RB_DISCOUNT_VALIDATION_ID)
     ns_end_transaction("Discount_AuthMessage", NS_AUTO_STATUS);
  else if(id == RB_GIFTCARD_ID) 
      ns_end_transaction("GC_AuthorizeMessage", NS_AUTO_STATUS);
  else
      ns_end_transaction("AuthorizeMessage", NS_AUTO_STATUS);

  next_page = getNextPageAndThinkTime("RentService", RentService, &pg_think_time);
  ns_page_think_time(pg_think_time);
  return(next_page);
}


static void preOptIn()
{
 #ifdef NS_DEBUG_ON
  fprintf(stderr, "Info: %s method called.\n", __FUNCTION__);
 #endif
  set_msg_id();
  //gen_email_id("EmailIdVar");
  ns_start_transaction("KioskOptInMessage");
}

static int postOptIn()
{
 #ifdef NS_DEBUG_ON
  fprintf(stderr, "Info: %s method called.\n", __FUNCTION__);
 #endif

  int next_page;
  double pg_think_time;
  
  ns_end_transaction("KioskOptInMessage", NS_AUTO_STATUS);
  next_page = getNextPageAndThinkTime("KioskOptInService", KioskOptInService, &pg_think_time);
  ns_page_think_time(pg_think_time);
  return(next_page);
}

static void preReconcile()
{
 #ifdef NS_DEBUG_ON 
  fprintf(stderr, "Info: %s method called.\n", __FUNCTION__);
 #endif
  set_msg_id();
  gen_email_id("EmailIdVar");
  int id = ns_get_int_val("ServiceIdVar");
 
  if(id == RB_GETCUST_CREDIT_ID){
    ns_start_transaction("GetCredit_ReconcileMessage");
    ns_save_string( "null", "DiscountCode");
    ns_save_string( "0", "DiscountValue");
  }
  else if(id == RB_DISCOUNT_VALIDATION_ID) {
    ns_start_transaction("Discount_ReconcileMessage");
    ns_save_string( "\"DVDONME\"", "DiscountCode");
  }
  else if(id == RB_GIFTCARD_ID) {
    ns_start_transaction("GC_ReconcileMessage");
    ns_save_string( "null", "DiscountCode");
    ns_save_string( "0", "DiscountValue");
  }
  else if(id != RB_OFFLINE_RENT_SERVICE_ID) {
    ns_start_transaction("ReconcileMessage");
    ns_save_string( "null", "DiscountCode");
    ns_save_string( "0", "DiscountValue");
  }
  else
  {
   ns_advance_param("CCNumVar");
   setLastOfflineRentalTS(); // Must take TS only in offline mode here
   set_data_rent_service();
   ns_start_transaction("ReconcileMessageOffline");
   ns_save_string( "null", "DiscountCode");
   ns_save_string( "0", "DiscountValue");
  }
}

static int postReconcile()
{
#ifdef NS_DEBUG_ON 
  fprintf(stderr, "Info: %s method called.\n", __FUNCTION__);
#endif

  int next_page;
  double pg_think_time;
  ErrorCheck("ReconcileService");
  int id = ns_get_int_val("ServiceIdVar");

  if(id == RB_GETCUST_CREDIT_ID)
    ns_end_transaction("GetCredit_ReconcileMessage", NS_AUTO_STATUS);
  else if(id == RB_DISCOUNT_VALIDATION_ID)
    ns_end_transaction("Discount_ReconcileMessage", NS_AUTO_STATUS);
  else if(id == RB_GIFTCARD_ID)
   ns_end_transaction("GC_ReconcileMessage", NS_AUTO_STATUS);
  else if(id == RB_OFFLINE_RENT_SERVICE_ID)
    ns_end_transaction("ReconcileMessageOffline", NS_AUTO_STATUS);
  else
    ns_end_transaction("ReconcileMessage", NS_AUTO_STATUS);

  next_page = getNextPageAndThinkTime("ReconcileService", ReconcileService, &pg_think_time);
  ns_page_think_time(pg_think_time);
  return(next_page);
}


static void preReturn()
{
#ifdef NS_DEBUG_ON 
  fprintf(stderr, "Info: %s method called.\n", __FUNCTION__);
#endif
  ns_start_transaction("ReturnDVD");
  set_msg_id();
  setLastReturnTS();
  //ns_advance_param("ReturnBarcodeVar");

  char *temp;
  int num;
  num = ns_get_random_number_int(1,10000);
  if(num < 1000){
    ns_advance_param("ReturnWidCreditVar");
    temp = ns_eval_string("{ReturnWidCreditVar}");
    ns_save_string(temp,"ReturnBarcodeVar");
  }else {
    ns_advance_param("ReturnWidNoCreditVar");
    temp = ns_eval_string("{ReturnWidNoCreditVar}");
    ns_save_string(temp,"ReturnBarcodeVar");
  }
}

static int postReturn()
{
#ifdef NS_DEBUG_ON 
  fprintf(stderr, "Info: %s method called.\n", __FUNCTION__);
#endif

  int next_page;
  double pg_think_time;

  ns_end_transaction("ReturnDVD", NS_AUTO_STATUS); //Chk iteturnservice
  next_page = getNextPageAndThinkTime("ReturnService", ReturnService, &pg_think_time);
  ns_page_think_time(pg_think_time);
  return(next_page);
}


static void prePing()
{
#ifdef NS_DEBUG_ON 
  fprintf(stderr, "Info: %s method called.\n", __FUNCTION__);
#endif
  ns_start_transaction("KioskPing");
  set_msg_id();
  setLastPingTS();
}

static int postPing()
{
#ifdef NS_DEBUG_ON 
  fprintf(stderr, "Info: %s method called.\n", __FUNCTION__);
#endif

  int next_page;
  double pg_think_time;
  ns_end_transaction("KioskPing", NS_AUTO_STATUS); //Chk iteturnservice
  next_page = getNextPageAndThinkTime("KioskPing", KioskPing, &pg_think_time);
  ns_page_think_time(pg_think_time);
  return(next_page);
}


static void preAuthFail()
{
#ifdef NS_DEBUG_ON 
  fprintf(stderr, "Info: %s method called.\n", __FUNCTION__);
#endif
  ns_start_transaction("AuthorizeFailure");
  ns_advance_param("CCNumVar");
  set_msg_id();
  setLastFailureRentalTS();
}

static int postAuthFail()
{
#ifdef NS_DEBUG_ON 
  fprintf(stderr, "Info: %s method called.\n", __FUNCTION__);
#endif
  int next_page;
  double pg_think_time;
  ErrorCheck("AuthorizeFailure");
  ns_end_transaction("AuthorizeFailure", NS_AUTO_STATUS); //Chk iteturnservice
  next_page = getNextPageAndThinkTime("AuthorizeFailure", AuthorizeFailure, &pg_think_time);
  ns_page_think_time(pg_think_time);
  return(next_page);
}

static void preReconcileFail()
{
#ifdef NS_DEBUG_ON 
  fprintf(stderr, "Info: %s method called.\n", __FUNCTION__);
#endif
  ns_start_transaction("ReconcileFailure");
  set_msg_id();
}

static int postReconcileFail()
{
#ifdef NS_DEBUG_ON 
  fprintf(stderr, "Info: %s method called.\n", __FUNCTION__);
#endif
  int next_page;
  double pg_think_time;
  ErrorCheck("ReconcileFailure");
  ns_end_transaction("ReconcileFailure", NS_AUTO_STATUS); //Chk iteturnservice
  next_page = getNextPageAndThinkTime("ReconcileFailure", ReconcileFailure, &pg_think_time);
  ns_page_think_time(pg_think_time);
  return(next_page);
}


static void preUnplayable()
{
#ifdef NS_DEBUG_ON 
  fprintf(stderr, "Info: %s method called.\n", __FUNCTION__);
#endif
  ns_start_transaction("UnplayableReturnMessage");
  set_msg_id();
  setLastUnplayableTS();
  ns_advance_param("ReturnBarcodeVar");
}

static int postUnplayable()
{
#ifdef NS_DEBUG_ON 
  fprintf(stderr, "Info: %s method called.\n", __FUNCTION__);
#endif
  int next_page;
  double pg_think_time;
  ns_end_transaction("UnplayableReturnMessage",NS_AUTO_STATUS);
  next_page = getNextPageAndThinkTime("UnplayableReturnService", UnplayableReturnService, &pg_think_time);
  ns_page_think_time(pg_think_time);
  return(next_page);
}

static void preReturn2()
{
#ifdef NS_DEBUG_ON 
  fprintf(stderr, "Info: %s method called.\n", __FUNCTION__);
#endif
  ns_start_transaction("ReturnMessage2");
  set_msg_id();
}

static int postReturn2()
{
#ifdef NS_DEBUG_ON 
  fprintf(stderr, "Info: %s method called.\n", __FUNCTION__);
#endif
  int next_page;
  double pg_think_time;
  ns_end_transaction("ReturnMessage2",NS_AUTO_STATUS);
  next_page = getNextPageAndThinkTime("ReturnService2", ReturnService2, &pg_think_time);
  ns_page_think_time(pg_think_time);
  return(next_page);
}


static void preAnalytics()
{
#ifdef NS_DEBUG_ON 
  fprintf(stderr, "Info: %s method called.\n", __FUNCTION__);
#endif
  ns_start_transaction("KioskAnalyticsMessage");
  set_msg_id();
  setLastKioskAnalyticsTS();
}

static int postAnalytics()
{
#ifdef NS_DEBUG_ON 
  fprintf(stderr, "Info: %s method called.\n", __FUNCTION__);
#endif
  int next_page;
  double pg_think_time;
  ns_end_transaction("KioskAnalyticsMessage",NS_AUTO_STATUS);
  next_page = getNextPageAndThinkTime("KioskAnalytics", KioskAnalytics, &pg_think_time);
  ns_page_think_time(pg_think_time);
  return(next_page);
}


static void preDiscAction()
{
#ifdef NS_DEBUG_ON
  fprintf(stderr, "Info: %s method called.\n", __FUNCTION__);
#endif
  ns_start_transaction("DiscActionMessage");
  set_msg_id();
  setLastDiscActionTS();
}

static int postDiscAction()
{
#ifdef NS_DEBUG_ON
  fprintf(stderr, "Info: %s method called.\n", __FUNCTION__);
#endif
  int next_page;
  double pg_think_time;
  ns_end_transaction("DiscActionMessage",NS_AUTO_STATUS);
  next_page = getNextPageAndThinkTime("DiscActionService", DiscActionService, &pg_think_time);
  ns_page_think_time(pg_think_time);
  return(next_page);
}

static void preEmailConfirm()
{
#ifdef NS_DEBUG_ON
  fprintf(stderr, "Info: %s method called.\n", __FUNCTION__);
#endif
  ns_start_transaction("EmailConfirmationMessage");
  set_msg_id();
  setLastEmailConfirmTS();
}

static int postEmailConfirm()
{
#ifdef NS_DEBUG_ON
  fprintf(stderr, "Info: %s method called.\n", __FUNCTION__);
#endif
  int next_page;
  double pg_think_time;
  ns_end_transaction("EmailConfirmationMessage",NS_AUTO_STATUS);
  next_page = getNextPageAndThinkTime("EmailConfirmation", EmailConfirmation, &pg_think_time);
  ns_page_think_time(pg_think_time);
  return(next_page);
}

static void prePickUpValidation()
{
 #ifdef NS_DEBUG_ON
  fprintf(stderr, "Info: %s method called.\n", __FUNCTION__);
 #endif
  int id = ns_get_int_val("ServiceIdVar");

  if(id == RB_PICK_UP_ID){
   ns_start_transaction("PickUpValidation");
   GCPickUp(0);
   setLastPickUpValidationTS();
  }
  else if(id == RB_GC_PICKUP_ID) {
   ns_start_transaction("GC_PickUpValidation");
   ns_save_string( "null", "PostalCode");
   ns_save_string( "6", "CardType");
   GCPickUp(100);
   setLastGCPickUpValidationTS();
  }
  set_msg_id();
}

static int postPickUpValidation()
{
 #ifdef NS_DEBUG_ON
  fprintf(stderr, "Info: %s method called.\n", __FUNCTION__);
 #endif
  int next_page;
  double pg_think_time;
  int id = ns_get_int_val("ServiceIdVar");

  if(id == RB_PICK_UP_ID)
   ns_end_transaction("PickUpValidation",NS_AUTO_STATUS);
  else if(id == RB_GC_PICKUP_ID)
   ns_end_transaction("GC_PickUpValidation", NS_AUTO_STATUS);

  next_page = getNextPageAndThinkTime("PickUpValidation", PickUpValidation, &pg_think_time);
  ns_page_think_time(pg_think_time);
  return(next_page);
}

static void prePickUp()
{
 #ifdef NS_DEBUG_ON
  fprintf(stderr, "Info: %s method called.\n", __FUNCTION__);
 #endif
  int id = ns_get_int_val("ServiceIdVar");
  
  if(id == RB_PICK_UP_ID)
   ns_start_transaction("PickUp");
  else if(id == RB_GC_PICKUP_ID)
   ns_start_transaction("GC_PickUp");
  set_msg_id();
}

static int postPickUp()
{
#ifdef NS_DEBUG_ON
  fprintf(stderr, "Info: %s method called.\n", __FUNCTION__);
#endif
  int next_page;
  double pg_think_time;
  int id = ns_get_int_val("ServiceIdVar");

  if(id == RB_PICK_UP_ID)
   ns_end_transaction("PickUp",NS_AUTO_STATUS);
  else if(id == RB_GC_PICKUP_ID)
   ns_end_transaction("GC_PickUp",NS_AUTO_STATUS);

  next_page = getNextPageAndThinkTime("PickUp", PickUp, &pg_think_time);
  ns_page_think_time(pg_think_time);
  return(next_page);
}


#define CHECK_AND_GOTO_NEXT_PAGE(next_page) \
{ \
  if (next_page == GetCustCredit) goto GetCreditPage;   \
  else if (next_page == DiscountValidationService)  goto DiscountPage;   \
  else if (next_page == RentService)  goto RentPage;   \
  else if (next_page == KioskOptInService)  goto KioskOptInPage;   \
  else if (next_page == ReconcileService)  goto ReconcilePage;   \
  else if (next_page == ReturnService)  goto ReturnPage;   \
  else if (next_page == KioskPing)  goto KioskPingPage;   \
  else if (next_page == AuthorizeFailure)  goto AuthFailPage;   \
  else if (next_page == ReconcileFailure)  goto ReconcileFailPage;   \
  else if (next_page == UnplayableReturnService)  goto UnplayablePage;   \
  else if (next_page == ReturnService2)  goto Return2Page;   \
  else if (next_page == KioskAnalytics)  goto AnalyticsPage;   \
  else if (next_page == DiscActionService)  goto DiscActionPage;   \
  else if (next_page == EmailConfirmation)  goto EmailConfirmPage;   \
  else if (next_page == PickUpValidation)  goto PickUpValidationPage;   \
  else if (next_page == PickUp)  goto PickUpPage;   \
}
  

void Load_KS_NEW()
{ 
int next_page;

    next_page = selectStartService();
    CHECK_AND_GOTO_NEXT_PAGE(next_page);

GetCreditPage: 
    preGetCredit();
    ns_web_url("GetCustCredit",
        "METHOD=POST",
        "URL=http://127.0.0.1/lab01-app01/KioskServices/MessageService_GetCustCredit.aspx",
	"HEADER=Accept-Language: en-us en;q=0.5",
        "HEADER=Accept-Charset: ISO-8859-1 utf-8;q=0.7 *;q=0.7",
        "HEADER=Content-Type: application/x-www-form-urlencoded",
	"HEADER=Expect: 100-continue",
        "BODY=$CAVINCLUDE$=GetCustCredit.json",
    );
    next_page = postGetCredit();
    CHECK_AND_GOTO_NEXT_PAGE(next_page);
    

DiscountPage:
    preDiscount();
    ns_web_url("DiscountValidationService",
        "METHOD=POST",
	"URL=http://127.0.0.1/lab01-app01/KioskServices/MessageService_DiscValdService.aspx",
	"HEADER=Accept-Language: en-us en;q=0.5",
        "HEADER=Accept-Charset: ISO-8859-1 utf-8;q=0.7 *;q=0.7",
        "HEADER=Content-Type: application/x-www-form-urlencoded", 
        "HEADER=Expect: 100-continue",
        "BODY=$CAVINCLUDE$=DiscountValidation.json",
        );
    next_page = postDiscount();
    CHECK_AND_GOTO_NEXT_PAGE(next_page);
 
   
RentPage:
    preRent();
    ns_web_url("RentService",
        "METHOD=POST",
	"URL=http://127.0.0.1/lab01-app01/KioskServices/MessageService_RentSvc.aspx",
	"HEADER=Accept-Language: en-us en;q=0.5",
        "HEADER=Accept-Charset: ISO-8859-1 utf-8;q=0.7 *;q=0.7",
        "HEADER=Content-Type: application/x-www-form-urlencoded",
        "HEADER=Expect: 100-continue",
        "BODY=$CAVINCLUDE$=AuthorizeReq.json",
    );
   next_page = postRent();
   CHECK_AND_GOTO_NEXT_PAGE(next_page);


KioskOptInPage:
   preOptIn();
   ns_web_url("KioskOptInService",
        "METHOD=POST",
	"URL=http://127.0.0.1/lab01-app01/KioskServices/MessageService_KioskOptInService.aspx",
	"HEADER=Accept-Language: en-us en;q=0.5",
        "HEADER=Accept-Charset: ISO-8859-1 utf-8;q=0.7 *;q=0.7",
        "HEADER=Content-Type: application/x-www-form-urlencoded",
        "HEADER=Expect: 100-continue",
        "BODY=$CAVINCLUDE$=KioskOptIn.json",
    );
   next_page = postOptIn();
   CHECK_AND_GOTO_NEXT_PAGE(next_page);


ReconcilePage:
    preReconcile();
    ns_web_url("ReconcileService",
        "METHOD=POST",
	"URL=http://127.0.0.1/lab01-app01/KioskServices/MessageService_ReconcileService.aspx",
	"HEADER=Accept-Language: en-us en;q=0.5",
        "HEADER=Accept-Charset: ISO-8859-1 utf-8;q=0.7 *;q=0.7",
        "HEADER=Content-Type: application/x-www-form-urlencoded",
        "HEADER=Expect: 100-continue",
        "BODY=$CAVINCLUDE$=ReconcileReq.json",
    );
    next_page = postReconcile();
    CHECK_AND_GOTO_NEXT_PAGE(next_page);


ReturnPage:
    preReturn();
    ns_web_url("ReturnService",
        "METHOD=POST",
	"URL=http://127.0.0.1/lab01-app01/KioskServices/MessageService_ReturnService.aspx",
	"HEADER=Accept-Language: en-us en;q=0.5",
        "HEADER=Accept-Charset: ISO-8859-1 utf-8;q=0.7 *;q=0.7",
        "HEADER=Content-Type: application/x-www-form-urlencoded",
        "HEADER=Expect: 100-continue",
        "BODY=$CAVINCLUDE$=ReturnReq.json",
    );
    next_page = postReturn();
    CHECK_AND_GOTO_NEXT_PAGE(next_page);
    
KioskPingPage:
    prePing();
    ns_web_url("KioskPing",
        "METHOD=POST",
	"URL=http://127.0.0.1/lab01-app01/KioskServices/MessageService_KioskPing.aspx",
	"HEADER=Accept-Language: en-us en;q=0.5",
        "HEADER=Accept-Charset: ISO-8859-1 utf-8;q=0.7 *;q=0.7",
        "HEADER=Content-Type: application/x-www-form-urlencoded",
        "HEADER=Expect: 100-continue",
        "BODY=$CAVINCLUDE$=KioskPing.json",
    );
    next_page = postPing();
    CHECK_AND_GOTO_NEXT_PAGE(next_page);


AuthFailPage:
    preAuthFail();
    ns_web_url("AuthorizeFailure",
        "METHOD=POST",
	"URL=http://127.0.0.1/lab01-app01/KioskServices/MessageService_AuthorizeFailure.aspx",
	"HEADER=Accept-Language: en-us en;q=0.5",
        "HEADER=Accept-Charset: ISO-8859-1 utf-8;q=0.7 *;q=0.7",
        "HEADER=Content-Type: application/x-www-form-urlencoded",
       	"HEADER=Expect: 100-continue",
        "BODY=$CAVINCLUDE$=AuthorizeFailure.json",
    );
    next_page = postAuthFail();
    CHECK_AND_GOTO_NEXT_PAGE(next_page);

   
ReconcileFailPage: 
    preReconcileFail();
    ns_web_url("ReconcileFailure",
        "METHOD=POST",
	"URL=http://127.0.0.1/lab01-app01/KioskServices/MessageService_ReconcileFailure.aspx",
	"HEADER=Accept-Language: en-us en;q=0.5",
        "HEADER=Accept-Charset: ISO-8859-1 utf-8;q=0.7 *;q=0.7", 
        "HEADER=Content-Type: application/x-www-form-urlencoded",
        "HEADER=Expect: 100-continue",
        "BODY=$CAVINCLUDE$=ReconcileFailure.json",
    );
    next_page = postReconcileFail();
    CHECK_AND_GOTO_NEXT_PAGE(next_page);


UnplayablePage:
    preUnplayable();
    ns_web_url("UnplayableReturnService",
        "METHOD=POST",
	"URL=http://127.0.0.1/lab01-app01/KioskServices/MessageService_UnplayableReturnService.aspx",
	"HEADER=Accept-Language: en-us en;q=0.5",
        "HEADER=Accept-Charset: ISO-8859-1 utf-8;q=0.7 *;q=0.7",
        "HEADER=Content-Type: application/x-www-form-urlencoded",
        "HEADER=Expect: 100-continue",
        "BODY=$CAVINCLUDE$=UnplayableReturnReq.json",
    );
    next_page = postUnplayable();
    CHECK_AND_GOTO_NEXT_PAGE(next_page);


Return2Page:
    preReturn2();
    ns_web_url("ReturnService2",
        "METHOD=POST",
	"URL=http://127.0.0.1/lab01-app01/KioskServices/MessageService_ReturnService2.aspx",
	"HEADER=Accept-Language: en-us en;q=0.5",
        "HEADER=Accept-Charset: ISO-8859-1 utf-8;q=0.7 *;q=0.7",
        "HEADER=Content-Type: application/x-www-form-urlencoded",
        "HEADER=Expect: 100-continue",
        "BODY=$CAVINCLUDE$=ReturnReq.json",
    );
    next_page = postReturn2();
    CHECK_AND_GOTO_NEXT_PAGE(next_page);


AnalyticsPage:
    preAnalytics();
    ns_web_url("KioskAnalytics",
        "METHOD=POST",
	"URL=http://127.0.0.1/lab01-app01/KioskServices/MessageService_KioskAnalytics.aspx",
	"HEADER=Accept-Language: en-us en;q=0.5",
        "HEADER=Accept-Charset: ISO-8859-1 utf-8;q=0.7 *;q=0.7",
        "HEADER=Content-Type: application/x-www-form-urlencoded",
        "HEADER=Expect: 100-continue",
        "BODY=$CAVINCLUDE$=KioskAnalytics.json",
    );
    next_page = postAnalytics();
    CHECK_AND_GOTO_NEXT_PAGE(next_page);

DiscActionPage:
    preDiscAction();
    ns_web_url("DiscActionService",
        "METHOD=POST",
        "URL=http://127.0.0.1/lab01-app01/KioskServices/MessageService_DiscActionService.aspx",
        "HEADER=Accept-Language: en-us en;q=0.5",
        "HEADER=Accept-Charset: ISO-8859-1 utf-8;q=0.7 *;q=0.7",
        "HEADER=Content-Type: application/x-www-form-urlencoded",
        "HEADER=Expect: 100-continue",
        "BODY=$CAVINCLUDE$=DiscAction.json",
    );
    next_page = postDiscAction();
    CHECK_AND_GOTO_NEXT_PAGE(next_page);

EmailConfirmPage:
    preEmailConfirm();
    ns_web_url("EmailConfirmation",
        "METHOD=POST",
        "URL=http://127.0.0.1/lab01-app01/KioskServices/MessageService_EmailConfirmation.aspx",
        "HEADER=Accept-Language: en-us en;q=0.5",
        "HEADER=Accept-Charset: ISO-8859-1 utf-8;q=0.7 *;q=0.7",
        "HEADER=Content-Type: application/x-www-form-urlencoded",
        "HEADER=Expect: 100-continue",
        "BODY=$CAVINCLUDE$=EmailConfirmReq.json",
    );
    next_page = postEmailConfirm();
    CHECK_AND_GOTO_NEXT_PAGE(next_page);

PickUpValidationPage:
    prePickUpValidation();
    ns_web_url("PickUpValidation",
        "METHOD=POST",
        "URL=http://127.0.0.1/lab01-app01/KioskServices/MessageService_PickUpValidation.aspx",
        "HEADER=Accept-Language: en-us en;q=0.5",
        "HEADER=Accept-Charset: ISO-8859-1 utf-8;q=0.7 *;q=0.7",
        "HEADER=Content-Type: application/x-www-form-urlencoded",
        "HEADER=Expect: 100-continue",
        "BODY=$CAVINCLUDE$=PickUpValidation.json",
    );
    next_page = postPickUpValidation();
    CHECK_AND_GOTO_NEXT_PAGE(next_page);

PickUpPage:
    prePickUp();
    ns_web_url("PickUp",
        "METHOD=POST",
        "URL=http://127.0.0.1/lab01-app01/KioskServices/MessageService_PickUp.aspx",
        "HEADER=Accept-Language: en-us en;q=0.5",
        "HEADER=Accept-Charset: ISO-8859-1 utf-8;q=0.7 *;q=0.7",
        "HEADER=Content-Type: application/x-www-form-urlencoded",
        "HEADER=Expect: 100-continue",
        "BODY=$CAVINCLUDE$=PickUp.json",
    );
    next_page = postPickUp();
    CHECK_AND_GOTO_NEXT_PAGE(next_page);
}
