/*-----------------------------------------------------------------------------
    Name: MainUrlAuth
    Generated By: netstorm
    Date of generation: 02/26/2012 11:12:39
    Flow details:
    Modification History:
-----------------------------------------------------------------------------*/

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "ns_string.h"

void MainUrlAuth()
{
    ns_web_url ("ntlm_html",
        "URL=http://127.0.0.1/http_auth/ntlm.xml%UrlSVC",
        "HTTPAuthUserName=%Username",
        "HTTPAuthPassword=%Password"

);
 
}
