#!/usr/bin/bash

version=`nsu_get_version | head -1 | awk -F " " '{print $2}'`
build=`nsu_get_version | head -1 | cut -d '#' -f2 | cut -d ')' -f1 | sed -e 's/\ //g'`
buildtimestamp=$(date +'%d/%m/%y %H:%M:%S %p')

pre_test_mail() {
	echo -e "
<!DOCTYPE html>
<html>
<head>
    <style type='text/css'>
        body{
            font-size: 1.0rem;
            color: #333;
        }
        .container{
          width: 50%;
          padding: 50px;
          border: 1px solid #e0e0e0;
        }
        hr {
          color: #A3C3FF;
        }
        .lead { 
        font-size: 1.68rem; 
        color: #616161; 
        font-weight: 300;
        }
        table {
            border-collapse: collapse;
            width: 80%;
        }
        table, th, td { 
            border: 1px solid #e0e0e0;
            padding: 10px;
            font-size: 1em;
        }
        th {
           background-color: #f5f5f5;
           text-align: left;
           color: #333;
        }
        .signature{ color: #607d8b;}
    </style>
</head>
<body>
    <div class='container'>
      <table style='width: 100%!important; border: 0px;'>
        <tr>
          <td width='30%' style='border: 0px!important; padding: 0px !important'><h2 class='lead'>NS Core Performance</h2></td>
          <td width='70%' style='border: 0px! important; padding: 0px!important'>
            <table>
               <tr>
               <th>Status</th>
               <th>Start Time</th>
               </tr>
               <tr>
               <td>Started</td>
               <td>$buildtimestamp</td>
               </tr>
            </table>
          </td>
        </tr>
    </table>
 
    <br><br>
 
    <p style='font-size: 110%'>
    Performance automation suite has been started for R$version B$build. <br>
    We shall notify you once the results are available.
    </p>
    
    <br><br>
    
    <p class='signature'>
        Automation Team,
        <br>Cavisson Systems Inc
    </p>
    
    </div>
</body>
</html>" >/home/automation/workbench/automation/nscore/lib/start_mail.html
	echo "curr.release = $version" >mail.properties
	echo "curr.build = $build" >>mail.properties
	echo "startup.mail.file = /home/automation/workbench/automation/nscore/lib/start_mail.html" >>mail.properties
    echo "configured.mail.list.to = dl-qa-teamleads@cavisson.com,neeraj@cavisson.com,functionalheads@cavisson.com" >>mail.properties
    echo "configured.mail.list.cc = dl-qa-nsc@cavisson.com,dl-qa-auto@cavisson.com,dl-sup-projmgt@cavisson.com" >>mail.properties
    #echo "configured.mail.list.to = vishal.singhal@cavisson.com, arun.yadav@cavisson.com" >>mail.properties
    #echo "configured.mail.list.cc = ranjeet.kumar@cavisson.com" >>mail.properties
	echo "mail.user = automation@cavisson.com" >> mail.properties
    echo "mail.password = Cavisson!" >> mail.properties
}

pre_test_mail
