#!/usr/bin/bash

version=`nsu_get_version | head -1 | awk -F " " '{print $2}'`
build=`nsu_get_version | head -1 | cut -d '#' -f2 | cut -d ')' -f1 | sed -e 's/\ //g'`
buildtimestamp=$(date +'%d/%m/%y %I:%M:%S %p')

pre_test_mail() {
	echo -e "
<!DOCTYPE html>
<html>
<head>
    <style type='text/css'>
       .container{
          width: 600px;
          padding: 10px;
          background-color: #F5F5F5;
          border: 1px solid #A3C3FF;
        }
        
        hr {
          color: #A3C3FF;
        }
    </style>
</head>
<body>
    <div class='container'>
        <h4>BUILD STARTED</h4>
        <b>Project:</b> NSCore Performance<br>
        <b>Start Time:</b> $buildtimestamp
        <hr/>
        <br><br>
        Automation Team,
        <br>Cavisson Systems Inc
    </div>
</body>
</html>" >/home/automation/workbench/automation/nscore/lib/start_mail.html
	echo "curr.release = $version" >mail.properties
	echo "curr.build = $build" >>mail.properties
	echo "startup.mail.file = /home/automation/workbench/automation/nscore/lib/start_mail.html" >>mail.properties
	echo "configured.mail.list.to = dl-qa-teamleads@cavisson.com,arun.yadav@cavisson.com,neeraj@cavisson.com,functionalheads@cavisson.com" >>mail.properties
	echo "configured.mail.list.cc = dl-qa-nsc@cavisson.com" >>mail.properties
}

pre_test_mail
