/*-----------------------------------------------------------------------------
    Name: allurlerr
    Generated By: netstorm
    Date of generation: 7/27/2011 1:20:49
    Flow details:
    Modification History:
-----------------------------------------------------------------------------*/

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "ns_string.h"

void allurlerr()
{
    ns_web_url ("test_1xx_html",
        "URL=http://127.0.0.1/custom/samples/response_line/test_1xx.html",
    );

    ns_page_think_time(0);

    ns_web_url ("test_2xx_html",
        "URL=http://127.0.0.1/custom/samples/response_line/test_2xx.html",
    );

    ns_page_think_time(0);

    ns_web_url ("test_3xx_html",
        "URL=http://127.0.0.1/custom/samples/response_line/test_3xx.html",
    );

    ns_page_think_time(0);

    ns_web_url ("test_4xx_html",
        "URL=http://127.0.0.1/custom/samples/response_line/test_4xx.html",
    );

    ns_page_think_time(0);

    ns_web_url ("test_5xx_html",
        "URL=http://127.0.0.1/custom/samples/response_line/test_5xx.html",
    );
    ns_page_think_time(0);

}