#!/usr/bin/env bash

source $NS_WDIR/lib/automation_util


function main(){
    case $(get_tname) in
        "SMOKE-028-001") validate_trace_level ;;
        "SMOKE-028-002") validate_trace_level ;;
        "SMOKE-028-003") validate_trace_level ;;
        "SMOKE-028-004") validate_trace_level ;;
        "SMOKE-028-005") validate_trace_level ;;
         *) handle_unknown_case ;;
         ?) handle_unknown_case ;;
    esac
}


function handle_unknown_case(){
    log_status_and_exit_ex "FAIL" "testcase not found"
}


function validate_trace_level(){
    log_status_and_exit_ex "PASS" "smoke trace level testcase passed"
}


main


exit 0

