#!/bin/bash

. $NS_WDIR/lib/automation_util
T_NAME=$(get_tname)


if [ "$T_NAME" == "SMOKE-003-001" ];then 
    if [ $SD_TotalURLHits -eq 6 ] && \
       [ $SD_TotalSuccURL -eq 6 ];then
        log_status_and_exit_ex "PASS" "Autofetch one main url five autofetch url Passed" 
    else
        log_status_and_exit_ex "FAIL" "Autofetch one main url five autofetch url Failed" 
    fi	 
fi


if [ "$T_NAME" == "SMOKE-003-002" ];then
    if [ $SD_TotalURLHits -eq 1 ] && \
       [ $SD_TotalSuccURL -eq 1 ];then
        log_status_and_exit_ex "PASS" "Autofetch disabled Passed"
    else
        log_status_and_exit_ex "FAIL" "Autofetch deisabled Failed"
    fi
fi


if [ "$T_NAME" == "SMOKE-003-003" ];then
    if [ $SD_TotalURLHits -eq 6 ] && \
       [ $SD_TotalSuccURL -eq 6 ];then
        log_status_and_exit_ex "PASS" "Autofetch enabled two embedded url Passed"
    else
        log_status_and_exit_ex "FAIL" "Autofetch enabled two embedded url Failed"
    fi
fi


if [ "$T_NAME" == "SMOKE-003-004" ];then
    if [ $SD_TotalURLHits -eq 3 ] && \
       [ $SD_TotalSuccURL -eq 3 ];then
        log_status_and_exit_ex "PASS" "Autofetch disabled two embedded url Passed"
    else
        log_status_and_exit_ex "FAIL" "Autofetch disabled two embedded url Failed"
    fi
fi


if [ "$T_NAME" == "SMOKE-003-005" ];then
    EXCL_DOM=`grep "10.10.30.96" $T_ID_REQ_PATH/url_req_0_0_0_0_0_0_0_0_0.dat| wc -l`
    debug "EXCL_DOM=${EXCL_DOM}"
    debug "SD_TotalSuccURL=${SD_TotalSuccURL}"
    echo ""
    if [ $SD_TotalSuccURL -eq 7 ] && \
       [ "$EXCL_DOM" == "13" ];then
          log_status_and_exit_ex "PASS" "Autofetch Inline Include Domain Passed"
    else
         log_status_and_exit_ex "FAIL" "Autofetch Inline Include Domain Failed"
    fi
fi


if [ "$T_NAME" == "SMOKE-003-006" ];then
    INCL_DOM_COUNT=`grep "Host: 10.10.30.96" $T_ID_REQ_PATH/url_req_0_0_0_0_0_0_0_0_0.dat | wc -l`
    debug "INCL_DOM_COUNT=${INCL_DOM_COUNT}"
    debug "INCL_DOM_COUNT=${INCL_DOM_COUNT}"  
  if [ $SD_TotalSuccURL -ge 7 ] && \
       [ "$INCL_DOM_COUNT" == "7" ];then
        log_status_and_exit_ex "PASS" "Autofetch Inline Exclude Domain Passed"
    else
        log_status_and_exit_ex "FAIL" "Autofetch Inline Exclude Domain Failed"
    fi
fi


if [ "$T_NAME" == "SMOKE-003-007" ];then
    INCL_URL_COUNT=`grep "GET .*.js" $T_ID_REQ_PATH/url_req_0_0_0_0_0_0_0_0_0.dat | wc -l`
    debug $INCL_URL_COUNT
    EXCL_URL_COUNT=`grep "*.css|*.png|*.jsp" $T_ID_REQ_PATH/url_req_0_0_0_0_0_0_0_0_0.dat | wc -l`
    debug $EXCL_URL_COUNT
    echo "SD_TotalSuccURL=${SD_TotalSuccURL}"
    if [ "$INCL_URL_COUNT" == "3" ] && \
       [ "$EXCL_URL_COUNT" == "0" ] && \
       [ $SD_TotalSuccURL -eq 4 ];then
        log_status_and_exit_ex "PASS" "Autofetch Inline Include Url Pattern Passed"
    else
        log_status_and_exit_ex "FAIL" "Autofetch Inline Include Url Pattern Failed"
    fi
fi


if [ "$T_NAME" == "SMOKE-003-008" ];then
    echo "T_NAME=$T_NAME matched"
    EXCL_URL_COUNT=`grep "/*/*/*/*.js?" $T_ID_REQ_PATH/url_req_0_0_0_0_0_0_0_0_0.dat | wc -l`
    echo $EXCL_URL_COUNT
    INCL_URL_COUNT=`grep "GET" $T_ID_REQ_PATH/url_req_0_0_0_0_0_0_0_0_0.dat | sed 1d | cut -d " " -f2 | cut -d '.' -f2 | grep -v "js?" | wc -l`
    echo $INCL_URL_COUNT 
    if [ "$INCL_URL_COUNT" == "10" ] && \
       [ "$EXCL_URL_COUNT" == "0" ] && \
       [ $SD_TotalSuccURL -eq 11 ];then
        log_status_and_exit_ex "PASS" "Autofetch Inline Exclude Url Pattern Passed"
    else
        log_status_and_exit_ex "FAIL" "Autofetch Inline Exclude Url Pattern Failed"
    fi
fi


if [ "$T_NAME" == "SMOKE-003-009" ];then
    JSP_URL=$(grep "GET" $T_ID_REQ_PATH/url_req_0_0_0_0_0_0_0_0_0.dat | cut -d " " -f2 | grep "jsp$")
    JS_URL=$(grep "GET" $T_ID_REQ_PATH/url_req_0_0_0_0_0_0_0_0_0.dat | cut -d " " -f2 | grep "js$")
    if [ -z "${JSP_URL}" ] && [ ! -z "${JS_URL}" ]; then
        log_status_and_exit_ex "PASS" "No jsp based url being requested after excluding jsp based pattern"
    else
        log_status_and_exit_ex "FAIL" "jsp based url being requested after excluding jsp based pattern"
    fi
fi


if [ "$T_NAME" == "SMOKE-003-010" ];then
    JSP_URL=$(grep "GET" $T_ID_REQ_PATH/url_req_0_0_0_0_0_0_0_0_0.dat | cut -d " " -f2 | grep "jsp$")
    JS_URL=$(grep "GET" $T_ID_REQ_PATH/url_req_0_0_0_0_0_0_0_0_0.dat | cut -d " " -f2 | grep "js$")
    if [ ! -z "${JSP_URL}" ] && [ -z "${JS_URL}" ]; then
        log_status_and_exit_ex "PASS" "jsp based url being requested after including jsp based pattern"
    else
        log_status_and_exit_ex "FAIL" "No jsp based url being requested after including jsp based pattern"
    fi
fi


if [ "$T_NAME" == "SMOKE-003-011" ];then
    JS_URL=$(grep "GET" $T_ID_REQ_PATH/url_req_0_0_0_0_0_0_0_0_0.dat | cut -d " " -f2 | grep "js$")
    JSP_URL=$(grep "GET" $T_ID_REQ_PATH/url_req_0_0_0_0_0_0_0_0_0.dat | cut -d " " -f2 | grep "jsp$")
    if [ ! -z "${JSP_URL}" ] && [ -z "${JS_URL}" ]; then
        log_status_and_exit_ex "PASS" "js based url were not requested after excluding js+ based pattern"
    else
        log_status_and_exit_ex "FAIL" "some js based url were found in request after excluding js+ based pattern"
    fi
fi


if [ "$T_NAME" == "SMOKE-003-012" ];then
    JS_URL=$(grep "GET" $T_ID_REQ_PATH/url_req_0_0_0_0_0_0_0_0_0.dat | cut -d " " -f2 | grep "js$")
    JSP_URL=$(grep "GET" $T_ID_REQ_PATH/url_req_0_0_0_0_0_0_0_0_0.dat | cut -d " " -f2 | grep "jsp$")
    if [ -z "${JSP_URL}" ] && [ ! -z "${JS_URL}" ]; then
        log_status_and_exit_ex "PASS" "jsp inlines have been filtered out but js being included for js? pattern"
    else
        log_status_and_exit_ex "FAIL" "jsp and js both inlines have been included for js? pattern"
    fi
fi


if [ "$T_NAME" == "SMOKE-003-013" ];then
    JS_URL=$(grep "GET" $T_ID_REQ_PATH/url_req_0_0_0_0_0_0_0_0_0.dat | cut -d " " -f2 | grep "js$")
    JSP_URL=$(grep "GET" $T_ID_REQ_PATH/url_req_0_0_0_0_0_0_0_0_0.dat | cut -d " " -f2 | grep "jsp$")
    if [ ! -z "${JSP_URL}" ] && [ ! -z "${JS_URL}" ]; then
        log_status_and_exit_ex "PASS" "only js and jsp based inlines have been requested for including jsp? pattern"
    else
        log_status_and_exit_ex "FAIL" "either of the url type; js or jsp have been missing in request;for including jsp? pattern"
    fi
fi


if [ "$T_NAME" == "SMOKE-003-014" ];then
    JS_URL=$(grep "GET" $T_ID_REQ_PATH/url_req_0_0_0_0_0_0_0_0_0.dat | cut -d " " -f2 | grep "js$")
    JSP_URL=$(grep "GET" $T_ID_REQ_PATH/url_req_0_0_0_0_0_0_0_0_0.dat | cut -d " " -f2 | grep "jsp$")
    if [ ! -z "${JSP_URL}" ] && [ ! -z "${JS_URL}" ]; then
        log_status_and_exit_ex "PASS" "jsp and js both inlines have been included for js* pattern"
    else
        log_status_and_exit_ex "FAIL" "some of js or jsp inlines have not been included for js* pattern"
    fi
fi


if [ "$T_NAME" == "SMOKE-003-015" ];then
    JS_URL=$(grep "GET" $T_ID_REQ_PATH/url_req_0_0_0_0_0_0_0_0_0.dat | cut -d " " -f2 | grep "js$")
    JSP_URL=$(grep "GET" $T_ID_REQ_PATH/url_req_0_0_0_0_0_0_0_0_0.dat | cut -d " " -f2 | grep "jsp$")
    if [ ! -z "${JSP_URL}" ] && [ ! -z "${JS_URL}" ]; then
        log_status_and_exit_ex "PASS" "jsp and js both inlines have been included for j[sp]+ pattern"
    else
        log_status_and_exit_ex "FAIL" "some of js or jsp inlines have not been included for j[sp]+ pattern"
    fi
fi


if [ "$T_NAME" == "SMOKE-003-016" ];then
    #TODO Need to add validation codes to check test results
    log_status_and_exit_ex "PASS" "PostURLCallBack for set embed objects api;mode zero;not implemented"
fi


if [ "$T_NAME" == "SMOKE-003-017" ];then
    #TODO Need to add validation codes to check test results
    log_status_and_exit_ex "PASS" "PostURLCallBack for set embd objects api;mode one;not implemented"
fi


if [ "$T_NAME" == "SMOKE-003-018" ];then
    #TODO Need to add validation codes to check test results
    log_status_and_exit_ex "PASS" "PostURLCallBack for set embd objects api;url redirection;not implemented"
fi


exit 0
