/*-----------------------------------------------------------------------------
    Name: CookieTest4URL_Mode1
    Generated By: netstorm
    Date of generation: 9/27/2011 3:7:32
    Flow details:
    Modification History:
-----------------------------------------------------------------------------*/

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "ns_string.h"

void CookieTest4URL_Mode1()
{
    ns_web_url ("cookie_test_html",
        "URL=http://127.0.0.1/AutoCookie/cookie_test.html?CookieMode={class}&Name={name}&Domain={dom}&Path={pa}&Expires={exp}",
    );

    ns_page_think_time(0);

    ns_web_url ("cookie_test_html_1",
        "URL=http://127.0.0.1/AutoCookie/cookie_test.html?CookieMode={class}&Name={name}&Domain={dom}&Path={pa}&Expires={exp}",
    );

    ns_page_think_time(0);

    ns_web_url ("cookie_test_html_2",
        "URL=http://127.0.0.1/AutoCookie/cookie_test.html?CookieMode={class}&Name={name}&Domain={dom}&Path={pa}&Expires={exp}",
    );

    ns_page_think_time(0);

    ns_web_url ("cookie_test_html_3",
        "URL=http://127.0.0.1/AutoCookie/cookie_test.html?CookieMode={class}&Name={name}&Domain={dom}&Path={pa}&Expires={exp}",
    );
    ns_page_think_time(0);

}
