/*-----------------------------------------------------------------------------
    Name: flow
    Generated By: netstorm
    Date of generation: 12/30/2014 10:27:24
    Flow details:
    Build details: 4.1.0 (build# 1)
    Modification History:
-----------------------------------------------------------------------------*/

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "ns_string.h"


void flow()
{

ns_imap_list("ns-imap-list",
        "IMAPS_SERVER=%name",
        "USER_ID=niraj.panda@cavisson.com",
        "PASSWORD=Cavisson!",
);

ns_imap_fetch("ns-imap-fetct",
        "IMAPS_SERVER=%name",
        "USER_ID=niraj.panda@cavisson.com",
        "PASSWORD=Cavisson!",
        "MAIL_SEQ=%type",
        "FETCH=%rr_type"
);

ns_imap_select("ns-imap-select",
        "IMAPS_SERVER=%name",
        "USER_ID=niraj.panda@cavisson.com",
        "PASSWORD=Cavisson!",
);

}
