#!/bin/bash

. $NS_WDIR/lib/automation_util
#fill_report_summary
T_NAME=$(get_tname)
PAGE_FAIL=`grep -r "Page Failures" $NS_WDIR/logs/TR$T_RUN_ID/summary.data |awk '{print $2}' | cut -d '|' -f2`

#Cases for Basic Authentication
if [ "XX$T_NAME" == "XXSMOKE-002-001" ];then 
    AUTH_HEADER=`grep -w "WWW-Authenticate:" $T_ID_REQ_PATH/url_rep_0_0_0_0_0_0_0_0_0.dat |cut -d ':' -f2`
    if [ "XX$SD_URLFailures" == "XX0" ] && \
       [ "XX$SD_TotalSuccURL" == "XX6" ] && \
       [ "$AUTH_HEADER" == " Basic realm=\"Basic Authentication\"" ];then
        log_status_and_exit_ex "PASS" "Http authentication basic for apache main param session Passed"
    else
	log_status_and_exit_ex "FAIL" "Http authentication basic for apache main param session Failed" 
    fi 
fi

if [ "XX$T_NAME" == "XXSMOKE-002-002" ];then
    AUTH_HEADER=`grep -w "WWW-Authenticate:" $T_ID_REQ_PATH/url_rep_0_0_0_0_0_0_0_0_0.dat |cut -d ':' -f2`
    if [ "XX$SD_URLFailures" == "XX0" ] && \
       [ "XX$SD_TotalSuccURL" == "XX4" ] && \
       [ "$AUTH_HEADER" == " Basic realm=\"Basic Authentication\"" ];then
        log_status_and_exit_ex "PASS" "Http authentication basic for apache main param use Passed"
    else
        log_status_and_exit_ex "FAIL" "Http authentication basic for apache main param use Failed"
    fi
fi

if [ "XX$T_NAME" == "XXSMOKE-002-003" ];then
    AUTH_HEADER=`grep -w "WWW-Authenticate:" $T_ID_REQ_PATH/url_rep_0_0_0_0_0_0_0_0_0.dat |cut -d ':' -f2`
    PAGE_DUMP=`grep -o "Flowers are modified leaves possessed only by the group known" $T_ID_REQ_PATH/../../page_dump/docs/0\:0\:Main_apache_PageDump\:flower_html\:0.orig`	 
    if [ "XX$SD_URLFailures" == "XX0" ] && \
       [ "XX$SD_TotalSuccURL" == "XX2" ] && \
       [ "$AUTH_HEADER" == " Basic realm=\"Basic Authentication\"" ] && \
       [ "XX$PAGE_DUMP" == "XXFlowers are modified leaves possessed only by the group known" ]; then
        log_status_and_exit_ex "PASS" "Http authentication basic for apache for Page Dump Passed"
    else
        log_status_and_exit_ex "FAIL" "Http authentication basic for apache for PageDump Failed"
    fi
fi

if [ "XX$T_NAME" == "XXSMOKE-002-004" ];then
    AUTH_HEADER=`grep -w "WWW-Authenticate:" $T_ID_REQ_PATH/url_rep_0_0_0_0_0_0_0_0_0.dat |cut -d ':' -f2`
    SEARCH_VAR=`grep -o "?response from 82 serevr for" $T_ID_REQ_PATH/url_req_0_0_0_1_0_0_0_1_0.dat |wc -l`
    if [ "XX$SD_URLFailures" == "XX0" ] && \
       [ "XX$SD_TotalSuccURL" == "XX5" ] && \
       [ "$AUTH_HEADER" == " Basic realm=\"Basic Authentication\"" ] && \
       [ "XX$SEARCH_VAR" == "XX2" ]; then
        log_status_and_exit_ex "PASS" "Http authentication basic main with keep alive Passed"
    else
        log_status_and_exit_ex "FAIL" "Http authentication basic main with keep alive Failed"
    fi
fi



if [ "XX$T_NAME" == "XXSMOKE-002-005" ];then
    AUTH_HEADER=`grep -w "WWW-Authenticate:" $T_ID_REQ_PATH/url_rep_0_0_0_0_0_0_0_0_0.dat |cut -d ':' -f2`
    SEARCH_VAR=`grep -o "?response from 82 serevr for" $T_ID_REQ_PATH/url_req_0_0_0_1_0_0_0_1_0.dat |wc -l`
    if [ "XX$PAGE_FAIL" == "XX1" ] && \
       [ "XX$SD_TotalSuccURL" == "XX5" ] && \
       [ "$AUTH_HEADER" == " Basic realm=\"Basic Authentication\"" ] && \
       [ "XX$SEARCH_VAR" == "XX2" ]; then
        log_status_and_exit_ex "PASS" "Http authentication basic main cvfail without keepalive Passed"
    else
        log_status_and_exit_ex "FAIL" "Http authentication basic main cvfail without keepalive Failed"
    fi
fi

exit 0
