/*-----------------------------------------------------------------------------
    Name: init_script
    Generated By: netstorm
    Date of generation: 9/30/2011 10:12:47
    Flow details:
    Modification History:
-----------------------------------------------------------------------------*/

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "ns_string.h"

int init_script()
{
    return 0;
}
