/*-----------------------------------------------------------------------------
    Name: auth_2_12_MissingIndex
    Generated By: netstorm
    Date of generation: 09/28/2016 01:06:45
    Flow details:
    Build details: 4.1.6 (build# 18)
    Modification History:
-----------------------------------------------------------------------------*/

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "ns_string.h"

void auth_2_12_MissingIndex()
{
    ns_web_url ("auth_2_12_MissingIndex",
        "URL=http://127.0.0.1/simsapp/authentication/authLogin",
        "METHOD=POST"
    );

    ns_page_think_time(((double )ns_get_pg_think_time())/1000.0);

}
