/*-----------------------------------------------------------------------------
    Name: init_script
    Generated By: netstorm
    Date of generation: 12/30/2014 10:27:24
    Flow details:
    Build details: 4.1.0 (build# 1)
    Modification History:
-----------------------------------------------------------------------------*/

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "ns_string.h"

int init_script()
{
    return 0;
}
