/*-----------------------------------------------------------------------------
    Name: CookieClient
    Generated By: netstorm
    Date of generation: 07/19/2012 11:29:15
    Flow details:
    Modification History:
-----------------------------------------------------------------------------*/

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "ns_string.h"

void CookieClient()
{
    ns_web_url ("Cookie_Smoke",
        "URL=http://127.0.0.1/Cookie_Smoke/Cookie_smoke.html"
    );

    ns_page_think_time(0);

    ns_web_url ("index_html",
            "URL=http://192.168.255.3/tours/index.html",
            "HEADER=Accept-Language:en-us,en;q=0.5",
            "PreSnapshot=webpage_1440668801861.png",
            "Snapshot=webpage_1440668802047.png",
          /*  INLINE_URLS,
            "URL=http://127.0.0.1/tours/Merc10-dev/images/banner_animated.gif", "HEADER=Accept-Language:en-us,en;q=0.5", END_INLINE,
            "URL=http://127.0.0.1/tours/Merc10-dev/images/sun_swede.gif", "HEADER=Accept-Language:en-us,en;q=0.5", END_INLINE,
            "URL=http://127.0.0.1/tours/Merc10-dev/images/login.gif", "HEADER=Accept-Language:en-us,en;q=0.5", END_INLINE,
            "URL=http://127.0.0.1/tours/images/banner_merctur.jpg", "HEADER=Accept-Language:en-us,en;q=0.5", END_INLINE*/
    ); 

    ns_page_think_time(0);



}
