/*-----------------------------------------------------------------------------
    Name:RegCheckOut
    Recorded By: netstorm
    Date of recording: 03/12/2013 12:51:01
    Flow details:
    Modification History:
    03/22/2013 - Updated to work with CD5 R3 - Madhu
    03/23/2013 - Updated to work with products with options - Madhu  
    04/10/2013 - Tested with CD5 R15 - Anjali  
-----------------------------------------------------------------------------*/

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "ns_string.h"
#include "Util.c"
void RegCheckOut()
{

       #ifdef NS_DEBUG_ON
	printf("\n ++++++++++ Reg CheckOut ++++++++++++++\n");
      #endif
    
    Fill_ATG_SignInBody();
    ns_start_transaction("RegisterUserPage");
    ns_web_url ("RegisterUserPage",
		//"URL=http://www-sf.kohlsecommerce.com/checkout/shipping_billing_information.jsp?_DARGS=/checkout/gadgets/checkoutSignIn.jsp",
        //URL=http://www-sf.kohlsecommerce.com/checkout/shipping_billing_information.jsp?_DARGS=/checkout/gadgets/billingInformation.jsp.bill_ship_form",
         "URL=https://www-sf.kohlsecommerce.com/checkout/shipping_billing_information.jsp?_DARGS=/checkout/gadgets/checkoutSignIn.jsp",
         "METHOD=POST",
        "HEADER=Accept-Language:en-us,en;q=0.5",
        "HEADER=Content-Length:2238",
        "HEADER=Content-Type:application/x-www-form-urlencoded",
        "COOKIE=cookieSetting;JSESSIONID;mbox;s_sess;s_pers;cookieSetting;fsr.s;CartTotal;ItemDetails;",
        "REDIRECT=YES",
        "LOCATION=http://www-sf.kohlsecommerce.com/checkout/shipping_billing_information.jsp?_requestid=687",
        "PreSnapshot=webpage_1363072664807.png",
        "Snapshot=webpage_1363072670392.png",
        //"BODY=_dyncharset=UTF-8&_dynSessConf=-4884099526684570934&csiMail=loadtest%40gmail.com&_D%3AcsiMail=+&csipwd=123456&_D%3Acsipwd=+&%2Fatg%2Fuserprofiling%2FProfileFormHandler.loginSuccessURL=checkout_login_success_url&_D%3A%2Fatg%2Fuserprofiling%2FProfileFormHandler.loginSuccessURL=+&%2Fatg%2Fuserprofiling%2FProfileFormHandler.loginErrorURL=checkout_login_error_url&_D%3A%2Fatg%2Fuserprofiling%2FProfileFormHandler.loginErrorURL=+&pageName=billingShipping&%2Fatg%2Fuserprofiling%2FProfileFormHandler.loginFromCheckout=true&_D%3A%2Fatg%2Fuserprofiling%2FProfileFormHandler.loginFromCheckout=+&%2Fatg%2Fuserprofiling%2FProfileFormHandler.login=&_D%3A%2Fatg%2Fuserprofiling%2FProfileFormHandler.login=+&kohls_checkout_registered=&_DARGS=%2Fcheckout%2Fgadgets%2FcheckoutSignIn.jsp",
        //"BODY=_dyncharset=UTF-8&_dynSessConf={DynSessionConfSP}&csiMail={UserIdFP}&_D%3AcsiMail=+&csipwd={PasswordIdFP}&_D%3Acsipwd=+&%2Fatg%2Fuserprofiling%2FProfileFormHandler.loginSuccessURL=checkout_login_success_url&_D%3A%2Fatg%2Fuserprofiling%2FProfileFormHandler.loginSuccessURL=+&%2Fatg%2Fuserprofiling%2FProfileFormHandler.loginErrorURL=checkout_login_error_url&_D%3A%2Fatg%2Fuserprofiling%2FProfileFormHandler.loginErrorURL=+&pageName=billingShipping&%2Fatg%2Fuserprofiling%2FProfileFormHandler.loginFromCheckout=true&_D%3A%2Fatg%2Fuserprofiling%2FProfileFormHandler.loginFromCheckout=+&%2Fatg%2Fuserprofiling%2FProfileFormHandler.login=&_D%3A%2Fatg%2Fuserprofiling%2FProfileFormHandler.login=+&kohls_checkout_registered=&_DARGS=%2Fcheckout%2Fgadgets%2FcheckoutSignIn.jsp",
        //"BODY=_dyncharset=UTF-8&_dynSessConf={DynSessionConfSP}&firstName={UserIdFP}&_D%3AfirstName=+&lastName={LastNameFP}&_D%3AlastName=+&address1={AddressFP}&_D%3Aaddress1=+&address2=&_D%3Aaddress2=+&city={CityFP}&_D%3Acity=+&_D%3Astate_cd=+&state_cd={StateFP}&bmText=BILL_TO_ADDRESS%3C%3Epostal&bmRequired=BILL_TO_ADDRESS%3C%3Epostal&postal={PostalCodeFP}&_D%3Apostal=+&_D%3Abill_phone=+&bill_phone=%28309%29550-5357&ssi=true&_D%3Assi=+&_D%3Assi=+&selectedShippkey=&%2Fcom%2Fkohls%2Fcommerce%2Forder%2Fpurchase%2FKLSBillingShippingInfoFormHandler.defaultShipAddress=false&_D%3A%2Fcom%2Fkohls%2Fcommerce%2Forder%2Fpurchase%2FKLSBillingShippingInfoFormHandler.defaultShipAddress=+&jfirstName={FirstNameFP}&_D%3AjfirstName=+&jlastName={LastNameFP}&_D%3AjlastName=+&jaddress1={AddressFP}&_D%3Ajaddress1=+&jaddress2=&_D%3Ajaddress2=+&jcity={CityFP}&_D%3Ajcity=+&_D%3Ajstate_cd=+&jstate_cd=CA&jpostal={StateFP}&_D%3Ajpostal=+&ship_phone=%28309%29550-5357&_D%3Aship_phone=+&%2Fcom%2Fkohls%2Fcommerce%2Forder%2Fpurchase%2FKLSBillingShippingInfoFormHandler.shippingGroupId=&_D%3A%2Fcom%2Fkohls%2Fcommerce%2Forder%2Fpurchase%2FKLSBillingShippingInfoFormHandler.shippingGroupId=+&%2Fcom%2Fkohls%2Fcommerce%2Forder%2Fpurchase%2FKLSBillingShippingInfoFormHandler.shipMethodId=&_D%3A%2Fcom%2Fkohls%2Fcommerce%2Forder%2Fpurchase%2FKLSBillingShippingInfoFormHandler.shipMethodId=+&moveToPurchaseInfoSuccessURL=checkout_billing_success_url&_D%3AmoveToPurchaseInfoSuccessURL=+&moveToPurchaseInfoErrorURL=checkout_billing_error_url&_D%3AmoveToPurchaseInfoErrorURL=+&shippingMethodSelected=&%2Fcom%2Fkohls%2Fcommerce%2Forder%2Fpurchase%2FKLSBillingShippingInfoFormHandler.moveToPaymentInfo=true&_D%3A%2Fcom%2Fkohls%2Fcommerce%2Forder%2Fpurchase%2FKLSBillingShippingInfoFormHandler.moveToPaymentInfo=+&fh_ship_group_id=sg766355&_D%3Afh_ship_group_id=+&_D%3Afh_ship_method_id=+&fh_ship_method_id=STD&%2Fcom%2Fkohls%2Fcommerce%2Forder%2Fpurchase%2FKLSBillingShippingInfoFormHandler.updateShippingMethod=true&_D%3A%2Fcom%2Fkohls%2Fcommerce%2Forder%2Fpurchase%2FKLSBillingShippingInfoFormHandler.updateShippingMethod=+&_DARGS=%2Fcheckout%2Fgadgets%2FbillingInformation.jsp.bill_ship_form",
        //"BODY=_dyncharset=UTF-8&_dynSessConf={DynSessionConfSP}&firstName={FirstNameFP}&_D%3AfirstName=+&lastName={LastNameFP}&_D%3AlastName=+&address1={AddressFP}&_D%3Aaddress1=+&address2=&_D%3Aaddress2=+&city={CityFP}&_D%3Acity=+&_D%3Astate_cd=+&state_cd={StateFP}&bmText=BILL_TO_ADDRESS%3C%3Epostal&bmRequired=BILL_TO_ADDRESS%3C%3Epostal&postal={PostalCodeFP}&_D%3Apostal=+&_D%3Abill_phone=+&bill_phone=%28309%29550-5357&ssi=true&_D%3Assi=+&_D%3Assi=+&selectedShippkey=&addressNickName=Address_0&_D%3AaddressNickName=+&%2Fcom%2Fkohls%2Fcommerce%2Forder%2Fpurchase%2FKLSBillingShippingInfoFormHandler.defaultShipAddress=false&_D%3A%2Fcom%2Fkohls%2Fcommerce%2Forder%2Fpurchase%2FKLSBillingShippingInfoFormHandler.defaultShipAddress=+&jfirstName={FirstNameFP}&_D%3AjfirstName=+&jlastName={LastNameFP}&_D%3AjlastName=+&jaddress1={AddressFP}&_D%3Ajaddress1=+&jaddress2=&_D%3Ajaddress2=+&jcity={CityFP}&_D%3Ajcity=+&_D%3Ajstate_cd=+&jstate_cd={StateFP}&jpostal={PostalCodeFP}&_D%3Ajpostal=+&ship_phone=%28309%29550-5357&_D%3Aship_phone=+&%2Fcom%2Fkohls%2Fcommerce%2Forder%2Fpurchase%2FKLSBillingShippingInfoFormHandler.shippingGroupId=&_D%3A%2Fcom%2Fkohls%2Fcommerce%2Forder%2Fpurchase%2FKLSBillingShippingInfoFormHandler.shippingGroupId=+&%2Fcom%2Fkohls%2Fcommerce%2Forder%2Fpurchase%2FKLSBillingShippingInfoFormHandler.shipMethodId=&_D%3A%2Fcom%2Fkohls%2Fcommerce%2Forder%2Fpurchase%2FKLSBillingShippingInfoFormHandler.shipMethodId=+&moveToPurchaseInfoSuccessURL=checkout_billing_success_url&_D%3AmoveToPurchaseInfoSuccessURL=+&moveToPurchaseInfoErrorURL=checkout_billing_error_url&_D%3AmoveToPurchaseInfoErrorURL=+&shippingMethodSelected=&%2Fcom%2Fkohls%2Fcommerce%2Forder%2Fpurchase%2FKLSBillingShippingInfoFormHandler.moveToPaymentInfo=true&_D%3A%2Fcom%2Fkohls%2Fcommerce%2Forder%2Fpurchase%2FKLSBillingShippingInfoFormHandler.moveToPaymentInfo=+&fh_ship_group_id=sg766355&_D%3Afh_ship_group_id=+&_D%3Afh_ship_method_id=+&fh_ship_method_id=STD&fh_ship_group_id=sg766429&_D%3Afh_ship_group_id=+&_D%3Afh_ship_method_id=+&fh_ship_method_id=AKH&%2Fcom%2Fkohls%2Fcommerce%2Forder%2Fpurchase%2FKLSBillingShippingInfoFormHandler.updateShippingMethod=true&_D%3A%2Fcom%2Fkohls%2Fcommerce%2Forder%2Fpurchase%2FKLSBillingShippingInfoFormHandler.updateShippingMethod=+&_DARGS=%2Fcheckout%2Fgadgets%2FbillingInformation.jsp.bill_ship_form",
        //"BODY=_dyncharset=UTF-8&_dynSessConf={DynSessionConfSP}&firstName={FirstNameFP}&_D%3AfirstName=+&lastName={LastNameFP}&_D%3AlastName=+&address1={AddressFP}&_D%3Aaddress1=+&address2=&_D%3Aaddress2=+&city={CityFP}&_D%3Acity=+&_D%3Astate_cd=+&state_cd={StateFP}&bmText=BILL_TO_ADDRESS%3C%3Epostal&bmRequired=BILL_TO_ADDRESS%3C%3Epostal&postal={PostalCodeFP}&_D%3Apostal=+&_D%3AbillCountyName=+&billCountyName=00&_D%3Abill_phone=+&bill_phone=%28631%29298-3713&ssi=true&_D%3Assi=+&_D%3Assi=+&%2Fcom%2Fkohls%2Fcommerce%2Forder%2Fpurchase%2FKLSBillingShippingInfoFormHandler.defaultShipAddress=false&_D%3A%2Fcom%2Fkohls%2Fcommerce%2Forder%2Fpurchase%2FKLSBillingShippingInfoFormHandler.defaultShipAddress=+&jfirstName=&_D%3AjfirstName=+&jlastName=&_D%3AjlastName=+&jaddress1=&_D%3Ajaddress1=+&jaddress2=&_D%3Ajaddress2=+&jcity=&_D%3Ajcity=+&_D%3Ajstate_cd=+&jstate_cd=&jpostal=&_D%3Ajpostal=+&ship_phone=&_D%3Aship_phone=+&%2Fcom%2Fkohls%2Fcommerce%2Forder%2Fpurchase%2FKLSBillingShippingInfoFormHandler.shippingGroupId={ShipGroupIdSP}&_D%3A%2Fcom%2Fkohls%2Fcommerce%2Forder%2Fpurchase%2FKLSBillingShippingInfoFormHandler.shippingGroupId=+&%2Fcom%2Fkohls%2Fcommerce%2Forder%2Fpurchase%2FKLSBillingShippingInfoFormHandler.shipMethodId=STD&_D%3A%2Fcom%2Fkohls%2Fcommerce%2Forder%2Fpurchase%2FKLSBillingShippingInfoFormHandler.shipMethodId=+&moveToPurchaseInfoSuccessURL=checkout_billing_success_url&_D%3AmoveToPurchaseInfoSuccessURL=+&moveToPurchaseInfoErrorURL=checkout_billing_error_url&_D%3AmoveToPurchaseInfoErrorURL=+&shippingMethodSelected=&%2Fcom%2Fkohls%2Fcommerce%2Forder%2Fpurchase%2FKLSBillingShippingInfoFormHandler.moveToPaymentInfo=true&_D%3A%2Fcom%2Fkohls%2Fcommerce%2Forder%2Fpurchase%2FKLSBillingShippingInfoFormHandler.moveToPaymentInfo=+&fh_ship_group_id={ShipGroupIdSP}&_D%3Afh_ship_group_id=+&_D%3Afh_ship_method_id=+&fh_ship_method_id=STD&%2Fcom%2Fkohls%2Fcommerce%2Forder%2Fpurchase%2FKLSBillingShippingInfoFormHandler.updateShippingMethod=true&_D%3A%2Fcom%2Fkohls%2Fcommerce%2Forder%2Fpurchase%2FKLSBillingShippingInfoFormHandler.updateShippingMethod=+&_DARGS=%2Fcheckout%2Fgadgets%2FbillingInformation.jsp.bill_ship_form",
        //"BODY=_dyncharset=UTF-8&_dynSessConf={DynSessionConfSP}&csiMail={UserIdFP}&_D%3AcsiMail=+&csipwd={PasswordIdFP}&_D%3Acsipwd=+&%2Fatg%2Fuserprofiling%2FProfileFormHandler.loginSuccessURL=checkout_login_success_url&_D%3A%2Fatg%2Fuserprofiling%2FProfileFormHandler.loginSuccessURL=+&%2Fatg%2Fuserprofiling%2FProfileFormHandler.loginErrorURL=checkout_login_error_url&_D%3A%2Fatg%2Fuserprofiling%2FProfileFormHandler.loginErrorURL=+&pageName=billingShipping&%2Fatg%2Fuserprofiling%2FProfileFormHandler.loginFromCheckout=true&_D%3A%2Fatg%2Fuserprofiling%2FProfileFormHandler.loginFromCheckout=+&%2Fatg%2Fuserprofiling%2FProfileFormHandler.login=&_D%3A%2Fatg%2Fuserprofiling%2FProfileFormHandler.login=+&kohls_checkout_registered=&_DARGS=%2Fcheckout%2Fgadgets%2FcheckoutSignIn.jsp",
        //"BODY=_dyncharset=UTF-8&_dynSessConf={DynSessionConfSP}&csiMail={UserIdFP}&_D%3AcsiMail=+&csipwd={PasswordFP}&_D%3Acsipwd=+&%2Fatg%2Fuserprofiling%2FProfileFormHandler.loginSuccessURL=checkout_login_success_url&_D%3A%2Fatg%2Fuserprofiling%2FProfileFormHandler.loginSuccessURL=+&%2Fatg%2Fuserprofiling%2FProfileFormHandler.loginErrorURL=checkout_login_error_url&_D%3A%2Fatg%2Fuserprofiling%2FProfileFormHandler.loginErrorURL=+&pageName=billingShipping&%2Fatg%2Fuserprofiling%2FProfileFormHandler.loginFromCheckout=true&_D%3A%2Fatg%2Fuserprofiling%2FProfileFormHandler.loginFromCheckout=+&%2Fatg%2Fuserprofiling%2FProfileFormHandler.login=&_D%3A%2Fatg%2Fuserprofiling%2FProfileFormHandler.login=+&kohls_checkout_registered=&_DARGS=%2Fcheckout%2Fgadgets%2FcheckoutSignIn.jsp",
        "BODY={ATG_SignInDP}",
        INLINE_URLS,
            "URL=http://www-sf.kohlsecommerce.com/checkout/shipping_billing_information.jsp?_requestid=687", "HEADER=Accept-Language:en-us,en;q=0.5", "COOKIE=cookieSetting;JSESSIONID;mbox;s_sess;s_pers;cookieSetting;fsr.s;CartTotal;ItemDetails;VisitorUsaFullName;", END_INLINE,
            "URL=http://www-sf.kohlsecommerce.com/media/foresee/foresee-alive.js", "HEADER=Accept-Language:en-us,en;q=0.5", "COOKIE=JSESSIONID;mbox;s_sess;s_pers;cookieSetting;fsr.s;CartTotal;ItemDetails;VisitorUsaFullName;", END_INLINE,
            "URL=http://www-sf.kohlsecommerce.com/media/javascript/launch_window.js", "HEADER=Accept-Language:en-us,en;q=0.5", "COOKIE=JSESSIONID;mbox;s_sess;s_pers;cookieSetting;fsr.s;CartTotal;ItemDetails;VisitorUsaFullName;fsr.a;", END_INLINE,
            "URL=http://www-sf.kohlsecommerce.com/media/javascript/jquery-1.7.2.min.js", "HEADER=Accept-Language:en-us,en;q=0.5", "COOKIE=JSESSIONID;mbox;s_sess;s_pers;cookieSetting;fsr.s;CartTotal;ItemDetails;VisitorUsaFullName;fsr.a;", END_INLINE,
            "URL=http://www-sf.kohlsecommerce.com/media/javascript/jquery.fancybox-1.3.4.pack.js", "HEADER=Accept-Language:en-us,en;q=0.5", "COOKIE=JSESSIONID;mbox;s_sess;s_pers;cookieSetting;fsr.s;CartTotal;ItemDetails;VisitorUsaFullName;fsr.a;", END_INLINE,
            "URL=http://www-sf.kohlsecommerce.com/media/javascript/jquery.maskedinput.js", "HEADER=Accept-Language:en-us,en;q=0.5", "COOKIE=JSESSIONID;mbox;s_sess;s_pers;cookieSetting;fsr.s;CartTotal;ItemDetails;VisitorUsaFullName;fsr.a;", END_INLINE,
            "URL=http://www-sf.kohlsecommerce.com/media/javascript/global.js", "HEADER=Accept-Language:en-us,en;q=0.5", "COOKIE=JSESSIONID;mbox;s_sess;s_pers;cookieSetting;fsr.s;CartTotal;ItemDetails;VisitorUsaFullName;fsr.a;", END_INLINE,
            "URL=http://www-sf.kohlsecommerce.com/media/javascript/custom.js", "HEADER=Accept-Language:en-us,en;q=0.5", "COOKIE=JSESSIONID;mbox;s_sess;s_pers;cookieSetting;fsr.s;CartTotal;ItemDetails;VisitorUsaFullName;fsr.a;", END_INLINE,
            "URL=http://www-sf.kohlsecommerce.com/media/javascript/myaccount.js", "HEADER=Accept-Language:en-us,en;q=0.5", "COOKIE=JSESSIONID;mbox;s_sess;s_pers;cookieSetting;fsr.s;CartTotal;ItemDetails;VisitorUsaFullName;fsr.a;", END_INLINE,
            "URL=http://www-sf.kohlsecommerce.com/media/javascript/modal_validation.js", "HEADER=Accept-Language:en-us,en;q=0.5", "COOKIE=JSESSIONID;mbox;s_sess;s_pers;cookieSetting;fsr.s;CartTotal;ItemDetails;VisitorUsaFullName;fsr.a;", END_INLINE,
            "URL=http://www-sf.kohlsecommerce.com/media/javascript/shipping_bill_custom.js", "HEADER=Accept-Language:en-us,en;q=0.5", "COOKIE=JSESSIONID;mbox;s_sess;s_pers;cookieSetting;fsr.s;CartTotal;ItemDetails;VisitorUsaFullName;fsr.a;", END_INLINE,
            "URL=http://www-sf.kohlsecommerce.com/media/javascript/checkout_custom.js", "HEADER=Accept-Language:en-us,en;q=0.5", "COOKIE=JSESSIONID;mbox;s_sess;s_pers;cookieSetting;fsr.s;CartTotal;ItemDetails;VisitorUsaFullName;fsr.a;", END_INLINE,
            "URL=http://www-sf.kohlsecommerce.com/media/javascript/jcarousellite.min.js", "HEADER=Accept-Language:en-us,en;q=0.5", "COOKIE=JSESSIONID;mbox;s_sess;s_pers;cookieSetting;fsr.s;CartTotal;ItemDetails;VisitorUsaFullName;fsr.a;", END_INLINE,
            "URL=http://s.btstatic.com/tag.js", "HEADER=Accept-Language:en-us,en;q=0.5", END_INLINE,
            "URL=http://www-sf.kohlsecommerce.com/media/omniture/s_code.js", "HEADER=Accept-Language:en-us,en;q=0.5", "COOKIE=JSESSIONID;mbox;s_sess;s_pers;cookieSetting;fsr.s;CartTotal;ItemDetails;VisitorUsaFullName;fsr.a;", END_INLINE,
            "URL=http://ww9.kohls.com/b/ss/kohlscomdev/1/H.25/s0918680660505?AQB=1&ndh=1&t=12%2F2%2F2013%2012%3A47%3A49%202%20-330&ns=kohls&pageName=checkout%3Ashipping%20billing&g=http%3A%2F%2F10.210.211.1%3A17010%2Fcheckout%2Fshipping_billing_information.jsp%3F_requestid%3D687&r=http%3A%2F%2F10.210.211.1%3A17010%2Fcheckout%2Fshipping_billing_information.jsp%3F_requestid%3D685&events=scCheckout&products=%3B&c1=checkout&c2=checkout&c3=checkout&v3=external&c4=checkout&c7=checkout&v8=non-search&v9=checkout%3Ashipping%20billing&c17=logged%20in&v17=logged%20in&c18=D%3Dv18&v18=02%3A17%20am&c19=D%3Dv19&v19=tuesday&c20=D%3Dv20&v20=week%20day&c22=2013-03-12&v22=Kohl%27s&c50=8L7xR2JS83y41GhjwP0GgTGmD0LnBTyY4QQZKKGM3S7ZyWKHTBLl!379186398!1363072082339&s=1366x768&c=24&j=1.7&v=N&k=Y&bw=1366&bh=588&pid=checkout%3Ashipping%20billing&pidt=1&oid=%0A%09%20%20%20%20%09%09%09%09%09%20%0A%09%20%20%20%20%09%09%09%09%09%20%09%0A%0A%0A%0A%0A%0A%0A%0A%0A%0A%0A%0A%0A%0A%0A%0A%0A%0A%09%0A%09%0A%09%0A%0A%09%0A%09%0A%09%0A%09%09%0A%09%09Sign-in%0A%09%0A%0A%09%20%20%20%20%09%09%09%09%09%20%0A%20%20%20%20%09%09%09%09%09%20&oidt=3&ot=SUBMIT&AQE=1", "HEADER=Accept-Language:en-us,en;q=0.5", "COOKIE=s_vi;", END_INLINE,
            "URL=http://www-sf.kohlsecommerce.com/media/foresee/foresee-trigger.js", "HEADER=Accept-Language:en-us,en;q=0.5", "COOKIE=JSESSIONID;mbox;s_sess;s_pers;cookieSetting;fsr.s;CartTotal;ItemDetails;VisitorUsaFullName;fsr.a;", END_INLINE,
            "URL=http://www-sf.kohlsecommerce.com/media/foresee/foresee-surveydef.js", "HEADER=Accept-Language:en-us,en;q=0.5", "COOKIE=JSESSIONID;mbox;s_sess;s_pers;cookieSetting;fsr.s;CartTotal;ItemDetails;VisitorUsaFullName;fsr.a;", END_INLINE,
            "URL=http://www-sf.kohlsecommerce.com/media/images/button_continue-hover.gif", "HEADER=Accept-Language:en-us,en;q=0.5", "COOKIE=JSESSIONID;mbox;s_sess;s_pers;cookieSetting;fsr.s;CartTotal;ItemDetails;VisitorUsaFullName;", END_INLINE
    );
     
    ns_end_transaction("RegisterUserPage", NS_AUTO_STATUS);
    ns_page_think_time(8.891);
    
    
    ns_start_transaction("Reg_BillingInformationPage");
    ns_web_url ("Reg_BillingInformationPage",
        "URL=https://www-sf.kohlsecommerce.com/checkout/shipping_billing_information.jsp?_DARGS=/checkout/gadgets/billingInformation.jsp.bill_ship_form",
        "METHOD=POST",
        "HEADER=Accept-Language:en-us,en;q=0.5",
        "HEADER=Content-Length:1607",
        "HEADER=Content-Type:application/x-www-form-urlencoded",
        "COOKIE=cookieSetting;JSESSIONID;mbox;s_sess;s_pers;cookieSetting;fsr.s;CartTotal;ItemDetails;VisitorUsaFullName;",
        "REDIRECT=YES",
        "LOCATION=http://www-sf.kohlsecommerce.com/checkout/checkout_payment_information.jsp?_requestid=689",
        "PreSnapshot=webpage_1363072690203.png",
        "Snapshot=webpage_1363072694227.png",
        //"BODY=_dyncharset=UTF-8&_dynSessConf=-4884099526684570934&firstName=Smith&_D%3AfirstName=+&lastName=Wesson&_D%3AlastName=+&address1=221+Wilmar+Ave&_D%3Aaddress1=+&address2=&_D%3Aaddress2=+&city=Grand+Island&_D%3Acity=+&_D%3Astate_cd=+&state_cd=NE&bmText=BILL_TO_ADDRESS%3C%3Epostal&bmRequired=BILL_TO_ADDRESS%3C%3Epostal&postal=68803&_D%3Apostal=+&_D%3AbillCountyName=+&billCountyName=00&_D%3Abill_phone=+&bill_phone=%28308%29385-0166&ssi=true&_D%3Assi=+&_D%3Assi=+&selectedShippkey=&addressNickName=Address&_D%3AaddressNickName=+&%2Fcom%2Fkohls%2Fcommerce%2Forder%2Fpurchase%2FKLSBillingShippingInfoFormHandler.defaultShipAddress=true&_D%3A%2Fcom%2Fkohls%2Fcommerce%2Forder%2Fpurchase%2FKLSBillingShippingInfoFormHandler.defaultShipAddress=+&jfirstName=Smith&_D%3AjfirstName=+&jlastName=Wesson&_D%3AjlastName=+&jaddress1=221+Wilmar+Ave&_D%3Ajaddress1=+&jaddress2=&_D%3Ajaddress2=+&jcity=Grand+Island&_D%3Ajcity=+&_D%3Ajstate_cd=+&jstate_cd=NE&jpostal=68803&_D%3Ajpostal=+&_D%3AshipCountyName=+&shipCountyName=00&ship_phone=%28308%29385-0166&_D%3Aship_phone=+&shipping_Group_Id=sg120038&_D%3Ashipping_Group_Id=+&ship_method_id=STD&_D%3Aship_method_id=+&moveToPurchaseInfoSuccessURL=checkout_billing_success_url&_D%3AmoveToPurchaseInfoSuccessURL=+&moveToPurchaseInfoErrorURL=checkout_billing_error_url&_D%3AmoveToPurchaseInfoErrorURL=+&%2Fcom%2Fkohls%2Fcommerce%2Forder%2Fpurchase%2FKLSBillingShippingInfoFormHandler.moveToPaymentInfo=true&_D%3A%2Fcom%2Fkohls%2Fcommerce%2Forder%2Fpurchase%2FKLSBillingShippingInfoFormHandler.moveToPaymentInfo=+&_DARGS=%2Fcheckout%2Fgadgets%2FbillingInformation.jsp.bill_ship_form",
        //"BODY=_dyncharset=UTF-8&_dynSessConf={DynSessionConfSP}&firstName={RegFirstNameFP}&_D%3AfirstName=+&lastName={RegLastNameFP}&_D%3AlastName=+&address1={RegAddressFP}&_D%3Aaddress1=+&address2=&_D%3Aaddress2=+&city={RegCityFP}&_D%3Acity=+&_D%3Astate_cd=+&state_cd={RegStateFP}&bmText=BILL_TO_ADDRESS%3C%3Epostal&bmRequired=BILL_TO_ADDRESS%3C%3Epostal&postal={RegPostalCodeFP}&_D%3Apostal=+&_D%3AbillCountyName=+&billCountyName=00&_D%3Abill_phone=+&bill_phone={RegPhoneNumberFP}&ssi=true&_D%3Assi=+&_D%3Assi=+&selectedShippkey=&addressNickName=Address&_D%3AaddressNickName=+&%2Fcom%2Fkohls%2Fcommerce%2Forder%2Fpurchase%2FKLSBillingShippingInfoFormHandler.defaultShipAddress=true&_D%3A%2Fcom%2Fkohls%2Fcommerce%2Forder%2Fpurchase%2FKLSBillingShippingInfoFormHandler.defaultShipAddress=+&jfirstName={RegFirstNameFP}&_D%3AjfirstName=+&jlastName={RegLastNameFP}&_D%3AjlastName=+&jaddress1={RegAddressFP}&_D%3Ajaddress1=+&jaddress2=&_D%3Ajaddress2=+&jcity=RegCityFP&_D%3Ajcity=+&_D%3Ajstate_cd=+&jstate_cd={RegStateFP}&jpostal={RegPostalCodeFP}&_D%3Ajpostal=+&_D%3AshipCountyName=+&shipCountyName=00&ship_phone={RegPhoneNumberFP}&_D%3Aship_phone=+&shipping_Group_Id=sg120038&_D%3Ashipping_Group_Id=+&ship_method_id=STD&_D%3Aship_method_id=+&moveToPurchaseInfoSuccessURL=checkout_billing_success_url&_D%3AmoveToPurchaseInfoSuccessURL=+&moveToPurchaseInfoErrorURL=checkout_billing_error_url&_D%3AmoveToPurchaseInfoErrorURL=+&%2Fcom%2Fkohls%2Fcommerce%2Forder%2Fpurchase%2FKLSBillingShippingInfoFormHandler.moveToPaymentInfo=true&_D%3A%2Fcom%2Fkohls%2Fcommerce%2Forder%2Fpurchase%2FKLSBillingShippingInfoFormHandler.moveToPaymentInfo=+&_DARGS=%2Fcheckout%2Fgadgets%2FbillingInformation.jsp.bill_ship_form",
        //"BODY=_dyncharset=UTF-8&_dynSessConf={DynSessionConfSP}&firstName={RegFirstNameFP}&_D%3AfirstName=+&lastName={RegLastNameFP}&_D%3AlastName=+&address1={RegAddressFP}&_D%3Aaddress1=+&address2=&_D%3Aaddress2=+&city={RegCityFP}&_D%3Acity=+&_D%3Astate_cd=+&state_cd={RegStateFP}&bmText=BILL_TO_ADDRESS%3C%3Epostal&bmRequired=BILL_TO_ADDRESS%3C%3Epostal&postal={RegPostalCodeFP}&_D%3Apostal=+&_D%3AbillCountyName=+&billCountyName=00&_D%3Abill_phone=+&bill_phone={RegPhoneNumberFP}&ssi=true&_D%3Assi=+&_D%3Assi=+&%2Fcom%2Fkohls%2Fcommerce%2Forder%2Fpurchase%2FKLSBillingShippingInfoFormHandler.defaultShipAddress=false&_D%3A%2Fcom%2Fkohls%2Fcommerce%2Forder%2Fpurchase%2FKLSBillingShippingInfoFormHandler.defaultShipAddress=+&jfirstName=&_D%3AjfirstName=+&jlastName=&_D%3AjlastName=+&jaddress1=&_D%3Ajaddress1=+&jaddress2=&_D%3Ajaddress2=+&jcity=&_D%3Ajcity=+&_D%3Ajstate_cd=+&jstate_cd=&jpostal=&_D%3Ajpostal=+&ship_phone=&_D%3Aship_phone=+&%2Fcom%2Fkohls%2Fcommerce%2Forder%2Fpurchase%2FKLSBillingShippingInfoFormHandler.shippingGroupId={ShipGroupIdSP}&_D%3A%2Fcom%2Fkohls%2Fcommerce%2Forder%2Fpurchase%2FKLSBillingShippingInfoFormHandler.shippingGroupId=+&%2Fcom%2Fkohls%2Fcommerce%2Forder%2Fpurchase%2FKLSBillingShippingInfoFormHandler.shipMethodId=STD&_D%3A%2Fcom%2Fkohls%2Fcommerce%2Forder%2Fpurchase%2FKLSBillingShippingInfoFormHandler.shipMethodId=+&moveToPurchaseInfoSuccessURL=checkout_billing_success_url&_D%3AmoveToPurchaseInfoSuccessURL=+&moveToPurchaseInfoErrorURL=checkout_billing_error_url&_D%3AmoveToPurchaseInfoErrorURL=+&shippingMethodSelected=&%2Fcom%2Fkohls%2Fcommerce%2Forder%2Fpurchase%2FKLSBillingShippingInfoFormHandler.moveToPaymentInfo=true&_D%3A%2Fcom%2Fkohls%2Fcommerce%2Forder%2Fpurchase%2FKLSBillingShippingInfoFormHandler.moveToPaymentInfo=+&fh_ship_group_id={ShipGroupIdSP}&_D%3Afh_ship_group_id=+&_D%3Afh_ship_method_id=+&fh_ship_method_id=STD&%2Fcom%2Fkohls%2Fcommerce%2Forder%2Fpurchase%2FKLSBillingShippingInfoFormHandler.updateShippingMethod=true&_D%3A%2Fcom%2Fkohls%2Fcommerce%2Forder%2Fpurchase%2FKLSBillingShippingInfoFormHandler.updateShippingMethod=+&_DARGS=%2Fcheckout%2Fgadgets%2FbillingInformation.jsp.bill_ship_form",
        //"BODY=_dyncharset=UTF-8&_dynSessConf={DynSessionConfSP}&firstName={RegFirstNameFP}&_D%3AfirstName=+&lastName={RegLastNameFP}&_D%3AlastName=+&address1={RegAddressFP}&_D%3Aaddress1=+&address2=&_D%3Aaddress2=+&city={RegCityFP}&_D%3Acity=+&_D%3Astate_cd=+&state_cd={RegStateFP}&bmText=BILL_TO_ADDRESS%3C%3Epostal&bmRequired=BILL_TO_ADDRESS%3C%3Epostal&postal={RegPostalCodeFP}&_D%3Apostal=+&_D%3AbillCountyName=+&billCountyName=00&_D%3Abill_phone=+&bill_phone={RegPhoneNumberFP}&indShipIsBillTo=true&_D%3AindShipIsBillTo=+&selectedShippkey=&addressNickName=Address&_D%3AaddressNickName=+&%2Fcom%2Fkohls%2Fcommerce%2Forder%2Fpurchase%2FKLSBillingShippingInfoFormHandler.defaultShipAddress=false&_D%3A%2Fcom%2Fkohls%2Fcommerce%2Forder%2Fpurchase%2FKLSBillingShippingInfoFormHandler.defaultShipAddress=+&jfirstName={RegFirstNameFP}&_D%3AjfirstName=+&jlastName={RegLastNameFP}&_D%3AjlastName=+&jaddress1={RegAddressFP}&_D%3Ajaddress1=+&jaddress2=&_D%3Ajaddress2=+&jcity={RegCityFP}&_D%3Ajcity=+&_D%3Ajstate_cd=+&jstate_cd={RegStateFP}&jpostal={RegPostalCodeFP}&_D%3Ajpostal=+&_D%3AshipCountyName=+&shipCountyName=00&ship_phone={RegPhoneNumberFP}&_D%3Aship_phone=+&%2Fcom%2Fkohls%2Fcommerce%2Forder%2Fpurchase%2FKLSBillingShippingInfoFormHandler.shippingGroupId=&_D%3A%2Fcom%2Fkohls%2Fcommerce%2Forder%2Fpurchase%2FKLSBillingShippingInfoFormHandler.shippingGroupId=+&%2Fcom%2Fkohls%2Fcommerce%2Forder%2Fpurchase%2FKLSBillingShippingInfoFormHandler.shipMethodId=&_D%3A%2Fcom%2Fkohls%2Fcommerce%2Forder%2Fpurchase%2FKLSBillingShippingInfoFormHandler.shipMethodId=+&moveToPurchaseInfoSuccessURL=checkout_billing_success_url&_D%3AmoveToPurchaseInfoSuccessURL=+&moveToPurchaseInfoErrorURL=checkout_billing_error_url&_D%3AmoveToPurchaseInfoErrorURL=+&shippingMethodSelected=&%2Fcom%2Fkohls%2Fcommerce%2Forder%2Fpurchase%2FKLSBillingShippingInfoFormHandler.moveToPaymentInfo=true&_D%3A%2Fcom%2Fkohls%2Fcommerce%2Forder%2Fpurchase%2FKLSBillingShippingInfoFormHandler.moveToPaymentInfo=+&fh_ship_group_id={ShipGroupIdSP}&_D%3Afh_ship_group_id=+&bmRadio=validShippingMethodList&bmRequired=validShippingMethodList&validShippingMethodList=STD&_D%3AvalidShippingMethodList=+&bmRadio=validShippingMethodList&bmRequired=validShippingMethodList&_D%3AvalidShippingMethodList=+&fh_ship_method_id=&_DARGS=%2Fcheckout%2Fgadgets%2FbillingInformation.jsp.bill_ship_form",
       //"BODY=_dyncharset=UTF-8&_dynSessConf={DynSessionConfSP}&billSameAsShip=&firstName={RegFirstNameFP}&_D%3AfirstName=+&lastName={RegLastNameFP}&_D%3AlastName=+&address1={RegAddressFP}&_D%3Aaddress1=+&address2=&_D%3Aaddress2=+&city={RegCityFP}&_D%3Acity=+&_D%3Astate_cd=+&state_cd={RegStateFP}&bmText=BILL_TO_ADDRESS%3C%3Epostal&bmRequired=BILL_TO_ADDRESS%3C%3Epostal&postal={RegPostalCodeFP}&_D%3Apostal=+&_D%3AbillCountyName=+&billCountyName=00&_D%3Abill_phone=+&bill_phone={RegPhoneNumberFP}&indShipIsBillTo=true&_D%3AindShipIsBillTo=+&selectedShippkey=&addressNickName=Address_0&_D%3AaddressNickName=+&%2Fcom%2Fkohls%2Fcommerce%2Forder%2Fpurchase%2FKLSBillingShippingInfoFormHandler.defaultShipAddress=true&_D%3A%2Fcom%2Fkohls%2Fcommerce%2Forder%2Fpurchase%2FKLSBillingShippingInfoFormHandler.defaultShipAddress=+&jfirstName={RegFirstNameFP}&_D%3AjfirstName=+&jlastName={RegLastNameFP}&_D%3AjlastName=+&jaddress1={RegAddressFP}&_D%3Ajaddress1=+&jaddress2=&_D%3Ajaddress2=+&jcity={RegCityFP}&_D%3Ajcity=+&_D%3Ajstate_cd=+&jstate_cd={RegStateFP}&jpostal={RegPostalCodeFP}&_D%3Ajpostal=+&_D%3AshipCountyName=+&shipCountyName=00&ship_phone={RegPhoneNumberFP}&_D%3Aship_phone=+&%2Fcom%2Fkohls%2Fcommerce%2Forder%2Fpurchase%2FKLSBillingShippingInfoFormHandler.shippingGroupId=&_D%3A%2Fcom%2Fkohls%2Fcommerce%2Forder%2Fpurchase%2FKLSBillingShippingInfoFormHandler.shippingGroupId=+&%2Fcom%2Fkohls%2Fcommerce%2Forder%2Fpurchase%2FKLSBillingShippingInfoFormHandler.shipMethodId=&_D%3A%2Fcom%2Fkohls%2Fcommerce%2Forder%2Fpurchase%2FKLSBillingShippingInfoFormHandler.shipMethodId=+&moveToPurchaseInfoSuccessURL=checkout_billing_success_url&_D%3AmoveToPurchaseInfoSuccessURL=+&billSameASshipp=true&_D%3AbillSameASshipp=+&moveToPurchaseInfoErrorURL=checkout_billing_error_url&_D%3AmoveToPurchaseInfoErrorURL=+&shippingMethodSelected=&%2Fcom%2Fkohls%2Fcommerce%2Forder%2Fpurchase%2FKLSBillingShippingInfoFormHandler.moveToPaymentInfo=true&_D%3A%2Fcom%2Fkohls%2Fcommerce%2Forder%2Fpurchase%2FKLSBillingShippingInfoFormHandler.moveToPaymentInfo=+&fh_ship_group_id={ShipGroupIdSP}&_D%3Afh_ship_group_id=+&bmRadio=validShippingMethodList&bmRequired=validShippingMethodList&_D%3AvalidShippingMethodList=+&bmRadio=validShippingMethodList&bmRequired=validShippingMethodList&_D%3AvalidShippingMethodList=+&bmRadio=validShippingMethodList&bmRequired=validShippingMethodList&validShippingMethodList=STD&_D%3AvalidShippingMethodList=+&fh_ship_method_id=&_DARGS=%2Fcheckout%2Fgadgets%2FbillingInformation.jsp.bill_ship_form",
        "BODY=_dyncharset=UTF-8&_dynSessConf={DynSessionConfSP}&billSameAsShip=&firstName={RegFirstNameFP}&_D%3AfirstName=+&lastName={RegLastNameFP}&_D%3AlastName=+&address1={RegAddressFP}&_D%3Aaddress1=+&address2=&_D%3Aaddress2=+&city={RegCityFP}&_D%3Acity=+&_D%3Astate_cd=+&state_cd={RegStateFP}&bmText=BILL_TO_ADDRESS%3C%3Epostal&bmRequired=BILL_TO_ADDRESS%3C%3Epostal&postal={RegPostalCodeFP}&_D%3Apostal=+&_D%3AbillCountyName=+&billCountyName=00&_D%3Abill_phone=+&bill_phone={RegPhoneNumberFP}&indShipIsBillTo=true&_D%3AindShipIsBillTo=+&selectedShippkey=&addressNickName=Address_0&_D%3AaddressNickName=+&%2Fcom%2Fkohls%2Fcommerce%2Forder%2Fpurchase%2FKLSBillingShippingInfoFormHandler.defaultShipAddress=true&_D%3A%2Fcom%2Fkohls%2Fcommerce%2Forder%2Fpurchase%2FKLSBillingShippingInfoFormHandler.defaultShipAddress=+&jfirstName={RegFirstNameFP}&_D%3AjfirstName=+&jlastName={RegLastNameFP}&_D%3AjlastName=+&jaddress1={RegAddressFP}&_D%3Ajaddress1=+&jaddress2=&_D%3Ajaddress2=+&jcity={RegCityFP}&_D%3Ajcity=+&_D%3Ajstate_cd=+&jstate_cd={RegStateFP}&jpostal={RegPostalCodeFP}&_D%3Ajpostal=+&_D%3AshipCountyName=+&shipCountyName=00&ship_phone={RegPhoneNumberFP}&_D%3Aship_phone=+&%2Fcom%2Fkohls%2Fcommerce%2Forder%2Fpurchase%2FKLSBillingShippingInfoFormHandler.shippingGroupId=&_D%3A%2Fcom%2Fkohls%2Fcommerce%2Forder%2Fpurchase%2FKLSBillingShippingInfoFormHandler.shippingGroupId=+&%2Fcom%2Fkohls%2Fcommerce%2Forder%2Fpurchase%2FKLSBillingShippingInfoFormHandler.shipMethodId=&_D%3A%2Fcom%2Fkohls%2Fcommerce%2Forder%2Fpurchase%2FKLSBillingShippingInfoFormHandler.shipMethodId=+&moveToPurchaseInfoSuccessURL=checkout_billing_success_url&_D%3AmoveToPurchaseInfoSuccessURL=+&billSameASshipp=true&_D%3AbillSameASshipp=+&moveToPurchaseInfoErrorURL=checkout_billing_error_url&_D%3AmoveToPurchaseInfoErrorURL=+&shippingMethodSelected=&%2Fcom%2Fkohls%2Fcommerce%2Forder%2Fpurchase%2FKLSBillingShippingInfoFormHandler.moveToPaymentInfo=true&_D%3A%2Fcom%2Fkohls%2Fcommerce%2Forder%2Fpurchase%2FKLSBillingShippingInfoFormHandler.moveToPaymentInfo=+&fh_ship_group_id={ShipGroupIdSP}&_D%3Afh_ship_group_id=+&bmRadio=validShippingMethodList&bmRequired=validShippingMethodList&_D%3AvalidShippingMethodList=+&bmRadio=validShippingMethodList&bmRequired=validShippingMethodList&_D%3AvalidShippingMethodList=+&bmRadio=validShippingMethodList&bmRequired=validShippingMethodList&validShippingMethodList=STD&_D%3AvalidShippingMethodList=+&fh_ship_method_id=&_DARGS=%2Fcheckout%2Fgadgets%2FbillingInformation.jsp.bill_ship_form",
        INLINE_URLS,
            "URL=http://www-sf.kohlsecommerce.com/checkout/checkout_payment_information.jsp?_requestid=689", "HEADER=Accept-Language:en-us,en;q=0.5", "COOKIE=cookieSetting;JSESSIONID;mbox;s_sess;s_pers;cookieSetting;fsr.s;CartTotal;ItemDetails;VisitorUsaFullName;", END_INLINE,
            "URL=http://www-sf.kohlsecommerce.com/media/foresee/foresee-alive.js", "HEADER=Accept-Language:en-us,en;q=0.5", "COOKIE=JSESSIONID;mbox;s_sess;s_pers;cookieSetting;fsr.s;CartTotal;ItemDetails;VisitorUsaFullName;", END_INLINE,
            "URL=http://www-sf.kohlsecommerce.com/media/javascript/launch_window.js", "HEADER=Accept-Language:en-us,en;q=0.5", "COOKIE=JSESSIONID;mbox;s_sess;s_pers;cookieSetting;fsr.s;CartTotal;ItemDetails;VisitorUsaFullName;fsr.a;", END_INLINE,
            "URL=http://www-sf.kohlsecommerce.com/media/javascript/jquery-1.7.2.min.js", "HEADER=Accept-Language:en-us,en;q=0.5", "COOKIE=JSESSIONID;mbox;s_sess;s_pers;cookieSetting;fsr.s;CartTotal;ItemDetails;VisitorUsaFullName;fsr.a;", END_INLINE,
            "URL=http://www-sf.kohlsecommerce.com/media/javascript/jquery.fancybox-1.3.4.pack.js", "HEADER=Accept-Language:en-us,en;q=0.5", "COOKIE=JSESSIONID;mbox;s_sess;s_pers;cookieSetting;fsr.s;CartTotal;ItemDetails;VisitorUsaFullName;fsr.a;", END_INLINE,
            "URL=http://www-sf.kohlsecommerce.com/media/javascript/global.js", "HEADER=Accept-Language:en-us,en;q=0.5", "COOKIE=JSESSIONID;mbox;s_sess;s_pers;cookieSetting;fsr.s;CartTotal;ItemDetails;VisitorUsaFullName;fsr.a;", END_INLINE,
            "URL=http://www-sf.kohlsecommerce.com/media/javascript/custom.js", "HEADER=Accept-Language:en-us,en;q=0.5", "COOKIE=JSESSIONID;mbox;s_sess;s_pers;cookieSetting;fsr.s;CartTotal;ItemDetails;VisitorUsaFullName;fsr.a;", END_INLINE,
            "URL=http://www-sf.kohlsecommerce.com/media/javascript/myaccount.js", "HEADER=Accept-Language:en-us,en;q=0.5", "COOKIE=JSESSIONID;mbox;s_sess;s_pers;cookieSetting;fsr.s;CartTotal;ItemDetails;VisitorUsaFullName;fsr.a;", END_INLINE,
            "URL=http://www-sf.kohlsecommerce.com/media/javascript/modal_validation.js", "HEADER=Accept-Language:en-us,en;q=0.5", "COOKIE=JSESSIONID;mbox;s_sess;s_pers;cookieSetting;fsr.s;CartTotal;ItemDetails;VisitorUsaFullName;fsr.a;", END_INLINE,
            "URL=http://www-sf.kohlsecommerce.com/media/javascript/checkout_custom.js", "HEADER=Accept-Language:en-us,en;q=0.5", "COOKIE=JSESSIONID;mbox;s_sess;s_pers;cookieSetting;fsr.s;CartTotal;ItemDetails;VisitorUsaFullName;fsr.a;", END_INLINE,
            "URL=http://www-sf.kohlsecommerce.com/media/javascript/jcarousellite.min.js", "HEADER=Accept-Language:en-us,en;q=0.5", "COOKIE=JSESSIONID;mbox;s_sess;s_pers;cookieSetting;fsr.s;CartTotal;ItemDetails;VisitorUsaFullName;fsr.a;", END_INLINE,
            "URL=http://www-sf.kohlsecommerce.com/media/images/Kohls_VisaCard.gif", "HEADER=Accept-Language:en-us,en;q=0.5", "COOKIE=JSESSIONID;mbox;s_sess;s_pers;cookieSetting;fsr.s;CartTotal;ItemDetails;VisitorUsaFullName;fsr.a;", END_INLINE,
            "URL=http://www-sf.kohlsecommerce.com/media/css/print_summary.css", END_INLINE,
            "URL=http://www-sf.kohlsecommerce.com/media/images/add_payment_method.gif", "HEADER=Accept-Language:en-us,en;q=0.5", "COOKIE=JSESSIONID;mbox;s_sess;s_pers;cookieSetting;fsr.s;CartTotal;ItemDetails;VisitorUsaFullName;fsr.a;", END_INLINE,
            "URL=http://www-sf.kohlsecommerce.com/media/images/button_apply.gif", "HEADER=Accept-Language:en-us,en;q=0.5", "COOKIE=JSESSIONID;mbox;s_sess;s_pers;cookieSetting;fsr.s;CartTotal;ItemDetails;VisitorUsaFullName;fsr.a;", END_INLINE,
            "URL=http://www-sf.kohlsecommerce.com/media/images/kohls_cash_icon.gif", "HEADER=Accept-Language:en-us,en;q=0.5", "COOKIE=JSESSIONID;mbox;s_sess;s_pers;cookieSetting;fsr.s;CartTotal;ItemDetails;VisitorUsaFullName;fsr.a;", END_INLINE,
            "URL=http://www-sf.kohlsecommerce.com/media/images/payment-information-heading.png", "HEADER=Accept-Language:en-us,en;q=0.5", "COOKIE=JSESSIONID;mbox;s_sess;s_pers;cookieSetting;fsr.s;CartTotal;ItemDetails;VisitorUsaFullName;fsr.a;", END_INLINE,
            "URL=http://www-sf.kohlsecommerce.com/media/images/indicator-complete.gif", "HEADER=Accept-Language:en-us,en;q=0.5", "COOKIE=JSESSIONID;mbox;s_sess;s_pers;cookieSetting;fsr.s;CartTotal;ItemDetails;VisitorUsaFullName;fsr.a;", END_INLINE,
            "URL=http://www-sf.kohlsecommerce.com/media/images/credit-card-heading.png", "HEADER=Accept-Language:en-us,en;q=0.5", "COOKIE=JSESSIONID;mbox;s_sess;s_pers;cookieSetting;fsr.s;CartTotal;ItemDetails;VisitorUsaFullName;fsr.a;", END_INLINE,
            "URL=http://www-sf.kohlsecommerce.com/media/images/gift-promo-heading.gif", "HEADER=Accept-Language:en-us,en;q=0.5", "COOKIE=JSESSIONID;mbox;s_sess;s_pers;cookieSetting;fsr.s;CartTotal;ItemDetails;VisitorUsaFullName;fsr.a;", END_INLINE,
            "URL=http://s.btstatic.com/tag.js", "HEADER=Accept-Language:en-us,en;q=0.5", END_INLINE,
            "URL=http://www-sf.kohlsecommerce.com/media/omniture/s_code.js", "HEADER=Accept-Language:en-us,en;q=0.5", "COOKIE=JSESSIONID;mbox;s_sess;s_pers;cookieSetting;fsr.s;CartTotal;ItemDetails;VisitorUsaFullName;fsr.a;", END_INLINE,
            "URL=http://ww9.kohls.com/b/ss/kohlscomdev/1/H.25/s0510476477726?AQB=1&ndh=1&t=12%2F2%2F2013%2012%3A48%3A13%202%20-330&ns=kohls&pageName=order%20confirm&g=http%3A%2F%2F10.210.211.1%3A17010%2Fcheckout%2Fcheckout_payment_information.jsp%3F_requestid%3D689&r=http%3A%2F%2F10.210.211.1%3A17010%2Fcheckout%2Fshipping_billing_information.jsp%3F_requestid%3D687&events=purchase%2Cevent9%2Cevent7%2Cevent6%2Cevent10%2Cevent4%2Cevent28&products=%3Bproductmerch2&c1=confirmation&c2=confirmation&c3=confirmation&v3=external&c4=confirmation&c7=confirmation&v8=non-search&v9=checkout%3Ashipping%20billing&c17=logged%20in&v17=logged%20in&c18=D%3Dv18&v18=02%3A18%20am&c19=D%3Dv19&v19=tuesday&c20=D%3Dv20&v20=week%20day&c22=2013-03-12&v22=Kohl%27s&c50=8L7xR2JS83y41GhjwP0GgTGmD0LnBTyY4QQZKKGM3S7ZyWKHTBLl!379186398!1363072082339&s=1366x768&c=24&j=1.7&v=N&k=Y&bw=1366&bh=588&AQE=1", "HEADER=Accept-Language:en-us,en;q=0.5", "COOKIE=s_vi;", END_INLINE,
            "URL=http://www-sf.kohlsecommerce.com/media/foresee/foresee-trigger.js", "HEADER=Accept-Language:en-us,en;q=0.5", "COOKIE=JSESSIONID;mbox;s_sess;s_pers;cookieSetting;fsr.s;CartTotal;ItemDetails;VisitorUsaFullName;fsr.a;", END_INLINE,
            "URL=http://www-sf.kohlsecommerce.com/media/foresee/foresee-surveydef.js", "HEADER=Accept-Language:en-us,en;q=0.5", "COOKIE=JSESSIONID;mbox;s_sess;s_pers;cookieSetting;fsr.s;CartTotal;ItemDetails;VisitorUsaFullName;fsr.a;", END_INLINE
    );
    ns_end_transaction("Reg_BillingInformationPage", NS_AUTO_STATUS);
    ns_page_think_time(126.862);


    Fill_Reg_PaymentDetailBody();
    ns_start_transaction("Reg_PaymentInformationPage");
    ns_web_url ("Reg_PaymentInformationPage",
        "URL=https://www-sf.kohlsecommerce.com/checkout/checkout_payment_information.jsp?_DARGS=/checkout/checkout_payment_information.jsp.payment_form_1#",
        "METHOD=POST",
        "HEADER=Accept-Language:en-us,en;q=0.5",
        "HEADER=Content-Length:1897",
        "HEADER=Content-Type:application/x-www-form-urlencoded",
        "COOKIE=cookieSetting;JSESSIONID;mbox;s_sess;s_pers;cookieSetting;fsr.s;CartTotal;ItemDetails;",
        "REDIRECT=YES",
        "LOCATION=http://www-sf.kohlsecommerce.com/checkout/order_review.jsp?_requestid=6233",
        "PreSnapshot=webpage_1362787686328.png",
        "Snapshot=webpage_1362787695813.png",
        //"BODY=_dyncharset=UTF-8&_dynSessConf=-2512362807654460524&_D%3Acardtype=+&cardtype=visa&cardname=Smith&_D%3Acardname=+&cardnum=4002410100000034&_D%3Acardnum=+&_D%3Acardexp_month=+&cardexp_month=8&_D%3Acardexp_year=+&cardexp_year=2015&cardcvv=124&_D%3Acardcvv=+&%2Fatg%2Fcommerce%2Forder%2Fpurchase%2FKLSPaymentInfoFormHandler.newCard=true&_D%3A%2Fatg%2Fcommerce%2Forder%2Fpurchase%2FKLSPaymentInfoFormHandler.newCard=+&%2Fatg%2Fcommerce%2Forder%2Fpurchase%2FKLSPaymentInfoFormHandler.saveCreditCard=false&_D%3A%2Fatg%2Fcommerce%2Forder%2Fpurchase%2FKLSPaymentInfoFormHandler.saveCreditCard=+&GIFT_CARD%3C%3EcardNumber=&_D%3AGIFT_CARD%3C%3EcardNumber=+&GIFT_CARD%3C%3EcardPin=Pin+%23&_D%3AGIFT_CARD%3C%3EcardPin=+&_D%3Aadd_gift_card=+&kohlsCashCouponNumber=&_D%3AkohlsCashCouponNumber=+&kohlsCashPin=Pin+%23&_D%3AkohlsCashPin=+&_D%3Aadd_kohls_cash=+&GENERIC%3C%3EpromotionCode=&_D%3AGENERIC%3C%3EpromotionCode=+&_D%3Aadd_promo_code=+&%2Fatg%2Fcommerce%2Forder%2Fpurchase%2FKLSPaymentInfoFormHandler.paymentInfoSuccessURL=create_payment_info_success_url&_D%3A%2Fatg%2Fcommerce%2Forder%2Fpurchase%2FKLSPaymentInfoFormHandler.paymentInfoSuccessURL=+&%2Fatg%2Fcommerce%2Forder%2Fpurchase%2FKLSPaymentInfoFormHandler.paymentInfoErrorURL=create_payment_info_error_url&_D%3A%2Fatg%2Fcommerce%2Forder%2Fpurchase%2FKLSPaymentInfoFormHandler.paymentInfoErrorURL=+&%2Fatg%2Fcommerce%2Forder%2Fpurchase%2FKLSPaymentInfoFormHandler.moveToConfirmSuccessURL=%2Fcheckout%2Forder_review.jsp&_D%3A%2Fatg%2Fcommerce%2Forder%2Fpurchase%2FKLSPaymentInfoFormHandler.moveToConfirmSuccessURL=+&%2Fatg%2Fcommerce%2Forder%2Fpurchase%2FKLSPaymentInfoFormHandler.moveToConfirmErrorURL=%2Fcheckout%2Fcheckout_payment_information.jsp&_D%3A%2Fatg%2Fcommerce%2Forder%2Fpurchase%2FKLSPaymentInfoFormHandler.moveToConfirmErrorURL=+&submit.x=34&submit.y=19&_D%3Asubmit=+&_DARGS=%2Fcheckout%2Fcheckout_payment_information.jsp.payment_form_1",
        //"BODY=_dyncharset=UTF-8&_dynSessConf={DynSessionConfSP}&_D%3Acardtype=+&cardtype={CardTypeFP}&cardname={CardNameIdFP}&_D%3Acardname=+&cardnum={CardNumFP}&_D%3Acardnum=+&_D%3Acardexp_month=+&cardexp_month=8&_D%3Acardexp_year=+&cardexp_year={CardExpYearFP}&cardcvv={CardCVVFP}&_D%3Acardcvv=+&%2Fatg%2Fcommerce%2Forder%2Fpurchase%2FKLSPaymentInfoFormHandler.newCard=true&_D%3A%2Fatg%2Fcommerce%2Forder%2Fpurchase%2FKLSPaymentInfoFormHandler.newCard=+&%2Fatg%2Fcommerce%2Forder%2Fpurchase%2FKLSPaymentInfoFormHandler.saveCreditCard=false&_D%3A%2Fatg%2Fcommerce%2Forder%2Fpurchase%2FKLSPaymentInfoFormHandler.saveCreditCard=+&GIFT_CARD%3C%3EcardNumber=&_D%3AGIFT_CARD%3C%3EcardNumber=+&GIFT_CARD%3C%3EcardPin=Pin+%23&_D%3AGIFT_CARD%3C%3EcardPin=+&_D%3Aadd_gift_card=+&kohlsCashCouponNumber=&_D%3AkohlsCashCouponNumber=+&kohlsCashPin=Pin+%23&_D%3AkohlsCashPin=+&_D%3Aadd_kohls_cash=+&GENERIC%3C%3EpromotionCode=&_D%3AGENERIC%3C%3EpromotionCode=+&_D%3Aadd_promo_code=+&%2Fatg%2Fcommerce%2Forder%2Fpurchase%2FKLSPaymentInfoFormHandler.paymentInfoSuccessURL=create_payment_info_success_url&_D%3A%2Fatg%2Fcommerce%2Forder%2Fpurchase%2FKLSPaymentInfoFormHandler.paymentInfoSuccessURL=+&%2Fatg%2Fcommerce%2Forder%2Fpurchase%2FKLSPaymentInfoFormHandler.paymentInfoErrorURL=create_payment_info_error_url&_D%3A%2Fatg%2Fcommerce%2Forder%2Fpurchase%2FKLSPaymentInfoFormHandler.paymentInfoErrorURL=+&%2Fatg%2Fcommerce%2Forder%2Fpurchase%2FKLSPaymentInfoFormHandler.moveToConfirmSuccessURL=%2Fcheckout%2Forder_review.jsp&_D%3A%2Fatg%2Fcommerce%2Forder%2Fpurchase%2FKLSPaymentInfoFormHandler.moveToConfirmSuccessURL=+&%2Fatg%2Fcommerce%2Forder%2Fpurchase%2FKLSPaymentInfoFormHandler.moveToConfirmErrorURL=%2Fcheckout%2Fcheckout_payment_information.jsp&_D%3A%2Fatg%2Fcommerce%2Forder%2Fpurchase%2FKLSPaymentInfoFormHandler.moveToConfirmErrorURL=+&submit.x=34&submit.y=19&_D%3Asubmit=+&_DARGS=%2Fcheckout%2Fcheckout_payment_information.jsp.payment_form_1",
        //"BODY=_dyncharset=UTF-8&_dynSessConf={DynSessionConfSP}&_D%3Acardtype=+&cardtype={CardTypeFP}&cardname={CardNameIdFP}&_D%3Acardname=+&cardnum={CardNumFP}&_D%3Acardnum=+&_D%3Acardexp_month=+&cardexp_month={CardExpMonthFP}&_D%3Acardexp_year=+&cardexp_year={CardExpYearFP}&cardcvv={CardCVVFP}&_D%3Acardcvv=+&%2Fatg%2Fcommerce%2Forder%2Fpurchase%2FKLSPaymentInfoFormHandler.newCard=true&_D%3A%2Fatg%2Fcommerce%2Forder%2Fpurchase%2FKLSPaymentInfoFormHandler.newCard=+&%2Fatg%2Fcommerce%2Forder%2Fpurchase%2FKLSPaymentInfoFormHandler.saveCreditCard=false&_D%3A%2Fatg%2Fcommerce%2Forder%2Fpurchase%2FKLSPaymentInfoFormHandler.saveCreditCard=+&GIFT_CARD%3C%3EcardNumber=&_D%3AGIFT_CARD%3C%3EcardNumber=+&GIFT_CARD%3C%3EcardPin=Pin+%23&_D%3AGIFT_CARD%3C%3EcardPin=+&_D%3Aadd_gift_card=+&kohlsCashCouponNumber=&_D%3AkohlsCashCouponNumber=+&kohlsCashPin=Pin+%23&_D%3AkohlsCashPin=+&_D%3Aadd_kohls_cash=+&GENERIC%3C%3EpromotionCode=&_D%3AGENERIC%3C%3EpromotionCode=+&_D%3Aadd_promo_code=+&%2Fatg%2Fcommerce%2Forder%2Fpurchase%2FKLSPaymentInfoFormHandler.paymentInfoSuccessURL=create_payment_info_success_url&_D%3A%2Fatg%2Fcommerce%2Forder%2Fpurchase%2FKLSPaymentInfoFormHandler.paymentInfoSuccessURL=+&%2Fatg%2Fcommerce%2Forder%2Fpurchase%2FKLSPaymentInfoFormHandler.paymentInfoErrorURL=create_payment_info_error_url&_D%3A%2Fatg%2Fcommerce%2Forder%2Fpurchase%2FKLSPaymentInfoFormHandler.paymentInfoErrorURL=+&%2Fatg%2Fcommerce%2Forder%2Fpurchase%2FKLSPaymentInfoFormHandler.moveToConfirmSuccessURL=%2Fcheckout%2Forder_review.jsp&_D%3A%2Fatg%2Fcommerce%2Forder%2Fpurchase%2FKLSPaymentInfoFormHandler.moveToConfirmSuccessURL=+&%2Fatg%2Fcommerce%2Forder%2Fpurchase%2FKLSPaymentInfoFormHandler.moveToConfirmErrorURL=%2Fcheckout%2Fcheckout_payment_information.jsp&_D%3A%2Fatg%2Fcommerce%2Forder%2Fpurchase%2FKLSPaymentInfoFormHandler.moveToConfirmErrorURL=+&submit.x=34&submit.y=19&_D%3Asubmit=+&_DARGS=%2Fcheckout%2Fcheckout_payment_information.jsp.payment_form_1",
        "BODY={Reg_PaymentInfoDP}",
        INLINE_URLS,
            "URL=http://www-sf.kohlsecommerce.com/checkout/checkout_payment_information.jsp?_DARGS=/checkout/checkout_payment_information.jsp.payment_form_1", END_INLINE,
            "URL=http://www-sf.kohlsecommerce.com/checkout/order_review.jsp?_requestid=6233", "HEADER=Accept-Language:en-us,en;q=0.5", "COOKIE=cookieSetting;JSESSIONID;mbox;s_sess;s_pers;cookieSetting;fsr.s;CartTotal;ItemDetails;", END_INLINE,
            "URL=http://www-sf.kohlsecommerce.com/media/foresee/foresee-alive.js", "HEADER=Accept-Language:en-us,en;q=0.5", "COOKIE=JSESSIONID;mbox;s_sess;s_pers;cookieSetting;fsr.s;CartTotal;ItemDetails;", END_INLINE,
            "URL=http://www-sf.kohlsecommerce.com/media/javascript/launch_window.js", "HEADER=Accept-Language:en-us,en;q=0.5", "COOKIE=JSESSIONID;mbox;s_sess;s_pers;cookieSetting;fsr.s;CartTotal;ItemDetails;fsr.a;", END_INLINE,
            "URL=http://www-sf.kohlsecommerce.com/media/javascript/jquery-1.7.2.min.js", "HEADER=Accept-Language:en-us,en;q=0.5", "COOKIE=JSESSIONID;mbox;s_sess;s_pers;cookieSetting;fsr.s;CartTotal;ItemDetails;fsr.a;", END_INLINE,
            "URL=http://www-sf.kohlsecommerce.com/media/javascript/jquery.fancybox-1.3.4.pack.js", "HEADER=Accept-Language:en-us,en;q=0.5", "COOKIE=JSESSIONID;mbox;s_sess;s_pers;cookieSetting;fsr.s;CartTotal;ItemDetails;fsr.a;", END_INLINE,
            "URL=http://www-sf.kohlsecommerce.com/media/javascript/global.js", "HEADER=Accept-Language:en-us,en;q=0.5", "COOKIE=JSESSIONID;mbox;s_sess;s_pers;cookieSetting;fsr.s;CartTotal;ItemDetails;fsr.a;", END_INLINE,
            "URL=http://www-sf.kohlsecommerce.com/media/javascript/custom.js", "HEADER=Accept-Language:en-us,en;q=0.5", "COOKIE=JSESSIONID;mbox;s_sess;s_pers;cookieSetting;fsr.s;CartTotal;ItemDetails;fsr.a;", END_INLINE,
            "URL=http://www-sf.kohlsecommerce.com/checkout/images/button_submitorder.gif", "HEADER=Accept-Language:en-us,en;q=0.5", "COOKIE=cookieSetting;JSESSIONID;mbox;s_sess;s_pers;cookieSetting;fsr.s;CartTotal;ItemDetails;fsr.a;", "REDIRECT=YES", "LOCATION=http://www-sf.kohlsecommerce.com/", END_INLINE,
            "URL=http://www-sf.kohlsecommerce.com/media/images/review-order-heading.png", "HEADER=Accept-Language:en-us,en;q=0.5", "COOKIE=JSESSIONID;mbox;s_sess;s_pers;cookieSetting;fsr.s;CartTotal;ItemDetails;fsr.a;", END_INLINE,
            "URL=http://www-sf.kohlsecommerce.com/media/images/customer-information-heading.png", "HEADER=Accept-Language:en-us,en;q=0.5", "COOKIE=JSESSIONID;mbox;s_sess;s_pers;cookieSetting;fsr.s;CartTotal;ItemDetails;fsr.a;", END_INLINE,
            "URL=http://www-sf.kohlsecommerce.com/", "HEADER=Accept-Language:en-us,en;q=0.5", "COOKIE=JSESSIONID;mbox;s_sess;s_pers;cookieSetting;fsr.s;CartTotal;ItemDetails;fsr.a;", END_INLINE,
            "URL=http://media.kohls.com.edgesuite.net/is/image/kohls/731799_Multi/None?wid=60&hei=60&op_sharpen=1", "HEADER=Accept-Language:en-us,en;q=0.5", END_INLINE,
            "URL=http://s.btstatic.com/tag.js", "HEADER=Accept-Language:en-us,en;q=0.5", END_INLINE,
            "URL=http://www-sf.kohlsecommerce.com/media/omniture/s_code.js", "HEADER=Accept-Language:en-us,en;q=0.5", "COOKIE=JSESSIONID;mbox;s_sess;s_pers;cookieSetting;fsr.s;CartTotal;ItemDetails;fsr.a;", END_INLINE,
            "URL=http://ww9.kohls.com/b/ss/kohlscomdev/1/H.25/s49214502114673?AQB=1&ndh=1&t=8%2F2%2F2013%2016%3A8%3A15%205%20480&ns=kohls&g=http%3A%2F%2F10.210.211.1%3A17010%2Fcheckout%2Forder_review.jsp%3F_requestid%3D6233&r=http%3A%2F%2F10.210.211.1%3A17010%2Fcheckout%2Fcheckout_payment_information.jsp%3F_requestid%3D6231&events=event28&products=%3Bproductmerch1&v3=external&v8=non-search&v9=order%20confirm&c17=not%20logged%20in&v17=not%20logged%20in&c18=D%3Dv18&v18=04%3A36%20am&c19=D%3Dv19&v19=friday&c20=D%3Dv20&v20=week%20day&c22=2013-03-08&v22=Kohl%27s&c50=kvZQR58PyD5X9M0sMdyvY3tJVwd7K2PJzNRRD86HyK3h9CLyCNGM!-393216387!1362738383273&s=1366x768&c=24&j=1.7&v=N&k=Y&bw=1366&bh=598&pid=order%20confirm&pidt=1&oid=http%3A%2F%2F10.210.211.1%3A17010%2Fmedia%2Fimages%2Fbutton_continue.gif&ot=IMAGE&AQE=1", "HEADER=Accept-Language:en-us,en;q=0.5", "COOKIE=s_vi;", END_INLINE,
            "URL=http://www-sf.kohlsecommerce.com/media/foresee/foresee-trigger.js", "HEADER=Accept-Language:en-us,en;q=0.5", "COOKIE=JSESSIONID;mbox;s_sess;s_pers;cookieSetting;fsr.s;CartTotal;ItemDetails;fsr.a;", END_INLINE,
            "URL=http://www-sf.kohlsecommerce.com/media/foresee/foresee-surveydef.js", "HEADER=Accept-Language:en-us,en;q=0.5", "COOKIE=JSESSIONID;mbox;s_sess;s_pers;cookieSetting;fsr.s;CartTotal;ItemDetails;fsr.a;", END_INLINE
    );
    ns_end_transaction("Reg_PaymentInformationPage", NS_AUTO_STATUS);
    ns_page_think_time(0);
    
    return;
    fill_SubmitOrderBody();
    ns_start_transaction("Reg_SubmitOrderPage");
    ns_web_url ("Reg_PlacedOrderPage",
        //"URL=http://www-sf.kohlsecommerce.com/checkout/order_confirm.jsp?_DARGS=/checkout/gadgets/orderInformation.jsp.checkout_submit_order",
        "URL=https://www-sf.kohlsecommerce.com/checkout/order_confirm.jsp?_DARGS=/checkout/gadgets/orderInformation.jsp.checkout_submit_order",
        "METHOD=POST",
        "HEADER=Accept-Language:en-us,en;q=0.5",
        "HEADER=Content-Length:680",
        "HEADER=Content-Type:application/x-www-form-urlencoded",
        "COOKIE=cookieSetting;JSESSIONID;mbox;s_sess;s_pers;cookieSetting;fsr.s;CartTotal;ItemDetails;",
        "REDIRECT=YES",
        "LOCATION=http://www-sf.kohlsecommerce.com/checkout/order_confirm.jsp?_requestid=4799",
        "PreSnapshot=webpage_1363258662752.png",
        "Snapshot=webpage_1363258670127.png",
        //"BODY=_dyncharset=UTF-8&_dynSessConf=6944508524083184195&%2Fatg%2Fcommerce%2Forder%2Fpurchase%2FCommitOrderFormHandler.commitOrderSuccessURL=commit_order_success_url&_D%3A%2Fatg%2Fcommerce%2Forder%2Fpurchase%2FCommitOrderFormHandler.commitOrderSuccessURL=+&%2Fatg%2Fcommerce%2Forder%2Fpurchase%2FCommitOrderFormHandler.commitOrderErrorURL=commit_order_error_url&_D%3A%2Fatg%2Fcommerce%2Forder%2Fpurchase%2FCommitOrderFormHandler.commitOrderErrorURL=+&%2Fatg%2Fcommerce%2Forder%2Fpurchase%2FCommitOrderFormHandler.commitOrder=submit&_D%3A%2Fatg%2Fcommerce%2Forder%2Fpurchase%2FCommitOrderFormHandler.commitOrder=+&_DARGS=%2Fcheckout%2Fgadgets%2ForderInformation.jsp.checkout_submit_order",
        //"BODY=_dyncharset=UTF-8&_dynSessConf={DynSessionConfSP}&%2Fatg%2Fcommerce%2Forder%2Fpurchase%2FCommitOrderFormHandler.commitOrderSuccessURL=commit_order_success_url&_D%3A%2Fatg%2Fcommerce%2Forder%2Fpurchase%2FCommitOrderFormHandler.commitOrderSuccessURL=+&%2Fatg%2Fcommerce%2Forder%2Fpurchase%2FCommitOrderFormHandler.commitOrderErrorURL=commit_order_error_url&_D%3A%2Fatg%2Fcommerce%2Forder%2Fpurchase%2FCommitOrderFormHandler.commitOrderErrorURL=+&%2Fatg%2Fcommerce%2Forder%2Fpurchase%2FCommitOrderFormHandler.commitOrder=submit&_D%3A%2Fatg%2Fcommerce%2Forder%2Fpurchase%2FCommitOrderFormHandler.commitOrder=+&_DARGS=%2Fcheckout%2Fgadgets%2ForderInformation.jsp.checkout_submit_order",
        "BODY={SubmitOrderDP}",
        INLINE_URLS,
            "URL=http://www-sf.kohlsecommerce.com/checkout/order_confirm.jsp?_requestid=4799", "HEADER=Accept-Language:en-us,en;q=0.5", "COOKIE=cookieSetting;JSESSIONID;mbox;s_sess;s_pers;cookieSetting;fsr.s;CartTotal;", END_INLINE,
            "URL=http://www-sf.kohlsecommerce.com/media/foresee/foresee-alive.js", "HEADER=Accept-Language:en-us,en;q=0.5", "COOKIE=JSESSIONID;mbox;s_sess;s_pers;cookieSetting;fsr.s;CartTotal;", END_INLINE,
            "URL=http://www-sf.kohlsecommerce.com/media/javascript/launch_window.js", "HEADER=Accept-Language:en-us,en;q=0.5", "COOKIE=JSESSIONID;mbox;s_sess;s_pers;cookieSetting;fsr.s;CartTotal;fsr.a;", END_INLINE,
            "URL=http://www-sf.kohlsecommerce.com/media/javascript/jquery-1.7.2.min.js", "HEADER=Accept-Language:en-us,en;q=0.5", "COOKIE=JSESSIONID;mbox;s_sess;s_pers;cookieSetting;fsr.s;CartTotal;fsr.a;", END_INLINE,
            "URL=http://www-sf.kohlsecommerce.com/media/javascript/jquery.fancybox-1.3.4.pack.js", "HEADER=Accept-Language:en-us,en;q=0.5", "COOKIE=JSESSIONID;mbox;s_sess;s_pers;cookieSetting;fsr.s;CartTotal;fsr.a;", END_INLINE,
            "URL=http://www-sf.kohlsecommerce.com/media/javascript/global.js", "HEADER=Accept-Language:en-us,en;q=0.5", "COOKIE=JSESSIONID;mbox;s_sess;s_pers;cookieSetting;fsr.s;CartTotal;fsr.a;", END_INLINE,
            "URL=http://www-sf.kohlsecommerce.com/media/javascript/custom.js", "HEADER=Accept-Language:en-us,en;q=0.5", "COOKIE=JSESSIONID;mbox;s_sess;s_pers;cookieSetting;fsr.s;CartTotal;fsr.a;", END_INLINE,
            "URL=http://www-sf.kohlsecommerce.com/media/javascript/shipping_bill_custom.js", "HEADER=Accept-Language:en-us,en;q=0.5", "COOKIE=JSESSIONID;mbox;s_sess;s_pers;cookieSetting;fsr.s;CartTotal;fsr.a;", END_INLINE,
            "URL=http://www-sf.kohlsecommerce.com/media/images/order-placed-heading.png", "HEADER=Accept-Language:en-us,en;q=0.5", "COOKIE=JSESSIONID;mbox;s_sess;s_pers;cookieSetting;fsr.s;CartTotal;fsr.a;", END_INLINE,
            "URL=http://www-sf.kohlsecommerce.com/checkout/order_review.jsp_files/button_save_v1_m56577569832236531.gif", "HEADER=Accept-Language:en-us,en;q=0.5", "COOKIE=cookieSetting;JSESSIONID;mbox;s_sess;s_pers;cookieSetting;fsr.s;CartTotal;fsr.a;", "REDIRECT=YES", "LOCATION=http://www-sf.kohlsecommerce.com/", END_INLINE,
            "URL=http://www-sf.kohlsecommerce.com/media/images/checkout-complete-heading.png", "HEADER=Accept-Language:en-us,en;q=0.5", "COOKIE=JSESSIONID;mbox;s_sess;s_pers;cookieSetting;fsr.s;CartTotal;fsr.a;", END_INLINE,
            "URL=http://www-sf.kohlsecommerce.com/", "HEADER=Accept-Language:en-us,en;q=0.5", "COOKIE=JSESSIONID;mbox;s_sess;s_pers;cookieSetting;fsr.s;CartTotal;fsr.a;", END_INLINE,
            "URL=http://s.btstatic.com/tag.js", "HEADER=Accept-Language:en-us,en;q=0.5", END_INLINE,
            "URL=http://www-sf.kohlsecommerce.com/media/omniture/s_code.js", "HEADER=Accept-Language:en-us,en;q=0.5", "COOKIE=JSESSIONID;mbox;s_sess;s_pers;cookieSetting;fsr.s;CartTotal;fsr.a;", END_INLINE,
            "URL=http://ww9.kohls.com/b/ss/kohlsatgsitoracle/1/H.25/s71119053115856?AQB=1&ndh=1&t=14%2F2%2F2013%2016%3A27%3A49%204%20-330&ns=kohls&pageName=checkout%3Areview&g=http%3A%2F%2F10.210.222.129%3A17010%2Fcheckout%2Forder_confirm.jsp%3F_requestid%3D4799&r=http%3A%2F%2F10.210.222.129%3A17010%2Fcheckout%2Forder_review.jsp%3F_requestid%3D4794&events=purchase&products=%3Btax%3B%3B%3Bevent4%3D0.0%2C%3Bshipping%201%3B%3B%3Bevent6%3D0.0%7Cevent10%3D0.0%3Bevar6%3Dstd%2C%3Bpayment%201%3B%3B%3Bevent7%3D0.0%3Bevar7%3Dcredit%20card&c1=checkout&c2=checkout&c3=checkout&v3=external&c4=checkout&c7=checkout&v8=non-search&c9=checkout&v9=checkout%3Areview&c10=checkout&c11=checkout&v14=0&c17=not%20logged%20in&v17=not%20logged%20in&c18=D%3Dv18&v18=05%3A57%20am&c19=D%3Dv19&v19=thursday&c20=D%3Dv20&v20=week%20day&c22=2013-03-14&v22=Kohl%27s&v48=650250424&c50=P3VgRBpVvPljPQQgD0vMMPfgvV10F2pgvg3GlndNxxv61nn5xh5y!982294971!1363257653903&s=1366x768&c=24&j=1.7&v=N&k=Y&bw=1366&bh=588&pid=checkout%3Areview&pidt=1&oid=%0A%09%09%09%20%20%20%20%20%20%20%20%20%20%20%20%09%09%09Place%20Order%0A%09%09%09%09%09%09%09%09&oidt=3&ot=SUBMIT&AQE=1", "HEADER=Accept-Language:en-us,en;q=0.5", "COOKIE=s_vi;", END_INLINE,
            "URL=http://www-sf.kohlsecommerce.com/media/foresee/foresee-trigger.js", "HEADER=Accept-Language:en-us,en;q=0.5", "COOKIE=JSESSIONID;mbox;s_sess;s_pers;cookieSetting;fsr.s;CartTotal;fsr.a;", END_INLINE,
            "URL=http://www-sf.kohlsecommerce.com/media/foresee/foresee-surveydef.js", "HEADER=Accept-Language:en-us,en;q=0.5", "COOKIE=JSESSIONID;mbox;s_sess;s_pers;cookieSetting;fsr.s;CartTotal;fsr.a;", END_INLINE
    );
    ns_end_transaction("Reg_SubmitOrderPage", NS_AUTO_STATUS);
    ns_page_think_time(0);

}
