/*-----------------------------------------------------------------------------
    Name:SearchKeyword
    Recorded By: netstorm
    Date of recording: 02/16/2013 03:08:39
    Flow details:
    Modification History:
    03/22/2013 - Updated to work with CD5 R3 - Madhu
    03/23/2013 - Updated to work with products with options - Madhu 
    04/10/2013 - Tested with CD5 R15 - Anjali   
    No of pages : 1
-----------------------------------------------------------------------------*/

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "ns_string.h"
void SearchKeyword()
{
	int loop = 0;

    if(strcmp(ns_eval_string("{DynSessionConfSP}"), "") == 0)
    {
    	ns_start_transaction("HomePage_SearchKeyword");
    	ns_web_url ("HomePageSearchK",
        	//"URL=http://www-sf.kohlsecommerce.com/kohlsStore/",
        	"URL=http://www-sf.kohlsecommerce.com/Home.html",
        	"HEADER=Accept-Language:en-us,en;q=0.5",
        	"PreSnapshot=webpage_1361007369767.png",
        	"Snapshot=webpage_1361007395075.png",
        	INLINE_URLS,
            "URL=http://www-sf.kohlsecommerce.com/kohlsdocroot/javascript/jquery-1.7.2.min.js", "HEADER=Accept-Language:en-us,en;q=0.5", "COOKIE=JSESSIONID;", END_INLINE,
            "URL=http://www-sf.kohlsecommerce.com/kohlsdocroot/javascript/global.js", "HEADER=Accept-Language:en-us,en;q=0.5", "COOKIE=JSESSIONID;", END_INLINE,
            "URL=http://www-sf.kohlsecommerce.com/kohlsdocroot/javascript/myaccount.js", "HEADER=Accept-Language:en-us,en;q=0.5", "COOKIE=JSESSIONID;", END_INLINE,
            "URL=http://www-sf.kohlsecommerce.com/kohlsdocroot/javascript/jquery.validate_product.js", "HEADER=Accept-Language:en-us,en;q=0.5", "COOKIE=JSESSIONID;", END_INLINE,
            "URL=http://www-sf.kohlsecommerce.com/kohlsdocroot/javascript/UI_validation.js", "HEADER=Accept-Language:en-us,en;q=0.5", "COOKIE=JSESSIONID;", END_INLINE,
            "URL=http://www-sf.kohlsecommerce.com/kohlsdocroot/javascript/jquery.validate.js", "HEADER=Accept-Language:en-us,en;q=0.5", "COOKIE=JSESSIONID;", END_INLINE,
            "URL=http://www-sf.kohlsecommerce.com/kohlsdocroot/javascript/cart.js", "HEADER=Accept-Language:en-us,en;q=0.5", "COOKIE=JSESSIONID;", END_INLINE,
            "URL=http://www-sf.kohlsecommerce.com/kohlsdocroot/fancybox/jquery.fancybox-1.3.4.pack.js", "HEADER=Accept-Language:en-us,en;q=0.5", "COOKIE=JSESSIONID;", END_INLINE,
            "URL=http://www-sf.kohlsecommerce.com/kohlsdocroot/javascript/custom.js", "HEADER=Accept-Language:en-us,en;q=0.5", "COOKIE=JSESSIONID;", END_INLINE,
            "URL=http://www-sf.kohlsecommerce.com/kohlsdocroot/javascript/jquery.numeric.js", "HEADER=Accept-Language:en-us,en;q=0.5", "COOKIE=JSESSIONID;", END_INLINE,
            "URL=http://www-sf.kohlsecommerce.com/kohlsdocroot/javascript/video.js", "HEADER=Accept-Language:en-us,en;q=0.5", "COOKIE=JSESSIONID;", END_INLINE,
            "URL=http://www-sf.kohlsecommerce.com/kohlsdocroot/javascript/myaccount_custom.js", "HEADER=Accept-Language:en-us,en;q=0.5", "COOKIE=JSESSIONID;", END_INLINE,
            "URL=http://www-sf.kohlsecommerce.com/kohlsdocroot/css/global.css", END_INLINE,
            "URL=http://www-sf.kohlsecommerce.com/kohlsdocroot/css/gift_registry_fix.css", END_INLINE,
            "URL=http://www-sf.kohlsecommerce.com/kohlsdocroot/javascript/launch_window.js", "HEADER=Accept-Language:en-us,en;q=0.5", "COOKIE=JSESSIONID;", END_INLINE,
            "URL=http://www-sf.kohlsecommerce.com/kohlsdocroot/javascript/banner.js", "HEADER=Accept-Language:en-us,en;q=0.5", "COOKIE=JSESSIONID;", END_INLINE,
            "URL=http://www-sf.kohlsecommerce.com/kohlsdocroot/omniture/mbox.js", "HEADER=Accept-Language:en-us,en;q=0.5", "COOKIE=JSESSIONID;", END_INLINE,
            "URL=http://www-sf.kohlsecommerce.com/kohlsdocroot/css/custom.css", END_INLINE,
            "URL=http://www-sf.kohlsecommerce.com/kohlsdocroot/css/balance_inquiry.css", END_INLINE,
            "URL=http://www-sf.kohlsecommerce.com/kohlsdocroot/css/kohls_custom.css", END_INLINE,
            "URL=http://www-sf.kohlsecommerce.com/kohlsdocroot/fancybox/jquery.fancybox-1.3.4.css", END_INLINE,
            "URL=http://www-sf.kohlsecommerce.com/kohlsdocroot/css/my_account.css", END_INLINE,
            "URL=http://www-sf.kohlsecommerce.com/kohlsdocroot/css/tabfix.css", END_INLINE,
            "URL=http://www-sf.kohlsecommerce.com/kohlsdocroot/css/callout.css", END_INLINE,
            "URL=http://www-sf.kohlsecommerce.com/kohlsdocroot/css/banner.css", END_INLINE,
            "URL=http://kohls.tt.omtrdc.net/m2/kohls/mbox/standard?mboxHost=10.210.211.1&mboxSession=1361007378586-605601&mboxPage=1361007378586-605601&screenHeight=768&screenWidth=1360&browserWidth=0&browserHeight=0&browserTimeOffset=330&colorDepth=24&mboxCount=1&mbox=kohlscom_equity_bar&mboxId=0&mboxTime=1361027178677&mboxURL=http%3A%2F%2F10.210.211.1%3A17010%2FkohlsStore%2F&mboxReferrer=&mboxVersion=40", "HEADER=Accept-Language:en-us,en;q=0.5", END_INLINE,
            "URL=http://www-sf.kohlsecommerce.com/kohlsdocroot/images/homepage/1107_FS50_v1_m56577569839035061.gif", "HEADER=Accept-Language:en-us,en;q=0.5", "COOKIE=JSESSIONID;mbox;", END_INLINE,
            "URL=http://www-sf.kohlsecommerce.com/kohlsdocroot/images/homepage/1030_earn_v1_m56577569839011790.gif", "HEADER=Accept-Language:en-us,en;q=0.5", "COOKIE=JSESSIONID;mbox;", END_INLINE,
            "URL=http://www-sf.kohlsecommerce.com/kohlsdocroot/images/homepage/1030_FS75_v1_m56577569839011788.gif", "HEADER=Accept-Language:en-us,en;q=0.5", "COOKIE=JSESSIONID;mbox;", END_INLINE,
            "URL=http://www-sf.kohlsecommerce.com/kohlsdocroot/images/kohls-logo.png", "HEADER=Accept-Language:en-us,en;q=0.5", "COOKIE=JSESSIONID;mbox;", END_INLINE,
            "URL=http://www-sf.kohlsecommerce.com/kohlsdocroot/images/header-icons-sprite.png", "HEADER=Accept-Language:en-us,en;q=0.5", "COOKIE=JSESSIONID;mbox;", END_INLINE,
            "URL=http://www-sf.kohlsecommerce.com/kohlsdocroot/images/top-nav-shadow.jpg", "HEADER=Accept-Language:en-us,en;q=0.5", "COOKIE=JSESSIONID;mbox;", END_INLINE,
            "URL=http://kohls.tt.omtrdc.net/m2/kohls/mbox/standard?mboxHost=10.210.211.1&mboxSession=1361007378586-605601&mboxPage=1361007378586-605601&screenHeight=768&screenWidth=1360&browserWidth=0&browserHeight=0&browserTimeOffset=330&colorDepth=24&mboxCount=2&entity.deptName=HomePage&mbox=kohlscom_product_recommendations_homepage&mboxId=0&mboxTime=1361027179896&mboxURL=http%3A%2F%2F10.210.211.1%3A17010%2FkohlsStore%2F&mboxReferrer=&mboxVersion=40", "HEADER=Accept-Language:en-us,en;q=0.5", END_INLINE,
            "URL=http://www-sf.kohlsecommerce.com/kohlsdocroot/images/homepage/eq3.jpg", "HEADER=Accept-Language:en-us,en;q=0.5", "COOKIE=JSESSIONID;mbox;", END_INLINE,
            "URL=http://www-sf.kohlsecommerce.com/kohlsdocroot/images/homepage/02_equity2.jpg", "HEADER=Accept-Language:en-us,en;q=0.5", "COOKIE=JSESSIONID;mbox;", END_INLINE,
            "URL=http://www-sf.kohlsecommerce.com/kohlsdocroot/images/homepage/eq_3.jpg", "HEADER=Accept-Language:en-us,en;q=0.5", "COOKIE=JSESSIONID;mbox;", END_INLINE,
            "URL=http://www-sf.kohlsecommerce.com/kohlsdocroot/images/homepage/eq-2.jpg", "HEADER=Accept-Language:en-us,en;q=0.5", "COOKIE=JSESSIONID;mbox;", END_INLINE,
            "URL=http://www-sf.kohlsecommerce.com/kohlsdocroot/images/homepage/eq2.jpg", "HEADER=Accept-Language:en-us,en;q=0.5", "COOKIE=JSESSIONID;mbox;", END_INLINE,
            "URL=http://www-sf.kohlsecommerce.com/kohlsdocroot/images/homepage/05_eq1.jpg", "HEADER=Accept-Language:en-us,en;q=0.5", "COOKIE=JSESSIONID;mbox;", END_INLINE,
            "URL=http://www-sf.kohlsecommerce.com/kohlsdocroot/images/homepage/100412equity_2.jpg", "HEADER=Accept-Language:en-us,en;q=0.5", "COOKIE=JSESSIONID;mbox;", END_INLINE,
            "URL=http://www-sf.kohlsecommerce.com/kohlsdocroot/images/homepage/equity_2.jpg", "HEADER=Accept-Language:en-us,en;q=0.5", "COOKIE=JSESSIONID;mbox;", END_INLINE,
            "URL=http://www-sf.kohlsecommerce.com/kohlsdocroot/images/homepage/SaleBanner_v1_m56577569839039713.png", "HEADER=Accept-Language:en-us,en;q=0.5", "COOKIE=JSESSIONID;mbox;", END_INLINE,
            "URL=http://www-sf.kohlsecommerce.com/kohlsdocroot/images/homepage/0000_01_S1_JewelrySuper_v1_m56577569838942914.png", "HEADER=Accept-Language:en-us,en;q=0.5", "COOKIE=JSESSIONID;mbox;", END_INLINE,
            "URL=http://www-sf.kohlsecommerce.com/kohlsdocroot/images/homepage/0000_01_S2_JewelrySuper_v1_m56577569838942918.png", "HEADER=Accept-Language:en-us,en;q=0.5", "COOKIE=JSESSIONID;mbox;", END_INLINE,
            "URL=http://www-sf.kohlsecommerce.com/kohlsdocroot/images/homepage/0000_01_S3_JewelrySuper_v1_m56577569839046212.png", "HEADER=Accept-Language:en-us,en;q=0.5", "COOKIE=JSESSIONID;mbox;", END_INLINE,
            "URL=http://www-sf.kohlsecommerce.com/kohlsdocroot/images/homepage/0000_01_S4_JewelrySuper_v1_m56577569839023708.png", "HEADER=Accept-Language:en-us,en;q=0.5", "COOKIE=JSESSIONID;mbox;", END_INLINE,
            "URL=http://www-sf.kohlsecommerce.com/kohlsdocroot/images/homepage/0000_01_S1_JewelrySuper_thumb_v1_m56577569838942913.png", "HEADER=Accept-Language:en-us,en;q=0.5", "COOKIE=JSESSIONID;mbox;", END_INLINE,
            "URL=http://www-sf.kohlsecommerce.com/kohlsdocroot/images/homepage/0000_01_S2_JewelrySuper_thumb_v1_m56577569838942912.png", "HEADER=Accept-Language:en-us,en;q=0.5", "COOKIE=JSESSIONID;mbox;", END_INLINE,
            "URL=http://www-sf.kohlsecommerce.com/kohlsdocroot/images/homepage/0000_01_S3_JewelrySuper_thumb_v1_m56577569839046226.png", "HEADER=Accept-Language:en-us,en;q=0.5", "COOKIE=JSESSIONID;mbox;", END_INLINE,
            "URL=http://www-sf.kohlsecommerce.com/kohlsdocroot/images/homepage/0000_01_S4_JewelrySuper_thumb_v1_m56577569839023713.png", "HEADER=Accept-Language:en-us,en;q=0.5", "COOKIE=JSESSIONID;mbox;", END_INLINE,
            "URL=http://www-sf.kohlsecommerce.com/media/images/StaticContent/flash/Background/20121007/navback_4.png", "HEADER=Accept-Language:en-us,en;q=0.5", "COOKIE=JSESSIONID;mbox;", END_INLINE,
            "URL=http://www-sf.kohlsecommerce.com/kohlsdocroot/images/homepage/feature2_v1_m56577569839014792.png", "HEADER=Accept-Language:en-us,en;q=0.5", "COOKIE=JSESSIONID;mbox;", END_INLINE,
            "URL=http://www-sf.kohlsecommerce.com/kohlsdocroot/images/homepage/Product1.JPG", "HEADER=Accept-Language:en-us,en;q=0.5", "COOKIE=JSESSIONID;mbox;", END_INLINE,
            "URL=http://www-sf.kohlsecommerce.com/kohlsdocroot/images/homepage/Product4.jpg", "HEADER=Accept-Language:en-us,en;q=0.5", "COOKIE=JSESSIONID;mbox;", END_INLINE,
            "URL=http://www-sf.kohlsecommerce.com/kohlsdocroot/images/homepage/beddingspotlight_v1_m56577569838405299.png", "HEADER=Accept-Language:en-us,en;q=0.5", "COOKIE=JSESSIONID;mbox;", END_INLINE,
            "URL=http://www-sf.kohlsecommerce.com/kohlsdocroot/images/homepage/shop-equity-2-tier-2.jpg", "HEADER=Accept-Language:en-us,en;q=0.5", "COOKIE=JSESSIONID;mbox;", END_INLINE,
            "URL=http://www-sf.kohlsecommerce.com/kohlsdocroot/images/homepage/shop-equity-3-tier-4.jpg", "HEADER=Accept-Language:en-us,en;q=0.5", "COOKIE=JSESSIONID;mbox;", END_INLINE,
            "URL=http://www-sf.kohlsecommerce.com/kohlsdocroot/images/homepage/shop-equity-1-tier-2.jpg", "HEADER=Accept-Language:en-us,en;q=0.5", "COOKIE=JSESSIONID;mbox;", END_INLINE,
            "URL=http://www-sf.kohlsecommerce.com/kohlsdocroot/images/homepage/Ecommerce.jpg", "HEADER=Accept-Language:en-us,en;q=0.5", "COOKIE=JSESSIONID;mbox;", END_INLINE,
            "URL=http://www-sf.kohlsecommerce.com/kohlsdocroot/images/homepage/shop-equity-2-tier-3.jpg", "HEADER=Accept-Language:en-us,en;q=0.5", "COOKIE=JSESSIONID;mbox;", END_INLINE,
            "URL=http://www-sf.kohlsecommerce.com/kohlsdocroot/images/homepage/A_01_1024_Spirit_v1_m56577569838941749.png", "HEADER=Accept-Language:en-us,en;q=0.5", "COOKIE=JSESSIONID;mbox;", END_INLINE,
            "URL=http://kohls.tt.omtrdc.net/m2/kohls/mbox/standard?mboxHost=10.210.211.1&mboxSession=1361007378586-605601&mboxPage=1361007378586-605601&screenHeight=768&screenWidth=1360&browserWidth=0&browserHeight=0&browserTimeOffset=330&colorDepth=24&mboxCount=3&mbox=kohlscom_home_feature&mboxId=0&mboxTime=1361027182149&mboxURL=http%3A%2F%2F10.210.211.1%3A17010%2FkohlsStore%2F&mboxReferrer=&mboxVersion=40", "HEADER=Accept-Language:en-us,en;q=0.5", END_INLINE,
            "URL=http://www-sf.kohlsecommerce.com/kohlsStore/brighttag/brighttag_akamai.jsp?folderPath=/Homepage&currentTemplate=/home.jsp", "HEADER=Accept-Language:en-us,en;q=0.5", "COOKIE=JSESSIONID;mbox;", END_INLINE,
            "URL=http://www-sf.kohlsecommerce.com/kohlsdocroot/images/moretoexplore.png", "HEADER=Accept-Language:en-us,en;q=0.5", "COOKIE=JSESSIONID;mbox;", END_INLINE,
            "URL=http://www-sf.kohlsecommerce.com/kohlsdocroot/images/homepage/E_01_1024_Oasis_v1_m56577569838942192.png", "HEADER=Accept-Language:en-us,en;q=0.5", "COOKIE=JSESSIONID;mbox;", END_INLINE,
            "URL=http://www-sf.kohlsecommerce.com/kohlsdocroot/images/homepage/C_02_1024_Comforters_v1_m56577569838942204.png", "HEADER=Accept-Language:en-us,en;q=0.5", "COOKIE=JSESSIONID;mbox;", END_INLINE,
            "URL=http://www-sf.kohlsecommerce.com/kohlsdocroot/images/homepage/C_12_1024_KidsBath_v1_m56577569838942199.png", "HEADER=Accept-Language:en-us,en;q=0.5", "COOKIE=JSESSIONID;mbox;", END_INLINE,
            "URL=http://www-sf.kohlsecommerce.com/kohlsdocroot/images/homepage/A_01_1024_Boot_Shop_v1_m56577569838973324.png", "HEADER=Accept-Language:en-us,en;q=0.5", "COOKIE=JSESSIONID;mbox;", END_INLINE,
            "URL=http://www-sf.kohlsecommerce.com/kohlsdocroot/images/homepage/B_01_1024_Nike_v1_m56577569838942150.png", "HEADER=Accept-Language:en-us,en;q=0.5", "COOKIE=JSESSIONID;mbox;", END_INLINE,
            "URL=http://www-sf.kohlsecommerce.com/kohlsdocroot/images/homepage/B_04_1024_Adidas_v1_m56577569838942153.png", "HEADER=Accept-Language:en-us,en;q=0.5", "COOKIE=JSESSIONID;mbox;", END_INLINE,
            "URL=http://www-sf.kohlsecommerce.com/kohlsdocroot/images/yes_cs.gif", "HEADER=Accept-Language:en-us,en;q=0.5", "COOKIE=JSESSIONID;mbox;", END_INLINE,
            "URL=http://www.facebook.com/plugins/likebox.php?href=http%3A%2F%2Fwww.facebook.com%2Fkohls&width=315&colorscheme=light&connections=5&border_color=%23A5A9AC&stream=false&header=false&height=185", "HEADER=Accept-Language:en-us,en;q=0.5", END_INLINE,
            "URL=http://www-sf.kohlsecommerce.com/kohlsdocroot/images/facebook.gif", "HEADER=Accept-Language:en-us,en;q=0.5", "COOKIE=JSESSIONID;mbox;", END_INLINE,
            "URL=http://www-sf.kohlsecommerce.com/kohlsdocroot/images/twitter.gif", "HEADER=Accept-Language:en-us,en;q=0.5", "COOKIE=JSESSIONID;mbox;", END_INLINE,
            "URL=http://www-sf.kohlsecommerce.com/kohlsdocroot/images/youtube.gif", "HEADER=Accept-Language:en-us,en;q=0.5", "COOKIE=JSESSIONID;mbox;", END_INLINE,
            "URL=http://s.btstatic.com/tag.js", "HEADER=Accept-Language:en-us,en;q=0.5", END_INLINE,
            "URL=http://static.ak.fbcdn.net/rsrc.php/v2/yO/r/ALeBTv6UlJb.js", "HEADER=Accept-Language:en-us,en;q=0.5", END_INLINE,
            "URL=http://profile.ak.fbcdn.net/hprofile-ak-snc6/203076_100002113274080_415673451_q.jpg", "HEADER=Accept-Language:en-us,en;q=0.5", END_INLINE,
            "URL=http://profile.ak.fbcdn.net/hprofile-ak-prn1/173355_1208155500_492238733_q.jpg", "HEADER=Accept-Language:en-us,en;q=0.5", END_INLINE,
            "URL=http://profile.ak.fbcdn.net/hprofile-ak-snc7/368823_100003977057185_1288930960_q.jpg", "HEADER=Accept-Language:en-us,en;q=0.5", END_INLINE,
            "URL=http://www-sf.kohlsecommerce.com/kohlsdocroot/omniture/s_code.js", "HEADER=Accept-Language:en-us,en;q=0.5", "COOKIE=JSESSIONID;mbox;", END_INLINE,
            "URL=http://www-sf.kohlsecommerce.com/kohlsStore/sitecatalyst/omniture_akamai.jsp", "HEADER=Accept-Language:en-us,en;q=0.5", "COOKIE=JSESSIONID;mbox;", END_INLINE,
            "URL=http://ww9.kohls.com/b/ss/kohlscomdev/1/H.25/s97041330048529?AQB=1&ndh=1&t=16%2F1%2F2013%2015%3A6%3A30%206%20-330&ns=kohls&pageName=homepage&g=http%3A%2F%2F10.210.211.1%3A17010%2FkohlsStore%2F&events=event28&products=%3Bproductmerch1&c1=homepage&c2=homepage&c3=homepage&v3=homepage&c4=homepage&c7=homepage&v8=non-search&c17=not%20logged%20in&v17=not%20logged%20in&c18=D%3Dv18&v18=03%3A36%20am&c19=D%3Dv19&v19=saturday&c20=D%3Dv20&v20=week%20end&c22=2013-02-16&v22=Kohl%27s&c50=Y75LRfTD5ZKw3Q56hJ9hRp9Q7nfGzP7jQ872C0cWnnQH48nxj4Jf!-513982135!1361007363683&s=1360x768&c=24&j=1.7&v=Y&k=Y&p=Mozilla%20Default%20Plug-in%3BGoogle%20Update%3BAVG%20SiteSafety%20plugin%3BJava%20Deployment%20Toolkit%206.0.220.4%3BJava(TM)%20Platform%20SE%206%20U22%3BMindSpark%20Toolbar%20Platform%20Plugin%20Stub%3BVLC%20Web%20Plugin%3B&AQE=1", "HEADER=Accept-Language:en-us,en;q=0.5", "REDIRECT=YES", "LOCATION=http://ww9.kohls.com/b/ss/kohlscomdev/1/H.25/s97041330048529?AQB=1&pccr=true&vidn=288FA98C051D2AD2-4000013600006C4E&&ndh=1&t=16%2F1%2F2013%2015%3A6%3A30%206%20-330&ns=kohls&pageName=homepage&g=http%3A%2F%2F10.210.211.1%3A17010%2FkohlsStore%2F&events=event28&products=%3Bproductmerch1&c1=homepage&c2=homepage&c3=homepage&v3=homepage&c4=homepage&c7=homepage&v8=non-search&c17=not%20logged%20in&v17=not%20logged%20in&c18=D%3Dv18&v18=03%3A36%20am&c19=D%3Dv19&v19=saturday&c20=D%3Dv20&v20=week%20end&c22=2013-02-16&v22=Kohl%27s&c50=Y75LRfTD5ZKw3Q56hJ9hRp9Q7nfGzP7jQ872C0cWnnQH48nxj4Jf!-513982135!1361007363683&s=1360x768&c=24&j=1.7&v=Y&k=Y&p=Mozilla%20Default%20Plug-in%3BGoogle%20Update%3BAVG%20SiteSafety%20plugin%3BJava%20Deployment%20Toolkit%206.0.220.4%3BJava(TM)%20Platform%20SE%206%20U22%3BMindSpark%20Toolbar%20Platform%20Plugin%20Stub%3BVLC%20Web%20Plugin%3B&AQE=1", END_INLINE,
            "URL=http://ww9.kohls.com/b/ss/kohlscomdev/1/H.25/s97041330048529?AQB=1&pccr=true&vidn=288FA98C051D2AD2-4000013600006C4E&&ndh=1&t=16%2F1%2F2013%2015%3A6%3A30%206%20-330&ns=kohls&pageName=homepage&g=http%3A%2F%2F10.210.211.1%3A17010%2FkohlsStore%2F&events=event28&products=%3Bproductmerch1&c1=homepage&c2=homepage&c3=homepage&v3=homepage&c4=homepage&c7=homepage&v8=non-search&c17=not%20logged%20in&v17=not%20logged%20in&c18=D%3Dv18&v18=03%3A36%20am&c19=D%3Dv19&v19=saturday&c20=D%3Dv20&v20=week%20end&c22=2013-02-16&v22=Kohl%27s&c50=Y75LRfTD5ZKw3Q56hJ9hRp9Q7nfGzP7jQ872C0cWnnQH48nxj4Jf!-513982135!1361007363683&s=1360x768&c=24&j=1.7&v=Y&k=Y&p=Mozilla%20Default%20Plug-in%3BGoogle%20Update%3BAVG%20SiteSafety%20plugin%3BJava%20Deployment%20Toolkit%206.0.220.4%3BJava(TM)%20Platform%20SE%206%20U22%3BMindSpark%20Toolbar%20Platform%20Plugin%20Stub%3BVLC%20Web%20Plugin%3B&AQE=1", "HEADER=Accept-Language:en-us,en;q=0.5", "COOKIE=s_vi;", END_INLINE
    	);
    	ns_end_transaction("HomePage_SearchKeyword", NS_AUTO_STATUS);
    	ns_page_think_time(0);    
    }

	#ifdef NS_DEBUG_ON
 	printf("\n ++++++++++ Search Keyword ++++++++++++++\n");
    #endif
    loop = ns_get_int_val("SearchLoop");	
    #ifdef NS_DEBUG_ON
    printf("\n Looping Search for %d \n", loop);
     #endif
    ns_set_int_val("SearchLoop", loop - 1);


    ns_start_transaction("SearchKeyword");    
    ns_web_url ("SearchKeywordPage",
        //"URL=http://www-sf.kohlsecommerce.com/kohlsStore/search.jsp?_dyncharset=UTF-8&_dynSessConf=5045202775304219307&search=socks&_D%3Asearch=+&%2Fcom%2Fkohls%2Fsearch%2Fformhandler%2FSearchFormHandler.queryBean.requestType=search&_D%3A%2Fcom%2Fkohls%2Fsearch%2Fformhandler%2FSearchFormHandler.queryBean.requestType=+&submit-search=&_D%3Asubmit-search=+&_DARGS=%2FkohlsStore%2Fcatalog%2Fsearch%2Fsearch.jsp",
        "URL=http://www-sf.kohlsecommerce.com/search.jsp?_dyncharset=UTF-8&search={SearchKeywordFP}&_D%3Asearch=+&%2Fcom%2Fkohls%2Fsearch%2Fformhandler%2FSearchFormHandler.queryBean.requestType=search&_D%3A%2Fcom%2Fkohls%2Fsearch%2Fformhandler%2FSearchFormHandler.queryBean.requestType=+&submit-search=&_D%3Asubmit-search=+&_DARGS=%2Fcatalog%2Fsearch%2Fsearch.jsp",
        "HEADER=Accept-Language:en-us,en;q=0.5",
        "COOKIE=JSESSIONID;mbox;s_sess;s_pers;",
        "REDIRECT=YES",
        "LOCATION=http://www-sf.kohlsecommerce.com/kohlsStore/search.jsp?search=socks&_requestid=4256",
        "PreSnapshot=webpage_1361007408271.png",
        "Snapshot=webpage_1361007474734.png",
        INLINE_URLS,
            "URL=http://www-sf.kohlsecommerce.com/kohlsStore/search.jsp?search=socks&_requestid=4256", "HEADER=Accept-Language:en-us,en;q=0.5", "COOKIE=JSESSIONID;mbox;s_sess;s_pers;", END_INLINE,
            "URL=http://www-sf.kohlsecommerce.com/kohlsdocroot/javascript/jquery-1.7.2.min.js", "HEADER=Accept-Language:en-us,en;q=0.5", "COOKIE=JSESSIONID;mbox;s_sess;s_pers;", END_INLINE,
            "URL=http://www-sf.kohlsecommerce.com/kohlsdocroot/javascript/global.js", "HEADER=Accept-Language:en-us,en;q=0.5", "COOKIE=JSESSIONID;mbox;s_sess;s_pers;", END_INLINE,
            "URL=http://www-sf.kohlsecommerce.com/kohlsdocroot/javascript/myaccount.js", "HEADER=Accept-Language:en-us,en;q=0.5", "COOKIE=JSESSIONID;mbox;s_sess;s_pers;", END_INLINE,
            "URL=http://www-sf.kohlsecommerce.com/kohlsdocroot/javascript/jquery.validate_product.js", "HEADER=Accept-Language:en-us,en;q=0.5", "COOKIE=JSESSIONID;mbox;s_sess;s_pers;", END_INLINE,
            "URL=http://www-sf.kohlsecommerce.com/kohlsdocroot/javascript/UI_validation.js", "HEADER=Accept-Language:en-us,en;q=0.5", "COOKIE=JSESSIONID;mbox;s_sess;s_pers;", END_INLINE,
            "URL=http://www-sf.kohlsecommerce.com/kohlsdocroot/javascript/jquery.validate.js", "HEADER=Accept-Language:en-us,en;q=0.5", "COOKIE=JSESSIONID;mbox;s_sess;s_pers;", END_INLINE,
            "URL=http://www-sf.kohlsecommerce.com/kohlsdocroot/javascript/cart.js", "HEADER=Accept-Language:en-us,en;q=0.5", "COOKIE=JSESSIONID;mbox;s_sess;s_pers;", END_INLINE,
            "URL=http://www-sf.kohlsecommerce.com/kohlsdocroot/fancybox/jquery.fancybox-1.3.4.pack.js", "HEADER=Accept-Language:en-us,en;q=0.5", "COOKIE=JSESSIONID;mbox;s_sess;s_pers;", END_INLINE,
            "URL=http://www-sf.kohlsecommerce.com/kohlsdocroot/javascript/custom.js", "HEADER=Accept-Language:en-us,en;q=0.5", "COOKIE=JSESSIONID;mbox;s_sess;s_pers;", END_INLINE,
            "URL=http://www-sf.kohlsecommerce.com/kohlsdocroot/javascript/jquery.numeric.js", "HEADER=Accept-Language:en-us,en;q=0.5", "COOKIE=JSESSIONID;mbox;s_sess;s_pers;", END_INLINE,
            "URL=http://www-sf.kohlsecommerce.com/kohlsdocroot/javascript/video.js", "HEADER=Accept-Language:en-us,en;q=0.5", "COOKIE=JSESSIONID;mbox;s_sess;s_pers;", END_INLINE,
            "URL=http://www-sf.kohlsecommerce.com/kohlsdocroot/javascript/myaccount_custom.js", "HEADER=Accept-Language:en-us,en;q=0.5", "COOKIE=JSESSIONID;mbox;s_sess;s_pers;", END_INLINE,
            "URL=http://www-sf.kohlsecommerce.com/kohlsdocroot/javascript/fb_like_pdt.js", "HEADER=Accept-Language:en-us,en;q=0.5", "COOKIE=JSESSIONID;mbox;s_sess;s_pers;", END_INLINE,
            "URL=http://www-sf.kohlsecommerce.com/kohlsdocroot/javascript/jquery.nicescroll.min.js", "HEADER=Accept-Language:en-us,en;q=0.5", "COOKIE=JSESSIONID;mbox;s_sess;s_pers;", END_INLINE,
            "URL=http://www-sf.kohlsecommerce.com/kohlsdocroot/javascript/scroll.js", "HEADER=Accept-Language:en-us,en;q=0.5", "COOKIE=JSESSIONID;mbox;s_sess;s_pers;", END_INLINE,
            "URL=http://www-sf.kohlsecommerce.com/kohlsdocroot/javascript/jcarousellite.min.js", "HEADER=Accept-Language:en-us,en;q=0.5", "COOKIE=JSESSIONID;mbox;s_sess;s_pers;", END_INLINE,
            "URL=http://www-sf.kohlsecommerce.com/kohlsdocroot/javascript/cloud-zoom.1.0.2.min.js", "HEADER=Accept-Language:en-us,en;q=0.5", "COOKIE=JSESSIONID;mbox;s_sess;s_pers;", END_INLINE,
            "URL=http://www-sf.kohlsecommerce.com/kohlsdocroot/javascript/carousel_inline.js", "HEADER=Accept-Language:en-us,en;q=0.5", "COOKIE=JSESSIONID;mbox;s_sess;s_pers;", END_INLINE,
            "URL=http://www-sf.kohlsecommerce.com/kohlsdocroot/javascript/product.js", "HEADER=Accept-Language:en-us,en;q=0.5", "COOKIE=JSESSIONID;mbox;s_sess;s_pers;", END_INLINE,
            "URL=http://www-sf.kohlsecommerce.com/kohlsdocroot/javascript/search_functionality.js", "HEADER=Accept-Language:en-us,en;q=0.5", "COOKIE=JSESSIONID;mbox;s_sess;s_pers;", END_INLINE,
            "URL=http://www-sf.kohlsecommerce.com/kohlsdocroot/javascript/kohls_v1_m56577569836982750.js", "HEADER=Accept-Language:en-us,en;q=0.5", "COOKIE=JSESSIONID;mbox;s_sess;s_pers;", END_INLINE,
            "URL=http://www-sf.kohlsecommerce.com/kohlsdocroot/omniture/mbox.js", "HEADER=Accept-Language:en-us,en;q=0.5", "COOKIE=JSESSIONID;mbox;s_sess;s_pers;", END_INLINE,
            "URL=http://www-sf.kohlsecommerce.com/kohlsdocroot/css/left-nav.css", END_INLINE,
            "URL=http://www-sf.kohlsecommerce.com/kohlsdocroot/css/sub_v1.css", END_INLINE,
            "URL=http://www-sf.kohlsecommerce.com/kohlsdocroot/css/sub_v2.css", END_INLINE,
            "URL=http://www-sf.kohlsecommerce.com/kohlsdocroot/css/overlay.css", END_INLINE,
            "URL=http://www-sf.kohlsecommerce.com/kohlsdocroot/css/search-again.css", END_INLINE,
            "URL=http://www-sf.kohlsecommerce.com/kohlsdocroot/css/product-matrix_v1_m56577569836982752.css", END_INLINE,
            "URL=http://www-sf.kohlsecommerce.com/kohlsdocroot/css/dept_rotator.css", END_INLINE,
            "URL=http://kohls.tt.omtrdc.net/m2/kohls/mbox/standard?mboxHost=10.210.211.1&mboxSession=1361007378586-605601&mboxPC=1361007378586-605601.25_06&mboxPage=1361007419549-256997&screenHeight=768&screenWidth=1360&browserWidth=1360&browserHeight=588&browserTimeOffset=330&colorDepth=24&mboxCount=1&mbox=kohlscom_equity_bar&mboxId=0&mboxTime=1361027220302&mboxURL=http%3A%2F%2F10.210.211.1%3A17010%2FkohlsStore%2Fsearch.jsp%3Fsearch%3Dsocks%26_requestid%3D4256&mboxReferrer=http%3A%2F%2F10.210.211.1%3A17010%2FkohlsStore%2F&mboxVersion=40", "HEADER=Accept-Language:en-us,en;q=0.5", END_INLINE,
            "URL=http://kohls.tt.omtrdc.net/m2/kohls/mbox/standard?mboxHost=10.210.211.1&mboxSession=1361007378586-605601&mboxPC=1361007378586-605601.25_06&mboxPage=1361007419549-256997&screenHeight=768&screenWidth=1360&browserWidth=1360&browserHeight=588&browserTimeOffset=330&colorDepth=24&mboxCount=2&mbox=kohlscom_search_feature&mboxId=0&mboxTime=1361027221740&mboxURL=http%3A%2F%2F10.210.211.1%3A17010%2FkohlsStore%2Fsearch.jsp%3Fsearch%3Dsocks%26_requestid%3D4256&mboxReferrer=http%3A%2F%2F10.210.211.1%3A17010%2FkohlsStore%2F&mboxVersion=40", "HEADER=Accept-Language:en-us,en;q=0.5", END_INLINE,
            "URL=http://media.kohls.com.edgesuite.net/is/image/kohls/1002790?wid=372&hei=372&op_sharpen=1", "HEADER=Accept-Language:en-us,en;q=0.5", END_INLINE,
            "URL=http://media.kohls.com.edgesuite.net/is/image/kohls/933122?wid=372&hei=372&op_sharpen=1", "HEADER=Accept-Language:en-us,en;q=0.5", END_INLINE,
            "URL=http://media.kohls.com.edgesuite.net/is/image/kohls/1011185_Blue?wid=372&hei=372&op_sharpen=1", "HEADER=Accept-Language:en-us,en;q=0.5", END_INLINE,
            "URL=http://media.kohls.com.edgesuite.net/is/image/kohls/1011185_Blue_sw?wid=20&hei=20", "HEADER=Accept-Language:en-us,en;q=0.5", END_INLINE,
            "URL=http://media.kohls.com.edgesuite.net/is/image/kohls/1011185_White_Black_sw?wid=20&hei=20", "HEADER=Accept-Language:en-us,en;q=0.5", END_INLINE,
            "URL=http://media.kohls.com.edgesuite.net/is/image/kohls/278182?wid=372&hei=372&op_sharpen=1", "HEADER=Accept-Language:en-us,en;q=0.5", END_INLINE,
            "URL=http://media.kohls.com.edgesuite.net/is/image/kohls/452155_Black_Assorted?wid=372&hei=372&op_sharpen=1", "HEADER=Accept-Language:en-us,en;q=0.5", END_INLINE,
            "URL=http://media.kohls.com.edgesuite.net/is/image/kohls/452155_Black_Assorted_sw?wid=20&hei=20", "HEADER=Accept-Language:en-us,en;q=0.5", END_INLINE,
            "URL=http://media.kohls.com.edgesuite.net/is/image/kohls/452155_Khaki_Assorted_sw?wid=20&hei=20", "HEADER=Accept-Language:en-us,en;q=0.5", END_INLINE,
            "URL=http://media.kohls.com.edgesuite.net/is/image/kohls/452155_Denim_Assorted_sw?wid=20&hei=20", "HEADER=Accept-Language:en-us,en;q=0.5", END_INLINE,
            "URL=http://media.kohls.com.edgesuite.net/is/image/kohls/535148_Fall_Bright?wid=372&hei=372&op_sharpen=1", "HEADER=Accept-Language:en-us,en;q=0.5", END_INLINE,
            "URL=http://media.kohls.com.edgesuite.net/is/image/kohls/535148_Fall_Bright_sw?wid=20&hei=20", "HEADER=Accept-Language:en-us,en;q=0.5", END_INLINE,
            "URL=http://media.kohls.com.edgesuite.net/is/image/kohls/535148_Denim_sw?wid=20&hei=20", "HEADER=Accept-Language:en-us,en;q=0.5", END_INLINE,
            "URL=http://media.kohls.com.edgesuite.net/is/image/kohls/1037501_Pink?wid=372&hei=372&op_sharpen=1", "HEADER=Accept-Language:en-us,en;q=0.5", END_INLINE,
            "URL=http://media.kohls.com.edgesuite.net/is/image/kohls/1037501_Pink_sw?wid=20&hei=20", "HEADER=Accept-Language:en-us,en;q=0.5", END_INLINE,
            "URL=http://media.kohls.com.edgesuite.net/is/image/kohls/1037501_Blue_sw?wid=20&hei=20", "HEADER=Accept-Language:en-us,en;q=0.5", END_INLINE,
            "URL=http://media.kohls.com.edgesuite.net/is/image/kohls/1036067?wid=372&hei=372&op_sharpen=1", "HEADER=Accept-Language:en-us,en;q=0.5", END_INLINE,
            "URL=http://media.kohls.com.edgesuite.net/is/image/kohls/1169348_Black?wid=372&hei=372&op_sharpen=1", "HEADER=Accept-Language:en-us,en;q=0.5", END_INLINE,
            "URL=http://media.kohls.com.edgesuite.net/is/image/kohls/1169348_Black_sw?wid=20&hei=20", "HEADER=Accept-Language:en-us,en;q=0.5", END_INLINE,
            "URL=http://media.kohls.com.edgesuite.net/is/image/kohls/1169348_Brown_sw?wid=20&hei=20", "HEADER=Accept-Language:en-us,en;q=0.5", END_INLINE,
            "URL=http://media.kohls.com.edgesuite.net/is/image/kohls/1239280?wid=372&hei=372&op_sharpen=1", "HEADER=Accept-Language:en-us,en;q=0.5", END_INLINE,
            "URL=http://media.kohls.com.edgesuite.net/is/image/kohls/278183?wid=372&hei=372&op_sharpen=1", "HEADER=Accept-Language:en-us,en;q=0.5", END_INLINE,
            "URL=http://media.kohls.com.edgesuite.net/is/image/kohls/320893_Black?wid=372&hei=372&op_sharpen=1", "HEADER=Accept-Language:en-us,en;q=0.5", END_INLINE,
            "URL=http://media.kohls.com.edgesuite.net/is/image/kohls/320893_Black_sw?wid=20&hei=20", "HEADER=Accept-Language:en-us,en;q=0.5", END_INLINE,
            "URL=http://media.kohls.com.edgesuite.net/is/image/kohls/320893_Brown_sw?wid=20&hei=20", "HEADER=Accept-Language:en-us,en;q=0.5", END_INLINE,
            "URL=http://media.kohls.com.edgesuite.net/is/image/kohls/320893_Navy_sw?wid=20&hei=20", "HEADER=Accept-Language:en-us,en;q=0.5", END_INLINE,
            "URL=http://media.kohls.com.edgesuite.net/is/image/kohls/1011131_Ivory_Coral?wid=372&hei=372&op_sharpen=1", "HEADER=Accept-Language:en-us,en;q=0.5", END_INLINE,
            "URL=http://media.kohls.com.edgesuite.net/is/image/kohls/1011131_Black_White_sw?wid=20&hei=20", "HEADER=Accept-Language:en-us,en;q=0.5", END_INLINE,
            "URL=http://media.kohls.com.edgesuite.net/is/image/kohls/1011131_Primer_Gray_sw?wid=20&hei=20", "HEADER=Accept-Language:en-us,en;q=0.5", END_INLINE,
            "URL=http://media.kohls.com.edgesuite.net/is/image/kohls/1011131_Ivory_Coral_sw?wid=20&hei=20", "HEADER=Accept-Language:en-us,en;q=0.5", END_INLINE,
            "URL=http://media.kohls.com.edgesuite.net/is/image/kohls/927692_Bootstrap?wid=372&hei=372&op_sharpen=1", "HEADER=Accept-Language:en-us,en;q=0.5", END_INLINE,
            "URL=http://media.kohls.com.edgesuite.net/is/image/kohls/927692_Bootstrap_sw?wid=20&hei=20", "HEADER=Accept-Language:en-us,en;q=0.5", END_INLINE,
            "URL=http://media.kohls.com.edgesuite.net/is/image/kohls/927692_Navy_sw?wid=20&hei=20", "HEADER=Accept-Language:en-us,en;q=0.5", END_INLINE,
            "URL=http://media.kohls.com.edgesuite.net/is/image/kohls/927692_Black_sw?wid=20&hei=20", "HEADER=Accept-Language:en-us,en;q=0.5", END_INLINE,
            "URL=http://media.kohls.com.edgesuite.net/is/image/kohls/1128523_Black?wid=372&hei=372&op_sharpen=1", "HEADER=Accept-Language:en-us,en;q=0.5", END_INLINE,
            "URL=http://media.kohls.com.edgesuite.net/is/image/kohls/1128523_White_sw?wid=20&hei=20", "HEADER=Accept-Language:en-us,en;q=0.5", END_INLINE,
            "URL=http://media.kohls.com.edgesuite.net/is/image/kohls/1128523_Black_sw?wid=20&hei=20", "HEADER=Accept-Language:en-us,en;q=0.5", END_INLINE,
            "URL=http://media.kohls.com.edgesuite.net/is/image/kohls/1128523_Assorted_sw?wid=20&hei=20", "HEADER=Accept-Language:en-us,en;q=0.5", END_INLINE,
            "URL=http://media.kohls.com.edgesuite.net/is/image/kohls/1128523_Color_Block_sw?wid=20&hei=20", "HEADER=Accept-Language:en-us,en;q=0.5", END_INLINE,
            "URL=http://media.kohls.com.edgesuite.net/is/image/kohls/404181?wid=372&hei=372&op_sharpen=1", "HEADER=Accept-Language:en-us,en;q=0.5", END_INLINE,
            "URL=http://media.kohls.com.edgesuite.net/is/image/kohls/1152208_Black?wid=372&hei=372&op_sharpen=1", "HEADER=Accept-Language:en-us,en;q=0.5", END_INLINE,
            "URL=http://media.kohls.com.edgesuite.net/is/image/kohls/1152208_Black_sw?wid=20&hei=20", "HEADER=Accept-Language:en-us,en;q=0.5", END_INLINE,
            "URL=http://media.kohls.com.edgesuite.net/is/image/kohls/1152208_Ivory_sw?wid=20&hei=20", "HEADER=Accept-Language:en-us,en;q=0.5", END_INLINE,
            "URL=http://media.kohls.com.edgesuite.net/is/image/kohls/1152208_Pink_sw?wid=20&hei=20", "HEADER=Accept-Language:en-us,en;q=0.5", END_INLINE,
            "URL=http://media.kohls.com.edgesuite.net/is/image/kohls/1002801?wid=372&hei=372&op_sharpen=1", "HEADER=Accept-Language:en-us,en;q=0.5", END_INLINE,
            "URL=http://media.kohls.com.edgesuite.net/is/image/kohls/986411_Black?wid=372&hei=372&op_sharpen=1", "HEADER=Accept-Language:en-us,en;q=0.5", END_INLINE,
            "URL=http://media.kohls.com.edgesuite.net/is/image/kohls/986411_Black_sw?wid=20&hei=20", "HEADER=Accept-Language:en-us,en;q=0.5", END_INLINE,
            "URL=http://media.kohls.com.edgesuite.net/is/image/kohls/986411_Olive_sw?wid=20&hei=20", "HEADER=Accept-Language:en-us,en;q=0.5", END_INLINE,
            "URL=http://media.kohls.com.edgesuite.net/is/image/kohls/986411_Natural_sw?wid=20&hei=20", "HEADER=Accept-Language:en-us,en;q=0.5", END_INLINE,
            "URL=http://media.kohls.com.edgesuite.net/is/image/kohls/986411_Plum_sw?wid=20&hei=20", "HEADER=Accept-Language:en-us,en;q=0.5", END_INLINE,
            "URL=http://media.kohls.com.edgesuite.net/is/image/kohls/986411_Charcoal_Heather_sw?wid=20&hei=20", "HEADER=Accept-Language:en-us,en;q=0.5", END_INLINE,
            "URL=http://media.kohls.com.edgesuite.net/is/image/kohls/1153757_Ivory_Combo?wid=372&hei=372&op_sharpen=1", "HEADER=Accept-Language:en-us,en;q=0.5", END_INLINE,
            "URL=http://media.kohls.com.edgesuite.net/is/image/kohls/1153757_Ivory_Combo_sw?wid=20&hei=20", "HEADER=Accept-Language:en-us,en;q=0.5", END_INLINE,
            "URL=http://media.kohls.com.edgesuite.net/is/image/kohls/1153757_Black_Combo_sw?wid=20&hei=20", "HEADER=Accept-Language:en-us,en;q=0.5", END_INLINE,
            "URL=http://media.kohls.com.edgesuite.net/is/image/kohls/1153757_Gray_Combo_sw?wid=20&hei=20", "HEADER=Accept-Language:en-us,en;q=0.5", END_INLINE,
            "URL=http://media.kohls.com.edgesuite.net/is/image/kohls/1122068?wid=372&hei=372&op_sharpen=1", "HEADER=Accept-Language:en-us,en;q=0.5", END_INLINE,
            "URL=http://media.kohls.com.edgesuite.net/is/image/kohls/495376?wid=372&hei=372&op_sharpen=1", "HEADER=Accept-Language:en-us,en;q=0.5", END_INLINE,
            "URL=http://media.kohls.com.edgesuite.net/is/image/kohls/157823_Jester_Red?wid=372&hei=372&op_sharpen=1", "HEADER=Accept-Language:en-us,en;q=0.5", END_INLINE,
            "URL=http://media.kohls.com.edgesuite.net/is/image/kohls/157823_Torro_Red_sw?wid=20&hei=20", "HEADER=Accept-Language:en-us,en;q=0.5", END_INLINE,
            "URL=http://media.kohls.com.edgesuite.net/is/image/kohls/157823_Jester_Red_sw?wid=20&hei=20", "HEADER=Accept-Language:en-us,en;q=0.5", END_INLINE,
            "URL=http://media.kohls.com.edgesuite.net/is/image/kohls/157823_Postal_Blue_sw?wid=20&hei=20", "HEADER=Accept-Language:en-us,en;q=0.5", END_INLINE,
            "URL=http://media.kohls.com.edgesuite.net/is/image/kohls/157823_Blue_Bounty_sw?wid=20&hei=20", "HEADER=Accept-Language:en-us,en;q=0.5", END_INLINE,
            "URL=http://media.kohls.com.edgesuite.net/is/image/kohls/157823_Pine_Forest_sw?wid=20&hei=20", "HEADER=Accept-Language:en-us,en;q=0.5", END_INLINE,
            "URL=http://media.kohls.com.edgesuite.net/is/image/kohls/157823_Olive_sw?wid=20&hei=20", "HEADER=Accept-Language:en-us,en;q=0.5", END_INLINE,
            "URL=http://media.kohls.com.edgesuite.net/is/image/kohls/157823_Skyline_Blue_sw?wid=20&hei=20", "HEADER=Accept-Language:en-us,en;q=0.5", END_INLINE,
            "URL=http://media.kohls.com.edgesuite.net/is/image/kohls/157823_Ginger_Jar_sw?wid=20&hei=20", "HEADER=Accept-Language:en-us,en;q=0.5", END_INLINE,
            "URL=http://media.kohls.com.edgesuite.net/is/image/kohls/914593_Nude?wid=372&hei=372&op_sharpen=1", "HEADER=Accept-Language:en-us,en;q=0.5", END_INLINE,
            "URL=http://media.kohls.com.edgesuite.net/is/image/kohls/914593_Nude_sw?wid=20&hei=20", "HEADER=Accept-Language:en-us,en;q=0.5", END_INLINE,
            "URL=http://media.kohls.com.edgesuite.net/is/image/kohls/914593_Black_sw?wid=20&hei=20", "HEADER=Accept-Language:en-us,en;q=0.5", END_INLINE,
            "URL=http://media.kohls.com.edgesuite.net/is/image/kohls/1194081?wid=372&hei=372&op_sharpen=1", "HEADER=Accept-Language:en-us,en;q=0.5", END_INLINE,
            "URL=http://media.kohls.com.edgesuite.net/is/image/kohls/320366_Khaki?wid=372&hei=372&op_sharpen=1", "HEADER=Accept-Language:en-us,en;q=0.5", END_INLINE,
            "URL=http://media.kohls.com.edgesuite.net/is/image/kohls/320366_Black_sw?wid=20&hei=20", "HEADER=Accept-Language:en-us,en;q=0.5", END_INLINE,
            "URL=http://media.kohls.com.edgesuite.net/is/image/kohls/320366_Navy_sw?wid=20&hei=20", "HEADER=Accept-Language:en-us,en;q=0.5", END_INLINE,
            "URL=http://media.kohls.com.edgesuite.net/is/image/kohls/320366_Khaki_sw?wid=20&hei=20", "HEADER=Accept-Language:en-us,en;q=0.5", END_INLINE,
            "URL=http://media.kohls.com.edgesuite.net/is/image/kohls/1152795_Black?wid=372&hei=372&op_sharpen=1", "HEADER=Accept-Language:en-us,en;q=0.5", END_INLINE,
            "URL=http://media.kohls.com.edgesuite.net/is/image/kohls/1152795_Black_sw?wid=20&hei=20", "HEADER=Accept-Language:en-us,en;q=0.5", END_INLINE,
            "URL=http://media.kohls.com.edgesuite.net/is/image/kohls/1152795_Boot_Strap_sw?wid=20&hei=20", "HEADER=Accept-Language:en-us,en;q=0.5", END_INLINE,
            "URL=http://media.kohls.com.edgesuite.net/is/image/kohls/883022_Black?wid=372&hei=372&op_sharpen=1", "HEADER=Accept-Language:en-us,en;q=0.5", END_INLINE,
            "URL=http://media.kohls.com.edgesuite.net/is/image/kohls/883022_Black_sw?wid=20&hei=20", "HEADER=Accept-Language:en-us,en;q=0.5", END_INLINE,
            "URL=http://media.kohls.com.edgesuite.net/is/image/kohls/883022_Tan_sw?wid=20&hei=20", "HEADER=Accept-Language:en-us,en;q=0.5", END_INLINE,
            "URL=http://media.kohls.com.edgesuite.net/is/image/kohls/320220_White?wid=372&hei=372&op_sharpen=1", "HEADER=Accept-Language:en-us,en;q=0.5", END_INLINE,
            "URL=http://media.kohls.com.edgesuite.net/is/image/kohls/320220_White_sw?wid=20&hei=20", "HEADER=Accept-Language:en-us,en;q=0.5", END_INLINE,
            "URL=http://media.kohls.com.edgesuite.net/is/image/kohls/320220_Black_sw?wid=20&hei=20", "HEADER=Accept-Language:en-us,en;q=0.5", END_INLINE,
            "URL=http://media.kohls.com.edgesuite.net/is/image/kohls/1194094?wid=372&hei=372&op_sharpen=1", "HEADER=Accept-Language:en-us,en;q=0.5", END_INLINE,
            "URL=http://media.kohls.com.edgesuite.net/is/image/kohls/696687_White?wid=372&hei=372&op_sharpen=1", "HEADER=Accept-Language:en-us,en;q=0.5", END_INLINE,
            "URL=http://media.kohls.com.edgesuite.net/is/image/kohls/1153692_Purple?wid=372&hei=372&op_sharpen=1", "HEADER=Accept-Language:en-us,en;q=0.5", END_INLINE,
            "URL=http://media.kohls.com.edgesuite.net/is/image/kohls/1214547?wid=372&hei=372&op_sharpen=1", "HEADER=Accept-Language:en-us,en;q=0.5", END_INLINE,
            "URL=http://media.kohls.com.edgesuite.net/is/image/kohls/528982_White?wid=372&hei=372&op_sharpen=1", "HEADER=Accept-Language:en-us,en;q=0.5", END_INLINE,
            "URL=http://media.kohls.com.edgesuite.net/is/image/kohls/930899_Drizzle?wid=372&hei=372&op_sharpen=1", "HEADER=Accept-Language:en-us,en;q=0.5", END_INLINE,
            "URL=http://media.kohls.com.edgesuite.net/is/image/kohls/778867_Black?wid=372&hei=372&op_sharpen=1", "HEADER=Accept-Language:en-us,en;q=0.5", END_INLINE,
            "URL=http://media.kohls.com.edgesuite.net/is/image/kohls/1119624?wid=372&hei=372&op_sharpen=1", "HEADER=Accept-Language:en-us,en;q=0.5", END_INLINE,
            "URL=http://media.kohls.com.edgesuite.net/is/image/kohls/1234052_Brick?wid=372&hei=372&op_sharpen=1", "HEADER=Accept-Language:en-us,en;q=0.5", END_INLINE,
            "URL=http://media.kohls.com.edgesuite.net/is/image/kohls/1038291_Stunning_Turquoise?wid=372&hei=372&op_sharpen=1", "HEADER=Accept-Language:en-us,en;q=0.5", END_INLINE,
            "URL=http://media.kohls.com.edgesuite.net/is/image/kohls/1204056?wid=372&hei=372&op_sharpen=1", "HEADER=Accept-Language:en-us,en;q=0.5", END_INLINE,
            "URL=http://media.kohls.com.edgesuite.net/is/image/kohls/1177540?wid=372&hei=372&op_sharpen=1", "HEADER=Accept-Language:en-us,en;q=0.5", END_INLINE,
            "URL=http://media.kohls.com.edgesuite.net/is/image/kohls/1228926?wid=372&hei=372&op_sharpen=1", "HEADER=Accept-Language:en-us,en;q=0.5", END_INLINE,
            "URL=http://media.kohls.com.edgesuite.net/is/image/kohls/1152200_Black?wid=372&hei=372&op_sharpen=1", "HEADER=Accept-Language:en-us,en;q=0.5", END_INLINE,
            "URL=http://media.kohls.com.edgesuite.net/is/image/kohls/1178496?wid=372&hei=372&op_sharpen=1", "HEADER=Accept-Language:en-us,en;q=0.5", END_INLINE,
            "URL=http://media.kohls.com.edgesuite.net/is/image/kohls/1062377_Slack?wid=372&hei=372&op_sharpen=1", "HEADER=Accept-Language:en-us,en;q=0.5", END_INLINE,
            "URL=http://media.kohls.com.edgesuite.net/is/image/kohls/1062377_Jet_Black_sw?wid=20&hei=20", "HEADER=Accept-Language:en-us,en;q=0.5", END_INLINE,
            "URL=http://media.kohls.com.edgesuite.net/is/image/kohls/1062377_Slack_sw?wid=20&hei=20", "HEADER=Accept-Language:en-us,en;q=0.5", END_INLINE,
            "URL=http://media.kohls.com.edgesuite.net/is/image/kohls/1002375?wid=372&hei=372&op_sharpen=1", "HEADER=Accept-Language:en-us,en;q=0.5", END_INLINE,
            "URL=http://media.kohls.com.edgesuite.net/is/image/kohls/1151102?wid=372&hei=372&op_sharpen=1", "HEADER=Accept-Language:en-us,en;q=0.5", END_INLINE,
            "URL=http://media.kohls.com.edgesuite.net/is/image/kohls/1190680_Navy?wid=372&hei=372&op_sharpen=1", "HEADER=Accept-Language:en-us,en;q=0.5", END_INLINE,
            "URL=http://media.kohls.com.edgesuite.net/is/image/kohls/1104697_Red?wid=372&hei=372&op_sharpen=1", "HEADER=Accept-Language:en-us,en;q=0.5", END_INLINE,
            "URL=http://media.kohls.com.edgesuite.net/is/image/kohls/1203530_Rich_Red?wid=372&hei=372&op_sharpen=1", "HEADER=Accept-Language:en-us,en;q=0.5", END_INLINE,
            "URL=http://media.kohls.com.edgesuite.net/is/image/kohls/1011155_Brown?wid=372&hei=372&op_sharpen=1", "HEADER=Accept-Language:en-us,en;q=0.5", END_INLINE,
            "URL=http://media.kohls.com.edgesuite.net/is/image/kohls/1229015?wid=372&hei=372&op_sharpen=1", "HEADER=Accept-Language:en-us,en;q=0.5", END_INLINE,
            "URL=http://media.kohls.com.edgesuite.net/is/image/kohls/177030_Barely_Black?wid=372&hei=372&op_sharpen=1", "HEADER=Accept-Language:en-us,en;q=0.5", END_INLINE,
            "URL=http://media.kohls.com.edgesuite.net/is/image/kohls/1169303_Brown?wid=372&hei=372&op_sharpen=1", "HEADER=Accept-Language:en-us,en;q=0.5", END_INLINE,
            "URL=http://media.kohls.com.edgesuite.net/is/image/kohls/914596_Black?wid=372&hei=372&op_sharpen=1", "HEADER=Accept-Language:en-us,en;q=0.5", END_INLINE,
            "URL=http://media.kohls.com.edgesuite.net/is/image/kohls/319407_White?wid=372&hei=372&op_sharpen=1", "HEADER=Accept-Language:en-us,en;q=0.5", END_INLINE,
            "URL=http://media.kohls.com.edgesuite.net/is/image/kohls/1228151?wid=372&hei=372&op_sharpen=1", "HEADER=Accept-Language:en-us,en;q=0.5", END_INLINE,
            "URL=http://media.kohls.com.edgesuite.net/is/image/kohls/1152791_Taupe?wid=372&hei=372&op_sharpen=1", "HEADER=Accept-Language:en-us,en;q=0.5", END_INLINE,
            "URL=http://media.kohls.com.edgesuite.net/is/image/kohls/320223?wid=372&hei=372&op_sharpen=1", "HEADER=Accept-Language:en-us,en;q=0.5", END_INLINE,
            "URL=http://media.kohls.com.edgesuite.net/is/image/kohls/1002775?wid=372&hei=372&op_sharpen=1", "HEADER=Accept-Language:en-us,en;q=0.5", END_INLINE,
            "URL=http://media.kohls.com.edgesuite.net/is/image/kohls/1169291_Black?wid=372&hei=372&op_sharpen=1", "HEADER=Accept-Language:en-us,en;q=0.5", END_INLINE,
            "URL=http://media.kohls.com.edgesuite.net/is/image/kohls/226002_Black_Gray?wid=372&hei=372&op_sharpen=1", "HEADER=Accept-Language:en-us,en;q=0.5", END_INLINE,
            "URL=http://media.kohls.com.edgesuite.net/is/image/kohls/1034711_Gray?wid=372&hei=372&op_sharpen=1", "HEADER=Accept-Language:en-us,en;q=0.5", END_INLINE,
            "URL=http://media.kohls.com.edgesuite.net/is/image/kohls/1052633_Green?wid=372&hei=372&op_sharpen=1", "HEADER=Accept-Language:en-us,en;q=0.5", END_INLINE,
            "URL=http://media.kohls.com.edgesuite.net/is/image/kohls/914938_Black?wid=372&hei=372&op_sharpen=1", "HEADER=Accept-Language:en-us,en;q=0.5", END_INLINE,
            "URL=http://media.kohls.com.edgesuite.net/is/image/kohls/1152107_Black?wid=372&hei=372&op_sharpen=1", "HEADER=Accept-Language:en-us,en;q=0.5", END_INLINE,
            "URL=http://media.kohls.com.edgesuite.net/is/image/kohls/1037550?wid=372&hei=372&op_sharpen=1", "HEADER=Accept-Language:en-us,en;q=0.5", END_INLINE,
            "URL=http://media.kohls.com.edgesuite.net/is/image/kohls/1116467?wid=372&hei=372&op_sharpen=1", "HEADER=Accept-Language:en-us,en;q=0.5", END_INLINE,
            "URL=http://media.kohls.com.edgesuite.net/is/image/kohls/495279?wid=372&hei=372&op_sharpen=1", "HEADER=Accept-Language:en-us,en;q=0.5", END_INLINE,
            "URL=http://media.kohls.com.edgesuite.net/is/image/kohls/1104837_Green?wid=372&hei=372&op_sharpen=1", "HEADER=Accept-Language:en-us,en;q=0.5", END_INLINE,
            "URL=http://media.kohls.com.edgesuite.net/is/image/kohls/676398_Black_White?wid=372&hei=372&op_sharpen=1", "HEADER=Accept-Language:en-us,en;q=0.5", END_INLINE,
            "URL=http://media.kohls.com.edgesuite.net/is/image/kohls/1151935_Jazzy_Olive?wid=372&hei=372&op_sharpen=1", "HEADER=Accept-Language:en-us,en;q=0.5", END_INLINE,
            "URL=http://media.kohls.com.edgesuite.net/is/image/kohls/599746_Lime?wid=372&hei=372&op_sharpen=1", "HEADER=Accept-Language:en-us,en;q=0.5", END_INLINE,
            "URL=http://media.kohls.com.edgesuite.net/is/image/kohls/930874_Silver_Tin?wid=372&hei=372&op_sharpen=1", "HEADER=Accept-Language:en-us,en;q=0.5", END_INLINE,
            "URL=http://media.kohls.com.edgesuite.net/is/image/kohls/1125074?wid=372&hei=372&op_sharpen=1", "HEADER=Accept-Language:en-us,en;q=0.5", END_INLINE,
            "URL=http://media.kohls.com.edgesuite.net/is/image/kohls/975931?wid=372&hei=372&op_sharpen=1", "HEADER=Accept-Language:en-us,en;q=0.5", END_INLINE,
            "URL=http://media.kohls.com.edgesuite.net/is/image/kohls/320033_White?wid=372&hei=372&op_sharpen=1", "HEADER=Accept-Language:en-us,en;q=0.5", END_INLINE,
            "URL=http://media.kohls.com.edgesuite.net/is/image/kohls/990614_Black?wid=372&hei=372&op_sharpen=1", "HEADER=Accept-Language:en-us,en;q=0.5", END_INLINE,
            "URL=http://media.kohls.com.edgesuite.net/is/image/kohls/1152218_Pink?wid=372&hei=372&op_sharpen=1", "HEADER=Accept-Language:en-us,en;q=0.5", END_INLINE,
            "URL=http://media.kohls.com.edgesuite.net/is/image/kohls/1087493_Gray_Combo?wid=372&hei=372&op_sharpen=1", "HEADER=Accept-Language:en-us,en;q=0.5", END_INLINE,
            "URL=http://media.kohls.com.edgesuite.net/is/image/kohls/930822_Machine?wid=372&hei=372&op_sharpen=1", "HEADER=Accept-Language:en-us,en;q=0.5", END_INLINE,
            "URL=http://media.kohls.com.edgesuite.net/is/image/kohls/1239281?wid=372&hei=372&op_sharpen=1", "HEADER=Accept-Language:en-us,en;q=0.5", END_INLINE,
            "URL=http://media.kohls.com.edgesuite.net/is/image/kohls/278191?wid=372&hei=372&op_sharpen=1", "HEADER=Accept-Language:en-us,en;q=0.5", END_INLINE,
            "URL=http://media.kohls.com.edgesuite.net/is/image/kohls/1228927?wid=372&hei=372&op_sharpen=1", "HEADER=Accept-Language:en-us,en;q=0.5", END_INLINE,
            "URL=http://media.kohls.com.edgesuite.net/is/image/kohls/1179433?wid=372&hei=372&op_sharpen=1", "HEADER=Accept-Language:en-us,en;q=0.5", END_INLINE,
            "URL=http://media.kohls.com.edgesuite.net/is/image/kohls/1189173_Cool_Combo?wid=372&hei=372&op_sharpen=1", "HEADER=Accept-Language:en-us,en;q=0.5", END_INLINE,
            "URL=http://media.kohls.com.edgesuite.net/is/image/kohls/1002368?wid=372&hei=372&op_sharpen=1", "HEADER=Accept-Language:en-us,en;q=0.5", END_INLINE,
            "URL=http://media.kohls.com.edgesuite.net/is/image/kohls/935923_Tan_Ivory?wid=372&hei=372&op_sharpen=1", "HEADER=Accept-Language:en-us,en;q=0.5", END_INLINE,
            "URL=http://media.kohls.com.edgesuite.net/is/image/kohls/509010?wid=372&hei=372&op_sharpen=1", "HEADER=Accept-Language:en-us,en;q=0.5", END_INLINE,
            "URL=http://media.kohls.com.edgesuite.net/is/image/kohls/1016111?wid=372&hei=372&op_sharpen=1", "HEADER=Accept-Language:en-us,en;q=0.5", END_INLINE,
            "URL=http://media.kohls.com.edgesuite.net/is/image/kohls/1112381_Pink?wid=372&hei=372&op_sharpen=1", "HEADER=Accept-Language:en-us,en;q=0.5", END_INLINE,
            "URL=http://media.kohls.com.edgesuite.net/is/image/kohls/918925_Blue_Stripes?wid=372&hei=372&op_sharpen=1", "HEADER=Accept-Language:en-us,en;q=0.5", END_INLINE,
            "URL=http://media.kohls.com.edgesuite.net/is/image/kohls/1144567?wid=372&hei=372&op_sharpen=1", "HEADER=Accept-Language:en-us,en;q=0.5", END_INLINE,
            "URL=http://media.kohls.com.edgesuite.net/is/image/kohls/1233132?wid=372&hei=372&op_sharpen=1", "HEADER=Accept-Language:en-us,en;q=0.5", END_INLINE,
            "URL=http://media.kohls.com.edgesuite.net/is/image/kohls/1250349_Brown?wid=372&hei=372&op_sharpen=1", "HEADER=Accept-Language:en-us,en;q=0.5", END_INLINE,
            "URL=http://media.kohls.com.edgesuite.net/is/image/kohls/1224790_Tan_Marl?wid=372&hei=372&op_sharpen=1", "HEADER=Accept-Language:en-us,en;q=0.5", END_INLINE,
            "URL=http://kohls.tt.omtrdc.net/m2/kohls/mbox/standard?mboxHost=10.210.211.1&mboxSession=1361007378586-605601&mboxPC=1361007378586-605601.25_06&mboxPage=1361007419549-256997&screenHeight=768&screenWidth=1360&browserWidth=1360&browserHeight=588&browserTimeOffset=330&colorDepth=24&mboxCount=3&entity.searchTerm=socks&mbox=kohlscom_product_recommendations_search&mboxId=0&mboxTime=1361027249983&mboxURL=http%3A%2F%2F10.210.211.1%3A17010%2FkohlsStore%2Fsearch.jsp%3Fsearch%3Dsocks%26_requestid%3D4256&mboxReferrer=http%3A%2F%2F10.210.211.1%3A17010%2FkohlsStore%2F&mboxVersion=40", "HEADER=Accept-Language:en-us,en;q=0.5", END_INLINE,
            "URL=http://s.btstatic.com/tag.js", "HEADER=Accept-Language:en-us,en;q=0.5", END_INLINE,
            "URL=http://www.facebook.com/plugins/likebox.php?href=http%3A%2F%2Fwww.facebook.com%2Fkohls&width=315&colorscheme=light&connections=5&border_color=%23A5A9AC&stream=false&header=false&height=185", "HEADER=Accept-Language:en-us,en;q=0.5", END_INLINE,
            "URL=http://www-sf.kohlsecommerce.com/kohlsdocroot/omniture/s_code.js", "HEADER=Accept-Language:en-us,en;q=0.5", "COOKIE=JSESSIONID;mbox;s_sess;s_pers;", END_INLINE,
            "URL=http://www-sf.kohlsecommerce.com/kohlsStore/sitecatalyst/omniture_akamai.jsp", "HEADER=Accept-Language:en-us,en;q=0.5", "COOKIE=JSESSIONID;mbox;s_sess;s_pers;", END_INLINE,
            "URL=http://ww9.kohls.com/b/ss/kohlscomdev/1/H.25/s96509892236582?AQB=1&ndh=1&t=16%2F1%2F2013%2015%3A7%3A30%206%20-330&ns=kohls&pageName=search&g=http%3A%2F%2F10.210.211.1%3A17010%2FkohlsStore%2Fsearch.jsp%3Fsearch%3Dsocks%26_requestid%3D4256&r=http%3A%2F%2F10.210.211.1%3A17010%2FkohlsStore%2F&events=event1%2Cevent28&products=%3Bproductmerch2&c1=no%20taxnomy&c2=no%20taxnomy&c3=no%20taxnomy&v3=external&c4=search%20results%3A%20page%201&c5=socks&c7=no%20taxnomy&v8=socks&v9=homepage&c17=not%20logged%20in&v17=not%20logged%20in&c18=D%3Dv18&v18=03%3A37%20am&c19=D%3Dv19&v19=saturday&c20=D%3Dv20&v20=week%20end&c22=2013-02-16&v22=Kohl%27s&v23=browse&v24=browse&c50=Y75LRfTD5ZKw3Q56hJ9hRp9Q7nfGzP7jQ872C0cWnnQH48nxj4Jf!-513982135!1361007363683&s=1360x768&c=24&j=1.7&v=Y&k=Y&bw=1360&bh=588&p=Mozilla%20Default%20Plug-in%3BGoogle%20Update%3BAVG%20SiteSafety%20plugin%3BJava%20Deployment%20Toolkit%206.0.220.4%3BJava(TM)%20Platform%20SE%206%20U22%3BMindSpark%20Toolbar%20Platform%20Plugin%20Stub%3BVLC%20Web%20Plugin%3B&AQE=1", "HEADER=Accept-Language:en-us,en;q=0.5", "COOKIE=s_vi;", END_INLINE,
            "URL=http://www-sf.kohlsecommerce.com/kohlsdocroot/javascript/launch_window.js", "HEADER=Accept-Language:en-us,en;q=0.5", "COOKIE=JSESSIONID;mbox;s_sess;s_pers;", END_INLINE,
            "URL=http://static.ak.fbcdn.net/rsrc.php/v2/yO/r/ALeBTv6UlJb.js", "HEADER=Accept-Language:en-us,en;q=0.5", END_INLINE,
            "URL=http://profile.ak.fbcdn.net/hprofile-ak-ash4/195313_100003614762293_92366657_q.jpg", "HEADER=Accept-Language:en-us,en;q=0.5", END_INLINE,
            "URL=http://profile.ak.fbcdn.net/hprofile-ak-prn1/49836_100005262911206_1227102137_q.jpg", "HEADER=Accept-Language:en-us,en;q=0.5", END_INLINE,
            "URL=http://profile.ak.fbcdn.net/hprofile-ak-snc6/186462_100001750615998_651816343_q.jpg", "HEADER=Accept-Language:en-us,en;q=0.5", END_INLINE,
            "URL=http://www-sf.kohlsecommerce.com/kohlsdocroot/javascript/search.js", "HEADER=Accept-Language:en-us,en;q=0.5", "COOKIE=JSESSIONID;mbox;s_sess;s_pers;", END_INLINE,
            "URL=http://media.kohls.com.edgesuite.net/is/image/kohls/1002790?wid=243&hei=243&op_sharpen=1", "HEADER=Accept-Language:en-us,en;q=0.5", END_INLINE,
            "URL=http://media.kohls.com.edgesuite.net/is/image/kohls/933122?wid=243&hei=243&op_sharpen=1", "HEADER=Accept-Language:en-us,en;q=0.5", END_INLINE,
            "URL=http://media.kohls.com.edgesuite.net/is/image/kohls/1011185_Blue?wid=243&hei=243&op_sharpen=1", "HEADER=Accept-Language:en-us,en;q=0.5", END_INLINE,
            "URL=http://media.kohls.com.edgesuite.net/is/image/kohls/278182?wid=243&hei=243&op_sharpen=1", "HEADER=Accept-Language:en-us,en;q=0.5", END_INLINE,
            "URL=http://media.kohls.com.edgesuite.net/is/image/kohls/452155_Black_Assorted?wid=243&hei=243&op_sharpen=1", "HEADER=Accept-Language:en-us,en;q=0.5", END_INLINE,
            "URL=http://media.kohls.com.edgesuite.net/is/image/kohls/535148_Fall_Bright?wid=243&hei=243&op_sharpen=1", "HEADER=Accept-Language:en-us,en;q=0.5", END_INLINE,
            "URL=http://media.kohls.com.edgesuite.net/is/image/kohls/1037501_Pink?wid=243&hei=243&op_sharpen=1", "HEADER=Accept-Language:en-us,en;q=0.5", END_INLINE,
            "URL=http://media.kohls.com.edgesuite.net/is/image/kohls/1036067?wid=243&hei=243&op_sharpen=1", "HEADER=Accept-Language:en-us,en;q=0.5", END_INLINE,
            "URL=http://media.kohls.com.edgesuite.net/is/image/kohls/1169348_Black?wid=243&hei=243&op_sharpen=1", "HEADER=Accept-Language:en-us,en;q=0.5", END_INLINE,
            "URL=http://media.kohls.com.edgesuite.net/is/image/kohls/1239280?wid=243&hei=243&op_sharpen=1", "HEADER=Accept-Language:en-us,en;q=0.5", END_INLINE,
            "URL=http://media.kohls.com.edgesuite.net/is/image/kohls/278183?wid=243&hei=243&op_sharpen=1", "HEADER=Accept-Language:en-us,en;q=0.5", END_INLINE,
            "URL=http://media.kohls.com.edgesuite.net/is/image/kohls/320893_Black?wid=243&hei=243&op_sharpen=1", "HEADER=Accept-Language:en-us,en;q=0.5", END_INLINE,
            "URL=http://media.kohls.com.edgesuite.net/is/image/kohls/1011131_Ivory_Coral?wid=243&hei=243&op_sharpen=1", "HEADER=Accept-Language:en-us,en;q=0.5", END_INLINE,
            "URL=http://media.kohls.com.edgesuite.net/is/image/kohls/927692_Bootstrap?wid=243&hei=243&op_sharpen=1", "HEADER=Accept-Language:en-us,en;q=0.5", END_INLINE,
            "URL=http://media.kohls.com.edgesuite.net/is/image/kohls/1128523_Black?wid=243&hei=243&op_sharpen=1", "HEADER=Accept-Language:en-us,en;q=0.5", END_INLINE,
            "URL=http://media.kohls.com.edgesuite.net/is/image/kohls/404181?wid=243&hei=243&op_sharpen=1", "HEADER=Accept-Language:en-us,en;q=0.5", END_INLINE,
            "URL=http://media.kohls.com.edgesuite.net/is/image/kohls/1152208_Black?wid=243&hei=243&op_sharpen=1", "HEADER=Accept-Language:en-us,en;q=0.5", END_INLINE,
            "URL=http://media.kohls.com.edgesuite.net/is/image/kohls/1002801?wid=243&hei=243&op_sharpen=1", "HEADER=Accept-Language:en-us,en;q=0.5", END_INLINE,
            "URL=http://media.kohls.com.edgesuite.net/is/image/kohls/986411_Black?wid=243&hei=243&op_sharpen=1", "HEADER=Accept-Language:en-us,en;q=0.5", END_INLINE,
            "URL=http://media.kohls.com.edgesuite.net/is/image/kohls/1153757_Ivory_Combo?wid=243&hei=243&op_sharpen=1", "HEADER=Accept-Language:en-us,en;q=0.5", END_INLINE,
            "URL=http://media.kohls.com.edgesuite.net/is/image/kohls/1122068?wid=243&hei=243&op_sharpen=1", "HEADER=Accept-Language:en-us,en;q=0.5", END_INLINE,
            "URL=http://media.kohls.com.edgesuite.net/is/image/kohls/495376?wid=243&hei=243&op_sharpen=1", "HEADER=Accept-Language:en-us,en;q=0.5", END_INLINE,
            "URL=http://media.kohls.com.edgesuite.net/is/image/kohls/157823_Jester_Red?wid=243&hei=243&op_sharpen=1", "HEADER=Accept-Language:en-us,en;q=0.5", END_INLINE,
            "URL=http://media.kohls.com.edgesuite.net/is/image/kohls/914593_Nude?wid=243&hei=243&op_sharpen=1", "HEADER=Accept-Language:en-us,en;q=0.5", END_INLINE,
            "URL=http://media.kohls.com.edgesuite.net/is/image/kohls/1194081?wid=243&hei=243&op_sharpen=1", "HEADER=Accept-Language:en-us,en;q=0.5", END_INLINE,
            "URL=http://media.kohls.com.edgesuite.net/is/image/kohls/320366_Khaki?wid=243&hei=243&op_sharpen=1", "HEADER=Accept-Language:en-us,en;q=0.5", END_INLINE,
            "URL=http://media.kohls.com.edgesuite.net/is/image/kohls/1152795_Black?wid=243&hei=243&op_sharpen=1", "HEADER=Accept-Language:en-us,en;q=0.5", END_INLINE,
            "URL=http://media.kohls.com.edgesuite.net/is/image/kohls/883022_Black?wid=243&hei=243&op_sharpen=1", "HEADER=Accept-Language:en-us,en;q=0.5", END_INLINE,
            "URL=http://media.kohls.com.edgesuite.net/is/image/kohls/320220_White?wid=243&hei=243&op_sharpen=1", "HEADER=Accept-Language:en-us,en;q=0.5", END_INLINE,
            "URL=http://media.kohls.com.edgesuite.net/is/image/kohls/1194094?wid=243&hei=243&op_sharpen=1", "HEADER=Accept-Language:en-us,en;q=0.5", END_INLINE,
            "URL=http://media.kohls.com.edgesuite.net/is/image/kohls/696687_White?wid=243&hei=243&op_sharpen=1", "HEADER=Accept-Language:en-us,en;q=0.5", END_INLINE,
            "URL=http://media.kohls.com.edgesuite.net/is/image/kohls/1153692_Purple?wid=243&hei=243&op_sharpen=1", "HEADER=Accept-Language:en-us,en;q=0.5", END_INLINE,
            "URL=http://media.kohls.com.edgesuite.net/is/image/kohls/1214547?wid=243&hei=243&op_sharpen=1", "HEADER=Accept-Language:en-us,en;q=0.5", END_INLINE,
            "URL=http://media.kohls.com.edgesuite.net/is/image/kohls/528982_White?wid=243&hei=243&op_sharpen=1", "HEADER=Accept-Language:en-us,en;q=0.5", END_INLINE,
            "URL=http://media.kohls.com.edgesuite.net/is/image/kohls/930899_Drizzle?wid=243&hei=243&op_sharpen=1", "HEADER=Accept-Language:en-us,en;q=0.5", END_INLINE,
            "URL=http://media.kohls.com.edgesuite.net/is/image/kohls/778867_Black?wid=243&hei=243&op_sharpen=1", "HEADER=Accept-Language:en-us,en;q=0.5", END_INLINE,
            "URL=http://media.kohls.com.edgesuite.net/is/image/kohls/1119624?wid=243&hei=243&op_sharpen=1", "HEADER=Accept-Language:en-us,en;q=0.5", END_INLINE,
            "URL=http://media.kohls.com.edgesuite.net/is/image/kohls/1234052_Brick?wid=243&hei=243&op_sharpen=1", "HEADER=Accept-Language:en-us,en;q=0.5", END_INLINE,
            "URL=http://media.kohls.com.edgesuite.net/is/image/kohls/1038291_Stunning_Turquoise?wid=243&hei=243&op_sharpen=1", "HEADER=Accept-Language:en-us,en;q=0.5", END_INLINE,
            "URL=http://media.kohls.com.edgesuite.net/is/image/kohls/1204056?wid=243&hei=243&op_sharpen=1", "HEADER=Accept-Language:en-us,en;q=0.5", END_INLINE,
            "URL=http://media.kohls.com.edgesuite.net/is/image/kohls/1177540?wid=243&hei=243&op_sharpen=1", "HEADER=Accept-Language:en-us,en;q=0.5", END_INLINE,
            "URL=http://media.kohls.com.edgesuite.net/is/image/kohls/1228926?wid=243&hei=243&op_sharpen=1", "HEADER=Accept-Language:en-us,en;q=0.5", END_INLINE,
            "URL=http://media.kohls.com.edgesuite.net/is/image/kohls/1152200_Black?wid=243&hei=243&op_sharpen=1", "HEADER=Accept-Language:en-us,en;q=0.5", END_INLINE,
            "URL=http://media.kohls.com.edgesuite.net/is/image/kohls/1178496?wid=243&hei=243&op_sharpen=1", "HEADER=Accept-Language:en-us,en;q=0.5", END_INLINE,
            "URL=http://media.kohls.com.edgesuite.net/is/image/kohls/1062377_Slack?wid=243&hei=243&op_sharpen=1", "HEADER=Accept-Language:en-us,en;q=0.5", END_INLINE,
            "URL=http://media.kohls.com.edgesuite.net/is/image/kohls/1002375?wid=243&hei=243&op_sharpen=1", "HEADER=Accept-Language:en-us,en;q=0.5", END_INLINE,
            "URL=http://media.kohls.com.edgesuite.net/is/image/kohls/1151102?wid=243&hei=243&op_sharpen=1", "HEADER=Accept-Language:en-us,en;q=0.5", END_INLINE,
            "URL=http://media.kohls.com.edgesuite.net/is/image/kohls/1190680_Navy?wid=243&hei=243&op_sharpen=1", "HEADER=Accept-Language:en-us,en;q=0.5", END_INLINE,
            "URL=http://media.kohls.com.edgesuite.net/is/image/kohls/1104697_Red?wid=243&hei=243&op_sharpen=1", "HEADER=Accept-Language:en-us,en;q=0.5", END_INLINE,
            "URL=http://media.kohls.com.edgesuite.net/is/image/kohls/1203530_Rich_Red?wid=243&hei=243&op_sharpen=1", "HEADER=Accept-Language:en-us,en;q=0.5", END_INLINE,
            "URL=http://media.kohls.com.edgesuite.net/is/image/kohls/1011155_Brown?wid=243&hei=243&op_sharpen=1", "HEADER=Accept-Language:en-us,en;q=0.5", END_INLINE,
            "URL=http://media.kohls.com.edgesuite.net/is/image/kohls/1229015?wid=243&hei=243&op_sharpen=1", "HEADER=Accept-Language:en-us,en;q=0.5", END_INLINE,
            "URL=http://media.kohls.com.edgesuite.net/is/image/kohls/177030_Barely_Black?wid=243&hei=243&op_sharpen=1", "HEADER=Accept-Language:en-us,en;q=0.5", END_INLINE,
            "URL=http://media.kohls.com.edgesuite.net/is/image/kohls/1169303_Brown?wid=243&hei=243&op_sharpen=1", "HEADER=Accept-Language:en-us,en;q=0.5", END_INLINE,
            "URL=http://media.kohls.com.edgesuite.net/is/image/kohls/914596_Black?wid=243&hei=243&op_sharpen=1", "HEADER=Accept-Language:en-us,en;q=0.5", END_INLINE,
            "URL=http://media.kohls.com.edgesuite.net/is/image/kohls/319407_White?wid=243&hei=243&op_sharpen=1", "HEADER=Accept-Language:en-us,en;q=0.5", END_INLINE,
            "URL=http://media.kohls.com.edgesuite.net/is/image/kohls/1228151?wid=243&hei=243&op_sharpen=1", "HEADER=Accept-Language:en-us,en;q=0.5", END_INLINE,
            "URL=http://media.kohls.com.edgesuite.net/is/image/kohls/1152791_Taupe?wid=243&hei=243&op_sharpen=1", "HEADER=Accept-Language:en-us,en;q=0.5", END_INLINE,
            "URL=http://media.kohls.com.edgesuite.net/is/image/kohls/320223?wid=243&hei=243&op_sharpen=1", "HEADER=Accept-Language:en-us,en;q=0.5", END_INLINE,
            "URL=http://media.kohls.com.edgesuite.net/is/image/kohls/1002775?wid=243&hei=243&op_sharpen=1", "HEADER=Accept-Language:en-us,en;q=0.5", END_INLINE,
            "URL=http://media.kohls.com.edgesuite.net/is/image/kohls/1169291_Black?wid=243&hei=243&op_sharpen=1", "HEADER=Accept-Language:en-us,en;q=0.5", END_INLINE,
            "URL=http://media.kohls.com.edgesuite.net/is/image/kohls/226002_Black_Gray?wid=243&hei=243&op_sharpen=1", "HEADER=Accept-Language:en-us,en;q=0.5", END_INLINE,
            "URL=http://media.kohls.com.edgesuite.net/is/image/kohls/1034711_Gray?wid=243&hei=243&op_sharpen=1", "HEADER=Accept-Language:en-us,en;q=0.5", END_INLINE,
            "URL=http://media.kohls.com.edgesuite.net/is/image/kohls/1052633_Green?wid=243&hei=243&op_sharpen=1", "HEADER=Accept-Language:en-us,en;q=0.5", END_INLINE,
            "URL=http://media.kohls.com.edgesuite.net/is/image/kohls/914938_Black?wid=243&hei=243&op_sharpen=1", "HEADER=Accept-Language:en-us,en;q=0.5", END_INLINE,
            "URL=http://media.kohls.com.edgesuite.net/is/image/kohls/1152107_Black?wid=243&hei=243&op_sharpen=1", "HEADER=Accept-Language:en-us,en;q=0.5", END_INLINE,
            "URL=http://media.kohls.com.edgesuite.net/is/image/kohls/1037550?wid=243&hei=243&op_sharpen=1", "HEADER=Accept-Language:en-us,en;q=0.5", END_INLINE,
            "URL=http://media.kohls.com.edgesuite.net/is/image/kohls/1116467?wid=243&hei=243&op_sharpen=1", "HEADER=Accept-Language:en-us,en;q=0.5", END_INLINE,
            "URL=http://media.kohls.com.edgesuite.net/is/image/kohls/495279?wid=243&hei=243&op_sharpen=1", "HEADER=Accept-Language:en-us,en;q=0.5", END_INLINE,
            "URL=http://media.kohls.com.edgesuite.net/is/image/kohls/1104837_Green?wid=243&hei=243&op_sharpen=1", "HEADER=Accept-Language:en-us,en;q=0.5", END_INLINE,
            "URL=http://media.kohls.com.edgesuite.net/is/image/kohls/676398_Black_White?wid=243&hei=243&op_sharpen=1", "HEADER=Accept-Language:en-us,en;q=0.5", END_INLINE,
            "URL=http://media.kohls.com.edgesuite.net/is/image/kohls/1151935_Jazzy_Olive?wid=243&hei=243&op_sharpen=1", "HEADER=Accept-Language:en-us,en;q=0.5", END_INLINE,
            "URL=http://media.kohls.com.edgesuite.net/is/image/kohls/599746_Lime?wid=243&hei=243&op_sharpen=1", "HEADER=Accept-Language:en-us,en;q=0.5", END_INLINE,
            "URL=http://media.kohls.com.edgesuite.net/is/image/kohls/930874_Silver_Tin?wid=243&hei=243&op_sharpen=1", "HEADER=Accept-Language:en-us,en;q=0.5", END_INLINE,
            "URL=http://media.kohls.com.edgesuite.net/is/image/kohls/1125074?wid=243&hei=243&op_sharpen=1", "HEADER=Accept-Language:en-us,en;q=0.5", END_INLINE,
            "URL=http://media.kohls.com.edgesuite.net/is/image/kohls/975931?wid=243&hei=243&op_sharpen=1", "HEADER=Accept-Language:en-us,en;q=0.5", END_INLINE,
            "URL=http://media.kohls.com.edgesuite.net/is/image/kohls/320033_White?wid=243&hei=243&op_sharpen=1", "HEADER=Accept-Language:en-us,en;q=0.5", END_INLINE,
            "URL=http://media.kohls.com.edgesuite.net/is/image/kohls/990614_Black?wid=243&hei=243&op_sharpen=1", "HEADER=Accept-Language:en-us,en;q=0.5", END_INLINE,
            "URL=http://media.kohls.com.edgesuite.net/is/image/kohls/1152218_Pink?wid=243&hei=243&op_sharpen=1", "HEADER=Accept-Language:en-us,en;q=0.5", END_INLINE,
            "URL=http://media.kohls.com.edgesuite.net/is/image/kohls/1087493_Gray_Combo?wid=243&hei=243&op_sharpen=1", "HEADER=Accept-Language:en-us,en;q=0.5", END_INLINE,
            "URL=http://media.kohls.com.edgesuite.net/is/image/kohls/930822_Machine?wid=243&hei=243&op_sharpen=1", "HEADER=Accept-Language:en-us,en;q=0.5", END_INLINE,
            "URL=http://media.kohls.com.edgesuite.net/is/image/kohls/1239281?wid=243&hei=243&op_sharpen=1", "HEADER=Accept-Language:en-us,en;q=0.5", END_INLINE,
            "URL=http://media.kohls.com.edgesuite.net/is/image/kohls/278191?wid=243&hei=243&op_sharpen=1", "HEADER=Accept-Language:en-us,en;q=0.5", END_INLINE,
            "URL=http://media.kohls.com.edgesuite.net/is/image/kohls/1228927?wid=243&hei=243&op_sharpen=1", "HEADER=Accept-Language:en-us,en;q=0.5", END_INLINE,
            "URL=http://media.kohls.com.edgesuite.net/is/image/kohls/1179433?wid=243&hei=243&op_sharpen=1", "HEADER=Accept-Language:en-us,en;q=0.5", END_INLINE,
            "URL=http://media.kohls.com.edgesuite.net/is/image/kohls/1189173_Cool_Combo?wid=243&hei=243&op_sharpen=1", "HEADER=Accept-Language:en-us,en;q=0.5", END_INLINE,
            "URL=http://media.kohls.com.edgesuite.net/is/image/kohls/1002368?wid=243&hei=243&op_sharpen=1", "HEADER=Accept-Language:en-us,en;q=0.5", END_INLINE,
            "URL=http://media.kohls.com.edgesuite.net/is/image/kohls/935923_Tan_Ivory?wid=243&hei=243&op_sharpen=1", "HEADER=Accept-Language:en-us,en;q=0.5", END_INLINE,
            "URL=http://media.kohls.com.edgesuite.net/is/image/kohls/509010?wid=243&hei=243&op_sharpen=1", "HEADER=Accept-Language:en-us,en;q=0.5", END_INLINE,
            "URL=http://media.kohls.com.edgesuite.net/is/image/kohls/1016111?wid=243&hei=243&op_sharpen=1", "HEADER=Accept-Language:en-us,en;q=0.5", END_INLINE,
            "URL=http://media.kohls.com.edgesuite.net/is/image/kohls/1112381_Pink?wid=243&hei=243&op_sharpen=1", "HEADER=Accept-Language:en-us,en;q=0.5", END_INLINE,
            "URL=http://media.kohls.com.edgesuite.net/is/image/kohls/918925_Blue_Stripes?wid=243&hei=243&op_sharpen=1", "HEADER=Accept-Language:en-us,en;q=0.5", END_INLINE,
            "URL=http://media.kohls.com.edgesuite.net/is/image/kohls/1144567?wid=243&hei=243&op_sharpen=1", "HEADER=Accept-Language:en-us,en;q=0.5", END_INLINE,
            "URL=http://media.kohls.com.edgesuite.net/is/image/kohls/1233132?wid=243&hei=243&op_sharpen=1", "HEADER=Accept-Language:en-us,en;q=0.5", END_INLINE,
            "URL=http://media.kohls.com.edgesuite.net/is/image/kohls/1250349_Brown?wid=243&hei=243&op_sharpen=1", "HEADER=Accept-Language:en-us,en;q=0.5", END_INLINE,
            "URL=http://media.kohls.com.edgesuite.net/is/image/kohls/1224790_Tan_Marl?wid=243&hei=243&op_sharpen=1", "HEADER=Accept-Language:en-us,en;q=0.5", END_INLINE
    );
    ns_end_transaction("SearchKeyword", NS_AUTO_STATUS);
    ns_page_think_time(0);
    
    /*
    ns_start_transaction("SelectProductPage");
    ns_web_url ("SelectProductPage",
        //"URL=http://www-sf.kohlsecommerce.com/product/prd-384796/vtech-explore-learn-helicopter.jsp",
        "URL=http://www-sf.kohlsecommerce.com/{SearchKwPrdPageFP}",
        //"URL=http://www-sf.kohlsecommerce.com/product/prd-731799/melissa-doug-bug-jug-fill-spill-set.jsp",
        //"URL=http://www-sf.kohlsecommerce.com/product/{ProductSelectUrlSP}",
        "HEADER=Accept-Language:en-us,en;q=0.5",
        "COOKIE=JSESSIONID;mbox;s_sess;s_pers;cookieSetting;fsr.s;",
        "PreSnapshot=webpage_1363333210798.png",
        "Snapshot=webpage_1363333564062.png",
        INLINE_URLS,
            "URL=http://www-sf.kohlsecommerce.com/media/foresee/foresee-alive.js", "HEADER=Accept-Language:en-us,en;q=0.5", "COOKIE=JSESSIONID;mbox;s_sess;s_pers;cookieSetting;fsr.s;", END_INLINE,
            "URL=http://www-sf.kohlsecommerce.com/media/javascript/jquery-1.7.2.min.js", "HEADER=Accept-Language:en-us,en;q=0.5", "COOKIE=JSESSIONID;mbox;s_sess;s_pers;cookieSetting;fsr.s;", END_INLINE,
            "URL=http://www-sf.kohlsecommerce.com/media/javascript/global.js", "HEADER=Accept-Language:en-us,en;q=0.5", "COOKIE=JSESSIONID;mbox;s_sess;s_pers;cookieSetting;fsr.s;", END_INLINE,
            "URL=http://www-sf.kohlsecommerce.com/media/javascript/myaccount.js", "HEADER=Accept-Language:en-us,en;q=0.5", "COOKIE=JSESSIONID;mbox;s_sess;s_pers;cookieSetting;fsr.s;", END_INLINE,
            "URL=http://www-sf.kohlsecommerce.com/media/javascript/jquery.validate_product.js", "HEADER=Accept-Language:en-us,en;q=0.5", "COOKIE=JSESSIONID;mbox;s_sess;s_pers;cookieSetting;fsr.s;", END_INLINE,
            "URL=http://www-sf.kohlsecommerce.com/media/javascript/UI_validation.js", "HEADER=Accept-Language:en-us,en;q=0.5", "COOKIE=JSESSIONID;mbox;s_sess;s_pers;cookieSetting;fsr.s;", END_INLINE,
            "URL=http://www-sf.kohlsecommerce.com/media/javascript/modal_validation.js", "HEADER=Accept-Language:en-us,en;q=0.5", "COOKIE=JSESSIONID;mbox;s_sess;s_pers;cookieSetting;fsr.s;", END_INLINE,
            "URL=http://www-sf.kohlsecommerce.com/media/javascript/cart.js", "HEADER=Accept-Language:en-us,en;q=0.5", "COOKIE=JSESSIONID;mbox;s_sess;s_pers;cookieSetting;fsr.s;", END_INLINE,
            "URL=http://www-sf.kohlsecommerce.com/media/fancybox/jquery.fancybox-1.3.4.pack.js", "HEADER=Accept-Language:en-us,en;q=0.5", "COOKIE=JSESSIONID;mbox;s_sess;s_pers;cookieSetting;fsr.s;", END_INLINE,
            "URL=http://www-sf.kohlsecommerce.com/media/javascript/custom.js", "HEADER=Accept-Language:en-us,en;q=0.5", "COOKIE=JSESSIONID;mbox;s_sess;s_pers;cookieSetting;fsr.s;", END_INLINE,
            "URL=http://www-sf.kohlsecommerce.com/media/javascript/jquery.numeric.js", "HEADER=Accept-Language:en-us,en;q=0.5", "COOKIE=JSESSIONID;mbox;s_sess;s_pers;cookieSetting;fsr.s;", END_INLINE,
            "URL=http://www-sf.kohlsecommerce.com/media/javascript/video.js", "HEADER=Accept-Language:en-us,en;q=0.5", "COOKIE=JSESSIONID;mbox;s_sess;s_pers;cookieSetting;fsr.s;", END_INLINE,
            "URL=http://www-sf.kohlsecommerce.com/media/javascript/myaccount_custom.js", "HEADER=Accept-Language:en-us,en;q=0.5", "COOKIE=JSESSIONID;mbox;s_sess;s_pers;cookieSetting;fsr.s;", END_INLINE,
            "URL=http://d3t1dw6evd1rv7.cloudfront.net/kregistry/wishlist.js", "HEADER=Accept-Language:en-us,en;q=0.5", END_INLINE,
            "URL=http://d3t1dw6evd1rv7.cloudfront.net/kregistry/giftguide.js", "HEADER=Accept-Language:en-us,en;q=0.5", END_INLINE,
            "URL=http://d3t1dw6evd1rv7.cloudfront.net/kregistry/registry.js", "HEADER=Accept-Language:en-us,en;q=0.5", END_INLINE,
            "URL=http://www-sf.kohlsecommerce.com/media/javascript/kohls_v1_m56577569839297458.js", "HEADER=Accept-Language:en-us,en;q=0.5", "COOKIE=JSESSIONID;mbox;s_sess;s_pers;cookieSetting;fsr.s;", END_INLINE,
            "URL=http://www-sf.kohlsecommerce.com/media/javascript/skava-pdp.js", "HEADER=Accept-Language:en-us,en;q=0.5", "COOKIE=JSESSIONID;mbox;s_sess;s_pers;cookieSetting;fsr.s;", END_INLINE,
            "URL=http://www-sf.kohlsecommerce.com/media/javascript/jquery.nicescroll.min.js", "HEADER=Accept-Language:en-us,en;q=0.5", "COOKIE=JSESSIONID;mbox;s_sess;s_pers;cookieSetting;fsr.s;", END_INLINE,
            "URL=http://www-sf.kohlsecommerce.com/media/javascript/scroll.js", "HEADER=Accept-Language:en-us,en;q=0.5", "COOKIE=JSESSIONID;mbox;s_sess;s_pers;cookieSetting;fsr.s;", END_INLINE,
            "URL=http://www-sf.kohlsecommerce.com/media/javascript/jcarousellite.min.js", "HEADER=Accept-Language:en-us,en;q=0.5", "COOKIE=JSESSIONID;mbox;s_sess;s_pers;cookieSetting;fsr.s;", END_INLINE,
            "URL=http://www-sf.kohlsecommerce.com/media/javascript/carousel_inline.js", "HEADER=Accept-Language:en-us,en;q=0.5", "COOKIE=JSESSIONID;mbox;s_sess;s_pers;cookieSetting;fsr.s;", END_INLINE,
            "URL=http://www-sf.kohlsecommerce.com/media/javascript/product.js", "HEADER=Accept-Language:en-us,en;q=0.5", "COOKIE=JSESSIONID;mbox;s_sess;s_pers;cookieSetting;fsr.s;", END_INLINE,
            "URL=http://www-sf.kohlsecommerce.com/media/javascript/kohls_v1_m56577569836982750.js", "HEADER=Accept-Language:en-us,en;q=0.5", "COOKIE=JSESSIONID;mbox;s_sess;s_pers;cookieSetting;fsr.s;", END_INLINE,
            "URL=http://www-sf.kohlsecommerce.com/media/javascript/jcarousellite_1.0.1.min.js", "HEADER=Accept-Language:en-us,en;q=0.5", "COOKIE=JSESSIONID;mbox;s_sess;s_pers;cookieSetting;fsr.s;", END_INLINE,
            "URL=http://www-sf.kohlsecommerce.com/media/javascript/cloud-zoom.1.0.2.min.js", "HEADER=Accept-Language:en-us,en;q=0.5", "COOKIE=JSESSIONID;mbox;s_sess;s_pers;cookieSetting;fsr.s;", END_INLINE,
            "URL=http://www-sf.kohlsecommerce.com/media/javascript/jquery.validate_tell.js", "HEADER=Accept-Language:en-us,en;q=0.5", "COOKIE=JSESSIONID;mbox;s_sess;s_pers;cookieSetting;fsr.s;", END_INLINE,
            "URL=http://www-sf.kohlsecommerce.com/media/fancybox/jquery.easing-1.3.pack.js", "HEADER=Accept-Language:en-us,en;q=0.5", "COOKIE=JSESSIONID;mbox;s_sess;s_pers;cookieSetting;fsr.s;", END_INLINE,
            "URL=http://www-sf.kohlsecommerce.com/media/fancybox/jquery.fancybox-1.3.4.js", "HEADER=Accept-Language:en-us,en;q=0.5", "COOKIE=JSESSIONID;mbox;s_sess;s_pers;cookieSetting;fsr.s;", END_INLINE,
            "URL=http://www-sf.kohlsecommerce.com/media/fancybox/jquery.mousewheel-3.0.4.pack.js", "HEADER=Accept-Language:en-us,en;q=0.5", "COOKIE=JSESSIONID;mbox;s_sess;s_pers;cookieSetting;fsr.s;", END_INLINE,
            "URL=http://www-sf.kohlsecommerce.com/media/javascript/customPDP.js", "HEADER=Accept-Language:en-us,en;q=0.5", "COOKIE=JSESSIONID;mbox;s_sess;s_pers;cookieSetting;fsr.s;", END_INLINE,
            "URL=http://www-sf.kohlsecommerce.com/media/omniture/mbox.js", "HEADER=Accept-Language:en-us,en;q=0.5", "COOKIE=JSESSIONID;mbox;s_sess;s_pers;cookieSetting;fsr.s;", END_INLINE,
            "URL=http://www-sf.kohlsecommerce.com/media/css/cloud-zoom.css", END_INLINE,
            "URL=http://www-sf.kohlsecommerce.com/media/javascript/jquery.nicescroll.min.js", "HEADER=Accept-Language:en-us,en;q=0.5", "COOKIE=JSESSIONID;mbox;s_sess;s_pers;cookieSetting;fsr.s;fsr.a;", END_INLINE,
            "URL=http://www-sf.kohlsecommerce.com/media/javascript/jcarousellite_1.0.1.min.js", "HEADER=Accept-Language:en-us,en;q=0.5", "COOKIE=JSESSIONID;mbox;s_sess;s_pers;cookieSetting;fsr.s;fsr.a;", END_INLINE,
            "URL=http://www-sf.kohlsecommerce.com/media/javascript/myaccount_custom.js", "HEADER=Accept-Language:en-us,en;q=0.5", "COOKIE=JSESSIONID;mbox;s_sess;s_pers;cookieSetting;fsr.s;fsr.a;", END_INLINE,
            "URL=http://www-sf.kohlsecommerce.com/media/fancybox/jquery.easing-1.3.pack.js", "HEADER=Accept-Language:en-us,en;q=0.5", "COOKIE=JSESSIONID;mbox;s_sess;s_pers;cookieSetting;fsr.s;fsr.a;", END_INLINE,
            "URL=http://www-sf.kohlsecommerce.com/media/fancybox/jquery.fancybox-1.3.4.pack.js", "HEADER=Accept-Language:en-us,en;q=0.5", "COOKIE=JSESSIONID;mbox;s_sess;s_pers;cookieSetting;fsr.s;fsr.a;", END_INLINE,
            "URL=http://kohls.tt.omtrdc.net/m2/kohls/mbox/standard?mboxHost=10.210.205.1&mboxSession=1363333109171-172636&mboxPC=1363333109171-172636.17_15&mboxPage=1363333216325-596327&screenHeight=768&screenWidth=1366&browserWidth=1366&browserHeight=588&browserTimeOffset=330&colorDepth=24&mboxCount=1&mbox=kohlscom_equity_bar&mboxId=0&mboxTime=1363353016341&mboxURL=http%3A%2F%2F10.210.205.1%3A17010%2Fproduct%2Fprd-384796%2Fvtech-explore-learn-helicopter.jsp&mboxReferrer=http%3A%2F%2F10.210.205.1%3A17010%2Fsearch.jsp%3Fsearch%3Dhelicopter%26_requestid%3D857&mboxVersion=40", "HEADER=Accept-Language:en-us,en;q=0.5", END_INLINE,
            "URL=http://www-sf.kohlsecommerce.com/media/javascript/sku_pdp.js", "HEADER=Accept-Language:en-us,en;q=0.5", "COOKIE=JSESSIONID;mbox;s_sess;s_pers;cookieSetting;fsr.s;fsr.a;", END_INLINE,
            "URL=http://kohls.tt.omtrdc.net/m2/kohls/mbox/standard?mboxHost=10.210.205.1&mboxSession=1363333109171-172636&mboxPC=1363333109171-172636.17_15&mboxPage=1363333216325-596327&screenHeight=768&screenWidth=1366&browserWidth=1366&browserHeight=588&browserTimeOffset=330&colorDepth=24&mboxCount=2&mbox=kohlscom_product384796_feature&mboxId=0&mboxTime=1363353026436&mboxURL=http%3A%2F%2F10.210.205.1%3A17010%2Fproduct%2Fprd-384796%2Fvtech-explore-learn-helicopter.jsp&mboxReferrer=http%3A%2F%2F10.210.205.1%3A17010%2Fsearch.jsp%3Fsearch%3Dhelicopter%26_requestid%3D857&mboxVersion=40", "HEADER=Accept-Language:en-us,en;q=0.5", END_INLINE,
            "URL=http://media.kohls.com.edgesuite.net/is/image/kohls/384796_Multi/None?wid=400&hei=400&op_sharpen=1", "HEADER=Accept-Language:en-us,en;q=0.5", END_INLINE,
            "URL=http://media.kohls.com.edgesuite.net/is/image/kohls/384796?wid=60&hei=60&op_sharpen=1", "HEADER=Accept-Language:en-us,en;q=0.5", END_INLINE,
            "URL=http://www.facebook.com/plugins/like.php?href=http://www-sf.kohlsecommerce.com/product/prd-384796/vtech-explore-learn-helicopter.jsp&ref=product_page&send=false&layout=button_count&width=200&show_faces=true&action=like&colorscheme=light&font=verdana&height=25", "HEADER=Accept-Language:en-us,en;q=0.5", END_INLINE,
            "URL=http://www-sf.kohlsecommerce.com/media/images/email_v1_m56577569832236561.gif", "HEADER=Accept-Language:en-us,en;q=0.5", "COOKIE=JSESSIONID;mbox;s_sess;s_pers;cookieSetting;fsr.s;fsr.a;", END_INLINE,
            "URL=http://media.kohls.com.edgesuite.net/is/image/kohls/676324_Multi/None?wid=75&hei=75&op_sharpen=1", "HEADER=Accept-Language:en-us,en;q=0.5", END_INLINE,
            "URL=http://media.kohls.com.edgesuite.net/is/image/kohls/864116_Multi/None?wid=75&hei=75&op_sharpen=1", "HEADER=Accept-Language:en-us,en;q=0.5", END_INLINE,
            "URL=http://media.kohls.com.edgesuite.net/is/image/kohls/901955_Multi/None?wid=75&hei=75&op_sharpen=1", "HEADER=Accept-Language:en-us,en;q=0.5", END_INLINE,
            "URL=http://s.btstatic.com/tag.js", "HEADER=Accept-Language:en-us,en;q=0.5", END_INLINE,
            "URL=http://www-sf.kohlsecommerce.com/media/images/shadow-helper.png", "HEADER=Accept-Language:en-us,en;q=0.5", "COOKIE=JSESSIONID;mbox;s_sess;s_pers;cookieSetting;fsr.s;fsr.a;", END_INLINE,
            "URL=http://www.facebook.com/plugins/likebox.php?href=http%3A%2F%2Fwww.facebook.com%2Fkohls&width=315&colorscheme=light&connections=5&border_color=%23A5A9AC&stream=false&header=false&height=185", "HEADER=Accept-Language:en-us,en;q=0.5", END_INLINE,
            "URL=http://www-sf.kohlsecommerce.com/media/omniture/s_code.js", "HEADER=Accept-Language:en-us,en;q=0.5", "COOKIE=JSESSIONID;mbox;s_sess;s_pers;cookieSetting;fsr.s;fsr.a;", END_INLINE,
            "URL=http://ww9.kohls.com/b/ss/kohlscomdev/1/H.25/s46293540921072?AQB=1&ndh=1&t=15%2F2%2F2013%2013%3A10%3A27%205%20-330&ns=kohls&pageName=pdp%3A(384796)%20vtech%20explore%20and%20learn%20helicopter&g=http%3A%2F%2F10.210.205.1%3A17010%2Fproduct%2Fprd-384796%2Fvtech-explore-learn-helicopter.jsp&r=http%3A%2F%2F10.210.205.1%3A17010%2Fsearch.jsp%3Fsearch%3Dhelicopter%26_requestid%3D857&events=prodView%2Cevent3&products=%3B384796%3B%3B%3B%3Bevar16%3Dn&v3=external&c4=product%20detail%20page&v8=non-search&v9=search%20results%3A%20page%20%201&c17=not%20logged%20in&v17=not%20logged%20in&c18=D%3Dv18&v18=02%3A40%20am&c19=D%3Dv19&v19=friday&c20=D%3Dv20&v20=week%20day&c22=2013-03-15&v22=Kohl%27s&c50=FRDGRCPHGV03ykh0zl9QnH2p7MNhQdWFr0wTx4nf2wnB2lJ6JhsC!1397552765!1363333095556&s=1366x768&c=24&j=1.7&v=N&k=Y&bw=1366&bh=588&AQE=1", "HEADER=Accept-Language:en-us,en;q=0.5", "COOKIE=s_vi;", END_INLINE,
            "URL=http://www-sf.kohlsecommerce.com/media/javascript/launch_window.js", "HEADER=Accept-Language:en-us,en;q=0.5", "COOKIE=JSESSIONID;mbox;s_sess;s_pers;cookieSetting;fsr.s;fsr.a;", END_INLINE,
            "URL=http://www-sf.kohlsecommerce.com/media/foresee/foresee-trigger.js", "HEADER=Accept-Language:en-us,en;q=0.5", "COOKIE=JSESSIONID;mbox;s_sess;s_pers;cookieSetting;fsr.s;fsr.a;", END_INLINE,
            "URL=https://d3t1dw6evd1rv7.cloudfront.net/kohlswishlist/v201303010537/img/addToList.png", "HEADER=Accept-Language:en-us,en;q=0.5", END_INLINE,
            "URL=https://d3t1dw6evd1rv7.cloudfront.net/kohlsregistry/v201303140801/img/add_to_reg.png", "HEADER=Accept-Language:en-us,en;q=0.5", END_INLINE,
            "URL=http://media.kohls.com.edgesuite.net/is/image/kohls/384796_Multi/None?wid=1000&hei=1000&op_sharpen=1", "HEADER=Accept-Language:en-us,en;q=0.5", END_INLINE,
            "URL=http://www-sf.kohlsecommerce.com/media/images/addtobag_v1_m56577569832236562.gif", "HEADER=Accept-Language:en-us,en;q=0.5", "COOKIE=JSESSIONID;mbox;s_sess;s_pers;cookieSetting;fsr.s;fsr.a;", END_INLINE,
            "URL=https://d3t1dw6evd1rv7.cloudfront.net/kohlsregistry/v201303140801/img/aTLLeft.png", "HEADER=Accept-Language:en-us,en;q=0.5", END_INLINE,
            "URL=https://d3t1dw6evd1rv7.cloudfront.net/kohlsregistry/v201303140801/img/aTLCenter.png", "HEADER=Accept-Language:en-us,en;q=0.5", END_INLINE,
            "URL=https://d3t1dw6evd1rv7.cloudfront.net/kohlsregistry/v201303140801/img/aTLRight.png", "HEADER=Accept-Language:en-us,en;q=0.5", END_INLINE,
            "URL=https://d3t1dw6evd1rv7.cloudfront.net/kohlswishlist/v201303010537/img/aTLLeft.png", "HEADER=Accept-Language:en-us,en;q=0.5", END_INLINE,
            "URL=https://d3t1dw6evd1rv7.cloudfront.net/kohlswishlist/v201303010537/img/aTLCenter.png", "HEADER=Accept-Language:en-us,en;q=0.5", END_INLINE,
            "URL=https://d3t1dw6evd1rv7.cloudfront.net/kohlswishlist/v201303010537/img/aTLRight.png", "HEADER=Accept-Language:en-us,en;q=0.5", END_INLINE,
            "URL=http://www-sf.kohlsecommerce.com/media/foresee/foresee-surveydef.js", "HEADER=Accept-Language:en-us,en;q=0.5", "COOKIE=JSESSIONID;mbox;s_sess;s_pers;cookieSetting;fsr.s;fsr.a;", END_INLINE,
            "URL=http://static.ak.fbcdn.net/rsrc.php/v2/yh/r/Ad2xCO8fWgA.js", "HEADER=Accept-Language:en-us,en;q=0.5", END_INLINE,
            "URL=http://static.ak.fbcdn.net/rsrc.php/v2/yh/r/Ad2xCO8fWgA.js", "HEADER=Accept-Language:en-us,en;q=0.5", END_INLINE,
            "URL=http://profile.ak.fbcdn.net/hprofile-ak-snc6/186177_1500105145_1427133611_q.jpg", "HEADER=Accept-Language:en-us,en;q=0.5", END_INLINE,
            "URL=http://profile.ak.fbcdn.net/hprofile-ak-ash4/371711_100002010730905_1972428977_q.jpg", "HEADER=Accept-Language:en-us,en;q=0.5", END_INLINE,
            "URL=http://www-sf.kohlsecommerce.com/product/prd-384796/", "HEADER=Accept-Language:en-us,en;q=0.5", "COOKIE=cookieSetting;JSESSIONID;mbox;s_sess;s_pers;cookieSetting;fsr.s;", "REDIRECT=YES", "LOCATION=http://www-sf.kohlsecommerce.com/", END_INLINE,
            "URL=http://www-sf.kohlsecommerce.com/", "HEADER=Accept-Language:en-us,en;q=0.5", "COOKIE=JSESSIONID;mbox;s_sess;s_pers;cookieSetting;fsr.s;", END_INLINE
    );
    ns_end_transaction("SelectProductPage", NS_AUTO_STATUS);
    ns_page_think_time(0);

	*/	
}
