/*-----------------------------------------------------------------------------
    Name: vuser
    Generated By: netstorm
    Date of generation: 7/27/2011 10:55:23
    Flow details:
    Modification History:
-----------------------------------------------------------------------------*/

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "ns_string.h"

void vuser()
{
    ns_web_url ("class2K_html",
        "URL=http://127.0.0.1/file_set/dir00000/class2K.html",
    );

    ns_page_think_time(0);

    ns_web_url ("class2K_html_1",
        "URL=http://127.0.0.1/file_set/dir00000/class2K.html",
        "BODY={Pagename}"
    );

    ns_page_think_time(0);

    ns_web_url ("class2K_html_2",
        "URL=http://127.0.0.1/file_set/dir00000/class2K.html",
    );

    ns_page_think_time(0);

    ns_web_url ("class2K_html_3",
        "URL=http://127.0.0.1/file_set/dir00000/class2K.html",
    );

    ns_page_think_time(0);

    ns_web_url ("class2K_html_4",
        "URL=http://127.0.0.1/file_set/dir00000/class2K.html",
    );

    ns_page_think_time(0);

    ns_web_url ("class2K_html_5",
        "URL=http://127.0.0.1/file_set/dir00000/class2K.html",
    );

    ns_page_think_time(0);

    ns_web_url ("class2K_html_6",
        "URL=http://127.0.0.1/file_set/dir00000/class2K.html",
    );

    ns_page_think_time(0);

    ns_web_url ("class2K_html_7",
        "URL=http://127.0.0.1/file_set/dir00000/class2K.html",
    );

    ns_page_think_time(0);

    ns_web_url ("class2K_html_8",
        "URL=http://127.0.0.1/file_set/dir00000/class2K.html",
    );

    ns_page_think_time(0);

    ns_web_url ("class2K_html_9",
        "URL=http://127.0.0.1/file_set/dir00000/class2K.html",
    );
    ns_page_think_time(0);

}
