/*-----------------------------------------------------------------------------
    Name: flow
    Generated By: root
    Date of generation: 06/24/2013 06:45:25
    Flow details:
    Modification History:
-----------------------------------------------------------------------------*/

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "ns_string.h"

void flow()
{
    ns_web_url ("Page19_html",
        "URL=http://127.0.0.1/RedirectionCases/Page19.html"
    );

    ns_page_think_time(0);

}
