/*-----------------------------------------------------------------------------
    Name: init_script
    Generated By: root
    Date of generation: 06/24/2013 06:45:25
    Flow details:
    Modification History:
-----------------------------------------------------------------------------*/

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "ns_string.h"

int init_script()
{
    return 0;
}
