/*-----------------------------------------------------------------------------
    Name: flow
    Generated By: netstorm
    Date of generation: 06/19/2012 01:35:43
    Flow details:
    Modification History:
-----------------------------------------------------------------------------*/

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "ns_string.h"
#define %API_TYPE
#define TEST_TYPE %TEST_CASE_TYPE_NUM

char *name=%FILE_NAME ; //File name with or without path.
int mode=%FILE_MODE ; //NS_APPEND_FILE && NS_TRUNC_FILE



#ifdef SET_INT_VAL
void call_to_set_int_val_api()
{
  int oneNumber = %inputString ;
  fprintf(stdout,"\nNS_SET_INT_VAL API Called");
  fprintf(stdout,"\nSaving %d to NS_DECL_VAR{NS_DP}",oneNumber);
  int return_val = ns_set_int_val("NS_DP",oneNumber);
  if ( return_val != 0 )
     fprintf(stderr,"\nSTATUS=FAIL\n");
  else 
     fprintf(stdout,"\nSTATUS=PASS\n");
 
  printf(stdout,"\nEND of NS_SET_INT_VAL API");
}
#endif 

#ifdef GET_INT_VAL
void call_to_get_int_val_api()
{
  int mNumberToSave = 223232; 
  fprintf(stdout,"\nNS_GET_INT_VAL API Called");
  fprintf(stdout,"\nSaving %d to NS_DECL_VAR{NS_DP}",mNumberToSave);
  ns_set_int_val("NS_DP",mNumberToSave);
  int saved_val = ns_get_int_val("NS_DP");
  fprintf(stdout,"\nNS_DECL_VAL  integer=%d",saved_val); 
  if ( saved_val == NULL )
     fprintf(stderr,"\nSTATUS=FAIL\n");
  else 
     fprintf(stdout,"\nSTATUS=PASS\n");
 
  printf(stdout,"\nEND of NS_SET_INT_VAL API");
}
#endif 

#ifdef GET_RANDOM_STR 
void call_to_get_random_str_api()
{
  char *charset = %inputString ; 
  fprintf(stdout,"\nNS_GET_RANDOM_STR API Called");
  char *emailSuffix = ns_get_random_str(6,12, charset);
  fprintf(stdout,"\nRANDOM EMAIL STRING  = [%s@cavisson.com]", emailSuffix);
  ns_save_string(emailSuffix,"NS_DP");
  if ( emailSuffix == NULL ) 
     fprintf(stderr,"\nSTATUS=FAIL\n");
  else
     fprintf(stdout,"\nSTATUS=PASS\n");

  printf(stdout,"\nEND of NS_GET_RANDOM_STR API");

}
#endif 

#ifdef SAVE_STRING
void call_to_save_string_api() 
{
  char *str = %inputString; 
  fprintf(stdout,"\nNS_SAVE_STRING API Called");
  fprintf(stdout,"\nSaving %s to NS_DECL_VAR{NS_DP}",str);
  int return_val = ns_save_string(str,"NS_DP");
  if ( return_val != 0 )
     fprintf(stderr,"\nSTATUS=FAIL\n");
  else 
     fprintf(stdout,"\nSTATUS=PASS\n");

  fprintf(stdout,"\nEND of SAVE_STRING API");
}
#endif 

#ifdef EVAL_STRING 
void call_to_eval_string_api()
{
  char *eval_string ; 
  fprintf(stdout,"\nNS_EVAL_STRING API Called");
  ns_save_string("EVALUATED TEST STRING","NS_DP_EVAL");
  eval_string = ns_eval_string("{NS_DP_EVAL}");
  fprintf(stdout,"\nNS_DECL_VAR String=%s",eval_string);
  if ( eval_string == NULL )
     fprintf(stderr,"\nSTATUS=FAIL\n");
  else
     fprintf(stdout,"\nSTATUS=PASS\n");
}
#endif

#ifdef ADV_PARAM 
void call_to_advance_param_api(int type)
{
  int status ;
  fprintf(stdout,"\nNS_ADVANCE_PARAM API Called");
  if ( type == 0 ) 
  {
    status = ns_advance_param("F1");
    status = ns_advance_param("F1");
    fprintf(stdout,"\nValue Read=%s, status=%d",ns_eval_string("{F1}"),status);
  }
  if ( type == 1 )
  {
     status= ns_advance_param("F2");
     char *tmp = ns_eval_string("{F2}");
     status = ns_advance_param("F3");
     char *tmp2 = ns_eval_string("{F2}");
     status = ns_advance_param("F3");
     fprintf(stdout,"\nValue Read=%s, status=%d",ns_eval_string("{F2}"),status);
  }
    if ( status !=0 )
      fprintf(stderr,"\nSTATUS=FAIL\n");
    else
      fprintf(stdout,"\nSTATUS=PASS\n");
}
#endif 

#ifdef SAVE_DATA_VAR 
void call_to_save_data_var_api() 
{
   char *str = %inputString;
   ns_save_string(str,"NS_DP");
   printf("\nNS_SAVE_DATA_VAR API Called");
   int return_val = ns_save_data_var(name,mode,"NS_DP");
   if ( return_val == 0)
   {
      printf("\nValues saved to %s in mode=%d",name,mode);
      printf("\nSTATUS=PASS\n");
   }
   else {
      printf("\nSTATUS=FAIL\n");
  }
}
#endif 

#ifdef SAVE_DATA_EVAL
void call_to_save_data_eval_api()
{
   char *str = %inputString;
   ns_save_string(str,"NS_DP");
   printf("\nNS_SAVE_DATA_EVAL API Called");
   int return_val = ns_save_data_eval(name,mode,"{NS_DP}");
   if ( return_val == 0)
   {
      printf("\nValues saved to %s in mode=%d",name,mode);
      printf("\nSTATUS=PASS\n");
   }
   else {
      printf("\nSTATUS=FAIL\n");
  }
}
#endif 

#ifdef SAVE_DATA_EX 
void call_to_save_data_ex_api()
{
   char *str = %inputString;
   ns_save_string(str,"NS_DP");
   printf("\nNS_SAVE_DATA_EX API Called");
   int return_val = ns_save_data_ex(name,mode,"%s",str);
   if ( return_val == 0)
   {
      printf("\nValues saved to %s in mode=%d",name,mode);
      printf("\nSTATUS=PASS\n");
   }
   else {
      printf("\nSTATUS=FAIL\n");
  }
}
#endif 

#ifdef GET_COOKIE_VAL_EX 
void call_to_get_cookie_val_ex()
{
   char *cookie = %COOKIE_NAME ; 
   char COOKIE_BUFF[1024];
   printf("\nUSING GET ALL METHOD FOR COOKIE=%s\n",ns_get_all_cookies(COOKIE_BUFF,1024 +1));
   printf("\nNS_GET_COOKIE_VAL_EX API called");
   char *cookie_found = ns_get_cookie_val_ex(cookie,NULL,NULL);
   //char *cookie_found = ns_get_cookie_val_ex("Cookie_Name",NULL,NULL);
   printf("\nCookie=%s",cookie_found);
   if ( cookie_found == NULL )
      printf("\nSTATUS=FAIL\n");
   else 
      printf("\nSTATUS=PASS\n");
   ns_save_string(cookie_found,"NS_DP");

}
#endif 

#ifdef SET_COOKIE_VAL_EX   
void call_to_set_cookie_val_ex()
{
  char *cookie = %COOKIE_NAME ;  
  printf("\nNS_SET_COOKIE_VAL_EX API called");
  ns_set_cookie_val_ex(cookie,NULL,NULL,%COOKIE_VAL);
  ns_save_string(ns_get_cookie_val_ex(cookie,NULL,NULL),"NS_DP");
  printf("Value saved = %s\n",ns_eval_string("{NS_DP}")); 
}

#endif 

#ifdef CHK_STR_CPY 
void call_to_chk_strcpy_api()
{
  int BUFF_LEN = 32 ;
  char destination[BUFF_LEN + 1] ;
  char source[128] = %inputString ;
  int ret  = ns_chk_strcpy(destination,source, BUFF_LEN + 1 ) ;
  fprintf(stdout,"source = [%s],destination = [%s], return value = [%d]\n",source, destination, ret) ;  
  if ( ret != 0 || ret != 1 )
     fprintf(stdout,"\nSTATUS=FAIL\n");
  else
     fprintf(stdout,"\nSTATUS=PASS\n");
}
#endif

#ifdef GETTERS
void call_to_all_get_api()
{
  int nvmid =  ns_get_nvmid();
  int userid = ns_get_userid();
  int sessid = ns_get_sessid();
  int testid = ns_get_testid();
  int thinktime =  ns_get_pg_think_time();
  int randomnum = ns_get_random_number_int(1,99);
  long uniqnum = ns_get_unique_number();
  int ka_time = ns_get_ka_time();
  int page_status = ns_get_page_status() ;
  int tx_status = ns_get_tx_status("API_T01") ;
  int sess_status = ns_get_session_status() ;
  int num_nvm = ns_get_num_nvm();
  int num_ka_pct = ns_get_num_ka_pct();
  int min_ka = ns_get_min_ka();
  int max_ka = ns_get_max_ka();
  char *guid  =  ns_get_guid();
  
  char buffer[512] ; 

  fprintf(stdout,"[info] nvmid = [%d], userid = [%d], sessid = [%d], testid = [%d]\n",nvmid, userid, sessid, testid);
  fprintf(stdout,"[info] thinktime = [%d], randomnum = [%d], uniqnum = [%ld], ka_time = [%d]\n",thinktime,randomnum,uniqnum,ka_time);
  fprintf(stdout,"[info] num_nvm = [%d], page_status = [%d], tx_status = [%d], sess_status = [%d]\n",num_nvm,page_status,tx_status,sess_status);
  fprintf(stdout,"[info] num_ka_pct = [%d], min_ka = [%d], max_ka = [%d], guid = [%s]\n",num_ka_pct,min_ka,max_ka,guid);

  sprintf(buffer,"nvmid = [%d], userid = [%u], sessid = [%u], testid = [%d]",nvmid, userid, sessid, testid);
  ns_save_string(buffer,"NS_DP");
  fprintf(stdout,"[debug] %s\n",ns_eval_string("{NS_DP}"));
  
  sprintf(buffer,"thinktime = [%d], randomnum = [%d], uniqnum = [%ld], ka_time = [%d]",thinktime,randomnum,uniqnum,ka_time);
  ns_save_string(buffer,"NS_DP");
  fprintf(stdout,"[debug] %s\n",ns_eval_string("{NS_DP}"));
  
  sprintf(buffer,"num_nvm = [%d], page_status = [%d], tx_status = [%d], sess_status = [%d]",num_nvm,page_status,tx_status,sess_status);
  ns_save_string(buffer,"NS_DP");
  fprintf(stdout,"[debug] %s\n",ns_eval_string("{NS_DP}"));
 
 sprintf(buffer,"num_ka_pct = [%d], min_ka = [%d], max_ka = [%d], guid = [%s]",num_ka_pct,min_ka,max_ka,guid);
 ns_save_string(buffer,"NS_DP");
 fprintf(stdout,"[debug] %s\n",ns_eval_string("{NS_DP}"));
  
}
#endif 

void flow()
{
  
#ifdef SAVE_STRING
  call_to_save_string_api();
#endif 

#ifdef EVAL_STRING
  call_to_eval_string_api();
#endif 

#ifdef ADV_PARAM
  call_to_advance_param_api(TEST_TYPE);
#endif 

#ifdef SAVE_DATA_VAR
  call_to_save_data_var_api();
#endif 

#ifdef SAVE_DATA_EVAL
  call_to_save_data_eval_api();
#endif

#ifdef SAVE_DATA_EX
  call_to_save_data_ex_api() ;
#endif

#ifdef SET_INT_VAL 
  call_to_set_int_val_api();
#endif 

#ifdef GET_INT_VAL 
  call_to_get_int_val_api();
#endif 

#ifdef GET_RANDOM_STR 
  call_to_get_random_str_api();
#endif 

#ifdef GETTERS 
  call_to_all_get_api();
#endif

#ifdef CHK_STR_CPY
  call_to_chk_strcpy_api();
#endif  

  
#ifdef GET_COOKIE_VAL_EX 
  ns_start_transaction("API_COOKIE_T01");
  ns_web_url("CookiePage",
    "URL=http://127.0.0.1/Cookie_Smoke/CookieMacys.html", 
  );
 call_to_get_cookie_val_ex();
 ns_end_transaction("API_COOKIE_T01",NS_AUTO_STATUS);
#endif 

   ns_start_transaction("API_T01");
   ns_web_url("Tiny",
      "URL=http://127.0.0.1/tiny?{NS_DP}",
      "BODY={NS_DP}"
   );

   ns_end_transaction("API_T01",NS_AUTO_STATUS);
   ns_page_think_time(0);

#ifdef SET_COOKIE_VAL_EX

  ns_start_transaction("API_COOKIE_T02"); 
  ns_web_url("CookiePage2",
  "URL=http://127.0.0.1/Cookie_Smoke/CookieMacys.html?"
  ); 
  call_to_set_cookie_val_ex();
  ns_web_url("Tiny_2",
    "URL=http://127.0.0.1/tiny?{NS_DP}",
    "BODY={NS_DP}"
  ); 
  ns_end_transaction("API_COOKIE_T02",NS_AUTO_STATUS);  
#endif
}

