##----------------------------------------------------------------------------------------------------#  
##  Generated by needle                                                                            #
##  Convention: ALL variables starts with K followed by underscore and appropriate name               #
##  Note: Do not use blank line and spaces. Comments are allowed                                      #
#----------------------------------------------------------------------------------------------------#
$K_TNAME|$K_NUM_USERS|$K_RAMP_UP_TIME|$K_DURATION|$K_RAMP_DOWN_TIME|$K_SCRIPT|$K_SVR_HOST|$K_REPORTING|$K_O_THINK_TIME|$K_THINK_TIME|$K_NEW_USER|$K_TRACING|$K_HIERARICHAL_VIEW|%post1|%post2|%REPEAT|$CONTINUE_ON_ERROR|$INLINE_DELAY
#
##stop the session after found the string by giving CVFail. (Failure condition checked).
SMOKE-036-001|1|ALL IMMEDIATELY|SESSIONS 1|ALL IMMEDIATELY|inline_checkpoint|127.0.0.1 10.10.30.96 -|ALL 1|ALL ALL 1|ALL ALL 3 10 50|ALL 1|ALL 0 0 0 0|default|"POSTURLCALLBACK=inline_checkpoint1"|"POSTURLCALLBACK=message"|0|0|1000
#
##continue with the session after found the string by giving CVFail. (Failure condition checked).
SMOKE-036-002|1|ALL IMMEDIATELY|SESSIONS 1|ALL IMMEDIATELY|inline_checkpoint|127.0.0.1 10.10.30.96 -|ALL 1|ALL ALL 1|ALL ALL 3 10 50|ALL 1|ALL 0 0 0 0|default|"POSTURLCALLBACK=inline_checkpoint2"|"POSTURLCALLBACK=message"|0|0|1000
#
##continue with the session after string found (NO CVFail will observed). (Failure condition unchecked).
SMOKE-036-003|1|ALL IMMEDIATELY|SESSIONS 1|ALL IMMEDIATELY|inline_checkpoint|127.0.0.1 10.10.30.96 -|ALL 1|ALL ALL 1|ALL ALL 3 10 50|ALL 1|ALL 0 0 0 0|default|"POSTURLCALLBACK=inline_checkpoint3"|"POSTURLCALLBACK=message"|0|0|1000
#
##stop the session if string not found (CVFail will observed). (Failure condition unchecked).
SMOKE-036-004|1|ALL IMMEDIATELY|SESSIONS 1|ALL IMMEDIATELY|inline_checkpoint|127.0.0.1 10.10.30.96 -|ALL 1|ALL ALL 1|ALL ALL 3 10 50|ALL 1|ALL 0 0 0 0|default|"POSTURLCALLBACK=inline_checkpoint4"|"POSTURLCALLBACK=message"|0|0|1000
#
##Regular Expression and ignore case : If string found then will stop the session by giving CVFail (Failure condition checked).
SMOKE-036-005|1|ALL IMMEDIATELY|SESSIONS 1|ALL IMMEDIATELY|inline_checkpoint|127.0.0.1 10.10.30.96 -|ALL 1|ALL ALL 1|ALL ALL 3 10 50|ALL 1|ALL 0 0 0 0|default|"POSTURLCALLBACK=inline_checkpoint5"|"POSTURLCALLBACK=message"|0|0|1000
#
##Regular Expression and ignore case : If string found then will continue the session by giving CVFail (Failure condition checked).
SMOKE-036-006|1|ALL IMMEDIATELY|SESSIONS 1|ALL IMMEDIATELY|inline_checkpoint|127.0.0.1 10.10.30.96 -|ALL 1|ALL ALL 1|ALL ALL 3 10 50|ALL 1|ALL 0 0 0 0|default|"POSTURLCALLBACK=inline_checkpoint6"|"POSTURLCALLBACK=message"|0|0|1000
#
##Regular Expression and ignore case : If string found then will continue the session(Failure condition unchecked) (NO CVFail will observed).
SMOKE-036-007|1|ALL IMMEDIATELY|SESSIONS 1|ALL IMMEDIATELY|inline_checkpoint|127.0.0.1 10.10.30.96 -|ALL 1|ALL ALL 1|ALL ALL 3 10 50|ALL 1|ALL 0 0 0 0|default|"POSTURLCALLBACK=inline_checkpoint7"|"POSTURLCALLBACK=message"|0|0|1000
#
##Multiple checkpoint case: Continue after string found in first checkpoint and stop after string found in second checkpoint with CVFail
SMOKE-036-008|1|ALL IMMEDIATELY|SESSIONS 1|ALL IMMEDIATELY|inline_checkpoint|127.0.0.1 10.10.30.96 -|ALL 1|ALL ALL 1|ALL ALL 3 10 50|ALL 1|ALL 0 0 0 0|default|"POSTURLCALLBACK=inline_checkpoint2"|"POSTURLCALLBACK=inline_checkpoint8"|5|0|1000
#
##Multiple checkpoint case:Continue after string found in first and stop after string found in second with CVFail(It will not stop the session because used "G_CONTINUE_ON_PAGE_ERROR ALL ALL ALL 1"
SMOKE-036-009|1|ALL IMMEDIATELY|SESSIONS 1|ALL IMMEDIATELY|inline_checkpoint|127.0.0.1 10.10.30.96 -|ALL 1|ALL ALL 1|ALL ALL 3 10 50|ALL 1|ALL 0 0 0 0|default|"POSTURLCALLBACK=inline_checkpoint2"|"POSTURLCALLBACK=inline_checkpoint1"|5|1|1000
##END_ITERATION
