#----------------------------------------------------------------------------------------------------#  
#  Generated by needle                                                                            #
#  Convention: ALL variables starts with K followed by underscore and appropriate name               #
#  Note: Do not use blank line and spaces. Comments are allowed                                      #
#----------------------------------------------------------------------------------------------------#
$K_TNAME|$K_RAMP_UP_TIME|$K_DURATION|$K_RAMP_DOWN_TIME|$G_TRACING|$AUTO_FETCH|$SGRP_SET|$SGRP_SET1|$URI_ENCODING|$URI_ENCODING1

SMOKE-ENCODING-067-001|ALL IMMEDIATELY|SESSIONS 1|ALL IMMEDIATELY|G_TRACING ALL 4 1 0 0 1 0|1|SGRP G1 NA NA Internet 0 hpd_tours 1|#|URI_ENCODING %20 0|#
SMOKE-ENCODING-067-002|ALL IMMEDIATELY|SESSIONS 1|ALL IMMEDIATELT|G_TRACING ALL 4 1 0 0 1 0|1|SGRP G2 NA NA Internet 0 hpd_tours_UriEncoding 1|#|URI_ENCODING %20 3 None None|#
SMOKE-ENCODING-067-003|ALL IMMEDIATELY|SESSIONS 1|ALL IMMEDIATELT|G_TRACING ALL 4 1 0 0 1 0|1|SGRP G2 NA NA Internet 0 hpd_tours_Uri_Encoding 1|#|URI_ENCODING %20 2 / *|#
SMOKE-ENCODING-067-004|ALL IMMEDIATELY|SESSIONS 1|ALL IMMEDIATELT|G_TRACING ALL 4 1 0 0 1 0|1|SGRP G2 NA NA Internet 0 hpd_tours_Uri_encoding 1|#|URI_ENCODING 20 1 } None|#

#SMOKE-ENCODING-067-002|ALL IMMEDIATELY|SESSIONS 1|ALL IMMEDIATELY|1|SGRP G1 NA NA Internet 0 hpd_tours 1|#|URI_ENCODING %20 3 { *|#

#END_ITERATION
