#!/bin/bash

. $NS_WDIR/lib/automation_util
T_NAME=$(get_tname)
PAGE_FAIL=`grep -r "Page Failures" $NS_WDIR/logs/TR$T_RUN_ID/summary.data |awk '{print $2}' | cut -d '|' -f2`

#Cases for search var
if [ "XX$T_NAME" == "XXSMOKE-009-001" ];then 
   RESPONSE=`cat $T_ID_REQ_PATH/url_req_0_0_* | grep -o class2K.html?9`
   if [ "$RESPONSE" == "class2K.html?9" ] && \
      [ "XX$SD_TotalSuccURL" == "XX2" ];then
       log_status_and_exit_ex "PASS" "Search in two main url Passed"
   else
       log_status_and_exit_ex "FAIL" "Search in two main url Failed"
   fi 
fi

if [ "XX$T_NAME" == "XXSMOKE-009-002" ];then
   RESPONSE_SEARCH_FAIL=`cat $T_ID_REQ_PATH/url_req_0_0_* | grep -o class2K.html?W`
   if [ "$RESPONSE_SEARCH_FAIL" == "class2K.html?W" ] && \
      [ "XX$SD_TotalSuccURL" == "XX2" ];then
       log_status_and_exit_ex "PASS" "Search in two main url with savelength mode Passed"
   else
       log_status_and_exit_ex "FAIL" "Search in two main url with savelength mode Failed"
   fi
fi

if [ "XX$T_NAME" == "XXSMOKE-009-003" ];then
   RESPONSE_SEARCH_FAIL=`cat $T_ID_REQ_PATH/url_req_0_0_* | grep -o class2K.html?99`
   if [ "$RESPONSE_SEARCH_FAIL" == "class2K.html?99" ] && \
      [ "XX$SD_TotalSuccURL" == "XX2" ];then
       log_status_and_exit_ex "PASS" "Search for two main url with save length and save offset mode  Passed"
   else
       log_status_and_exit_ex "FAIL" "Search for two main url with save length and save offset mode Failed"
   fi
fi

if [ "XX$T_NAME" == "XXSMOKE-009-004" ];then
   RESPONSE_SEARCH_FAIL=`cat $T_ID_REQ_PATH/url_req_0_0_* | grep -o class2K.html?98`
   if [ "XX$RESPONSE_SEARCH_FAIL" == "XX" ] && \
      [ "XX$SD_TotalSuccURL" == "XX2" ];then
       log_status_and_exit_ex "PASS" "Search for two main url with save length and save offset mode Passed"
   else
       log_status_and_exit_ex "FAIL" "Search for two main url with save length and save offset mode Failed"
   fi
fi

if [ "XX$T_NAME" == "XXSMOKE-009-005" ];then
   RESPONSE_SEARCH_FAIL=`cat $T_ID_REQ_PATH/url_req_0_0_* | grep -o /tours/index.html?ur`
   if [ "$RESPONSE_SEARCH_FAIL" == "/tours/index.html?ur" ] && \
      [ "XX$SD_TotalSuccURL" == "XX3" ];then
       log_status_and_exit_ex "PASS" "Search for two main url with save length and save offset mode in 2 pages Passed"
   else
       log_status_and_exit_ex "FAIL" "Search for two main url with save length and save offset mode in 2 pages Failed"
   fi
fi


if [ "XX$T_NAME" == "XXSMOKE-009-006" ];then
   RESPONSE_SEARCH_FAIL=`cat $T_ID_REQ_PATH/url_req_0_0_* | grep -o /tours/index.html?ur`
   if [ "$RESPONSE_SEARCH_FAIL" == "/tours/index.html?ur" ] && \
      [ "XX$SD_TotalSuccURL" == "XX3" ];then
       log_status_and_exit_ex "PASS" "Search for two main url with save length and save offset mode in 2 pages Passed"
   else
       log_status_and_exit_ex "FAIL" "Search for two main url with save length and save offset mode in 2 pages Failed"
   fi
fi

#Cases for Check Point

if [ "XX$T_NAME" == "XXSMOKE-009-007" ];then
   if [ "XX$PAGE_FAIL" == "XX4" ];then
       log_status_and_exit_ex "PASS" "Checkpoint with two main url check value found Passed"
   else
       log_status_and_exit_ex "FAIL" "Checkpoint with two main url check value found Failed"
   fi
fi

if [ "XX$T_NAME" == "XXSMOKE-009-008" ];then
   if [ "XX$PAGE_FAIL" == "XX4" ];then
       log_status_and_exit_ex "PASS" "Checkpoint with two main url check value not found Passed"
   else
       log_status_and_exit_ex "FAIL" "Checkpoint with two main url check value not found Failed"
   fi
fi

if [ "XX$T_NAME" == "XXSMOKE-009-009" ];then
   if [ "XX$PAGE_FAIL" == "XX2" ];then
       log_status_and_exit_ex "PASS" "Checkpoint with two main url check value with prefix and suffix found Passed"
   else
       log_status_and_exit_ex "FAIL" "Checkpoint with two main url check value with prefix and suffix found Failed"
   fi
fi


if [ "XX$T_NAME" == "XXSMOKE-009-010" ];then
   if [ "XX$PAGE_FAIL" == "XX2" ];then
       log_status_and_exit_ex "PASS" "Checkpoint with two main url check value with prefix and suffix not found Passed"
   else
       log_status_and_exit_ex "FAIL" "Checkpoint with two main url check value with prefix and suffix not found Failed"
   fi
fi

if [ "XX$T_NAME" == "XXSMOKE-009-011" ];then
   if [ "XX$PAGE_FAIL" == "XX1" ] && \
      [ "XX$SD_TotalSuccURL" == "XX2" ];then
       log_status_and_exit_ex "PASS" "Checkpoint with two main url check value with prefix and suffix found and ActionOnfailContinue Passed"
   else
       log_status_and_exit_ex "FAIL" "Checkpoint with two main url check value with prefix and suffix found ActionOnfailContinue Failed"
   fi
fi

if [ "XX$T_NAME" == "XXSMOKE-009-012" ];then
   if [ "XX$PAGE_FAIL" == "XX1" ] && \
      [ "XX$SD_TotalSuccURL" == "XX1" ];then
       log_status_and_exit_ex "PASS" "Checkpoint with two main url check value with prefix and suffix not found ActionOnfailStop Passed"
   else
       log_status_and_exit_ex "FAIL" "Checkpoint with two main url check value with prefix and suffix not found ActionOnfailStop Failed"
   fi
fi


if [ "XX$T_NAME" == "XXSMOKE-009-013" ];then
   if [ "XX$PAGE_FAIL" == "XX2" ] && \
      [ "XX$SD_TotalSuccURL" == "XX4" ];then
       log_status_and_exit_ex "PASS" "Checkpoint with two main url check value with prefix and suffix found comparing from a file Passed"
   else
       log_status_and_exit_ex "FAIL" "Checkpoint with two main url check value with prefix and suffix found comparing from a file Failed"
   fi
fi


if [ "XX$T_NAME" == "XXSMOKE-009-014" ];then
   if [ "XX$PAGE_FAIL" == "XX2" ] && \
      [ "XX$SD_TotalSuccURL" == "XX4" ];then
       log_status_and_exit_ex "PASS" "Checkpoint with two main url check value with prefix and suffix not found Passed"
   else
       log_status_and_exit_ex "FAIL" "Checkpoint with two main url check value with prefix and suffix not found Failed"
   fi
fi

if [ "XX$T_NAME" == "XXSMOKE-009-015" ] && \
   [ "XX$SD_TotalSuccURL" == "XX5" ];then
   RESPONSE=`cat $T_ID_REQ_PATH/url_req_0_0_0_1_0_0_0_1_0.dat | grep -o class2K.html?Netstorm`
   RESPONSE1=`cat $T_ID_REQ_PATH/url_req_0_0_0_2_0_0_0_2_0.dat | grep -o class2K.html?NetOcean`
   RESPONSE2=`cat $T_ID_REQ_PATH/url_req_0_0_0_3_0_0_0_3_0.dat | grep -o class2K.html?NetFunction`
   RESPONSE3=`cat $T_ID_REQ_PATH/url_req_0_0_0_4_0_0_0_4_0.dat | grep -o class2K.html?NetOmni`

   if [ $RESPONSE == "class2K.html?Netstorm" ] && \
      [ $RESPONSE1 == "class2K.html?NetOcean" ] && \
      [ $RESPONSE2 == "class2K.html?NetFunction" ] && \
      [ $RESPONSE3 == "class2K.html?NetOmni" ];then
       log_status_and_exit_ex "PASS" "File Parameter 5 main url ChangeOnUse Passed"
   else
       log_status_and_exit_ex "FAIL" "File Parameter 5 main url ChangeOnUse Failed"
   fi
fi

if [ "XX$T_NAME" == "XXSMOKE-009-016" ] && \
   [ "XX$SD_TotalSuccURL" == "XX20" ];then
   RESPONSE_1Session=`cat $T_ID_REQ_PATH/url_req_0_0_0_1_0_0_0_1_0.dat | grep -o class2K.html?Netstorm`
   RESPONSE_2Session=`cat $T_ID_REQ_PATH/url_req_0_0_1_1_0_0_0_1_0.dat | grep -o class2K.html?NetOcean`
   RESPONSE_3Session=`cat $T_ID_REQ_PATH/url_req_0_0_2_1_0_0_0_1_0.dat | grep -o class2K.html?NetFunction`
   RESPONSE_4Session=`cat $T_ID_REQ_PATH/url_req_0_0_3_1_0_0_0_1_0.dat | grep -o class2K.html?NetOmni`

   if [ $RESPONSE_1Session == "class2K.html?Netstorm" ] && \
      [ $RESPONSE_2Session == "class2K.html?NetOcean" ] && \
      [ $RESPONSE_3Session == "class2K.html?NetFunction" ] && \
      [ $RESPONSE_4Session == "class2K.html?NetOmni" ];then
       log_status_and_exit_ex "PASS" "File Parameter 5 main url ChangeOnSession Passed"
   else
       log_status_and_exit_ex "FAIL" "File Parameter 5 main url ChangeOnSession Failed"
   fi
fi

if [ "XX$T_NAME" == "XXSMOKE-009-017" ];then
    if [ $SD_TotalSuccURL -eq 5 ];then 
        log_status_and_exit_ex "PASS" "File Parameter 5 url ModeWeighted Passed"
    else
        log_status_and_exit_ex "FAIL" "File Parameter 5 url ModeWeighted Failed"
    fi
fi

if [ "XX$T_NAME" == "XXSMOKE-009-018" ];then
   RESPONSE_SEARCH_FAIL=`cat $T_ID_REQ_PATH/url_req_0_0_* | grep -o class2K.html?9`
   if [ "X$RESPONSE_SEARCH_FAIL" == "X" ] && [ "XX$SD_TotalSuccURL" == "XX2" ];then
       echo "Passing..."
       log_status_and_exit_ex "PASS" "Serach Param for two main url Passed"
   else
       echo "Failing..."
       log_status_and_exit_ex "FAIL" "Search Param for two main url Failed"
   fi
fi

if [ "XX$T_NAME" == "XXSMOKE-009-019" ];then
    REQ_QUERY=`grep "GET" $T_ID_REQ_PATH/url_req_0_0_0_1_0_0_0_1_0.dat | cut -d '?' -f2 | cut -d 'H' -f1`
    REP_MSG=`grep -o -m1 "400 Bad Request" $T_ID_REQ_PATH/url_rep_0_0_0_1_0_0_0_1_0.dat`
    if [ "$REQ_QUERY" ==  " is  " ] && \
       [ "$REP_MSG" == "400 Bad Request" ] && \
       [ $SD_TotalSuccURL -eq 1 ];then
        echo "Values matched"
        log_status_and_exit_ex "PASS" "Search Param for 5 url with single page search savelenght and saveoffset and ORD all Passed"
    else
        echo "Values didnt match"
       log_status_and_exit_ex "FAIL" "Search Param for 5 url with single page search savelenght and saveoffset and ORD all Failed"
    fi
fi

exit 0
