#----------------------------------------------------------------------------------------------------#  
#  Generated by needle                                                                            #
#  Convention: ALL variables starts with K followed by underscore and appropriate name               #
#  Note: Do not use blank line and spaces. Comments are allowed                                      #
#----------------------------------------------------------------------------------------------------#
$K_TNAME|$K_NUM_USERS|$K_RAMP_UP_TIME|$K_DURATION|$K_RAMP_DOWN_TIME|$K_SCRIPT|$K_SVR_HOST|$K_REPORTING|$K_SESSION_PACING|$K_O_THINK_TIME|$K_THINK_TIME|$K_NEW_USER|$K_TRACING|$K_HIERARICHAL_VIEW|$K_NVM_COUNT|$K_FSR_ENABLED|$K_SECOND_SGRP|$K_THIRD_SGRP|$PCT_MODE|$TOTAL_USERS|$K_NVM_DISTRIBUTION

##########NVM DISTRIBUTION 0##################

#Iterations for FCU
SMOKE-049-001|8|ALL IMMEDIATELY|TIME 00:00:10|ALL IMMEDIATELY|hpd_tours|127.0.0.1 10.10.30.96 -|ALL 2|ALL 1 0 1000|ALL ALL 1|ALL ALL 3 10 50|ALL 1|ALL 0 0 0 0|default|4|#|#|#|NUM|#|0|

SMOKE-049-002|8|ALL IMMEDIATELY|TIME 00:00:10|ALL IMMEDIATELY|hpd_tours|127.0.0.1 10.10.30.96 -|ALL 2|ALL 1 0 1000|ALL ALL 1|ALL ALL 3 10 50|ALL 1|ALL 0 0 0 0|default|8|#|#|#|NUM|#|0|

SMOKE-049-003|4|ALL IMMEDIATELY|TIME 00:00:10|ALL IMMEDIATELY|hpd_tours|127.0.0.1 10.10.30.96 -|ALL 2|ALL 1 0 1000|ALL ALL 1|ALL ALL 3 10 50|ALL 1|ALL 0 0 0 0|default|8|#|#|#|NUM|#|0|

#Iterations for FSR
SMOKE-049-004|8|ALL IMMEDIATELY|TIME 00:00:10|ALL IMMEDIATELY|hpd_tours|127.0.0.1 10.10.30.96 -|ALL 2|ALL 1 0 1000|ALL ALL 1|ALL ALL 3 10 50|ALL 1|ALL 0 0 0 0|default|4|STYPE FIX_SESSION_RATE|#|#|NUM|#|0|

SMOKE-049-005|8|ALL IMMEDIATELY|TIME 00:00:10|ALL IMMEDIATELY|hpd_tours|127.0.0.1 10.10.30.96 -|ALL 2|ALL 1 0 1000|ALL ALL 1|ALL ALL 3 10 50|ALL 1|ALL 0 0 0 0|default|8|STYPE FIX_SESSION_RATE|#|#|NUM|#|0|

SMOKE-049-006|5|ALL IMMEDIATELY|TIME 00:00:10|ALL IMMEDIATELY|hpd_tours|127.0.0.1 10.10.30.96 -|ALL 2|ALL 1 0 1000|ALL ALL 1|ALL ALL 3 10 50|ALL 1|ALL 0 0 0 0|default|8|STYPE FIX_SESSION_RATE|#|#|NUM|#|0|

#Iteration for Percentile mode
SMOKE-049-007|70.00|ALL IMMEDIATELY|TIME 00:00:10|ALL IMMEDIATELY|hpd_tours|127.0.0.1 10.10.30.96 -|ALL 2|ALL 1 0 1000|ALL ALL 1|ALL ALL 3 10 50|ALL 1|ALL 0 0 0 0|default|5|#|SGRP G2 NA NA Internet 0 hpd_tours 30.00|#|PCT|NUM_USERS 10|0|



###########NVM DISTRIBUTION 1##################

SMOKE-049-008|8|ALL IMMEDIATELY|TIME 00:00:10|ALL IMMEDIATELY|hpd_tours|127.0.0.1 10.10.30.96 -|ALL 2|ALL 1 0 1000|ALL ALL 1|ALL ALL 3 10 50|ALL 1|ALL 0 0 0 0|default|4|#|SGRP G2 NA NA Internet 0 ash_tours 8|SGRP G3 NA NA Internet 0 hpd_tours 8|NUM|#|1|

###########NVM DISTRIBUTION 2##################
SMOKE-049-009|8 1|ALL IMMEDIATELY|TIME 00:00:10|ALL IMMEDIATELY|hpd_tours|127.0.0.1 10.10.30.96 -|ALL 2|ALL 1 0 1000|ALL ALL 1|ALL ALL 3 10 50|ALL 1|ALL 0 0 0 0|default|4|#|SGRP G2 NA NA Internet 0 ash_tours 8 1|SGRP G3 NA NA Internet 0 hpd_tours 8 2|NUM|#|2|


#END_ITERATION
