/*-----------------------------------------------------------------------------
    Name: default_flow
    Generated By: netstorm
    Date of generation: 09/28/2016 01:06:45
    Flow details:
    Build details: 4.1.6 (build# 18)
    Modification History:
-----------------------------------------------------------------------------*/

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "ns_string.h"


void default_flow()
{
  int cav_replay_page_id = ns_get_int_val("cav_replay_page_id");
  //Default is called when page id is not valid. So log event.
  ns_log_event(EVENT_CRITICAL, "Replay default flow called for invalid page_id = %d", cav_replay_page_id);
  ns_page_think_time(0.1); 
}