/*-----------------------------------------------------------------------------
    Name: default_flow
    Generated By: netstorm
    Date of generation: 7/13/2011 1:11:28
    Flow details:
    Modification History:
-----------------------------------------------------------------------------*/

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "ns_string.h"



void default_flow()
{


}