/*-----------------------------------------------------------------------------
    Name: flow
    Generated By: netstorm
    Date of generation: 03/06/2014 03:21:39
    Flow details:
    Modification History:
-----------------------------------------------------------------------------*/

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "ns_string.h"

void flow()
{
ns_web_url ("file_multipart",
  "METHOD=POST",
  "URL=http://127.0.0.1/file_set/dir00000/class0_5.html",
  "HEADER=Content-type:multipart/form-data",
   MULTIPART_BODY_BEGIN,
   MULTIPART_BOUNDARY,  
  "BODY=$CAVINCLUDE$=Multi.xml",
   MULTIPART_BODY_END,
INLINE_URLS,
   "URL=http://127.0.0.1/file_set/dir00000/class200B.html",
END_INLINE,

    );
  ns_page_think_time(0);





  }
