#!/usr/bin/env bash

source $NS_WDIR/lib/automation_util
# This is for tool run test
Tool="/home/automation/workbench/automation/nscore/smoke/testcases/SmokeTest_RAL_validation/Replay_wells"

debug_log "${Tool}"

Directory_Path="/home/netstorm/work/scripts/webService_Replay"
Scenario_File="/home/netstorm/work/scenarios/webService_Replay.conf"

########### Remove Script file if exist before tool run #############
    if [ -d ${Directory_Path} ] ; then 
        rm -rf ${Directory_Path}
        debug_log "Directory removed"
    else
        debug_log "Script does not exist"
    fi

############# Remove Scenarion file if exist before tool run #################
    if [ -f ${Scenario_File} ]; then 
        rm -rf ${Scenario_File}
        debug_log "Scenario file removed"
    else
        debug_log "Scenario file does not exist"

    fi 

###### Script generation tool ##############    
Tool_Run=$( ${Tool}/ntp_replay_gen  -i  ${Tool}/Replay.conf -f )
#debug_log $Tool_Run


    if [ -f ${Scenario_File} ]; then
        debug_log "File exist"
        echo "SERVER_HOST 127.0.0.1 10.10.30.96 -" >> ${Scenario_File}
        debug_log "Server host added sucessfully inside scenario file"
    else
        debug_log "Scenario file does not exist"
    fi


