#!/bin/bash

. $NS_WDIR/lib/automation_util

#BaseLine tsr with 3.8.4
BaseLineCSV="$NS_WDIR/logs/tsr/$TEST_CYCLE_NUM/BaseLineCSVData.CSV"
CurrentCSV="$NS_WDIR/logs/tsr/$TEST_CYCLE_NUM/CurrentDataCSVData.CSV"
T_NAME=$(get_tname)
Component=$(component_name)

function BaseLine(){
    BaseLine_Tsr_Directory_CPSFile="$NS_WDIR/logs/tsr/031416_115515/3348/hps_results.csv"
    echo  "Test description name is=$T_NAME"
    B_T_RUN_ID=`grep -w $T_NAME $BaseLine_Tsr_Directory_CPSFile |cut -d ',' -f2` 
    
    debug_log "BaselineTR for HPS = ${B_T_RUN_ID}" 
    
    CPS_MAX_VALUE=`grep -w "TCP Connections Open/Sec(NA)" $NS_WDIR/logs/TR${B_T_RUN_ID}/summary_gdf.data |cut -d '|' -f8`
    HPS_MAX_VALUE=`grep -w "Requests Successful/Sec(NA" $NS_WDIR/logs/TR${B_T_RUN_ID}/summary_gdf.data |cut -d '|' -f8`
    Throughput_Rx=`grep -w "Ethernet Receive Throughput (Kbps)(NA)" $NS_WDIR/logs/TR${B_T_RUN_ID}/summary_gdf.data |cut -d '|' -f8`
    Throughput_Tx=`grep -w "Ethernet Send Throughput (Kbps)(NA)" $NS_WDIR/logs/TR${B_T_RUN_ID}/summary_gdf.data |cut -d '|' -f8`
    CPS_MAX_VALUE=`echo $CPS_MAX_VALUE '*1' | bc -l | awk -F '.' '{ print $1; exit; }'`
    HPS_MAX_VALUE=`echo $HPS_MAX_VALUE '*1' | bc -l | awk -F '.' '{ print $1; exit; }'`
    Throughput_Rx=`echo $Throughput_Rx '*1' | bc -l | awk -F '.' '{ print $1; exit; }'`
    Throughput_Tx=`echo $Throughput_Tx '*1' | bc -l | awk -F '.' '{ print $1; exit; }'`
    echo "HPS,$T_NAME,${Component},${RELEASE_ID},${BUILD_ID},${COMPONENT_ID},TR${B_T_RUN_ID},$CPS_MAX_VALUE,$HPS_MAX_VALUE,$Throughput_Rx,$Throughput_Tx" >>$BaseLineCSV
}

function CurrentHPS() {
    debug_log "current test run number is =$T_RUN_ID"
	
	CPS_MAX_VALUE_CR=$(grep -w "TCP Connections Open/Sec(NA)" $NS_WDIR/logs/TR$T_RUN_ID/summary_gdf.data |cut -d '|' -f8)
	HPS_MAX_VALUE_CR=$(grep -w "Requests Successful/Sec(NA" $NS_WDIR/logs/TR$T_RUN_ID/summary_gdf.data |cut -d '|' -f8)
	Throughput_Rx_CR=$(grep -w "Ethernet Receive Throughput (Kbps)(NA)" $NS_WDIR/logs/TR$T_RUN_ID/summary_gdf.data |cut -d '|' -f8)
	Throughput_Tx_CR=$(grep -w "Ethernet Send Throughput (Kbps)(NA)" $NS_WDIR/logs/TR$T_RUN_ID/summary_gdf.data |cut -d '|' -f8)
    
	CPS_MAX_VALUE_CR=$(echo $CPS_MAX_VALUE_CR '*1' | bc -l | awk -F '.' '{ print $1; exit; }')
	HPS_MAX_VALUE_CR=$(echo $HPS_MAX_VALUE_CR '*1' | bc -l | awk -F '.' '{ print $1; exit; }')
	Throughput_Rx_CR=$(echo $Throughput_Rx_CR '*1' | bc -l | awk -F '.' '{ print $1; exit; }')
	Throughput_Tx_CR=$(echo $Throughput_Tx_CR '*1' | bc -l | awk -F '.' '{ print $1; exit; }')
    
	echo "HPS,$T_NAME,${Component},${RELEASE_ID},${BUILD_ID},${COMPONENT_ID},TR$T_RUN_ID,$CPS_MAX_VALUE_CR,$HPS_MAX_VALUE_CR,$Throughput_Rx_CR,$Throughput_Tx_CR"  >>$CurrentCSV
}


function Compare_Results(){
    Conn_Perc_Change=`echo "$CPS_MAX_VALUE" "$CPS_MAX_VALUE_CR" | awk '{print ($1-$2)/$1*100}'`
    echo "Conn_Perc_Change is =$Conn_Perc_Change"
    if (($(echo "scale=9; $Conn_Perc_Change < 5" |bc)!=0)) ;then	
        debug_log "going to pass testcase"	
	log_status_and_exit_ex "PASS" "$T_NAME Passed"
    else
        debug_log "going to fail testcase"	
	log_status_and_exit_ex "FAIL" "$T_NAME Failed"
    fi
}


function main(){ 
    BaseLine
    CurrentHPS   
    Compare_Results
}


if [[ "$T_NAME" == "Performance_hps_java_128User_OEF"* ]]; then
	debug_log "evaluating perf java results .... t_name is $T_NAME"
	CurrentHPS
	
	JAVA_BASED_HPS_MAX=13779
	Conn_Perc_Change=$(echo "$JAVA_BASED_HPS_MAX" "$HPS_MAX_VALUE_CR" | awk '{print ($1-$2)/$1*100}')
    
	debug_log "connection pct change is = $Conn_Perc_Change"
    
	if (($(echo "scale=9; $Conn_Perc_Change < 5" |bc)!=0));then
	    log_status_and_exit_ex "PASS" "testcase $T_NAME passed"
    else
	    log_status_and_exit_ex "FAIL" "testcase $T_NAME failed"
    fi
else
	main
fi


exit 0
