#!/bin/bash

. $NS_WDIR/lib/automation_util

#BaseLine tsr with 3.8.4
BaseLineCSV="$NS_WDIR/logs/tsr/$TEST_CYCLE_NUM/BaseLineCSVData.CSV"
CurrentCSV="$NS_WDIR/logs/tsr/$TEST_CYCLE_NUM/CurrentDataCSVData.CSV"
T_NAME=$(get_tname)
Component=performance

function BaseLine(){
    BaseLine_Tsr_Directory_HPSFile="$NS_WDIR/logs/tsr/170425_170922/1263/hps_results.csv"
    echo  "Test description name is=$T_NAME"
    B_T_RUN_ID=`grep -w $T_NAME $BaseLine_Tsr_Directory_HPSFile |cut -d ',' -f2` 
    
    debug_log "BaselineTR for HPS = ${B_T_RUN_ID}" 
    
    CPS_MAX_VALUE=`grep -w "TCP Connections Open/Sec(NA)" $NS_WDIR/logs/TR${B_T_RUN_ID}/summary_gdf.data |cut -d '|' -f8`
    CPS_AVG_VALUE=$(python /home/automation/workbench/automation/nscore/performance/shell/python/nsi_get_performance_stats.py -t ${B_T_RUN_ID} -m 1)
    HPS_MAX_VALUE=`grep -w "Requests Successful/Sec(NA" $NS_WDIR/logs/TR${B_T_RUN_ID}/summary_gdf.data |cut -d '|' -f8`
    HPS_AVG_VALUE=$(python /home/automation/workbench/automation/nscore/performance/shell/python/nsi_get_performance_stats.py -t ${B_T_RUN_ID} -m 2)
    echo "hps average value for baseline test run:$HPS_AVG_VALUE"
    Throughput_Rx=`grep -w "HTTP Body receive throughput (Kbps)(NA)" $NS_WDIR/logs/TR${B_T_RUN_ID}/summary_gdf.data |cut -d '|' -f8`
    #Throughput_Tx=`grep -w "Ethernet Send Throughput (Kbps)(NA)" $NS_WDIR/logs/TR${B_T_RUN_ID}/summary_gdf.data |cut -d '|' -f8`
    Throughput_Rx_Avg=$(python /home/automation/workbench/automation/nscore/performance/shell/python/nsi_get_performance_stats.py -t ${B_T_RUN_ID} -m 3)
    CPS_MAX_VALUE=`echo $CPS_MAX_VALUE '*1' | bc -l | awk -F '.' '{ print $1; exit; }'`
    HPS_MAX_VALUE=`echo $HPS_MAX_VALUE '*1' | bc -l | awk -F '.' '{ print $1; exit; }'`
    Throughput_Rx=`echo $Throughput_Rx '*1' | bc -l | awk -F '.' '{ print $1; exit; }'`
    #Throughput_Tx=`echo $Throughput_Tx '*1' | bc -l | awk -F '.' '{ print $1; exit; }'`
    echo "HPS,$T_NAME,${Component},${RELEASE_ID},${BUILD_ID},${COMPONENT_ID},TR${B_T_RUN_ID},$CPS_MAX_VALUE,$HPS_MAX_VALUE,$Throughput_Rx",${CPS_AVG_VALUE},${HPS_AVG_VALUE},${Throughput_Rx_Avg} >>$BaseLineCSV
}

function CurrentHPS() {
    debug_log "current test run number is =$T_RUN_ID"
	
	CPS_MAX_VALUE_CR=$(grep -w "TCP Connections Open/Sec(NA)" $NS_WDIR/logs/TR$T_RUN_ID/summary_gdf.data |cut -d '|' -f8)
    CPS_AVG_VALUE_CR=$(python /home/automation/workbench/automation/nscore/performance/shell/python/nsi_get_performance_stats.py -t ${T_RUN_ID} -m 1)
	HPS_MAX_VALUE_CR=$(grep -w "Requests Successful/Sec(NA" $NS_WDIR/logs/TR$T_RUN_ID/summary_gdf.data |cut -d '|' -f8)
    HPS_AVG_VALUE_CR=$(python /home/automation/workbench/automation/nscore/performance/shell/python/nsi_get_performance_stats.py -t ${T_RUN_ID} -m 2)
    echo "hps average value for current test run:$HPS_AVG_VALUE_CR"
    Throughput_Rx_CR=$(grep -w "HTTP Body receive throughput (Kbps)(NA)" $NS_WDIR/logs/TR$T_RUN_ID/summary_gdf.data |cut -d '|' -f8)
	#Throughput_Tx_CR=$(grep -w "Ethernet Send Throughput (Kbps)(NA)" $NS_WDIR/logs/TR$T_RUN_ID/summary_gdf.data |cut -d '|' -f8)
    Throughput_Rx_Avg_CR=$(python /home/automation/workbench/automation/nscore/performance/shell/python/nsi_get_performance_stats.py -t ${T_RUN_ID} -m 3)

	CPS_MAX_VALUE_CR=$(echo $CPS_MAX_VALUE_CR '*1' | bc -l | awk -F '.' '{ print $1; exit; }')
	HPS_MAX_VALUE_CR=$(echo $HPS_MAX_VALUE_CR '*1' | bc -l | awk -F '.' '{ print $1; exit; }')
	Throughput_Rx_CR=$(echo $Throughput_Rx_CR '*1' | bc -l | awk -F '.' '{ print $1; exit; }')
	#Throughput_Tx_CR=$(echo $Throughput_Tx_CR '*1' | bc -l | awk -F '.' '{ print $1; exit; }')
    
	echo "HPS,$T_NAME,${Component},${RELEASE_ID},${BUILD_ID},${COMPONENT_ID},TR$T_RUN_ID,$CPS_MAX_VALUE_CR,$HPS_MAX_VALUE_CR,$Throughput_Rx_CR,${CPS_AVG_VALUE_CR},${HPS_AVG_VALUE_CR},${Throughput_Rx_Avg_CR}"  >>$CurrentCSV
}


function Compare_Results(){
    Hits_Perc_Change=`echo "$HPS_AVG_VALUE" "$HPS_AVG_VALUE_CR" | awk '{print ($1-$2)/$1*100}'`
    echo "Hits_Perc_Change is =$Hits_Perc_Change"
    if (($(echo "scale=9; $Hits_Perc_Change < 5" |bc)!=0)) ;then	
        debug_log "going to pass testcase"	
	log_status_and_exit_ex "PASS" "$T_NAME Passed"
    else
        debug_log "going to fail testcase"	
	log_status_and_exit_ex "FAIL" "$T_NAME Failed"
    fi
}


function main(){ 
    BaseLine
    CurrentHPS   
    Compare_Results
}


if [[ "$T_NAME" == "Performance_hps_java_128User_OEF"* ]]; then
	debug_log "evaluating perf java results .... t_name is $T_NAME"
	CurrentHPS
    BaseLine_Tsr_Directory_HPSFile="$NS_WDIR/logs/tsr/170425_170922/1263/hps_results.csv"
    echo  "Test description name is=$T_NAME"
    B_T_RUN_ID=`grep -w $T_NAME $BaseLine_Tsr_Directory_HPSFile |cut -d ',' -f2` 
    
    debug_log "BaselineTR for HPS = ${B_T_RUN_ID}" 
	
	#JAVA_BASED_HPS_MAX=13779
    JAVA_BASED_HPS_MAX=`grep -w "Requests Successful/Sec(NA" $NS_WDIR/logs/TR${B_T_RUN_ID}/summary_gdf.data |cut -d '|' -f8`
    debug_log "JAVA_BASED_HPS_MAX = $JAVA_BASED_HPS_MAX"

	Hits_Perc_Change=$(echo "$JAVA_BASED_HPS_MAX" "$HPS_MAX_VALUE_CR" | awk '{print ($1-$2)/$1*100}')
    
	debug_log "hits pct change is = $Hits_Perc_Change"
    
	if (($(echo "scale=9; $Hits_Perc_Change < 5" |bc)!=0));then
	    log_status_and_exit_ex "PASS" "testcase $T_NAME passed"
    else
	    log_status_and_exit_ex "FAIL" "testcase $T_NAME failed"
    fi
else
	main
fi


exit 0
