/*-----------------------------------------------------------------------------
    Name: DumpBasic
    Generated By: netstorm
    Date of generation: 04/14/2012 07:03:19
    Flow details:
    Modification History:
-----------------------------------------------------------------------------*/

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "ns_string.h"

void DumpBasic()
{
    ns_web_url ("flower_html",
        "URL=http://127.0.0.1/BasicDigest/flower.html",
	"HTTPAuthUserName=netstorm",
        "HTTPAuthPassword=netstorm",
    );

    ns_page_think_time(0);

}
