/*-----------------------------------------------------------------------------
    Name: PageDump_NTLM
    Generated By: netstorm
    Date of generation: 03/15/2012 12:59:15
    Flow details:
    Modification History:
-----------------------------------------------------------------------------*/

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "ns_string.h"

void PageDump_NTLM()
{
    ns_web_url ("flower_html",
        "URL=http://127.0.0.1/Ntlm/flower.html"
    );

    ns_page_think_time(0);

}
