/*-----------------------------------------------------------------------------
    Name: flow
    Generated By: netstorm
    Date of generation: 12/24/2012 04:45:23
    Flow details:
    Modification History:
-----------------------------------------------------------------------------*/

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "ns_string.h"

void flow()
{
    ns_start_transaction("FirstPage");
    ns_web_url("Page1",
        "URL=http://127.0.0.1/NetworkCaching/page5.html"
    );
    ns_end_transaction("FirstPage", NS_AUTO_STATUS);

    ns_start_transaction("SecondPage");
    ns_web_url("Page2",
        "URL=http://127.0.0.1/NetworkCaching/page6.html"
    );
    ns_end_transaction("SecondPage", NS_AUTO_STATUS);
}
