#----------------------------------------------------------------------------------------------------#  
#  Generated by needle                                                                            #
#  Convention: ALL variables starts with K followed by underscore and appropriate name               #
#  Note: Do not use blank line and spaces. Comments are allowed                                      #
#----------------------------------------------------------------------------------------------------#
$K_TNAME|$K_SCRIPT_1|$K_SCRIPT_2|$K_SESSIONS_1|$K_SESSIONS_2|$K_START|$K_RAMP_UP_1_TIME|$K_DURATION_1|$K_RAMP_DOWN_1|$K_DURATION_2|$K_RAMP_UP_2_TIME|$K_DURATION_3|$K_RAMP_DOWN_2|$K_SVR_HOST|$K_RR_MODE|$K_O_THINK_TIME|$K_THINK_TIME|$K_SCHEDULE_TYPE|$K_PCT_MODE|$K_SCENARIO_TYPE|$K_HIERARICHAL_VIEW

SMOKE-056-001|ash_tours|ash_tours|400.00|600.00|START IMMEDIATELY|RAMP_UP 200.00 IMMEDIATELY|DURATION TIME 00:00:30|RAMP_DOWN 100.00 IMMEDIATELY|DURATION TIME 00:00:10|RAMP_UP 900.00 TIME_SESSIONS 00:00:30 1 10|DURATION TIME 00:00:30|RAMP_DOWN ALL TIME_SESSIONS 00:01:00 0|127.0.0.1 10.10.30.96|1|ALL ALL 1|ALL ALL 3 500 1000|ADVANCED|NUM|FIX_SESSION_RATE|default

SMOKE-056-001|ash_tours|ash_tours|40.00|60.00|START IMMEDIATELY|RAMP_UP 500.00 TIME_SESSIONS 00:00:30 1 10|DURATION TIME 00:00:30|RAMP_DOWN 250.00 TIME_SESSIONS 00:00:30 0|DURATION TIME 00:00:10|RAMP_UP 750.00 TIME_SESSIONS 00:00:30 2 3|DURATION TIME 00:00:30|RAMP_DOWN ALL IMMEDIATELY|127.0.0.1 10.10.30.96|1|ALL ALL 1|ALL ALL 3 500 1000|ADVANCED|PCT|FIX_SESSION_RATE|default
#END_ITERATION
