#----------------------------------------------------------------------------------------------------#  
#  Generated by needle                                                                            #
#  Convention: ALL variables starts with K followed by underscore and appropriate name               #
#  Note: Do not use blank line and spaces. Comments are allowed                                      #
#----------------------------------------------------------------------------------------------------#
$K_TNAME|$K_NUM_USERS|$K_RAMP_UP_TIME|$K_DURATION|$K_RAMP_DOWN_TIME|$K_SCRIPT|$K_SVR_HOST|$K_RR_MODE|$K_REPORTING|$K_SESSION_PACING|$K_O_THINK_TIME|$K_THINK_TIME|$K_NEW_USER|$K_TRACING|$K_HIERARICHAL_VIEW|$K_USE_SRC_IP|$K_SRC_IP_LIST

#Enable USE_SRC_IP and making different client ip conection 
SMOKE-052-001|1|ALL IMMEDIATELY|SESSIONS 5|ALL IMMEDIATELY|hpd_tours|127.0.0.1 10.10.30.96 -|1|ALL 1|ALL 1 0 2000|ALL ALL 1|ALL ALL 3 10 50|G_NEW_USER_ON_SESSION ALL 1|ALL 0 0 0 0|default|1 999999999|#

#Enable USE_SRC_IP and making different client ip conection with suitable ip_addr provided.
SMOKE-052-002|1|ALL IMMEDIATELY|SESSIONS 5|ALL IMMEDIATELY|hpd_tours|127.0.0.1 10.10.30.96 -|1|ALL 1|ALL 1 0 2000|ALL ALL 1|ALL ALL 3 10 50|G_NEW_USER_ON_SESSION ALL 1|ALL 0 0 0 0|default|1 4|#

#Enable USE_SRC_IP and making different client ip conection provided inside ip_file.txt. 
SMOKE-052-003|1|ALL IMMEDIATELY|SESSIONS 5|ALL IMMEDIATELY|hpd_tours|127.0.0.1 10.10.30.96 -|1|ALL 1|ALL 1 0 2000|ALL ALL 1|ALL ALL 3 10 50|G_NEW_USER_ON_SESSION ALL 1|ALL 0 0 0 0|default|3 /home/netstorm/work/ip_file.txt|#

#Enable USE_SRC_IP and SRC_IP_LIST and making different client ip conection with suitable ip_addr provided.
SMOKE-052-004|1|ALL IMMEDIATELY|SESSIONS 5|ALL IMMEDIATELY|hpd_tours|127.0.0.1 10.10.30.96 -|1|ALL 1|ALL 1 0 2000|ALL ALL 1|ALL ALL 3 10 50|G_NEW_USER_ON_SESSION ALL 1|ALL 0 0 0 0|default|1 0|G_SRC_IP_LIST ALL 199.99.99.1 4

#Enable USE_SRC_IP and Disable G_NEW_USER_ON_SESSION Keywords and  making different  client ip conection
##SMOKE-052-005|5|ALL IMMEDIATELY|SESSIONS 5|ALL IMMEDIATELY|hpd_tours|127.0.0.1 10.10.30.96 -|1|ALL 1|ALL 1 0 2000|ALL ALL 1|ALL ALL 3 10 50|#|ALL 0 0 0 0|default|2 999999999|#

#Enable USE_SRC_IP and Disbale G_NEW_USER_ON_SESSION Keywords and making same client ip conection
SMOKE-052-006|1|ALL IMMEDIATELY|SESSIONS 5|ALL IMMEDIATELY|hpd_tours|127.0.0.1 10.10.30.96 -|1|ALL 1|ALL 1 0 2000|ALL ALL 1|ALL ALL 3 10 50|#|ALL 0 0 0 0|default|2 4|#

#Enable USE_SRC_IP and Disable G_NEW_USER_ON_SESSION Keywords and making different client ip conection 
SMOKE-052-007|2|ALL IMMEDIATELY|SESSIONS 4|ALL IMMEDIATELY|hpd_tours|127.0.0.1 10.10.30.96 -|1|ALL 1|ALL 1 0 2000|ALL ALL 1|ALL ALL 3 10 50|#|ALL 0 0 0 0|default|4 /home/netstorm/work/ip_file.txt|#

#Enable USE_SRC_IP and SRC_IP_LIST Keywords and making same client ip conection
SMOKE-052-008|1|ALL IMMEDIATELY|SESSIONS 12|ALL IMMEDIATELY|hpd_tours|127.0.0.1 10.10.30.96 -|1|ALL 1|ALL 1 0 2000|ALL ALL 1|ALL ALL 3 10 50|#|ALL 0 0 0 0|default|2 0|G_SRC_IP_LIST ALL 199.99.99.1 10
#END_ITERATION
