/*-----------------------------------------------------------------------------
    Name: MainUrlAuth
    Generated By: netstorm
    Date of generation: 02/26/2012 11:12:39
    Flow details:
    Modification History:
-----------------------------------------------------------------------------*/

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "ns_string.h"

void MainUrlAuth()
{
    ns_web_url ("ntlm_html",
        "URL=http://10.10.30.97:8802/tours/test",
        "HTTPAuthUserName=%Username",
        "HTTPAuthPassword=%Password",
        INLINE_URLS,
            "URL=http://%UrlSVC", "HEADER=Accept-Language:en-us,en;q=0.5",
        "HTTPAuthUserName=%Username",
        "HTTPAuthPassword=%Password",
            END_INLINE,

);
 
}
